const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328gzx000vvi8wfsswginy';

const spots = [
  // LUXURY HOTELS
  { name: 'Amanpuri Phuket', slug: 'amanpuri-phuket', category: 'ACCOMMODATION', description: 'The original Aman resort and the property that invented the ultra-luxury private pool villa concept in 1988. Thirty pavilions and 40 pool villas on a private beach at Pansea Bay, with a 400-year-old coconut grove, a world-class spa, and the timeless Aman approach to total immersive luxury.', address: 'Pansea Beach, Surin, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Amanpuri+Phuket', phone: '+66 76 324 333', website: 'https://www.aman.com/resorts/amanpuri', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/amanpuri-phuket.jpg', tags: ['aman', 'original', 'pool-villa', 'private-beach', '1988'] },
  { name: 'Trisara Phuket', slug: 'trisara-phuket', category: 'ACCOMMODATION', description: 'A private oceanfront estate with 39 villas, each with its own infinity pool flowing toward the Andaman Sea, on a secluded bay north of Phuket. PRU, Trisara\'s restaurant, holds one of the few Michelin stars in Thailand outside Bangkok, making Trisara the most complete luxury hotel experience on the island.', address: '60/1 Moo 6, Srisoonthorn, Thalang, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Trisara+Phuket', phone: '+66 76 310 100', website: 'https://trisara.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/trisara-phuket.jpg', tags: ['oceanfront', 'infinity-pool', 'michelin', 'private-bay', 'estate'] },
  { name: 'Rosewood Phuket', slug: 'rosewood-phuket', category: 'ACCOMMODATION', description: 'A stunning resort of 71 pool villas cascading down a rocky headland to a private beach at Emerald Bay, designed with dramatic Thai contemporary architecture. The multiple infinity pools at different levels, the underwater cave bar accessible only through a waterfall, and the signature spa make Rosewood Phuket uniquely dramatic.', address: '88/28 Muen-Ngern Road, Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Rosewood+Phuket', phone: '+66 76 356 888', website: 'https://www.rosewoodhotels.com/phuket', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/rosewood-phuket.jpg', tags: ['headland', 'cave-bar', 'dramatic', 'pool-villa', 'spa'] },
  { name: 'Pavilions Phuket', slug: 'pavilions-phuket', category: 'ACCOMMODATION', description: 'A hillside collection of private pool villas with panoramic views over the Andaman Sea from a ridgeline above the northwest coast. The Pavilions Phuket combines complete privacy, spectacular sunsets, and exceptional food in an adults-only setting that defines the Phuket luxury hilltop villa concept.', address: '31/1 Moo 6, Cherng Talay, Thalang, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pavilions+Phuket', phone: '+66 76 317 600', website: 'https://www.thepavilionsresorts.com/phuket', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/pavilions-phuket.jpg', tags: ['hillside', 'adults-only', 'sunset-views', 'privacy', 'andaman'] },
  // BUDGET HOTELS
  { name: 'The Memory at On On Hotel Phuket', slug: 'memory-at-on-on-hotel-phuket', category: 'ACCOMMODATION', description: 'The historic On On Hotel (the original from The Beach film) renovated into a charming boutique property with preserved 1920s Sino-Portuguese architecture, a rooftop pool, and a location in the heart of Phuket Old Town. The most atmospheric mid-range hotel in the island\'s heritage district.', address: '19 Phang Nga Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Memory+at+On+On+Hotel+Phuket', phone: '+66 76 211 154', website: 'https://www.thememoryhotel.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/memory-at-on-on-hotel-phuket.jpg', tags: ['sino-portuguese', 'old-town', 'the-beach-film', 'heritage', 'rooftop-pool'] },
  { name: 'Phuket Heritage Hotel', slug: 'phuket-heritage-hotel', category: 'ACCOMMODATION', description: 'A superbly restored 1920s shophouse in Phuket Old Town with beautiful Peranakan tile floors, antique furniture, and a courtyard cafe. The Heritage Hotel is the most architecturally significant mid-range accommodation in Phuket, putting the best restaurants, cafes, and street art of the Old Town at your doorstep.', address: 'Thalang Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phuket+Heritage+Hotel', phone: '+66 76 216 016', website: 'https://phuketheritage.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/phuket-heritage-hotel.jpg', tags: ['shophouse', 'peranakan', 'old-town', 'antique', '1920s'] },
  { name: 'Kalima Resort and Spa Patong', slug: 'kalima-resort-spa-patong', category: 'ACCOMMODATION', description: 'A well-designed mid-range resort with an infinity pool overlooking Patong Bay from a hillside above the beach, at prices that represent excellent value for Phuket. The pool views at sunset, the Thai spa, and the easy access to Patong\'s beach and nightlife make Kalima a consistently popular choice.', address: '76/23 Kalim Beach Road, Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Kalima+Resort+Patong+Phuket', phone: '+66 76 606 888', website: 'https://kalimaresort.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/kalima-resort-spa-patong.jpg', tags: ['infinity-pool', 'patong-bay', 'hillside', 'value', 'spa'] },
  { name: 'Old Phuket Town Hostel', slug: 'old-phuket-town-hostel', category: 'ACCOMMODATION', description: 'A clean, affordable guesthouse in a restored Sino-Portuguese shophouse in the heart of the Old Town, with well-maintained rooms, fast wifi, and a common area for meeting fellow travelers. The central location within walking distance of all the Old Town\'s cafes, restaurants, and street art makes it exceptional value.', address: 'Dibuk Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Old+Phuket+Town+Hostel', phone: '+66 76 258 300', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/old-phuket-town-hostel.jpg', tags: ['sino-portuguese', 'old-town', 'wifi', 'budget', 'central'] },
  // HOSTELS
  { name: 'Lub d Phuket Patong', slug: 'lub-d-phuket-patong', category: 'ACCOMMODATION', description: 'The Phuket flagship of Thailand\'s leading design hostel brand with a stunning pool, rooftop deck, pod bunks, and social events in the best location on the Patong beach strip. Lub d Phuket combines the design quality of a boutique hotel with the social energy of the best party hostel.', address: '29 Bangla Road, Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Lub+d+Phuket+Patong', phone: '+66 76 607 999', website: 'https://www.lubd.com/phuket-patong', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/lub-d-phuket-patong.jpg', tags: ['design', 'pool', 'pods', 'patong', 'social'] },
  { name: 'Phuket Old Town Hostel', slug: 'phuket-old-town-hostel', category: 'ACCOMMODATION', description: 'A social hostel in an old Phuket shophouse with a rooftop terrace, pub quiz nights, a free cooking class on Sundays, and the most knowledgeable staff in Phuket for recommending off-the-beaten-path beaches, hidden restaurants, and island day trips beyond the tourist circuit.', address: 'Phang Nga Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phuket+Old+Town+Hostel', phone: '+66 76 217 100', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/phuket-old-town-hostel.jpg', tags: ['shophouse', 'rooftop', 'cooking-class', 'social', 'knowledgeable-staff'] },
  { name: 'Slumber Party Hostel Phuket', slug: 'slumber-party-hostel-phuket', category: 'ACCOMMODATION', description: 'The Phuket location of the famous Thai party hostel brand with a pool bar, nightly pub crawls down Bangla Road, DJs, and the most energetic social scene of any hostel in Patong. This is the right hostel if you want to dive headfirst into Phuket\'s legendary nightlife with a built-in social group.', address: 'Nanai Road, Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Slumber+Party+Phuket', phone: '+66 76 292 555', website: 'https://slumberpartyhostel.com/phuket', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/slumber-party-hostel-phuket.jpg', tags: ['party', 'pool-bar', 'pub-crawl', 'bangla', 'social'] },
  { name: 'Mad Monkey Phuket', slug: 'mad-monkey-phuket', category: 'ACCOMMODATION', description: 'The Phuket outpost of Southeast Asia\'s best-known social hostel brand with the same formula of swim-up pool bar, nightly events, and a community atmosphere that makes solo travel feel effortless. The rooftop bar overlooks Patong Bay and the breakfast spread is the most generous of any hostel in Phuket.', address: 'Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mad+Monkey+Phuket', phone: '+66 76 292 300', website: 'https://madmonkeyhostels.com/phuket', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/mad-monkey-phuket.jpg', tags: ['social', 'swim-up-pool', 'rooftop', 'breakfast', 'events'] },
  // CAFES
  { name: 'Torry\'s Ice Cream Phuket', slug: 'torrys-ice-cream-phuket', category: 'CAFE', description: 'A beloved Old Town institution serving handmade local ice cream in Phuket\'s most beautiful shophouse interior - all original 1920s tile floors, wooden beams, and rattan furniture. The durian, lychee, and mango ice creams made daily from fresh Phuket produce have become synonymous with the Old Town experience.', address: '19 Dibuk Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Torrys+Ice+Cream+Phuket', phone: '+66 76 212 323', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/torrys-ice-cream-phuket.jpg', tags: ['ice-cream', 'old-town', 'durian', 'shophouse', 'institution'] },
  { name: 'Kopitiam Phuket', slug: 'kopitiam-phuket', category: 'CAFE', description: 'The finest traditional Phuket kopitiam (Chinese coffeehouse) in the Old Town, serving Phuket coffee with thick condensed milk, kao tom rice porridge, and dim sum from 6am. Kopitiam is where Phuket\'s Chinese-Thai community has breakfasted for three generations - the dark roast Phuket Robusta coffee is extraordinary.', address: '18 Thalang Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Kopitiam+Phuket', phone: '+66 76 217 903', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/kopitiam-phuket.jpg', tags: ['kopitiam', 'phuket-coffee', 'dim-sum', 'chinese', 'morning'] },
  { name: 'Cherngtalay Artisan Coffee Phuket', slug: 'cherngtalay-artisan-coffee-phuket', category: 'CAFE', description: 'A specialty coffee bar in the upscale Cherngtalay/Laguna area with exceptional single-origin espresso, homemade cakes, and reliable fast internet for nomads. The large windows, natural wood interior, and carefully curated playlist make it the most comfortable working cafe in the Laguna-Surin beach area.', address: 'Cherngtalay, Thalang, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Cherngtalay+Artisan+Coffee+Phuket', phone: '+66 93 123 4567', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/cherngtalay-artisan-coffee-phuket.jpg', tags: ['specialty', 'nomad', 'wifi', 'espresso', 'laguna'] },
  { name: 'Two Black Sheep Cafe Phuket', slug: 'two-black-sheep-cafe-phuket', category: 'CAFE', description: 'A New Zealand-run specialty cafe in Phuket Old Town with excellent flat whites, sour dough toasts, and a dog-friendly terrace. Two Black Sheep is a favorite of expats and long-stay travelers who value consistent quality coffee in a relaxed setting without the tourist surcharge that plagues Old Town\'s more photographed cafes.', address: 'Soi Romanee, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Two+Black+Sheep+Cafe+Phuket', phone: '+66 93 234 5678', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/two-black-sheep-cafe-phuket.jpg', tags: ['flat-white', 'new-zealand', 'sourdough', 'dog-friendly', 'expat'] },
  { name: 'Naughty Nuri\'s Phuket', slug: 'naughty-nuris-phuket', category: 'CAFE', description: 'The Phuket branch of the legendary Ubud institution with the same iconic pork ribs, house BBQ sauce, and bucket martinis. Located in the Cherngtalay area near Laguna Beach, Naughty Nuri\'s Phuket attracts the resort crowd who heard about it in Bali and made it a standard stop on the Southeast Asia circuit.', address: 'Srisoonthorn Road, Cherngtalay, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Naughty+Nuris+Phuket', phone: '+66 76 271 781', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/naughty-nuris-phuket.jpg', tags: ['ribs', 'martinis', 'bbq', 'cherngtalay', 'institution'] },
  { name: 'Ka Jok See Restaurant and Bar Phuket', slug: 'ka-jok-see-phuket', category: 'CAFE', description: 'Phuket\'s most unique dining experience - a restaurant that transforms into a wild dance party after 10pm where staff and guests dance on tables to 1970s and 80s disco. By day Ka Jok See is a beautifully decorated Thai-Chinese restaurant in a 1930s shophouse; by night it\'s the most memorable evening in Phuket.', address: '26 Takua Pa Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Ka+Jok+See+Phuket', phone: '+66 76 217 903', website: null, priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/ka-jok-see-phuket.jpg', tags: ['restaurant-bar', 'dancing', 'disco', 'shophouse', 'unique'] },
  // RESTAURANTS
  { name: 'PRU Restaurant Phuket', slug: 'pru-restaurant-phuket', category: 'FOOD', description: 'Thailand\'s most celebrated farm-to-table restaurant with a Michelin star, located at Trisara resort. Chef Jimmy Ophorst sources all ingredients from the resort\'s private farm and from sustainable Phuket producers - an evolving tasting menu that changes daily with the harvest.', address: 'Trisara Resort, Srisoonthorn, Thalang, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=PRU+Restaurant+Phuket', phone: '+66 76 310 100', website: 'https://pru.restaurant', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/pru-restaurant-phuket.jpg', tags: ['michelin', 'farm-to-table', 'tasting-menu', 'sustainable', 'best-phuket'] },
  { name: 'Suay Restaurant Phuket', slug: 'suay-restaurant-phuket', category: 'FOOD', description: 'A beloved Phuket Old Town restaurant by Chef Noi Tammasak, serving modern Thai cuisine with a focus on southern Thai flavors - crab curry, mussaman with potato, and sea bass with turmeric. The beautiful heritage house setting and exceptional quality at moderate prices make Suay a Phuket institution.', address: '50/2 Takua Pa Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Suay+Restaurant+Phuket', phone: '+66 76 216 892', website: 'https://suayrestaurant.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/suay-restaurant-phuket.jpg', tags: ['modern-thai', 'southern-thai', 'old-town', 'heritage', 'crab-curry'] },
  { name: 'Roti Talay Phuket', slug: 'roti-talay-phuket', category: 'FOOD', description: 'A simple, legendary restaurant near Surin Beach serving the best roti mataba and Muslim-style seafood in Phuket. The crab roti with curry sauce and the gaeng massaman are outstanding and the prices are what locals pay - a completely authentic southern Thai Muslim dining experience.', address: 'Surin Beach, Cherngtalay, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Roti+Talay+Phuket', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/roti-talay-phuket.jpg', tags: ['roti', 'muslim', 'crab', 'massaman', 'surin'] },
  { name: 'Kan Eang 2 Restaurant Phuket', slug: 'kan-eang-2-restaurant-phuket', category: 'FOOD', description: 'A landmark seafood restaurant on the Chalong Bay waterfront that has served Phuket\'s freshest seafood since 1977. The grilled whole grouper with fresh herbs, the giant river prawns in garlic butter, and the deep-fried soft-shell crab have been the same exceptional quality for three generations.', address: '9/4 Chao Fa Tawan Tok Road, Chalong, Phuket 83130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Kan+Eang+2+Restaurant+Phuket', phone: '+66 76 381 323', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/kan-eang-2-restaurant-phuket.jpg', tags: ['seafood', '1977', 'grouper', 'prawns', 'chalong'] },
  { name: 'Laem Hin Seafood Phuket', slug: 'laem-hin-seafood-phuket', category: 'FOOD', description: 'An atmospheric seafood restaurant built over the water at Phuket\'s Laem Hin fishing village with wooden pier seating, excellent fresh seafood at non-tourist prices, and a local crowd of fishermen, families, and Phuket residents who know where the real food is. The steamed clams with holy basil are extraordinary.', address: 'Laem Hin, Koh Kaew, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Laem+Hin+Seafood+Phuket', phone: '+66 76 218 789', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/laem-hin-seafood-phuket.jpg', tags: ['seafood', 'over-water', 'local', 'fishing-village', 'clams'] },
  { name: 'Bampot Kitchen Phuket', slug: 'bampot-kitchen-phuket', category: 'FOOD', description: 'A craft beer bar and kitchen in Phuket Old Town with an excellent selection of Thai and imported craft beers alongside creative Thai-Western fusion small plates. The beer-braised pork belly with local Phuket herbs and the smoked duck pizza are signatures in a menu that changes seasonally.', address: '58/1 Thalang Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Bampot+Kitchen+Phuket', phone: '+66 76 213 636', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/bampot-kitchen-phuket.jpg', tags: ['craft-beer', 'fusion', 'old-town', 'pork-belly', 'creative'] },
  // MARKETS
  { name: 'Phuket Weekend Market (Indy Market)', slug: 'phuket-indy-weekend-market', category: 'FOOD', description: 'The most popular night market in Phuket, held every Friday, Saturday, and Sunday near Central Festival mall, with an enormous selection of Thai street food, live music, fashion stalls, and local handicrafts. The market is a genuine local affair - more attended by Phuket residents than tourists.', address: 'Chao Fa West Road, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Indy+Weekend+Market+Phuket', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/phuket-indy-weekend-market.jpg', tags: ['weekend-market', 'street-food', 'live-music', 'local', 'friday-saturday-sunday'] },
  { name: 'Phuket Town Sunday Walking Street', slug: 'phuket-town-sunday-walking-street', category: 'FOOD', description: 'A weekly Sunday evening street market along Thalang Road in Phuket Old Town where the Sino-Portuguese shophouses become a living backdrop for street art, local food stalls, and cultural performances. The traditional Phuket hawker foods - oh tao oyster cake, mee sua noodles, and loh mee - are the highlight.', address: 'Thalang Road, Phuket Old Town 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phuket+Sunday+Walking+Street', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/phuket-town-sunday-walking-street.jpg', tags: ['walking-street', 'sunday', 'old-town', 'oh-tao', 'sino-portuguese'] },
  { name: 'Malin Plaza Night Market Patong', slug: 'malin-plaza-night-market-patong', category: 'FOOD', description: 'The main night market for tourists staying in Patong with a wide selection of Thai street food, freshly grilled seafood, som tam, and pad thai at a good price-to-quality ratio. Less chaotic than walking Bangla Road, Malin Plaza gives a more accessible taste of Thai market culture on the island\'s busiest beach.', address: '75/1 Ratuthit Road, Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Malin+Plaza+Night+Market+Patong', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/malin-plaza-night-market-patong.jpg', tags: ['night-market', 'patong', 'seafood', 'tourist', 'accessible'] },
  { name: 'Banzaan Fresh Market Phuket', slug: 'banzaan-fresh-market-phuket', category: 'FOOD', description: 'A two-floor upscale fresh market in Patong Beach with a ground floor of premium fresh seafood, tropical fruits, and imported cheeses, and an upper floor of cooked food stalls serving everything from fresh oysters to pad see ew. Upmarket and clean by Thai market standards.', address: 'Patong, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Banzaan+Market+Patong+Phuket', phone: null, website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/banzaan-fresh-market-phuket.jpg', tags: ['fresh-market', 'oysters', 'seafood', 'premium', 'patong'] },
  { name: 'Naka Weekend Market Phuket', slug: 'naka-weekend-market-phuket', category: 'FOOD', description: 'The largest and most varied weekend market in Phuket, held Saturday and Sunday in the Ratsada area, with an enormous selection of secondhand goods, vintage clothing, electronics, handicrafts, and street food stalls. Genuinely attended by Phuket residents and a fascinating cross-section of the island\'s diverse population.', address: 'Wiset Road, Ratsada, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Naka+Weekend+Market+Phuket', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/naka-weekend-market-phuket.jpg', tags: ['weekend-market', 'vintage', 'secondhand', 'diverse', 'local'] },
  // TOURIST SITES
  { name: 'Phuket Old Town Heritage Zone', slug: 'phuket-old-town-heritage-zone', category: 'CULTURE', description: 'One of Southeast Asia\'s best-preserved colonial heritage zones - 30 blocks of Sino-Portuguese shophouses dating from the 1890s tin-mining boom, painted in pastels and decorated with ornate iron shutters. The Old Town\'s Sunday Walking Street, cafes, and street art make it the cultural heart of the island.', address: 'Phuket Old Town, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phuket+Old+Town', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/phuket-old-town-heritage-zone.jpg', tags: ['sino-portuguese', 'heritage', 'shophouses', 'walking', 'instagram'] },
  { name: 'Big Buddha Phuket', slug: 'big-buddha-phuket', category: 'CULTURE', description: 'A 45-meter white Burmese marble Buddha seated on Nakkerd Hill, visible from almost everywhere on the island. The viewing platform at the base of the statue provides the most comprehensive panorama over Phuket\'s southwestern coastline, with Kata, Karon, and Chalong Bay stretching to the horizon.', address: 'Nakkerd Hill, Karon, Phuket 83100, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Big+Buddha+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/big-buddha-phuket.jpg', tags: ['buddha', 'hilltop', 'panorama', 'marble', 'views'] },
  { name: 'Phang Nga Bay Day Trip', slug: 'phang-nga-bay-phuket', category: 'NATURE', description: 'The most spectacular day trip from Phuket - a limestone karst archipelago of 40+ islands and sea caves rising from emerald green water. James Bond Island (Ko Tapu), the floating Koh Panyee fishing village, and kayaking through sea caves make Phang Nga Bay the essential Phuket area excursion.', address: 'Phang Nga Bay, Phang Nga Province, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phang+Nga+Bay+Thailand', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/phang-nga-bay-phuket.jpg', tags: ['day-trip', 'limestone-karst', 'james-bond-island', 'kayaking', 'emerald-water'] },
  { name: 'Patong Beach Phuket', slug: 'patong-beach-phuket', category: 'NATURE', description: 'The most famous beach in Phuket - a 3km curved bay of white sand and clear water flanked by the island\'s most concentrated hotel, restaurant, and nightlife strip. Patong is quintessential mass-market Southeast Asian beach tourism at its most extreme and simultaneously undeniable - the energy is electric.', address: 'Patong, Kathu, Phuket 83150, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Patong+Beach+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.2, imageUrl: '/spots/patong-beach-phuket.jpg', tags: ['beach', 'famous', 'nightlife', 'buzzing', 'iconic'] },
  { name: 'Wat Chalong Phuket', slug: 'wat-chalong-phuket', category: 'CULTURE', description: 'The largest and most revered Buddhist temple in Phuket with five grand pagodas, a relic of Buddha, and thousands of local worshippers presenting offerings. The Grand Pagoda contains a fragment of bone believed to be from the Buddha himself, drawing pilgrims from across southern Thailand daily.', address: 'Chalong, Mueang, Phuket 83130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Wat+Chalong+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/wat-chalong-phuket.jpg', tags: ['temple', 'buddhist', 'pilgrimage', 'pagoda', 'important'] },
  { name: 'Promthep Cape Phuket', slug: 'promthep-cape-phuket', category: 'NATURE', description: 'The southernmost point of Phuket with 270-degree views of the Andaman Sea, the small islands to the south, and the rugged coastline - the most famous sunset viewpoint on the island. Arrive 30 minutes early to claim a rock perch and bring a Chang beer - the sunset here is genuinely extraordinary.', address: 'Rawai, Mueang, Phuket 83130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Promthep+Cape+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/promthep-cape-phuket.jpg', tags: ['cape', 'sunset', 'andaman', 'views', 'southernmost'] },
  { name: 'Surin Beach and Millionaires Row Phuket', slug: 'surin-beach-phuket', category: 'NATURE', description: 'Phuket\'s most upscale beach - a 1km bay flanked by the island\'s most expensive villas and the Amanpuri resort, with clear blue water, excellent shade trees, and a sophisticated but relaxed atmosphere. The beach clubs along Surin serve excellent food and cocktails to Phuket\'s most affluent crowd.', address: 'Surin Beach, Cherngtalay, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Surin+Beach+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/surin-beach-phuket.jpg', tags: ['beach', 'upscale', 'beach-clubs', 'clear-water', 'sophisticated'] },
  { name: 'Karon Viewpoint Phuket', slug: 'karon-viewpoint-phuket', category: 'NATURE', description: 'A hilltop viewpoint between Kata and Karon beaches with the most classic Phuket coastline view - three beaches curving around rocky headlands in a sequence, with brilliant blue water and forested hills. The most photographed view in Phuket outside Old Town and accessible for free with any vehicle.', address: 'Karon, Mueang, Phuket 83100, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Karon+Viewpoint+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/karon-viewpoint-phuket.jpg', tags: ['viewpoint', 'three-beaches', 'photography', 'free', 'classic'] },
  { name: 'Phuket Aquarium', slug: 'phuket-aquarium', category: 'CULTURE', description: 'A well-maintained public aquarium at Cape Panwa run by the Marine Biological Research Center, with excellent Gulf of Thailand and Andaman Sea marine life displays, an impressive shark tank, and a turtle conservation center. A genuinely educational and underrated attraction that local Phuket families love.', address: '51 Sakdidet Road, Vichit, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phuket+Aquarium', phone: '+66 76 391 128', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/phuket-aquarium.jpg', tags: ['aquarium', 'sharks', 'turtle', 'marine', 'cape-panwa'] },
  // COWORKING
  { name: 'HUBBA Phuket Coworking', slug: 'hubba-phuket-coworking', category: 'COWORKING', description: 'The Phuket branch of Thailand\'s most respected coworking brand in a prime Old Town location with a gorgeous heritage building interior, excellent event programming, and a community of entrepreneurs and creatives. Monthly memberships include access to all HUBBA locations across Thailand.', address: 'Phuket Old Town, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=HUBBA+Phuket+Coworking', phone: '+66 76 213 234', website: 'https://hubba.co/phuket', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/hubba-phuket-coworking.jpg', tags: ['hubba', 'old-town', 'heritage', 'community', 'events'] },
  { name: 'Phuket Working Space', slug: 'phuket-working-space', category: 'COWORKING', description: 'A modern coworking facility near the Phuket Central shopping complex with 24-hour access, dedicated desks, private offices, a podcast studio, and a large event space. Popular with local Phuket entrepreneurs and visiting remote workers based in the city\'s commercial center.', address: 'Phuket Town, Phuket 83000, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Phuket+Working+Space', phone: '+66 76 214 567', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/phuket-working-space.jpg', tags: ['24-hour', 'podcast-studio', 'event-space', 'central', 'entrepreneurs'] },
  { name: 'Sandbox Coworking Phuket', slug: 'sandbox-coworking-phuket', category: 'COWORKING', description: 'A beach-area coworking space in the Karon area with fiber internet, ergonomic chairs, good natural light, and a location that puts both the beach and the Old Town within 15 minutes. Sandbox caters to the wave of remote workers who want Phuket\'s beaches without sacrificing professional workspace quality.', address: 'Karon, Mueang, Phuket 83100, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Sandbox+Coworking+Phuket', phone: '+66 93 345 6789', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/sandbox-coworking-phuket.jpg', tags: ['beach-area', 'fiber', 'karon', 'remote-workers', 'balanced'] },
  { name: 'Digital Nomad Phuket Hub', slug: 'digital-nomad-phuket-hub', category: 'COWORKING', description: 'A dedicated digital nomad coworking and community space in Rawai at the southern end of Phuket island, operating on a pay-what-you-can model with a monthly community pass. The Rawai location is preferred by longer-stay nomads who prioritize the local beach atmosphere over proximity to tourist areas.', address: 'Rawai, Mueang, Phuket 83130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Digital+Nomad+Phuket+Hub', phone: '+66 93 456 7890', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/digital-nomad-phuket-hub.jpg', tags: ['community', 'rawai', 'pay-what-you-can', 'monthly', 'local-beach'] },
  { name: 'Kata Center Cowork Phuket', slug: 'kata-center-cowork-phuket', category: 'COWORKING', description: 'A convenient coworking cafe in the Kata Beach area with reliable 100Mbps internet, good coffee, and affordable day passes. Kata Center Cowork serves the significant population of nomads and remote workers who prefer the quieter Kata and Kata Noi beaches over the crowds of Patong, and is a 5-minute drive from both.', address: 'Kata Beach, Phuket 83100, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Kata+Center+Cowork+Phuket', phone: '+66 93 567 8901', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/kata-center-cowork-phuket.jpg', tags: ['kata-beach', 'day-pass', '100mbps', 'cafe', 'nomad'] },
  { name: 'Laguna Coworking Phuket', slug: 'laguna-coworking-phuket', category: 'COWORKING', description: 'A premium coworking space within the Laguna Phuket resort complex, offering a professional environment with resort-quality amenities - pool access, restaurant, spa - alongside a well-equipped workspace with fast internet and private offices. Ideal for executives and high-earning nomads who want work and luxury simultaneously.', address: 'Laguna Phuket, Cherngtalay, Phuket 83110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Laguna+Phuket+Coworking', phone: '+66 76 362 300', website: 'https://www.lagunaphuket.com', priceRange: 'HIGH', rating: 4.6, imageUrl: '/spots/laguna-coworking-phuket.jpg', tags: ['resort-cowork', 'pool-access', 'spa', 'executive', 'premium'] },
  { name: 'Kata Noi Beach Phuket', slug: 'kata-noi-beach-phuket', category: 'NATURE', description: 'The most beautiful small beach on Phuket island - a 500-meter arc of powder-white sand backed by forested hills, with clearer water than the larger beaches and a calm, uncrowded atmosphere. Kata Noi is consistently voted one of the best beaches in Thailand by those who have seen all of them.', address: 'Kata Noi, Karon, Phuket 83100, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Kata+Noi+Beach+Phuket', phone: null, website: null, priceRange: 'FREE', rating: 4.8, imageUrl: '/spots/kata-noi-beach-phuket.jpg', tags: ['beach', 'powder-sand', 'clear-water', 'uncrowded', 'best-beach'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Phuket: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
