const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328f0o000nvi8wt7s20t16';

const spots = [
  // LUXURY HOTELS
  { name: 'Marco Polo Plaza Cebu', slug: 'marco-polo-plaza-cebu', category: 'ACCOMMODATION', description: 'Cebu\'s leading luxury hotel on a hilltop overlooking the city and Mactan Strait with two pools, multiple restaurants, a full-service spa, and meeting facilities. The Cafe Marco serves the best Sunday brunch on the island and the outdoor lap pool with city views is Cebu\'s most photogenic swimming pool.', address: 'Cebu Veterans Drive, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Marco+Polo+Plaza+Cebu', phone: '+63 32 253 1111', website: 'https://www.marcopolohotels.com/cebu', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/marco-polo-plaza-cebu.jpg', tags: ['luxury', 'hilltop', 'pool', 'brunch', 'views'] },
  { name: 'Radisson Blu Hotel Cebu', slug: 'radisson-blu-cebu', category: 'ACCOMMODATION', description: 'A sleek business-class hotel in the IT Park tech district of Cebu with an infinity rooftop pool overlooking the city, multiple dining options, and the most sophisticated rooms in Cebu at the luxury tier. The location in IT Park puts the best restaurants and nightlife of Cebu within walking distance.', address: 'Sergio Osmena Blvd, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Radisson+Blu+Cebu', phone: '+63 32 402 9900', website: 'https://www.radissonblu.com/cebu', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/radisson-blu-cebu.jpg', tags: ['luxury', 'it-park', 'rooftop-pool', 'business', 'city-views'] },
  { name: 'Crimson Resort and Spa Mactan', slug: 'crimson-resort-spa-mactan-cebu', category: 'ACCOMMODATION', description: 'A beachfront resort on Mactan Island with direct access to a coral reef, exceptional dive and snorkeling facilities, a stunning infinity pool facing the Cebu Strait, and Balinese-style spa. Crimson Mactan is the most complete luxury beach resort experience within 30 minutes of Cebu City.', address: 'Seascapes Resort Town, Mactan Island, Lapu-Lapu City 6015, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Crimson+Resort+Mactan+Cebu', phone: '+63 32 401 9999', website: 'https://www.crimsonhotel.com/mactan', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/crimson-resort-spa-mactan-cebu.jpg', tags: ['beach-resort', 'mactan', 'diving', 'infinity-pool', 'spa'] },
  { name: 'Plantation Bay Resort and Spa Cebu', slug: 'plantation-bay-resort-cebu', category: 'ACCOMMODATION', description: 'A self-contained luxury lagoon resort on Mactan Island with over 5 hectares of interconnected saltwater lagoons, swim-up bars, multiple pools, and a private beach. Plantation Bay\'s tropical Caribbean aesthetic - coconut palms, white sand, and clear water - is unlike any other resort in the Philippines.', address: 'Marigondon, Mactan Island, Lapu-Lapu City 6015, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Plantation+Bay+Resort+Cebu', phone: '+63 32 505 9800', website: 'https://plantationbay.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/plantation-bay-resort-cebu.jpg', tags: ['lagoon', 'mactan', 'swim-up-bar', 'tropical', 'private-beach'] },
  // BUDGET HOTELS
  { name: 'Hotel Elizabeth Cebu', slug: 'hotel-elizabeth-cebu', category: 'ACCOMMODATION', description: 'A well-regarded mid-range hotel in the Cebu Business Park area with a good pool, comfortable rooms, a gym, and a location that puts the city\'s business and shopping districts within walking distance. Hotel Elizabeth offers hotel-quality facilities at guesthouse prices and consistently receives excellent service reviews.', address: 'North Reclamation Area, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Elizabeth+Cebu', phone: '+63 32 231 8000', website: 'https://www.hotelelizabethcebu.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/hotel-elizabeth-cebu.jpg', tags: ['mid-range', 'pool', 'business-park', 'gym', 'value'] },
  { name: 'Be Hotel Cebu', slug: 'be-hotel-cebu', category: 'ACCOMMODATION', description: 'A stylish boutique hotel in the trendy IT Park area with design-forward rooms, a rooftop pool with city views, and an excellent restaurant. Be Hotel attracts digital nomads and young professionals with its combination of strong wifi, smart design, and proximity to the best cafes and restaurants in Cebu.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Be+Hotel+Cebu', phone: '+63 32 505 1888', website: 'https://behotelcebu.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/be-hotel-cebu.jpg', tags: ['boutique', 'it-park', 'rooftop-pool', 'design', 'nomad'] },
  { name: 'Fuente Pension House Cebu', slug: 'fuente-pension-house-cebu', category: 'ACCOMMODATION', description: 'A popular, well-maintained budget hotel near Fuente Osmena circle in central Cebu - the most accessible area for exploring the old city, Carbon Market, and waterfront. Simple but clean rooms, reliable AC, fast wifi, and a friendly staff that provides exceptional local restaurant recommendations.', address: 'Fuente Osmena Circle, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Fuente+Pension+House+Cebu', phone: '+63 32 232 5000', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/fuente-pension-house-cebu.jpg', tags: ['budget', 'central', 'clean', 'fuente-osmena', 'friendly'] },
  { name: 'Castle Peak Hotel Cebu', slug: 'castle-peak-hotel-cebu', category: 'ACCOMMODATION', description: 'A reliable budget hotel in the Cebu IT Park area - the most lively part of the city at night - with clean rooms, a small pool, and a location that gives access to dozens of restaurants and cafes within a 10-minute walk. Consistently rated among Cebu\'s best budget options for value and cleanliness.', address: 'A.S. Fortuna Street, Mandaue, Cebu 6014, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Castle+Peak+Hotel+Cebu', phone: '+63 32 344 0808', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/castle-peak-hotel-cebu.jpg', tags: ['budget', 'it-park', 'pool', 'clean', 'restaurants-nearby'] },
  // HOSTELS
  { name: 'Hop Hostel Cebu', slug: 'hop-hostel-cebu', category: 'ACCOMMODATION', description: 'A popular social hostel in the IT Park area with pod dorms, a rooftop bar, nightly events, and a community of solo travelers who tend to extend their stays. The hostel organizes island-hopping day trips, whale shark tours, and Oslob diving packages at competitive prices.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Hop+Hostel+Cebu', phone: '+63 917 625 2767', website: 'https://hophostelcebu.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/hop-hostel-cebu.jpg', tags: ['social', 'pods', 'rooftop-bar', 'island-hopping', 'tours'] },
  { name: 'Seagull Hostel Cebu', slug: 'seagull-hostel-cebu', category: 'ACCOMMODATION', description: 'A clean, friendly hostel in the Colon heritage district with pod bunks, a common lounge, free breakfast, and staff who genuinely help with trip planning. The location near Cebu\'s oldest street makes it easy to explore the colonial heritage sites, churches, and Carbon Market on foot.', address: 'Colon Street, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Seagull+Hostel+Cebu', phone: '+63 32 255 3030', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/seagull-hostel-cebu.jpg', tags: ['hostel', 'colon', 'breakfast', 'heritage', 'clean'] },
  { name: 'Cebu Backpackers', slug: 'cebu-backpackers-hostel', category: 'ACCOMMODATION', description: 'A no-frills budget hostel near the South Bus Terminal - ideal for travelers using Cebu as a transit point to the southern islands. Clean dorms with good lockers, a common kitchen, and a helpful notice board listing bus schedules, ferry times, and diving packages to Moalboal and Oslob.', address: 'Colon Area, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Cebu+Backpackers+Hostel', phone: '+63 32 233 4567', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/cebu-backpackers-hostel.jpg', tags: ['backpacker', 'transit', 'kitchen', 'diving', 'budget'] },
  { name: 'The Greenery Hostel Cebu', slug: 'greenery-hostel-cebu', category: 'ACCOMMODATION', description: 'A quirky hostel in a colonial heritage house in the Colon area with individually painted rooms, a garden hammock area, and an owner who is Cebu\'s best local guide. The weekly communal BBQ on Sunday evenings brings together travelers from across the Philippines for Cebu lechon, San Miguel, and roof-top conversation.', address: 'Mabini Street, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Greenery+Hostel+Cebu', phone: '+63 917 321 5432', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/greenery-hostel-cebu.jpg', tags: ['heritage-house', 'garden', 'communal-bbq', 'lechon', 'social'] },
  // CAFES
  { name: 'Bo\'s Coffee Cebu', slug: 'bos-coffee-cebu', category: 'CAFE', description: 'The hometown pioneer of Philippine specialty coffee, founded in Cebu in 1996 and now a national chain with its original flagship in Ayala Center. Bo\'s sources exclusively from Philippine highland farms in Sagada, Benguet, and Bukidnon - a strong espresso and excellent wifi make it the go-to work cafe in Cebu.', address: 'Ayala Center Cebu, Cebu Business Park, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Bo+Coffee+Ayala+Cebu', phone: '+63 32 234 7100', website: 'https://boscoffee.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/bos-coffee-cebu.jpg', tags: ['philippine-coffee', 'pioneer', 'wifi', 'flagship', 'specialty'] },
  { name: 'Abaca Baking Company Cebu', slug: 'abaca-baking-company-cebu', category: 'CAFE', description: 'A celebrated artisan bakery and cafe from the Abaca Group, serving wood-fired sourdough bread, excellent espresso, and creative brunch dishes in a beautiful space near IT Park. The Saturday morning bread queue and the almond croissants are the best bread experiences in the Philippines.', address: 'Nivel Hills, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Abaca+Baking+Company+Cebu', phone: '+63 32 231 5195', website: 'https://abacagroup.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/abaca-baking-company-cebu.jpg', tags: ['bakery', 'sourdough', 'espresso', 'brunch', 'artisan'] },
  { name: 'Coffee Project Cebu', slug: 'coffee-project-cebu', category: 'CAFE', description: 'A well-designed specialty coffee cafe chain that started in Cebu with excellent espresso, a full food menu, and strong wifi in a welcoming atmosphere. The sea salt caramel cold brew and the avocado toast have cult status in Cebu and the cafe is consistently full of university students and young professionals.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Coffee+Project+Cebu', phone: '+63 32 234 9900', website: 'https://coffeeproject.com.ph', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/coffee-project-cebu.jpg', tags: ['specialty', 'cold-brew', 'avocado-toast', 'wifi', 'popular'] },
  { name: 'Yolk Cafe Cebu', slug: 'yolk-cafe-cebu', category: 'CAFE', description: 'A bright, sunny breakfast and brunch cafe in Cebu\'s Banilad area with exceptional egg dishes, homemade granola, and excellent pour-over coffee in a relaxed neighborhood setting. Yolk operates from morning to midafternoon only - arrive by 10am on weekends or expect to wait for a table.', address: 'Banilad, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Yolk+Cafe+Cebu', phone: '+63 917 321 9876', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/yolk-cafe-cebu.jpg', tags: ['breakfast', 'brunch', 'eggs', 'granola', 'pour-over'] },
  { name: 'Ground Zero Cafe Cebu', slug: 'ground-zero-cafe-cebu', category: 'CAFE', description: 'A socially conscious community cafe in the heart of the IT Park area supporting local coffee farmers and environmental causes. The Mindanao single-origin espresso and the ube latte are local favorites, and the sustainable bamboo and reclaimed wood interior makes it the most thoughtfully designed cafe in Cebu.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Ground+Zero+Cafe+Cebu', phone: '+63 32 238 0808', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/ground-zero-cafe-cebu.jpg', tags: ['social', 'sustainable', 'ube-latte', 'local-coffee', 'eco'] },
  { name: 'Handuraw Pizza and Cafe Cebu', slug: 'handuraw-pizza-cafe-cebu', category: 'CAFE', description: 'A beloved institution in Cebu City near the University of San Carlos, combining artisanal thin-crust pizza with craft coffee and an extensive loose-leaf tea selection in a casual, student-friendly atmosphere. The free wifi, slow service, and all-day menu make Handuraw Cebu\'s most popular long-stay cafe.', address: 'Gorordo Avenue, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Handuraw+Pizza+Cebu', phone: '+63 32 236 2516', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/handuraw-pizza-cafe-cebu.jpg', tags: ['pizza', 'craft-coffee', 'wifi', 'student', 'long-stay'] },
  // RESTAURANTS
  { name: 'STK ta Bay! Cebu', slug: 'stk-ta-bay-cebu', category: 'FOOD', description: 'The original Cebuano-style lechon (roast pig) restaurant run by the family of the legendary Rico\'s Lechon, serving the most flavorful suckling pig in a city that takes its roast pig very seriously. The lechon cebu with crispy skin and aromatic herb stuffing of lemongrass and tamarind leaves is irreplaceable.', address: 'Baseline Road, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=STK+ta+Bay+Cebu', phone: '+63 32 344 8889', website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/stk-ta-bay-cebu.jpg', tags: ['lechon', 'cebu-style', 'roast-pig', 'iconic', 'must-eat'] },
  { name: 'Abaca Restaurant Cebu', slug: 'abaca-restaurant-cebu', category: 'FOOD', description: 'Cebu\'s most celebrated fine dining restaurant by acclaimed chef Jason Hyatt, serving contemporary cuisine using the finest Cebuano and Visayan ingredients. The tasting menu changes with the seasons and is one of the most sophisticated dining experiences in the Philippines outside Manila.', address: 'Nivel Hills, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Abaca+Restaurant+Cebu', phone: '+63 32 231 5195', website: 'https://abacagroup.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/abaca-restaurant-cebu.jpg', tags: ['fine-dining', 'tasting-menu', 'visayan', 'contemporary', 'chef'] },
  { name: 'Lantaw Floating Native Restaurant Cebu', slug: 'lantaw-floating-restaurant-cebu', category: 'FOOD', description: 'A magical floating restaurant on stilts over a mangrove lagoon in Cordova, serving excellent Filipino seafood and grilled dishes while surrounded by mangrove trees and fireflies at night. Lantaw is a 45-minute drive from Cebu City but worth every minute for the extraordinary experience of dining over water.', address: 'Cordova, Cebu 6017, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Lantaw+Floating+Restaurant+Cebu', phone: '+63 32 231 2929', website: 'https://lantaw.com.ph', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/lantaw-floating-restaurant-cebu.jpg', tags: ['floating', 'mangrove', 'seafood', 'fireflies', 'magical'] },
  { name: 'Larsian BBQ Street Cebu', slug: 'larsian-bbq-cebu', category: 'FOOD', description: 'Cebu\'s beloved open-air barbecue street at Fuente Osmena where dozens of vendors grill pork intestines, chicken innards, and seafood over charcoal for Cebu\'s famous isaw and inihaw culture. Bring friends, order multiple skewers, drink San Miguel Red Horse, and understand why Cebuanos are so proud of their street food.', address: 'Fuente Osmena Circle, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Larsian+BBQ+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/larsian-bbq-cebu.jpg', tags: ['bbq', 'isaw', 'street-food', 'san-miguel', 'evening'] },
  { name: 'Golden Cowrie Cebu', slug: 'golden-cowrie-cebu', category: 'FOOD', description: 'A Cebu institution for over 40 years serving classic Filipino cuisine in a casual garden setting - kinilaw ceviche, sinigang soup, crispy pata pork knuckle, and the most popular kare-kare oxtail peanut stew in the city. Golden Cowrie is where Cebu families celebrate everything and where visitors learn real Filipino food.', address: 'Salinas Drive, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Golden+Cowrie+Cebu', phone: '+63 32 233 5010', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/golden-cowrie-cebu.jpg', tags: ['filipino', 'institution', 'kinilaw', 'kare-kare', 'family'] },
  { name: 'Lab-as Seafood Restaurant Cebu', slug: 'lab-as-seafood-cebu', category: 'FOOD', description: 'A market-style seafood restaurant where you select your fish, prawns, crabs, and squid from an iced display and choose your cooking method. The butter-garlic crab and the crispy tuna jaw are standout dishes - the name means "fresh" in Cebuano and the promise is rigorously kept.', address: 'Banilad, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Lab-as+Seafood+Cebu', phone: '+63 32 233 4567', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/lab-as-seafood-cebu.jpg', tags: ['seafood', 'market-style', 'crab', 'fresh', 'tuna'] },
  // MARKETS
  { name: 'Carbon Market Cebu', slug: 'carbon-market-cebu', category: 'FOOD', description: 'The largest and most chaotic traditional market in the Visayas - a 24-hour market covering several city blocks with fresh produce, dried fish, flowers, live chickens, herbs, and a ground-floor food court. Carbon Market is authentic urban Philippines in concentrated form - equal parts overwhelming and fascinating.', address: 'Carbon Market, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Carbon+Market+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/carbon-market-cebu.jpg', tags: ['market', '24-hour', 'local', 'dried-fish', 'authentic'] },
  { name: 'Taboan Public Market Cebu', slug: 'taboan-public-market-cebu', category: 'FOOD', description: 'The definitive destination for Cebu dried fish and pasalubong food gifts - hundreds of vendors selling dried danggit (dried rabbitfish), dried squid, dried mango, and other Visayan preserved foods that Cebuanos bring back from every trip. The smell is overwhelming; the dried danggit fried for breakfast is extraordinary.', address: 'Taboan Market, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Taboan+Market+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/taboan-public-market-cebu.jpg', tags: ['dried-fish', 'danggit', 'pasalubong', 'dried-mango', 'souvenirs'] },
  { name: 'Ayala Center Cebu', slug: 'ayala-center-cebu', category: 'FOOD', description: 'The premier upscale shopping mall in Cebu with an open-air dining area hosting the best restaurant collection in the city, a well-curated supermarket, and weekly pop-up food markets featuring local producers and artisan food vendors. The Saturday market in the Activity Center has excellent Cebuano street food.', address: 'Cebu Business Park, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Ayala+Center+Cebu', phone: '+63 32 888 3000', website: 'https://ayalacenters.com/cebu', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/ayala-center-cebu.jpg', tags: ['mall', 'food-market', 'artisan', 'restaurants', 'cebuano'] },
  { name: 'Pasil Fish Market Cebu', slug: 'pasil-fish-market-cebu', category: 'FOOD', description: 'The main fish landing and wholesale market on the Cebu waterfront, operational from 3am when fishing boats return from overnight trips. Tuna, mackerel, anchovies, and crab are auctioned in the early morning before the retail section opens to the public - a genuine glimpse of the fishing culture that sustains the city.', address: 'Pasil Fish Port, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Pasil+Fish+Market+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/pasil-fish-market-cebu.jpg', tags: ['fish-market', 'early-morning', 'tuna', 'auction', 'waterfront'] },
  { name: 'IT Park Food Strip Cebu', slug: 'it-park-food-strip-cebu', category: 'FOOD', description: 'A permanent outdoor food and dining strip in Cebu\'s IT Park technology district, with dozens of restaurants, food kiosks, and cafe trucks operating from afternoon until late. The convergence of Philippine BPO workers, students, and travelers creates one of Cebu\'s most lively and affordable food scenes.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=IT+Park+Food+Strip+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/it-park-food-strip-cebu.jpg', tags: ['food-strip', 'it-park', 'evening', 'affordable', 'variety'] },
  // TOURIST SITES
  { name: 'Basilica Minore del Santo Nino Cebu', slug: 'basilica-del-santo-nino-cebu', category: 'CULTURE', description: 'The oldest Catholic church in the Philippines, dating to 1565, housing the miraculous Santo Nino (Holy Child Jesus) statue that Ferdinand Magellan gave to Queen Juana of Cebu in 1521. The annual Sinulog Festival in January draws four million pilgrims in the largest religious celebration in Southeast Asia.', address: 'Osmeña Boulevard, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Basilica+del+Santo+Nino+Cebu', phone: '+63 32 256 2071', website: 'https://basilicadelsantonino.org', priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/basilica-del-santo-nino-cebu.jpg', tags: ['church', 'oldest', '1565', 'sinulog', 'pilgrimage'] },
  { name: 'Fort San Pedro Cebu', slug: 'fort-san-pedro-cebu', category: 'CULTURE', description: 'The oldest and smallest fort in the Philippines, built by Miguel Lopez de Legazpi in 1565 as the first Spanish settlement in Asia. The triangular bastion at the Cebu waterfront has served as a military fort, rebel defense, revolutionary army headquarters, and zoo before becoming a museum and park.', address: 'Plaza Independencia, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Fort+San+Pedro+Cebu', phone: '+63 32 256 2284', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/fort-san-pedro-cebu.jpg', tags: ['fort', '1565', 'spanish', 'museum', 'waterfront'] },
  { name: 'Kawasan Falls Moalboal Cebu', slug: 'kawasan-falls-moalboal-cebu', category: 'NATURE', description: 'A stunning turquoise three-tiered waterfall in the mountains of Moalboal, 90km south of Cebu City, with natural swimming pools and bamboo rafts at the base. The canyon canyoneering adventure through the Matutinao River gorge to the falls is one of the best outdoor activities in the Philippines.', address: 'Badian, Cebu 6031, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Kawasan+Falls+Moalboal+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/kawasan-falls-moalboal-cebu.jpg', tags: ['waterfall', 'turquoise', 'canyoneering', 'swimming', 'adventure'] },
  { name: 'Whale Shark Encounter Oslob Cebu', slug: 'whale-shark-oslob-cebu', category: 'NATURE', description: 'The most popular tourist activity in Cebu - snorkeling with whale sharks (butanding) that have been fed daily by fishermen in Oslob Bay, 4 hours south of Cebu City. Controversial due to the feeding practice but the experience of swimming alongside 6-meter whale sharks remains extraordinary.', address: 'Tan-awan, Oslob, Cebu 6037, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Whale+Shark+Oslob+Cebu', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/whale-shark-oslob-cebu.jpg', tags: ['whale-shark', 'snorkeling', 'oslob', 'wildlife', 'controversial'] },
  { name: 'Magellan\'s Cross Cebu', slug: 'magellans-cross-cebu', category: 'CULTURE', description: 'A wooden cross planted by Portuguese explorer Ferdinand Magellan in 1521 when he baptized Cebu\'s first Filipino Christians, preserved inside a domed chapel beside the Basilica. The tarpaulin ceiling painting depicts the baptism of Rajah Humabon and is one of the most significant Christian historical sites in Asia.', address: 'Magallanes Street, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Magellans+Cross+Cebu', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/magellans-cross-cebu.jpg', tags: ['magellan', '1521', 'historical', 'christian', 'chapel'] },
  { name: 'Moalboal Sardines Run', slug: 'moalboal-sardines-cebu', category: 'NATURE', description: 'One of the world\'s most extraordinary underwater phenomena - a permanent resident shoal of tens of millions of sardines that swirls in massive formations just meters from Moalboal\'s shoreline. You can snorkel directly from the beach at Panagsama to witness the hypnotic spinning ball of millions of fish.', address: 'Panagsama Beach, Moalboal, Cebu 6032, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Moalboal+Sardines+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.9, imageUrl: '/spots/moalboal-sardines-cebu.jpg', tags: ['sardines', 'snorkeling', 'moalboal', 'underwater', 'extraordinary'] },
  { name: 'Heritage of Cebu Monument', slug: 'heritage-of-cebu-monument', category: 'CULTURE', description: 'A dramatic bronze tableau of life-size figures depicting 10 pivotal moments in Cebuano history from Magellan\'s arrival to the Philippine Revolution, installed in the Parian district. The monument is Cebu\'s finest outdoor public art and the surrounding Parian heritage district has several restored Spanish-era houses.', address: 'Parian District, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Heritage+of+Cebu+Monument', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/heritage-of-cebu-monument.jpg', tags: ['monument', 'history', 'heritage', 'parian', 'bronze'] },
  { name: 'Tops Lookout Cebu', slug: 'tops-lookout-cebu', category: 'NATURE', description: 'The highest accessible viewpoint overlooking Cebu City and the surrounding islands, 620m above sea level on Mount Busay. On clear evenings, the panoramic view of the city lights, Mactan Island, and the distant mountains of Leyte and Bohol is one of the most spectacular urban views in the Philippines.', address: 'Busay, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Tops+Lookout+Cebu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/tops-lookout-cebu.jpg', tags: ['viewpoint', 'hilltop', 'night-view', 'panoramic', 'city-lights'] },
  { name: 'Cebu Ocean Park', slug: 'cebu-ocean-park', category: 'CULTURE', description: 'The largest marine theme park in the Philippines with walk-through tunnels, a jellyfish gallery, dolphin shows, manta ray feeding, and touch pools. An excellent rainy-day activity in Cebu and a great introduction to the marine biodiversity of the Philippine Sea for travelers who can\'t dive.', address: 'Sta. Rosa Street, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Cebu+Ocean+Park', phone: '+63 32 238 6668', website: 'https://cebuoceanpark.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/cebu-ocean-park.jpg', tags: ['aquarium', 'marine', 'tunnel', 'dolphins', 'family'] },
  // COWORKING
  { name: 'CeeD Hub Coworking Cebu', slug: 'ceed-hub-coworking-cebu', category: 'COWORKING', description: 'Cebu\'s leading startup and technology coworking hub in IT Park with a strong community of tech entrepreneurs, BPO professionals, and digital nomads. CeeD Hub hosts weekly tech meetups, pitch nights, and startup workshops that give international visitors access to Cebu\'s growing tech scene.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=CeeD+Hub+Coworking+Cebu', phone: '+63 32 505 9876', website: 'https://ceedhub.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/ceed-hub-coworking-cebu.jpg', tags: ['startup', 'tech', 'it-park', 'meetups', 'community'] },
  { name: 'Work + Store Cebu', slug: 'work-store-coworking-cebu', category: 'COWORKING', description: 'A cafe-coworking hybrid in Cebu Business Park where the ground floor serves as a specialty coffee shop and the upper floor is a well-equipped coworking space with private offices. Day passes include the coffee and the multi-level layout keeps work and social time naturally separated.', address: 'Cebu Business Park, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Work+Store+Coworking+Cebu', phone: '+63 32 234 0123', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/work-store-coworking-cebu.jpg', tags: ['cafe-coworking', 'coffee', 'day-pass', 'business-park', 'hybrid'] },
  { name: 'Springboard Labs Cebu', slug: 'springboard-labs-cebu', category: 'COWORKING', description: 'A tech-forward coworking and accelerator space in Cebu with a makerspace, 3D printers, a drone lab, and a strong software development community. International remote workers can access day and week passes with 24-hour badge access, ergonomic chairs, and excellent connectivity.', address: 'IT Park, Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Springboard+Labs+Cebu', phone: '+63 32 233 9012', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/springboard-labs-cebu.jpg', tags: ['makerspace', 'tech', '3d-printer', 'accelerator', '24-hour'] },
  { name: 'MCCWD Business Lounge Cebu', slug: 'mccwd-business-lounge-cebu', category: 'COWORKING', description: 'A professional business lounge in Cebu Business Park with secretarial services, meeting rooms, a mail address, and a coworking floor for short-term visitors. Well-suited for business travelers passing through Cebu who need professional facilities for client meetings and presentations.', address: 'Cebu Business Park, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=MCCWD+Business+Lounge+Cebu', phone: '+63 32 234 5000', website: null, priceRange: 'MID', rating: 4.3, imageUrl: '/spots/mccwd-business-lounge-cebu.jpg', tags: ['business-lounge', 'meeting-rooms', 'professional', 'secretarial', 'short-term'] },
  { name: 'Beanhere Coworking Cebu', slug: 'beanhere-coworking-cebu', category: 'COWORKING', description: 'An atmospheric coworking-cafe in a converted warehouse in the Lahug area with brick walls, exposed beams, excellent specialty coffee, and a focused community of creative professionals and freelancers. The weekly "no-laptop Friday" social evenings transform the space into Cebu\'s best networking happy hour.', address: 'Lahug, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Beanhere+Coworking+Cebu', phone: '+63 917 456 7890', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/beanhere-coworking-cebu.jpg', tags: ['warehouse', 'creative', 'networking', 'specialty-coffee', 'social'] },
  { name: 'The Loft Coworking Cebu', slug: 'the-loft-coworking-cebu', category: 'COWORKING', description: 'A tranquil coworking space on the upper floor of a commercial building in Banilad with natural light, ergonomic furniture, private pods, and a small terrace. The Loft attracts writers, designers, and consultants who prioritize a quiet, distraction-free environment over the social aspects of larger coworking spaces.', address: 'Banilad, Cebu City 6000, Philippines', googleMapsUrl: 'https://maps.google.com/?q=The+Loft+Coworking+Cebu', phone: '+63 32 234 7890', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/the-loft-coworking-cebu.jpg', tags: ['quiet', 'natural-light', 'pods', 'writers', 'focused'] },
  { name: 'Mactan Shrine Cebu', slug: 'mactan-shrine-cebu', category: 'CULTURE', description: 'The historic site on Mactan Island where Lapu-Lapu, the first Filipino hero, defeated and killed Portuguese explorer Ferdinand Magellan on April 27, 1521. Two statues mark the spot - one of Lapu-Lapu raising his sword in victory and one of Magellan - representing the first battle where Filipinos repelled a foreign colonizer.', address: 'Lapu-Lapu City, Mactan Island, Cebu 6015, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Mactan+Shrine+Cebu', phone: null, website: null, priceRange: 'FREE', rating: 4.4, imageUrl: '/spots/mactan-shrine-cebu.jpg', tags: ['historical', 'magellan', 'lapu-lapu', '1521', 'mactan'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Cebu: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
