const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328by00009vi8wt03kvl3s';

const spots = [
  // LUXURY HOTELS
  { name: 'Park Hyatt Saigon', slug: 'park-hyatt-saigon', category: 'ACCOMMODATION', description: "An elegant French colonial-inspired hotel on Lam Son Square across from the Opera House. The Park Hyatt Saigon is HCMC's most refined address - afternoon tea in the lobby, a rooftop pool above the city's energy, and rooms that feel like private apartments.", address: '2 Lam Son Square, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Park+Hyatt+Saigon', phone: '+84 28 3824 1234', website: 'https://saigon.park.hyatt.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/park-hyatt-saigon.jpg', tags: ['luxury', 'colonial', 'opera-house', 'rooftop', 'central'] },
  { name: 'Reverie Saigon', slug: 'reverie-saigon-hcmc', category: 'ACCOMMODATION', description: "An extraordinarily opulent 5-star hotel in the Times Square building with maximalist Italian interiors - Versace tiles, Baccarat crystal, and hand-painted Murano glass ceilings. The most theatrical luxury hotel in Vietnam, loved by travelers who appreciate spectacle.", address: '22-36 Nguyen Hue Boulevard, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=The+Reverie+Saigon', phone: '+84 28 3823 6688', website: 'https://www.thereveriesaigon.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/reverie-saigon-hcmc.jpg', tags: ['luxury', 'opulent', 'italian-design', 'iconic', 'nguyen-hue'] },
  { name: 'Hotel des Arts Saigon', slug: 'hotel-des-arts-saigon', category: 'ACCOMMODATION', description: "A chic boutique hotel in a beautifully restored 1930s building celebrating Vietnamese art and culture. Each floor is curated around a different artistic movement - lacquerware, silk paintings, and contemporary installations line every corridor. Rooftop bar with 360-degree views.", address: '76-78 Nguyen Thi Minh Khai, Vo Thi Sau Ward, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Hotel+des+Arts+Saigon', phone: '+84 28 3989 8888', website: 'https://hoteldesartssaigon.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/hotel-des-arts-saigon.jpg', tags: ['boutique', 'art', 'colonial', 'rooftop', 'culture'] },
  { name: 'Sofitel Saigon Plaza', slug: 'sofitel-saigon-plaza', category: 'ACCOMMODATION', description: "A classic 5-star tower in the heart of District 1 combining French art de vivre with Vietnamese culture. The rooftop pool on the 17th floor overlooks the colonial Opera House district, and the L'Olivier restaurant is one of the city's finest French dining rooms.", address: '17 Le Duan Boulevard, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Sofitel+Saigon+Plaza', phone: '+84 28 3824 1555', website: 'https://all.accor.com/hotel/1558/index.en.shtml', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/sofitel-saigon-plaza.jpg', tags: ['luxury', 'french', 'pool', 'district-1', 'rooftop'] },
  // BUDGET HOTELS
  { name: 'Saigon Backpacker Hostel - Central', slug: 'saigon-backpacker-hostel-central', category: 'ACCOMMODATION', description: "The most reliable budget hotel in District 1 - spotlessly clean, great location on De Tham Street (backpacker alley), fast wifi, and a travel desk that can arrange every trip in southern Vietnam. Private rooms available alongside dorms.", address: '265 De Tham Street, Pham Ngu Lao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Saigon+Backpacker+Hostel+Central', phone: '+84 28 3836 7849', website: 'https://saigonbackpacker.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/saigon-backpacker-hostel-central.jpg', tags: ['budget', 'de-tham', 'reliable', 'travel-desk', 'central'] },
  { name: 'Glow Saigon Hotel', slug: 'glow-saigon-hotel', category: 'ACCOMMODATION', description: "A design-forward boutique hotel in District 1 with bright, minimalist rooms, great wifi, a rooftop terrace with city views, and a location walkable to every major attraction. Excellent value at around $40/night for private rooms with hotel-quality service.", address: '132 Bui Vien Street, Pham Ngu Lao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Glow+Saigon+Hotel', phone: '+84 28 3838 5888', website: 'https://glowsaigon.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/glow-saigon-hotel.jpg', tags: ['boutique', 'bui-vien', 'rooftop', 'design', 'value'] },
  { name: 'The Common Room Project', slug: 'the-common-room-project-hcmc', category: 'ACCOMMODATION', description: "A social co-living hotel concept in the creative District 3 neighborhood loved by digital nomads and long-stay travelers. Private rooms with co-working access, communal kitchen, weekly community events, and curated city guides. The best way to meet HCMC's expat creative community.", address: '55 Nguyen Van Troi Street, Ward 11, Phu Nhuan District, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=The+Common+Room+Project+HCMC', phone: '+84 28 6268 0072', website: 'https://thecommonroomproject.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/the-common-room-project-hcmc.jpg', tags: ['coliving', 'nomad', 'community', 'creative', 'district-3'] },
  { name: 'Bui Vien Walking Street Hotel', slug: 'bui-vien-walking-street-hotel-hcmc', category: 'ACCOMMODATION', description: "On the famous Bui Vien Walking Street - HCMC's backpacker and nightlife strip. Clean, air-conditioned rooms above the action with all the street food, cheap beer, and fellow travelers you could want. For those who want to be in the thick of it at a rock-bottom price.", address: '234 Bui Vien Street, Pham Ngu Lao, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Bui+Vien+Street+Saigon', phone: '+84 28 3836 1234', website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/bui-vien-walking-street-hotel-hcmc.jpg', tags: ['budget', 'bui-vien', 'nightlife', 'backpacker', 'central'] },
  // HOSTELS
  { name: 'Long Hostel Saigon', slug: 'long-hostel-saigon', category: 'ACCOMMODATION', description: "HCMC's most design-conscious hostel - a converted French villa in District 3 with indoor pool, a rooftop garden bar, and photogenic common spaces. Pod bunks with USB charging and privacy curtains, lockers, and a breakfast spread that makes the morning worthwhile.", address: '34 Tran Quoc Thao Street, Ward 7, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Long+Hostel+Saigon', phone: '+84 28 3930 1268', website: 'https://longhostelsaigon.com', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/long-hostel-saigon.jpg', tags: ['design', 'pool', 'villa', 'rooftop', 'district-3'] },
  { name: 'Hideout Hostel Saigon', slug: 'hideout-hostel-saigon', category: 'ACCOMMODATION', description: "A social hostel in the heart of backpacker Pham Ngu Lao with well-organized pub crawls, free walking tours, and a friendly front desk that helps every solo traveler build their Vietnam itinerary. Clean dorms and private rooms, great wifi, and a lively ground-floor bar.", address: '186/4 De Tham Street, Pham Ngu Lao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Hideout+Hostel+Saigon', phone: '+84 28 3837 2662', website: 'https://hideouthostel.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/hideout-hostel-saigon.jpg', tags: ['social', 'pub-crawl', 'walking-tour', 'pham-ngu-lao', 'bar'] },
  { name: 'Onetrip Hostel Saigon', slug: 'onetrip-hostel-saigon', category: 'ACCOMMODATION', description: "A well-run hostel from one of Vietnam's most respected tour operators - Onetrip Saigon offers clean dorms, excellent tour arrangements, and a community board full of travel companions seeking Mekong Delta day trips and Phu Quoc weekenders.", address: '209 De Tham Street, Pham Ngu Lao, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Onetrip+Hostel+Saigon', phone: '+84 28 3920 3888', website: 'https://onetriphostels.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/onetrip-hostel-saigon.jpg', tags: ['hostel', 'tours', 'mekong', 'travel-desk', 'reliable'] },
  { name: 'The Mix Hostel Saigon', slug: 'the-mix-hostel-saigon', category: 'ACCOMMODATION', description: "A boutique hostel in a quiet alley near the Ben Thanh Market that attracts travelers who want central location without Bui Vien chaos. Pod-style bunks, a rooftop hammock garden, and free afternoon iced coffee make it an easy place to spend a few happy days.", address: '103/3 Pham Ngu Lao Street, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=The+Mix+Hostel+Saigon', phone: '+84 28 3836 3636', website: 'https://themixhostel.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/the-mix-hostel-saigon.jpg', tags: ['boutique', 'quiet', 'rooftop', 'hammock', 'ben-thanh'] },
  // CAFES
  { name: 'The Refinery', slug: 'the-refinery-hcmc', category: 'CAFE', description: "A stunning colonial-era opium refinery converted into a lush garden cafe and cocktail bar in District 1. Stone floors, tropical plants climbing old French walls, and a menu of specialty coffee and all-day brunch. The most atmospheric daytime setting in HCMC.", address: '74 Hai Ba Trung Street, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=The+Refinery+HCMC', phone: '+84 28 3823 0509', website: 'https://www.therefinerysaigon.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/the-refinery-hcmc.jpg', tags: ['colonial', 'garden', 'atmospheric', 'brunch', 'heritage'] },
  { name: 'Saigon Oi', slug: 'saigon-oi-cafe-hcmc', category: 'CAFE', description: "A beautiful, thoughtfully designed cafe in District 3 serving Vietnamese-style coffee alongside light meals and fresh juices. The hand-drip ca phe and egg coffee are exceptional, and the rooftop terrace with potted plants and city views is a digital nomad favorite.", address: '112 Tran Hung Dao Street, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Saigon+Oi+Cafe+HCMC', phone: '+84 28 3920 7799', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/saigon-oi-cafe-hcmc.jpg', tags: ['vietnamese-coffee', 'rooftop', 'egg-coffee', 'nomad', 'chill'] },
  { name: 'Bosgaurus Coffee', slug: 'bosgaurus-coffee-hcmc', category: 'CAFE', description: "Saigon's finest specialty coffee roastery with a minimalist, light-filled cafe in the Binh Thanh district. Bosgaurus sources single-origin beans from Da Lat, Buon Ma Thuot, and highland farms across Vietnam, roasting in-house and serving dialed-in espresso and filter options.", address: '12 Dinh Tien Hoang Street, Binh Thanh District, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Bosgaurus+Coffee+HCMC', phone: '+84 93 662 8787', website: 'https://bosgauruscoffee.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/bosgaurus-coffee-hcmc.jpg', tags: ['specialty', 'roastery', 'vietnamese-beans', 'filter', 'minimalist'] },
  { name: 'Cong Caphe Saigon', slug: 'cong-caphe-saigon', category: 'CAFE', description: "The beloved retro Communist-era cafe chain (based in Hanoi) has its HCMC outpost on Dong Khoi, the city's most elegant boulevard. Propaganda posters, military memorabilia, and the addictive coconut coffee - a beloved ritual for every Vietnam traveler.", address: '26 Dong Khoi Street, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Cong+Caphe+Saigon+Dong+Khoi', phone: '+84 28 3823 7979', website: 'https://congcaphe.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/cong-caphe-saigon.jpg', tags: ['retro', 'communist', 'coconut-coffee', 'iconic', 'dong-khoi'] },
  { name: 'Oromia Coffee', slug: 'oromia-coffee-hcmc', category: 'CAFE', description: "A specialty coffee gem in the Binh Thanh neighborhood with a focus on Vietnamese highland beans and African single-origins. The friendly baristas run regular free cupping sessions and the pour-over bar is the best in the city. Popular with HCMC's growing coffee community.", address: '245 Dien Bien Phu Street, Ward 7, Binh Thanh District, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Oromia+Coffee+HCMC', phone: '+84 90 989 8765', website: 'https://www.facebook.com/oromiacoffee.vn', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/oromia-coffee-hcmc.jpg', tags: ['specialty', 'cupping', 'african-origins', 'pour-over', 'community'] },
  { name: 'Cafe Apartment', slug: 'cafe-apartment-hcmc', category: 'CAFE', description: "An entire 1960s residential tower on Nguyen Hue Boulevard turned vertical cafe complex - each floor of the former apartment building now houses a different cafe, boutique, or creative space. One of HCMC's most photographed addresses and a genuinely interesting afternoon of exploration.", address: '42 Nguyen Hue Boulevard, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Cafe+Apartment+HCMC+42+Nguyen+Hue', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/cafe-apartment-hcmc.jpg', tags: ['quirky', 'tower', 'instagrammable', 'multiple-cafes', 'nguyen-hue'] },
  // RESTAURANTS
  { name: 'Nha Hang Ngon', slug: 'nha-hang-ngon-hcmc', category: 'FOOD', description: "HCMC's most loved introduction to Vietnamese regional cuisine - a restored French villa where stalls around the courtyard serve specialties from every Vietnamese province. Banh mi from Hoi An, bun bo from Hue, banh xeo from Da Nang - all under one elegant roof.", address: '160 Pasteur Street, Vo Thi Sau Ward, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Nha+Hang+Ngon+HCMC', phone: '+84 28 3827 7131', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/nha-hang-ngon-hcmc.jpg', tags: ['regional', 'villa', 'vietnamese', 'varied', 'popular'] },
  { name: 'Banh Mi Huynh Hoa', slug: 'banh-mi-huynh-hoa-hcmc', category: 'FOOD', description: "Widely considered the best banh mi in Vietnam - the bold claim is backed by legendary queues at this tiny shophouse on Le Thi Rieng. The pork rolls are stuffed to almost comic excess with pate, cold cuts, pickled daikon, and herbs. Open from 2pm until sold out.", address: '26 Le Thi Rieng Street, Ben Thanh Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Banh+Mi+Huynh+Hoa+HCMC', phone: '+84 90 898 3100', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/banh-mi-huynh-hoa-hcmc.jpg', tags: ['banh-mi', 'legendary', 'queue', 'street-food', 'must-eat'] },
  { name: 'Oc Dao Restaurant', slug: 'oc-dao-restaurant-hcmc', category: 'FOOD', description: "HCMC's famous seafood snail restaurants (quan oc) are a Vietnamese institution - piled-high plates of whelks, clams, sea snails, and oysters cooked in a dozen different sauces. Oc Dao is the best of the cluster on Hoang Sa Street, serving cold beer and fresh shellfish in chaotic, joyful outdoor seating.", address: '134 Hoang Sa Street, Ward 8, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Oc+Dao+Restaurant+HCMC', phone: '+84 28 3930 6398', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/oc-dao-restaurant-hcmc.jpg', tags: ['seafood', 'snails', 'outdoor', 'local', 'beer'] },
  { name: 'The Deck Saigon', slug: 'the-deck-saigon-hcmc', category: 'FOOD', description: "An elevated riverside restaurant in District 2 (Thao Dien) with the best sunset views over the Saigon River. Modern Vietnamese cuisine with French-trained technique, a carefully curated wine list, and a terrace that makes every meal feel like a special occasion.", address: '38 Nguyen U Di Street, Thao Dien Ward, District 2, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=The+Deck+Saigon', phone: '+84 28 3744 6632', website: 'https://thedecksaigon.com', priceRange: 'HIGH', rating: 4.6, imageUrl: '/spots/the-deck-saigon-hcmc.jpg', tags: ['riverside', 'sunset', 'fine-dining', 'thao-dien', 'wine'] },
  { name: 'Pho Hung', slug: 'pho-hung-hcmc', category: 'FOOD', description: "The definitive pho for Ho Chi Minh City - a southern-style bowl with a sweeter, more herb-forward broth than the Hanoi version. Pho Hung has served the same recipe since 1981 at multiple locations across the city. The breakfast crowd at 6am is half the city's office workers.", address: '240 Pasteur Street, Vo Thi Sau Ward, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Pho+Hung+HCMC', phone: '+84 28 3829 9027', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/pho-hung-hcmc.jpg', tags: ['pho', 'southern-style', 'legendary', 'breakfast', '1981'] },
  { name: 'Quan Bui Garden Restaurant', slug: 'quan-bui-garden-restaurant-hcmc', category: 'FOOD', description: "A beautiful, candlelit outdoor restaurant in District 1 set in a tropical garden around an old banyan tree. The menu spans northern and southern Vietnamese classics - com tam (broken rice), ca kho to (clay pot fish), and ca ri ga (chicken curry). One of the most romantic solo dinner settings in the city.", address: '17A Ngo Van Nam Street, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Quan+Bui+Garden+Restaurant+HCMC', phone: '+84 28 3829 1515', website: 'https://quanbui.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/quan-bui-garden-restaurant-hcmc.jpg', tags: ['garden', 'vietnamese', 'atmospheric', 'banyan', 'dinner'] },
  // MARKETS
  { name: 'Ben Thanh Market', slug: 'ben-thanh-market-hcmc', category: 'FOOD', description: "The iconic landmark and social center of HCMC - a covered market with 1,400 stalls selling fabric, spices, clothing, lacquerware, and street food. The surrounding Ben Thanh Street Food Market operates at night with dozens of outdoor restaurants. The landmark clock tower is on every postcard.", address: 'Le Loi Street, Ben Thanh Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Ben+Thanh+Market+HCMC', phone: null, website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/ben-thanh-market-hcmc.jpg', tags: ['iconic', 'landmark', 'fabric', 'night-market', 'central'] },
  { name: 'Cho Binh Tay Market', slug: 'cho-binh-tay-market-hcmc', category: 'FOOD', description: "The real wholesale market of Cholon (HCMC's Chinatown) - a bustling 1920s covered market with a Chinese pagoda-style tower. Less touristy than Ben Thanh, Binh Tay is where local restaurateurs and traders shop for spices, dried goods, textiles, and Vietnamese-Chinese products.", address: '57A Thap Muoi Street, Ward 2, District 6, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Cho+Binh+Tay+Market+HCMC', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/cho-binh-tay-market-hcmc.jpg', tags: ['cholon', 'chinatown', 'wholesale', 'authentic', 'spices'] },
  { name: 'Thao Dien Night Market', slug: 'thao-dien-night-market-hcmc', category: 'FOOD', description: "A weekly outdoor night market in the expat enclave of Thao Dien (District 2) with a strong international food selection - wood-fired pizza, Mexican tacos, Thai curries, and Vietnamese classics all in one spot. Popular with the city's expat families and long-stay digital nomads.", address: 'Thao Dien Ward, District 2, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Thao+Dien+Night+Market+HCMC', phone: null, website: null, priceRange: 'MID', rating: 4.3, imageUrl: '/spots/thao-dien-night-market-hcmc.jpg', tags: ['night-market', 'expat', 'international', 'thao-dien', 'families'] },
  { name: 'Cho Lon (Chinatown) Street Food', slug: 'cholon-chinatown-hcmc', category: 'FOOD', description: "HCMC's Chinatown (Cho Lon) is a layered world of Chinese clan houses, Buddhist temples, herbal medicine shops, and food stalls serving dim sum, braised pork rice, and century egg porridge. The Thien Hau Temple and the narrow market lanes behind it are worth half a day.", address: 'District 5, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Cho+Lon+Chinatown+HCMC', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/cholon-chinatown-hcmc.jpg', tags: ['chinatown', 'dim-sum', 'temple', 'heritage', 'food'] },
  { name: 'Bui Vien Walking Street Night Market', slug: 'bui-vien-night-market-hcmc', category: 'FOOD', description: "HCMC's nightly pedestrianized street festival - from 7pm the Bui Vien strip closes to traffic and becomes a wall-to-wall carnival of street food carts, beer vendors, live music, and fire performers. Chaotic, cheap, and brilliantly fun for solo travelers.", address: 'Bui Vien Street, Pham Ngu Lao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Bui+Vien+Walking+Street+HCMC', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/bui-vien-night-market-hcmc.jpg', tags: ['nightlife', 'street-food', 'walking-street', 'backpacker', 'beer'] },
  // TOURIST SITES
  { name: 'War Remnants Museum', slug: 'war-remnants-museum-hcmc', category: 'CULTURE', description: "The most powerful and sobering museum in Southeast Asia - a comprehensive documentation of the Vietnam War through photographs, military hardware, and first-person accounts. The third floor's photo journalism exhibit by war correspondents is unforgettable. Plan 2-3 hours.", address: '28 Vo Van Tan Street, Vo Thi Sau Ward, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=War+Remnants+Museum+HCMC', phone: '+84 28 3930 5587', website: 'https://baotangchungtichchientranh.vn', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/war-remnants-museum-hcmc.jpg', tags: ['museum', 'war', 'history', 'powerful', 'photography'] },
  { name: 'Cu Chi Tunnels', slug: 'cu-chi-tunnels-hcmc', category: 'CULTURE', description: "A 250km underground network used by Viet Cong soldiers during the Vietnam War, now preserved as a memorial site. Visitors can crawl through widened tunnel sections, see tunnel traps and weapons exhibits, and understand the ingenuity of guerrilla warfare firsthand. 40km from central HCMC.", address: 'Phu Hiep Hamlet, Phu My Hung Ward, Cu Chi District, Ho Chi Minh City, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Cu+Chi+Tunnels+HCMC', phone: '+84 28 3794 8830', website: 'https://www.diaochocuchitunnel.org.vn', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/cu-chi-tunnels-hcmc.jpg', tags: ['history', 'tunnels', 'war', 'day-trip', 'underground'] },
  { name: 'Reunification Palace', slug: 'reunification-palace-hcmc', category: 'CULTURE', description: "The former presidential palace of South Vietnam - the site where a North Vietnamese tank crashed through the gates on April 30, 1975, ending the Vietnam War. The entire 1960s modernist complex is preserved intact, including the war room bunker in the basement.", address: '135 Nam Ky Khoi Nghia Street, Ben Thanh Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Reunification+Palace+HCMC', phone: '+84 28 3822 3652', website: 'https://dinhdoclap.gov.vn', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/reunification-palace-hcmc.jpg', tags: ['historic', 'presidential-palace', 'war', '1975', 'bunker'] },
  { name: 'Notre-Dame Cathedral Basilica of Saigon', slug: 'notre-dame-cathedral-hcmc', category: 'CULTURE', description: "A twin red-brick neo-Romanesque cathedral built by French colonists between 1877 and 1883 using materials imported entirely from France, including the red bricks from Marseille. Standing in the heart of District 1, it remains the most recognized landmark in Ho Chi Minh City.", address: '1 Cong Xa Paris Square, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Notre+Dame+Cathedral+Saigon+HCMC', phone: '+84 28 3822 0477', website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/notre-dame-cathedral-hcmc.jpg', tags: ['cathedral', 'french-colonial', 'landmark', 'architecture', 'free'] },
  { name: 'Jade Emperor Pagoda', slug: 'jade-emperor-pagoda-hcmc', category: 'CULTURE', description: "HCMC's most atmospheric Chinese-Vietnamese temple - a 1909 Taoist pagoda filled with elaborate carved deities, incense smoke, and turtle ponds. Barack Obama visited in 2016 and released turtles into the pond. One of the most visually rich temple experiences in southern Vietnam.", address: '73 Mai Thi Luu Street, Da Kao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Jade+Emperor+Pagoda+HCMC', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/jade-emperor-pagoda-hcmc.jpg', tags: ['temple', 'taoist', 'incense', 'turtles', 'atmospheric'] },
  { name: 'Nguyen Hue Walking Street', slug: 'nguyen-hue-walking-street-hcmc', category: 'CULTURE', description: "HCMC's grand pedestrian boulevard connecting the Saigon River waterfront to the historic City Hall. Lined with fountains, flower beds, and open-air cafes, it comes alive at night with cyclists, families, street performers, and the full panorama of Saigon urban life.", address: 'Nguyen Hue Boulevard, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Nguyen+Hue+Walking+Street+HCMC', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/nguyen-hue-walking-street-hcmc.jpg', tags: ['boulevard', 'walking', 'evening', 'free', 'river-view'] },
  { name: 'Mekong Delta Day Trip', slug: 'mekong-delta-day-trip-hcmc', category: 'NATURE', description: "A full-day boat journey through the Mekong Delta's maze of rivers, rice paddies, and floating markets. Most tours depart from HCMC at 7am and visit My Tho or Ben Tre - coconut candy workshops, rowing through mangrove tunnels, and lunch on a river island. Every travel desk in Pham Ngu Lao books them.", address: 'Departs from District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=My+Tho+Mekong+Delta+Vietnam', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/mekong-delta-day-trip-hcmc.jpg', tags: ['day-trip', 'mekong', 'boat', 'rice-paddies', 'floating-market'] },
  { name: 'Thien Hau Temple - Cho Lon', slug: 'thien-hau-temple-hcmc', category: 'CULTURE', description: "The most important Chinese temple in Vietnam - an 18th-century Cantonese temple dedicated to the goddess Thien Hau (Queen of Heaven), patron of sailors. The rooftop ceramic decorations, incense coil ceiling, and surrounding herbal medicine market make it an all-morning exploration.", address: '710 Nguyen Trai Street, Ward 11, District 5, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Thien+Hau+Temple+HCMC', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/thien-hau-temple-hcmc.jpg', tags: ['temple', 'chinese', 'incense', 'cantonese', 'free'] },
  { name: 'Bui Vien Street Nightlife', slug: 'bui-vien-nightlife-hcmc', category: 'NIGHTLIFE', description: "Southeast Asia's most famous backpacker party strip - open-air bars, live DJ music, fire shows, and 50-cent beers every night of the week. It's loud, chaotic, and exactly what you need after a day at the war museum. Start at 9pm, which is when it comes fully alive.", address: 'Bui Vien Street, Pham Ngu Lao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Bui+Vien+Street+HCMC', phone: null, website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/bui-vien-nightlife-hcmc.jpg', tags: ['nightlife', 'backpacker', 'bar', 'party', 'cheap'] },
  { name: 'Saigon Skydeck (Bitexco Tower)', slug: 'saigon-skydeck-bitexco', category: 'CULTURE', description: "The 49th-floor observation deck of the iconic Bitexco Financial Tower - a helicopter landing pad jutting from the 52nd floor is the building's signature feature. On clear days the view encompasses the Saigon River delta, the entire city grid, and the rice paddies beyond.", address: '2 Hai Trieu Street, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Saigon+Skydeck+Bitexco+Tower', phone: '+84 28 3915 6156', website: 'https://www.bitexcofinancialtower.com/skydeck', priceRange: 'MID', rating: 4.3, imageUrl: '/spots/saigon-skydeck-bitexco.jpg', tags: ['views', 'skydeck', 'tower', 'helicopter-pad', 'panoramic'] },
  // COWORKING
  { name: 'Toong Coworking HCMC', slug: 'toong-coworking-hcmc', category: 'COWORKING', description: "Vietnam's biggest coworking chain brings the same premium formula to Saigon - high-speed fiber, private offices, meeting rooms, and a schedule of startup events. The Nguyen Thi Minh Khai flagship in District 3 is the largest and most social location.", address: '364 Cong Hoa Street, Ward 13, Tan Binh District, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Toong+Coworking+HCMC', phone: '+84 28 7300 7979', website: 'https://toong.co', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/toong-coworking-hcmc.jpg', tags: ['coworking', 'premium', 'fiber', 'events', 'chain'] },
  { name: 'Dreamplex Coworking Saigon', slug: 'dreamplex-coworking-saigon', category: 'COWORKING', description: "HCMC's most design-forward coworking space with four locations across the city. Dreamplex specializes in creating a community experience - daily programming, health and wellness perks, and a carefully curated membership. The Dien Bien Phu location has a stunning garden rooftop.", address: '21 Nguyen Trung Ngan Street, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Dreamplex+Coworking+Saigon', phone: '+84 28 3827 2332', website: 'https://dreamplex.co', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/dreamplex-coworking-saigon.jpg', tags: ['coworking', 'design', 'community', 'wellness', 'rooftop'] },
  { name: 'Kafnu Saigon', slug: 'kafnu-saigon-hcmc', category: 'COWORKING', description: "A hybrid coworking, hotel, and social club in a stunning converted industrial building near the Ben Thanh Market. Kafnu caters to the nomadic professional - daily work passes, event memberships, or extended monthly stays with accommodation all available under one roof.", address: '16 Huynh Khuong Ninh Street, Da Kao Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Kafnu+Saigon+HCMC', phone: '+84 28 3911 0779', website: 'https://kafnu.com/saigon', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/kafnu-saigon-hcmc.jpg', tags: ['coliving', 'coworking', 'hybrid', 'nomad', 'industrial'] },
  { name: 'UP Coworking HCMC', slug: 'up-coworking-hcmc', category: 'COWORKING', description: "Vietnam's reliable mid-market coworking chain operates multiple HCMC locations with the same formula: fast fiber, ergonomic chairs, AC, private booths, and day passes from 100,000 VND. The District 1 location near Bui Vien is best for solo travelers.", address: '53 Vo Van Tan Street, Vo Thi Sau Ward, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=UP+Coworking+HCMC', phone: '+84 28 7300 1818', website: 'https://up.edu.vn', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/up-coworking-hcmc.jpg', tags: ['coworking', 'budget', 'day-pass', 'reliable', 'chain'] },
  { name: 'Circo Coworking Saigon', slug: 'circo-coworking-saigon', category: 'COWORKING', description: "The Hanoi-born creative coworking brand's southern outpost - an airy, plant-filled space in the Binh Thanh District with dedicated desks, private meeting rooms, and a community of designers and freelancers. Day passes and monthly memberships both available.", address: '98 Truong Dinh Street, Vo Thi Sau Ward, District 3, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=Circo+Coworking+Saigon', phone: '+84 28 3825 8688', website: 'https://circo.co', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/circo-coworking-saigon.jpg', tags: ['coworking', 'creative', 'plants', 'design', 'freelancers'] },
  { name: 'WE Work HCMC', slug: 'wework-hcmc', category: 'COWORKING', description: "WeWork's flagship Vietnam location occupies five floors of the Friendship Tower in District 1 with the brand's signature amenities - unlimited espresso, phone booths, rooftop terrace, and a global community network. Best for corporate remote workers on day passes.", address: '31 Le Duan Boulevard, Ben Nghe Ward, District 1, Ho Chi Minh City 700000, Vietnam', googleMapsUrl: 'https://maps.google.com/?q=WeWork+HCMC+Le+Duan', phone: '+84 28 7101 4440', website: 'https://www.wework.com/l/vietnam--ho-chi-minh-city', priceRange: 'HIGH', rating: 4.5, imageUrl: '/spots/wework-hcmc.jpg', tags: ['wework', 'premium', 'global', 'espresso', 'rooftop'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('HCMC: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
