const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfq04000vvimohm63l3h1';

const spots = [
  { name: 'Hotel Alfonso XIII', slug: 'hotel-alfonso-xiii-seville', category: 'ACCOMMODATION', description: "Spain's most magnificent hotel — a Mudejar Revival palace built for King Alfonso XIII's 1929 Ibero-American Exposition, with a central courtyard of orange trees and fountains, Moorish arches, hand-painted Sevillian tiles, and a rooftop pool. The most beautiful hotel in Andalusia.", address: 'Calle de San Fernando 2, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Alfonso+XIII+Seville', phone: '+34 954 917 000', website: 'https://www.hotel-alfonsoxiii-seville.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/hotel-alfonso-xiii-seville.jpg', tags: ['luxury', 'mudejar', 'palace', '1929', 'iconic'] },
  { name: 'Hotel Mercer Sevilla', slug: 'hotel-mercer-seville', category: 'ACCOMMODATION', description: "A boutique hotel in a carefully restored 18th-century palace in the Santa Cruz quarter with a rooftop pool overlooking the Giralda tower, a tapas restaurant in the Andalusian courtyard, and beautifully curated rooms with original architectural details.", address: 'Calle Castelar 26, 41001 Seville', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Mercer+Seville', phone: '+34 954 225 000', website: 'https://www.mercersevilla.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/hotel-mercer-seville.jpg', tags: ['boutique', 'palace', 'rooftop-pool', 'giralda-view', 'santa-cruz'] },
  { name: 'The Indigo Hotel Seville', slug: 'the-indigo-seville', category: 'ACCOMMODATION', description: "A stylish boutique hotel inside a converted 18th-century palace near the Cathedral with characteristic Seville-inspired design, a courtyard bar, and the best mid-range location in the city.", address: 'Calle Teodosio 22, 41002 Seville', googleMapsUrl: 'https://maps.google.com/?q=Indigo+Hotel+Seville', phone: '+34 954 980 000', website: 'https://www.ihg.com/hotelindigo/hotels/us/en/seville', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/the-indigo-seville.jpg', tags: ['boutique', 'palace', 'courtyard', 'cathedral', 'mid-range'] },
  { name: 'Oasis Backpackers\' Palace Seville', slug: 'oasis-backpackers-seville', category: 'ACCOMMODATION', description: "Seville's best hostel — a converted Andalusian mansion near the Cathedral with a rooftop pool, hammock terrace, free tapas at check-in, and a social atmosphere that has made it the social hub for solo travelers in southern Spain for over a decade.", address: 'Calle del Almirante Ulloa 1, 41001 Seville', googleMapsUrl: 'https://maps.google.com/?q=Oasis+Backpackers+Seville', phone: '+34 954 293 777', website: 'https://www.oasisseville.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/oasis-backpackers-seville.jpg', tags: ['hostel', 'pool', 'rooftop', 'free-tapas', 'social'] },
  // CAFES
  { name: 'Lalola Café Seville', slug: 'lalola-cafe-seville', category: 'CAFE', description: "A beautiful café in the Triana neighborhood with excellent specialty coffee, homemade cakes, and a terrace overlooking the Guadalquivir riverbank. The best work-friendly café in Seville with reliable wifi and natural light all morning.", address: 'Calle Pagés del Corro 90, 41010 Seville', googleMapsUrl: 'https://maps.google.com/?q=Lalola+Cafe+Seville', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/lalola-cafe-seville.jpg', tags: ['specialty', 'triana', 'terrace', 'work-friendly', 'wifi'] },
  { name: 'Café Central Seville', slug: 'cafe-central-seville', category: 'CAFE', description: "A classic Sevillian café on the edge of Alameda de Hércules with marble counters, tiled walls, strong café solo, and the best churros con chocolate in the neighborhood. Open since 1920; the morning ritual here is as Sevillian as flamenco.", address: 'Alameda de Hércules 62, 41002 Seville', googleMapsUrl: 'https://maps.google.com/?q=Cafe+Central+Seville', phone: '+34 954 376 888', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/cafe-central-seville.jpg', tags: ['classic', 'churros', 'marble', '1920', 'morning-ritual'] },
  // FOOD
  { name: 'Bar El Comercio', slug: 'bar-el-comercio-seville', category: 'FOOD', description: "Seville's most legendary tapas bar near the Cathedral — a standing-room bar under a vaulted 19th-century ceiling where a glass of cold fino sherry and a plate of montaditos (small sandwiches) costs less than €3. The bartenders have worked here for decades.", address: 'Calle Lineros 9, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=Bar+El+Comercio+Seville', phone: '+34 954 221 688', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/bar-el-comercio-seville.jpg', tags: ['tapas', 'fino', 'standing-bar', 'legendary', 'cheap'] },
  { name: 'La Azotea Seville', slug: 'la-azotea-seville', category: 'FOOD', description: "The most creative tapas restaurant in Seville — a modern spin on Andalusian classics with inventive croquetas, rabo de toro reinventions, and the finest local wine selection. Multiple locations; the Jesús del Gran Poder branch is the most consistent.", address: 'Calle Jesús del Gran Poder 31, 41002 Seville', googleMapsUrl: 'https://maps.google.com/?q=La+Azotea+Seville', phone: '+34 955 116 748', website: 'https://www.laazotea.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/la-azotea-seville.jpg', tags: ['creative-tapas', 'modern', 'rabo-de-toro', 'wine', 'best-in-city'] },
  { name: 'Mercado de Triana', slug: 'mercado-de-triana-seville', category: 'FOOD', description: "Seville's most atmospheric food market — a 1948 building on the edge of the Triana bridge with fish stalls, vegetable vendors, and tapas bars inside. The ceramic tile murals documenting Triana's history are extraordinary; the fresh fish counter is the finest in the city.", address: 'Plaza del Altozano s/n, 41010 Seville', googleMapsUrl: 'https://maps.google.com/?q=Mercado+de+Triana+Seville', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/mercado-de-triana-seville.jpg', tags: ['market', 'triana', 'ceramic-tiles', 'fish', 'tapas-bars'] },
  // CULTURE
  { name: 'Seville Cathedral & Giralda', slug: 'seville-cathedral', category: 'CULTURE', description: "The largest Gothic cathedral in the world — a building so vast that when construction began in 1401, the canons declared 'Let us build a church so large that those who see it finished will think we were mad.' Christopher Columbus is buried here. The Giralda tower view over Seville is incomparable.", address: 'Av. de la Constitución s/n, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=Seville+Cathedral', phone: '+34 954 214 971', website: 'https://www.catedraldesevilla.es', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/seville-cathedral.jpg', tags: ['gothic', 'largest', 'columbus', 'giralda', 'must-see'] },
  { name: 'Real Alcázar of Seville', slug: 'real-alcazar-seville', category: 'CULTURE', description: "The oldest royal palace still in use in Europe — a UNESCO World Heritage complex of Moorish, Mudejar, and Renaissance architecture begun in the 9th century. The Patio de las Doncellas, the royal gardens, and the underground baths are extraordinary. Game of Thrones' Dorne was filmed here.", address: 'Patio de Banderas s/n, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=Real+Alcazar+Seville', phone: '+34 954 502 324', website: 'https://www.alcazarsevilla.org', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/real-alcazar-seville.jpg', tags: ['moorish', 'mudejar', 'royal-palace', 'game-of-thrones', 'gardens'] },
  { name: 'Plaza de España Seville', slug: 'plaza-de-espana-seville', category: 'CULTURE', description: "Spain's most spectacular public square — a semicircular Renaissance Revival building built for the 1929 Exposition with a canal, rowing boats, and 48 ceramic tile alcoves depicting every province of Spain. The architect Aníbal González designed it as a national tribute; the result is extraordinary.", address: 'Av. Isabel la Católica s/n, 41013 Seville', googleMapsUrl: 'https://maps.google.com/?q=Plaza+de+Espana+Seville', phone: null, website: null, priceRange: 'FREE', rating: 4.8, imageUrl: '/spots/plaza-de-espana-seville.jpg', tags: ['renaissance-revival', '1929', 'ceramic-tiles', 'canal', 'must-see'] },
  { name: 'Barrio de Santa Cruz', slug: 'barrio-santa-cruz-seville', category: 'CULTURE', description: "Seville's most atmospheric quarter — the former Jewish ghetto turned labyrinthine neighborhood of whitewashed houses, orange-blossom patios, and narrow alleys that don't appear on most maps. The city of Seville that existed before tourism discovered it still exists in the inner courtyards.", address: 'Santa Cruz, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=Barrio+Santa+Cruz+Seville', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/barrio-santa-cruz-seville.jpg', tags: ['jewish-quarter', 'whitewashed', 'patios', 'labyrinthine', 'orange-blossom'] },
  { name: 'Torre del Oro', slug: 'torre-del-oro-seville', category: 'CULTURE', description: "Seville's most recognizable medieval tower — a 13th-century Almohad military watchtower on the Guadalquivir riverbank, once linked by a chain to a twin tower to control river traffic. Now houses a small naval museum. The view from the top at golden hour, with the river and city below, is beautiful.", address: 'Paseo de Cristóbal Colón s/n, 41001 Seville', googleMapsUrl: 'https://maps.google.com/?q=Torre+del+Oro+Seville', phone: '+34 954 222 419', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/torre-del-oro-seville.jpg', tags: ['medieval', 'almohad', 'guadalquivir', 'naval-museum', '13th-century'] },
  { name: 'Parque de María Luisa', slug: 'parque-de-maria-luisa-seville', category: 'NATURE', description: "Seville's most beautiful park — a 19th-century garden of palm trees, fountains, duck ponds, and ceramic-tiled benches surrounding the Plaza de España. Horse-drawn carriages clip through the avenues; the sounds of cicadas and water are the most Sevillian sensory experience on a hot afternoon.", address: 'Parque de María Luisa, 41013 Seville', googleMapsUrl: 'https://maps.google.com/?q=Parque+de+Maria+Luisa+Seville', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/parque-de-maria-luisa-seville.jpg', tags: ['park', 'palm-trees', 'fountains', 'carriages', 'afternoon'] },
  // FLAMENCO
  { name: 'Tablao Flamenco El Arenal', slug: 'tablao-el-arenal-seville', category: 'CULTURE', description: "Seville's most respected flamenco tablao — a small venue in the El Arenal district with professional Sevillian performers, an intimate 150-seat room, and none of the tourist-trap dilution that affects some flamenco venues. The show begins at 8pm and 10pm; dinner optional.", address: 'Calle de Rodó 7, 41001 Seville', googleMapsUrl: 'https://maps.google.com/?q=Tablao+Flamenco+El+Arenal+Seville', phone: '+34 954 216 492', website: 'https://www.tablaoelareanalsevilla.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/tablao-el-arenal-seville.jpg', tags: ['flamenco', 'tablao', 'authentic', 'intimate', 'must-do'] },
  // COWORKING
  { name: 'Coconet Coworking Seville', slug: 'coconet-coworking-seville', category: 'COWORKING', description: "Seville's leading coworking space in the Nervión business district — a professional environment with private offices, hot desks, meeting rooms, and a member base of local startups and international remote workers. Day passes available; strong startup ecosystem connections.", address: 'Avenida de la Buhaira 2, 41018 Seville', googleMapsUrl: 'https://maps.google.com/?q=Coconet+Coworking+Seville', phone: '+34 955 636 360', website: 'https://www.coconet.es', priceRange: 'MID', rating: 4.4, imageUrl: '/spots/coconet-coworking-seville.jpg', tags: ['coworking', 'nervion', 'professional', 'day-pass', 'startup'] },
  { name: 'The Pool Seville', slug: 'the-pool-seville', category: 'COWORKING', description: "A relaxed, design-forward coworking space in the Alameda neighborhood — popular with digital nomads, creative freelancers, and remote workers who want a social atmosphere alongside productivity. Day passes from €10; the exposed brick and natural light are excellent.", address: 'Calle Amor de Dios 15, 41002 Seville', googleMapsUrl: 'https://maps.google.com/?q=The+Pool+Coworking+Seville', phone: '+34 663 397 977', website: 'https://www.thepoolseville.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/the-pool-seville.jpg', tags: ['coworking', 'alameda', 'nomad', 'day-pass', 'relaxed'] },
  // WELLNESS / NIGHTLIFE
  { name: 'Aire de Sevilla Ancient Baths', slug: 'aire-de-sevilla-baths', category: 'WELLNESS', description: "Thermal baths in a beautifully restored 14th-century Moorish building — pools of different temperatures, a steam room, a flotation bath, and optional massages in an atmosphere of candlelight and Arabesque architecture. The most atmospheric wellness experience in Seville.", address: 'Calle Aire 15, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=Aire+de+Sevilla+Baths', phone: '+34 955 010 024', website: 'https://www.airedesevilla.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/aire-de-sevilla-baths.jpg', tags: ['hammam', 'moorish', 'thermal', 'candlelight', 'wellness'] },
  { name: 'El Garlochí Bar Seville', slug: 'el-garlochi-seville', category: 'NIGHTLIFE', description: "Seville's most extraordinary bar — an extravagant religious-kitsch interior of icons, incense, and bleeding-heart imagery where the signature cocktail is the Sangre de Cristo (Blood of Christ). Campy, irreverent, and absolutely unique to Seville's particular brand of Catholic baroque culture.", address: 'Calle de los Boteros 26, 41004 Seville', googleMapsUrl: 'https://maps.google.com/?q=El+Garlochi+Seville', phone: '+34 669 441 736', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/el-garlochi-seville.jpg', tags: ['bar', 'religious-kitsch', 'unique', 'campy', 'iconic'] },
  { name: 'Mercado Lonja del Barranco', slug: 'mercado-lonja-del-barranco-seville', category: 'FOOD', description: "Seville's most beautiful food market — a 1883 Gustave Eiffel-designed iron pavilion on the Guadalquivir waterfront converted into a gourmet market with 20 food stalls, a cocktail bar, and the finest terrace views of the Torre del Oro. Excellent for a solo dinner at the bar.", address: 'Calle Arjona s/n, 41001 Seville', googleMapsUrl: 'https://maps.google.com/?q=Mercado+Lonja+del+Barranco+Seville', phone: '+34 954 220 095', website: 'https://www.lonjadelbarranco.com', priceRange: 'MID', rating: 4.4, imageUrl: '/spots/mercado-lonja-del-barranco-seville.jpg', tags: ['eiffel', 'food-market', 'waterfront', 'torre-del-oro-view', 'solo-dinner'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Seville: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
