const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfro60011vimoehlh7pei';

const spots = [
  { name: 'Hotel Telegraaf Tallinn', slug: 'hotel-telegraaf-tallinn', category: 'ACCOMMODATION', description: "Tallinn's most elegant luxury hotel in a converted 19th-century telegraph station on Vene Street in the Old Town — beautiful Art Nouveau interiors, an excellent restaurant, and a spa in the vaulted cellars. The most atmospheric stay in the medieval city.", address: 'Vene 9, 10123 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Telegraaf+Tallinn', phone: '+372 600 0600', website: 'https://www.telegraafhotel.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/hotel-telegraaf-tallinn.jpg', tags: ['luxury', 'art-nouveau', 'old-town', 'spa', 'telegraph'] },
  { name: 'Meriton Grand Conference & Spa', slug: 'meriton-grand-tallinn', category: 'ACCOMMODATION', description: "A well-run 4-star hotel on Toompea hill with a large spa, excellent buffet breakfast, and panoramic views over the Old Town roofscape from the upper floors. One of the best-value luxury-adjacent stays in Tallinn.", address: 'Toompuiestee 27, 10149 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Meriton+Grand+Tallinn', phone: '+372 667 7000', website: 'https://www.meritonhotels.com/tallinn/grand', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/meriton-grand-tallinn.jpg', tags: ['spa', 'toompea', 'old-town-views', 'buffet', 'mid-range'] },
  { name: 'Hostel Vana Tom Tallinn', slug: 'hostel-vana-tom-tallinn', category: 'ACCOMMODATION', description: "A beloved budget hostel inside the Old Town walls — low ceilings, cozy dorms, and a position in the medieval heart of the city that has made it the meeting point for budget travelers in Tallinn for over 20 years.", address: 'Väike-Karja 1, 10140 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Hostel+Vana+Tom+Tallinn', phone: '+372 631 3252', website: 'https://www.hostelvanatom.ee', priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/hostel-vana-tom-tallinn.jpg', tags: ['hostel', 'old-town', 'budget', 'medieval', 'cozy'] },
  { name: 'My City Hotel Tallinn', slug: 'my-city-hotel-tallinn', category: 'ACCOMMODATION', description: "A smart, affordable boutique hotel in the city center just outside the Old Town walls with clean modern rooms, excellent service, and a location that means walking to all attractions takes under 10 minutes.", address: 'Odessa 2, 10111 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=My+City+Hotel+Tallinn', phone: '+372 626 5100', website: 'https://www.mycityhotel.ee', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/my-city-hotel-tallinn.jpg', tags: ['boutique', 'central', 'clean', 'affordable', 'walkable'] },
  // CAFES
  { name: 'Rösterei Tallinn', slug: 'rosterei-tallinn', category: 'CAFE', description: "Estonia's finest specialty coffee roastery — a beautifully designed space in the Kalamaja neighborhood where beans from verified sustainable farms are roasted weekly and served as precision filter and espresso. The standard for specialty coffee in the Baltic states.", address: 'Telliskivi 60a/3, 10412 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Rosterei+Tallinn', phone: null, website: 'https://www.rosterei.ee', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/rosterei-tallinn.jpg', tags: ['specialty', 'roastery', 'kalamaja', 'sustainable', 'precision'] },
  { name: 'Café Maiasmokk', slug: 'cafe-maiasmokk-tallinn', category: 'CAFE', description: "Estonia's oldest café, in continuous operation since 1864 — an Art Nouveau confectioner's on Pikk Street in the Old Town with hand-painted wallpaper, marzipan sculptures, and the finest Estonian pastries: kringel (braided cardamom bread), kringle, and the legendary chocolate-covered marzipan.", address: 'Pikk 16, 10123 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Cafe+Maiasmokk+Tallinn', phone: '+372 646 4066', website: 'https://www.maiasmokk.ee', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/cafe-maiasmokk-tallinn.jpg', tags: ['oldest', '1864', 'art-nouveau', 'marzipan', 'kringel'] },
  { name: 'F-Hoone Tallinn', slug: 'f-hoone-tallinn', category: 'CAFE', description: "The social hub of Tallinn's Telliskivi Creative City — a large, eclectic café-restaurant in a converted factory building with excellent coffee, a varied menu, free wifi, and the most sociable working atmosphere in the city. The best digital nomad café in Estonia.", address: 'Telliskivi 60a, 10412 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=F-Hoone+Tallinn', phone: '+372 515 5455', website: 'https://www.fhoone.ee', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/f-hoone-tallinn.jpg', tags: ['creative-city', 'factory', 'nomad', 'wifi', 'social'] },
  // FOOD
  { name: 'NOA Restaurant Tallinn', slug: 'noa-restaurant-tallinn', category: 'FOOD', description: "The best restaurant in Estonia — a Nordic-influenced fine dining experience on Tallinn Bay with floor-to-ceiling windows over the water, a 5-course tasting menu of Estonian seasonal ingredients, and a natural wine list that features the finest producers of Northern Europe.", address: 'Ranna tee 3, 11911 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=NOA+Restaurant+Tallinn', phone: '+372 508 3877', website: 'https://www.noarestaurant.ee', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/noa-restaurant-tallinn.jpg', tags: ['fine-dining', 'nordic', 'bay-views', 'tasting-menu', 'estonian'] },
  { name: 'Balti Jaam Market Tallinn', slug: 'balti-jaam-market-tallinn', category: 'FOOD', description: "Tallinn's main food market behind the Baltic Station — Soviet-era concrete stalls selling smoked Baltic herring, sauerkraut, rye bread, fresh mushrooms from the forest, and Estonian dairy products. The most authentic and affordable food experience in the city.", address: 'Kopli 1, 10416 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Balti+Jaam+Market+Tallinn', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/balti-jaam-market-tallinn.jpg', tags: ['market', 'herring', 'rye-bread', 'soviet', 'authentic'] },
  { name: 'Rataskaevu 16 Tallinn', slug: 'rataskaevu-16-tallinn', category: 'FOOD', description: "The most beloved restaurant in the Old Town — a cozy stone-walled bistro serving modern Estonian cuisine: elk stew, pork with black pudding, and wild berry desserts, in a warm atmosphere that has made it the hardest reservation in Tallinn for a decade.", address: 'Rataskaevu 16, 10123 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Rataskaevu+16+Tallinn', phone: '+372 642 4025', website: 'https://www.rataskaevu16.ee', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/rataskaevu-16-tallinn.jpg', tags: ['estonian', 'stone-walls', 'elk', 'cozy', 'beloved'] },
  // CULTURE
  { name: 'Tallinn Old Town', slug: 'tallinn-old-town', category: 'CULTURE', description: "The best-preserved medieval city in Northern Europe — a UNESCO-listed ensemble of Gothic guild houses, merchant's towers, and cobblestone lanes that has barely changed since the 14th century. The Town Hall Square, the Wheel Well, and the bastion towers together form a city that looks as though it was designed for a fairy tale.", address: 'Tallinna vanalinn, 10130 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Tallinn+Old+Town', phone: null, website: 'https://www.visittallinn.ee', priceRange: 'FREE', rating: 4.8, imageUrl: '/spots/tallinn-old-town.jpg', tags: ['unesco', 'medieval', 'gothic', 'preserved', 'fairy-tale'] },
  { name: 'Toompea Castle', slug: 'toompea-castle-tallinn', category: 'CULTURE', description: "The hilltop fortress at the heart of Tallinn's upper city — home to the Estonian Parliament (Riigikogu), the 48-meter Tall Hermann Tower (where the national flag flies), and the Alexander Nevsky Cathedral. The platform at the base of Tall Hermann has the finest view over the Old Town roofscape.", address: 'Lossi plats 1a, 15165 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Toompea+Castle+Tallinn', phone: '+372 631 6100', website: 'https://www.riigikogu.ee', priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/toompea-castle-tallinn.jpg', tags: ['castle', 'parliament', 'tall-hermann', 'views', 'cathedral'] },
  { name: 'Kadriorg Palace & Park', slug: 'kadriorg-palace-tallinn', category: 'CULTURE', description: "Peter the Great's summer palace built for his wife Catherine — a Baroque palace in manicured gardens 2km from the Old Town, now housing the Foreign Art Museum. The formal gardens and the swan pond are Tallinn's most elegant outdoor space.", address: 'Weizenbergi 37, 10127 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Kadriorg+Palace+Tallinn', phone: '+372 606 6400', website: 'https://www.kadriorgpark.ee', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/kadriorg-palace-tallinn.jpg', tags: ['baroque', 'peter-the-great', 'gardens', 'museum', 'elegant'] },
  { name: 'Kumu Art Museum', slug: 'kumu-art-museum-tallinn', category: 'CULTURE', description: "Estonia's national art museum and one of the finest contemporary art institutions in Northern Europe — a striking limestone and copper building by Pekka Vapaavuori, opened 2006, with the permanent collection of Estonian art from the 18th century to the present day.", address: 'Weizenbergi 34, 10127 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Kumu+Art+Museum+Tallinn', phone: '+372 602 6000', website: 'https://www.kumu.ekm.ee', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/kumu-art-museum-tallinn.jpg', tags: ['museum', 'estonian-art', 'contemporary', 'limestone', 'national'] },
  { name: 'Tallinn Town Hall', slug: 'tallinn-town-hall', category: 'CULTURE', description: "The finest Gothic civic building in Northern Europe — a 15th-century Town Hall on Raekoja Plats with a distinctive octagonal tower topped by the weathervane figure of 'Old Thomas' (symbol of Tallinn). Climb the tower for the finest view over the Old Town; the Council Chamber inside is extraordinary.", address: 'Raekoja plats 1, 10146 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Tallinn+Town+Hall', phone: '+372 645 7900', website: 'https://www.tallinn.ee', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/tallinn-town-hall.jpg', tags: ['gothic', 'town-hall', 'old-thomas', 'tower-views', '15th-century'] },
  { name: 'Estonian Open Air Museum', slug: 'estonian-open-air-museum-tallinn', category: 'CULTURE', description: "An extraordinary living museum 6km from the center — 72 original farmsteads, windmills, and village churches relocated from across Estonia to a forested coastal site. Traditional crafts, summer festivals, and the most complete picture of Estonian rural life before industrialization.", address: 'Vabaõhumuuseumi tee 12, 13521 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Estonian+Open+Air+Museum', phone: '+372 654 9100', website: 'https://www.evm.ee', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/estonian-open-air-museum-tallinn.jpg', tags: ['open-air', 'farmsteads', 'windmills', 'estonian-heritage', 'living-museum'] },
  // COWORKING
  { name: 'Telliskivi Creative City', slug: 'telliskivi-creative-city-tallinn', category: 'COWORKING', description: "Tallinn's most vibrant creative district — a converted Soviet factory complex in Kalamaja with 200+ creative businesses, cafés, studios, boutiques, and the F-Hoone café-restaurant. The outdoor market every weekend, the street art, and the startup energy make it the most interesting neighborhood in Estonia.", address: 'Telliskivi 60, 10412 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Telliskivi+Creative+City+Tallinn', phone: null, website: 'https://telliskivi.cc', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/telliskivi-creative-city-tallinn.jpg', tags: ['creative-district', 'soviet-factory', 'startups', 'street-art', 'market'] },
  { name: 'Spring Hub Coworking Tallinn', slug: 'spring-hub-tallinn', category: 'COWORKING', description: "A well-equipped coworking space in the city center near Viru Gate with private offices, hot desks, meeting rooms, and reliable gigabit internet. A strong base for digital nomads and remote workers spending time in Tallinn.", address: 'Tartu mnt 2, 10145 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Spring+Hub+Tallinn', phone: '+372 600 0390', website: 'https://www.springhub.ee', priceRange: 'MID', rating: 4.4, imageUrl: '/spots/spring-hub-tallinn.jpg', tags: ['coworking', 'central', 'gigabit', 'nomad', 'meeting-rooms'] },
  // WELLNESS / NATURE
  { name: 'Kalma Saun Tallinn', slug: 'kalma-saun-tallinn', category: 'WELLNESS', description: "The most authentic traditional sauna experience in Tallinn — a 1928 public sauna in Kalamaja with wood-fired birch-smoke saunas, cold pools, and the communal atmosphere of a genuine Estonian neighbourhood bathhouse. The birch whisk (viht) treatment is a must.", address: 'Vana-Kalamaja 9a, 10414 Tallinn', googleMapsUrl: 'https://maps.google.com/?q=Kalma+Saun+Tallinn', phone: '+372 661 1211', website: 'https://www.kalmasaun.ee', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/kalma-saun-tallinn.jpg', tags: ['sauna', '1928', 'birch', 'kalamaja', 'authentic'] },
  { name: 'Lahemaa National Park', slug: 'lahemaa-national-park-tallinn', category: 'NATURE', description: "Estonia's largest national park, 70km east of Tallinn — ancient forests, coastal boulders, manor houses, and pristine bogs that stretch to the horizon. Day trips by rental car or guided tour from Tallinn; the Viru bog boardwalk at dawn is one of the most tranquil experiences in Northern Europe.", address: 'Lahemaa, 45202 Harju County', googleMapsUrl: 'https://maps.google.com/?q=Lahemaa+National+Park', phone: null, website: 'https://www.lahemaa.ee', priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/lahemaa-national-park-tallinn.jpg', tags: ['national-park', 'bogs', 'manor-houses', 'day-trip', 'tranquil'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Tallinn: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
