const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328g1k000rvi8wxg6u2e7i';

const spots = [
  // LUXURY HOTELS
  { name: 'Belle Villa Resort Pai', slug: 'belle-villa-resort-pai', category: 'ACCOMMODATION', description: 'The finest resort in Pai - a collection of pool villas and suites on 5 acres of rice paddy and mountain views, with infinity-edge pools, a full spa, and an outdoor restaurant. Belle Villa is the most complete luxury experience in the Pai valley, combining Thai country house elegance with modern amenities.', address: '113 Moo 8, Wiang Tai, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Belle+Villa+Resort+Pai', phone: '+66 53 698 226', website: 'https://bellevillaresort.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/belle-villa-resort-pai.jpg', tags: ['pool-villa', 'rice-paddy', 'mountains', 'spa', 'infinity-pool'] },
  { name: 'Reverie Siam Resort Pai', slug: 'reverie-siam-resort-pai', category: 'ACCOMMODATION', description: 'An extraordinary art hotel in the jungle above Pai with 12 individually themed suites, an adult-only infinity pool, a celebrated farm-to-table restaurant, and a private gallery of Thai antiquities. Reverie Siam is the most creatively designed hotel in northern Thailand - each room is a different aesthetic universe.', address: '6/1 Moo 6, Ban Mae Yen, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Reverie+Siam+Resort+Pai', phone: '+66 98 891 8900', website: 'https://reveriesiam.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/reverie-siam-resort-pai.jpg', tags: ['art-hotel', 'adult-only', 'farm-to-table', 'antiquities', 'jungle'] },
  { name: 'Pai Treehouse Luxury Resort', slug: 'pai-treehouse-luxury-resort', category: 'ACCOMMODATION', description: 'A romantic resort of elevated bamboo and wood treehouses set in a forested hillside above the Pai valley with outdoor rain showers, private decks, and extraordinary valley and mountain views. The treehouses combine nature immersion with luxury amenities - heated water, AC, and gourmet breakfast delivered by basket.', address: 'Mae Yen Village, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Treehouse+Resort', phone: '+66 93 132 6789', website: null, priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/pai-treehouse-luxury-resort.jpg', tags: ['treehouse', 'valley-views', 'bamboo', 'romantic', 'rain-shower'] },
  { name: 'Pai Village Boutique Resort', slug: 'pai-village-boutique-resort', category: 'ACCOMMODATION', description: 'A beautiful Thai-style boutique resort in traditional northern Thai wooden bungalows set in extensive tropical gardens near the town center. The swimming pool is surrounded by banana trees and the open-air restaurant serves excellent Thai food while views of the surrounding mountains frame every meal.', address: '88 Moo 3, Wiang Tai, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Village+Boutique+Resort', phone: '+66 53 699 225', website: 'https://paivillage.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/pai-village-boutique-resort.jpg', tags: ['thai-wooden', 'gardens', 'pool', 'mountains', 'boutique'] },
  // BUDGET HOTELS
  { name: 'Baan Krating Pai Resort', slug: 'baan-krating-pai-resort', category: 'ACCOMMODATION', description: 'A well-reviewed riverside resort with Thai-style wooden bungalows on the banks of the Pai River, with a beautiful pool, hammock garden, and restaurant. The riverside location, mountain views, and excellent breakfast make Baan Krating one of Pai\'s best mid-range options.', address: '139 Moo 8, Mae Hi, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Baan+Krating+Pai', phone: '+66 53 699 272', website: 'https://baankrating.com/pai', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/baan-krating-pai-resort.jpg', tags: ['riverside', 'wooden-bungalow', 'pool', 'breakfast', 'hammock'] },
  { name: 'Pai Nai Suan Garden Resort', slug: 'pai-nai-suan-garden-resort', category: 'ACCOMMODATION', description: 'A popular garden resort with comfortable fan and air-conditioned bungalows scattered around a lush tropical garden with a central pool. The relaxed atmosphere, helpful staff, and free bicycle rental make it an excellent base for exploring the Pai countryside and valley on two wheels.', address: 'Wiang Tai, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Nai+Suan+Garden+Resort', phone: '+66 53 699 345', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/pai-nai-suan-garden-resort.jpg', tags: ['garden', 'bungalow', 'pool', 'bicycle', 'relaxed'] },
  { name: 'Mountain Blue House Pai', slug: 'mountain-blue-house-pai', category: 'ACCOMMODATION', description: 'A charming guesthouse on the edge of Pai town with clean, simple rooms, mountain views from every window, a small pool, and a lovely garden cafe downstairs. Mountain Blue House is run by a friendly Thai-Danish couple who know every waterfall and hiking trail in the Pai area personally.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mountain+Blue+House+Pai', phone: '+66 53 699 456', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/mountain-blue-house-pai.jpg', tags: ['mountain-views', 'pool', 'cafe', 'helpful-owners', 'hiking'] },
  { name: 'Lucky Guesthouse Pai', slug: 'lucky-guesthouse-pai', category: 'ACCOMMODATION', description: 'A long-running budget guesthouse on the walking street with clean rooms, good AC, fast wifi, and a ground-floor restaurant serving good pad thai and khao soi. Lucky Guesthouse is one of the best-value options in central Pai - the friendly staff and helpful notice board make it ideal for first-time Pai visitors.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Lucky+Guesthouse+Pai', phone: '+66 53 699 233', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/lucky-guesthouse-pai.jpg', tags: ['budget', 'walking-street', 'wifi', 'pad-thai', 'central'] },
  // HOSTELS
  { name: 'Pai Hostel', slug: 'pai-hostel', category: 'ACCOMMODATION', description: 'A well-designed hostel in the heart of Pai with pod dorms, hammock areas, a small plunge pool, and an extremely social atmosphere that makes solo travel in Pai very easy. The hostel runs free daily yoga, organized scooter trips to nearby waterfalls, and movie nights in the common room.', address: 'Rungsiynanon Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Hostel', phone: '+66 53 699 567', website: 'https://paihostel.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/pai-hostel.jpg', tags: ['social', 'yoga', 'plunge-pool', 'scooter-trips', 'pods'] },
  { name: 'In The Mood For Love Guesthouse Pai', slug: 'in-the-mood-for-love-pai', category: 'ACCOMMODATION', description: 'A quirky, artistically decorated hostel-guesthouse named after the Wong Kar-Wai film with film posters, vintage furniture, fairy lights, and a record collection in the common room. The vibe attracts artists, photographers, and indie travelers who appreciate the atmospheric setting over modern amenities.', address: 'Wang Tai Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=In+The+Mood+For+Love+Pai', phone: '+66 53 699 678', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/in-the-mood-for-love-pai.jpg', tags: ['artistic', 'vintage', 'film-decor', 'indie', 'atmospheric'] },
  { name: 'Charlie\'s Guesthouse Pai', slug: 'charlies-guesthouse-pai', category: 'ACCOMMODATION', description: 'A legendary Pai backpacker institution that has hosted generations of travelers in simple bungalows with fan cooling and mosquito nets, surrounding a garden of hammocks and banana trees. The communal breakfast and owner Charlie\'s evening storytelling have built a devoted global following over 20 years.', address: 'Rungsiynanon Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Charlies+Guesthouse+Pai', phone: '+66 53 699 789', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/charlies-guesthouse-pai.jpg', tags: ['institution', 'garden', 'hammock', 'communal', '20-years'] },
  { name: 'Baan Toong Tent Camping Pai', slug: 'baan-toong-tent-camping-pai', category: 'ACCOMMODATION', description: 'A unique glamping experience at the edge of a rice paddy 4km from Pai town with safari tents, outdoor showers, a communal fire pit, and nightly star-gazing far from town lights. The morning mist over the valley, the sounds of birds, and a campfire breakfast make this the most memorable stay in the Pai area.', address: 'Mae Yen, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Baan+Toong+Camping+Pai', phone: '+66 86 123 4567', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/baan-toong-tent-camping-pai.jpg', tags: ['glamping', 'rice-paddy', 'stargazing', 'campfire', 'nature'] },
  // CAFES
  { name: 'Witching Well Cafe Pai', slug: 'witching-well-cafe-pai', category: 'CAFE', description: 'A beloved artisan coffee shop in Pai town with excellent single-origin espresso, hand-drip filter coffees, and homemade cakes. The relaxed atmosphere, fairy light garden, and consistently outstanding coffee quality make Witching Well the daily ritual of Pai\'s extended-stay community of travelers and artists.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Witching+Well+Cafe+Pai', phone: '+66 53 699 890', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/witching-well-cafe-pai.jpg', tags: ['specialty', 'filter', 'garden', 'fairy-lights', 'community'] },
  { name: 'Art in Chai Pai', slug: 'art-in-chai-pai', category: 'CAFE', description: 'A beautiful art cafe with gallery walls, a clay pottery studio, and an excellent menu of herbal teas, cold brew, and Thai food. The owner is a local artist and the handmade mugs, bowls, and decorations are all for sale - a creative community space that feels distinctly Pai.', address: 'Rungsiynanon Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Art+in+Chai+Pai', phone: '+66 92 123 4567', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/art-in-chai-pai.jpg', tags: ['art', 'gallery', 'pottery', 'herbal-tea', 'creative'] },
  { name: 'Naughty Boy Coffee Pai', slug: 'naughty-boy-coffee-pai', category: 'CAFE', description: 'A compact specialty coffee bar run by a barista-enthusiast with single-origin Thai and Burmese beans, rotating brew methods including siphon and aeropress, and a menu that changes weekly. The tiny shop has only 8 seats and lines form at 8am - the most serious coffee experience in Pai.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Naughty+Boy+Coffee+Pai', phone: '+66 86 234 5678', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/naughty-boy-coffee-pai.jpg', tags: ['specialty', 'siphon', 'aeropress', 'rotating', 'serious'] },
  { name: 'Own Time Cafe Pai', slug: 'own-time-cafe-pai', category: 'CAFE', description: 'A slow-travel cafe designed for long stays - massive tables, hammocks, board games, a book exchange, fast wifi, and a kitchen that serves simple but excellent food all day. Own Time embodies the Pai philosophy of unscheduled time - you\'re not asked to leave after finishing your coffee.', address: 'Wang Tai Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Own+Time+Cafe+Pai', phone: '+66 92 345 6789', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/own-time-cafe-pai.jpg', tags: ['slow-travel', 'hammock', 'board-games', 'book-exchange', 'wifi'] },
  { name: 'River Corner Cafe Pai', slug: 'river-corner-cafe-pai', category: 'CAFE', description: 'A riverside cafe and yoga studio with meditation cushions, herbal teas, organic smoothies, and a daily yoga class schedule. The sound of the Pai River flowing beneath the bamboo deck and the surrounding mountains create the kind of peaceful setting that keeps people in Pai for weeks longer than planned.', address: 'Riverside, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=River+Corner+Cafe+Pai', phone: '+66 93 456 7890', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/river-corner-cafe-pai.jpg', tags: ['riverside', 'yoga', 'herbal-tea', 'meditation', 'bamboo'] },
  { name: 'Baandam Coffee Pai', slug: 'baandam-coffee-pai', category: 'CAFE', description: 'A charming wooden coffee shop in a traditional northern Thai house with a courtyard garden, excellent Doi Chang coffee, and homemade cookies. Baandam Coffee opens only until noon, ensuring the best seats fill fast with travelers planning their day over a perfectly brewed morning cup.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Baandam+Coffee+Pai', phone: '+66 93 567 8901', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/baandam-coffee-pai.jpg', tags: ['traditional-house', 'doi-chang', 'morning-only', 'courtyard', 'cookies'] },
  // RESTAURANTS
  { name: 'Edible Jazz Pai', slug: 'edible-jazz-pai', category: 'FOOD', description: 'The finest dining restaurant in Pai - a romantic candlelit venue with live jazz most evenings, serving a menu of Thai and Mediterranean fusion that changes with market availability. The duck massaman curry, Burmese tea leaf salad, and wood-fired whole fish are standout dishes in a genuinely beautiful setting.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Edible+Jazz+Pai', phone: '+66 53 699 901', website: null, priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/edible-jazz-pai.jpg', tags: ['live-jazz', 'romantic', 'fusion', 'massaman', 'candlelit'] },
  { name: 'Mama Falafel Pai', slug: 'mama-falafel-pai', category: 'FOOD', description: 'A beloved Middle Eastern vegetarian restaurant run by an Israeli family with outstanding falafel, hummus, shakshuka, and fresh pita bread baked daily. Mama Falafel has been a Pai institution since the 1990s when Israeli travelers first made the hill town a regular stop - still the best falafel in northern Thailand.', address: 'Rungsiynanon Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mama+Falafel+Pai', phone: '+66 53 699 012', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/mama-falafel-pai.jpg', tags: ['falafel', 'hummus', 'vegetarian', 'israeli', 'institution'] },
  { name: 'Big Brother Burgers Pai', slug: 'big-brother-burgers-pai', category: 'FOOD', description: 'The most popular burger joint in Pai, with massive handmade beef and mushroom burgers, crispy fries, and cold beers in a casual open-air restaurant. The consistency, generous portions, and competitive prices have made Big Brother a must-visit for carnivores after a week of rice and noodles.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Big+Brother+Burgers+Pai', phone: '+66 53 699 123', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/big-brother-burgers-pai.jpg', tags: ['burgers', 'casual', 'comfort-food', 'beer', 'popular'] },
  { name: 'Na\'s Kitchen Pai', slug: 'nas-kitchen-pai', category: 'FOOD', description: 'A tiny local restaurant run by Na and her family, serving the most authentic northern Thai food in Pai - khao soi egg noodle curry, sai ua herbed pork sausage, and kaeng hang le Burmese-style pork curry at prices locals pay. The daily menu is determined by the morning market - Na cooks whatever is freshest.', address: 'Ketket Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Na+Kitchen+Pai', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/nas-kitchen-pai.jpg', tags: ['northern-thai', 'khao-soi', 'sai-ua', 'authentic', 'local'] },
  { name: 'All About Coffee and More Pai', slug: 'all-about-coffee-more-pai', category: 'FOOD', description: 'A comprehensive restaurant-cafe that serves excellent Thai and international food from morning to midnight with a long menu, reliable wifi, and a friendly atmosphere. The evening grilled meats, Thai curries, and international dishes cater to every dietary preference, making it the go-to dinner spot for groups with mixed requirements.', address: 'Rungsiynanon Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=All+About+Coffee+Pai', phone: '+66 53 699 234', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/all-about-coffee-more-pai.jpg', tags: ['all-day', 'thai-international', 'wifi', 'groups', 'reliable'] },
  { name: 'Amido Italian Restaurant Pai', slug: 'amido-italian-restaurant-pai', category: 'FOOD', description: 'A surprisingly authentic Italian restaurant with a wood-fired oven, housemade pasta, and a good wine selection in the most unexpected location - a small mountain valley in northern Thailand. Amido has been run by the same Italian family for 15 years and the tiramisu is made from a grandmother\'s recipe.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Amido+Italian+Restaurant+Pai', phone: '+66 53 699 345', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/amido-italian-restaurant-pai.jpg', tags: ['italian', 'wood-fired', 'pasta', 'tiramisu', 'authentic'] },
  // MARKETS
  { name: 'Pai Walking Street Market', slug: 'pai-walking-street-market', category: 'FOOD', description: 'The famous Pai night market running the full length of Chaisongkram Road from 6pm - a daily street festival of hill tribe handicrafts, handmade jewelry, vintage clothing, and dozens of food stalls serving khao soi, grilled corn, fruit smoothies, and Thai sweets. The busiest and best night market in northern Thailand.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Walking+Street', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/pai-walking-street-market.jpg', tags: ['night-market', 'walking-street', 'hill-tribe', 'khao-soi', 'evening'] },
  { name: 'Pai Morning Market', slug: 'pai-morning-market', category: 'FOOD', description: 'The local fresh market on the outskirts of Pai town where hill tribe women and valley farmers sell mountain vegetables, jungle herbs, wild mushrooms, and live chickens from 5-10am. The fresh-pressed sugarcane juice and sticky rice with grilled pork (kao ji) at the market entrance are the best breakfast in Pai.', address: 'Ketket Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Morning+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/pai-morning-market.jpg', tags: ['morning-market', 'hill-tribe', 'mushrooms', 'sticky-rice', 'early'] },
  { name: 'Pai Saturday Market', slug: 'pai-saturday-market', category: 'FOOD', description: 'A weekly Saturday afternoon market in a different location each week where local growers and artisans sell organic produce, handmade soap, beeswax candles, and Northern Thai specialty foods. The farmers market is patronized almost exclusively by long-stay residents and expats - a window into the real Pai community.', address: 'Various locations, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Saturday+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/pai-saturday-market.jpg', tags: ['organic', 'farmers-market', 'artisan', 'expat', 'weekly'] },
  { name: 'Pai Fruits and Snacks Alley', slug: 'pai-fruits-snacks-alley', category: 'FOOD', description: 'A permanent lane of vendors near the Walking Street selling tropical fruits, fresh-cut mango with sticky rice, fried bananas, takoyaki octopus balls, and traditional Thai desserts. Perfect for grazing during an evening on the Walking Street - the seasonal mountain strawberries from December to February are outstanding.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Fruits+Snacks+Alley', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/pai-fruits-snacks-alley.jpg', tags: ['snacks', 'mango-sticky-rice', 'fried-banana', 'strawberries', 'seasonal'] },
  { name: 'Hill Tribe Arts and Crafts Market Pai', slug: 'hill-tribe-arts-crafts-market-pai', category: 'FOOD', description: 'A dedicated artisan market near the bus terminal where hill tribe women from the Lisu, Lahu, and Shan communities sell handmade textiles, silver jewelry, and embroidered clothing. The silver work from the Lisu community is genuinely exceptional craftsmanship - pieces here are made by the seller and unique.', address: 'Jaroenphat Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Hill+Tribe+Market+Pai', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/hill-tribe-arts-crafts-market-pai.jpg', tags: ['hill-tribe', 'silver', 'textiles', 'lisu', 'embroidery'] },
  // TOURIST SITES
  { name: 'Pai Canyon (Kong Lan)', slug: 'pai-canyon-kong-lan', category: 'NATURE', description: 'A dramatic canyon of narrow red sandstone ridges rising 30 meters above the valley floor, with walking paths along the knife-edge ridgelines offering panoramic views of the Pai River valley and surrounding mountains. The most popular sunset walk in the Pai area - the ridges glow orange at golden hour.', address: 'Kong Lan, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Canyon+Kong+Lan', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/pai-canyon-kong-lan.jpg', tags: ['canyon', 'sunset', 'ridgeline', 'views', 'hiking'] },
  { name: 'Pai Hot Springs', slug: 'pai-hot-springs', category: 'NATURE', description: 'Natural geothermal springs 9km from Pai town where mineral-rich water at 80 degrees Celsius flows from underground into an outdoor bathing complex of individual tubs and a central stream. The mineral waters are reported to have skin-healing properties and the setting in a forested valley is tranquil.', address: 'Tha Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Hot+Springs', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/pai-hot-springs.jpg', tags: ['hot-springs', 'geothermal', 'mineral-water', 'relaxing', 'nature'] },
  { name: 'Mor Paeng Waterfall Pai', slug: 'mor-paeng-waterfall-pai', category: 'NATURE', description: 'A multi-level waterfall cascading over smooth rock shelves into a series of natural swimming pools 8km from Pai town. Mor Paeng\'s gentle gradient allows visitors to slide down the natural rock chutes from pool to pool - the most fun natural slide in northern Thailand and equally loved by locals and travelers.', address: 'Moo 4, Mae Hi, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mor+Paeng+Waterfall+Pai', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/mor-paeng-waterfall-pai.jpg', tags: ['waterfall', 'swimming', 'natural-slide', 'pools', 'fun'] },
  { name: 'Wat Phra That Mae Yen (White Buddha) Pai', slug: 'wat-phra-that-mae-yen-pai', category: 'CULTURE', description: 'A hilltop temple with a large white Buddha statue overlooking the Pai valley, reached by 353 steps. The panoramic 360-degree view from the top covers the entire valley, the town below, and the surrounding mountain ridges - the most comprehensive viewpoint accessible on foot in the Pai area.', address: 'Mae Yen, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Wat+Phra+That+Mae+Yen+Pai', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/wat-phra-that-mae-yen-pai.jpg', tags: ['temple', 'hilltop', 'white-buddha', 'views', '353-steps'] },
  { name: 'Shan Village Home Stay Pai', slug: 'shan-village-homestay-pai', category: 'CULTURE', description: 'A community tourism program allowing visitors to spend the night in a Shan ethnic village 12km from Pai, cooking with local families, learning weaving techniques, and participating in morning alms-giving. An extraordinary immersive cultural experience run by the village community themselves with all income staying local.', address: 'Shan Village, near Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Shan+Village+Pai+Thailand', phone: '+66 86 456 7890', website: null, priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/shan-village-homestay-pai.jpg', tags: ['homestay', 'shan', 'cultural', 'weaving', 'community'] },
  { name: 'Pai River Rafting', slug: 'pai-river-rafting', category: 'NATURE', description: 'Bamboo and rubber tube rafting on the Pai River through lush jungle gorges, rice paddies, and limestone formations. The 2-hour gentle journey is more floating than white-water and the bamboo raft stops at swimming holes and waterfall sprays - an ideal morning activity before Pai Canyon\'s afternoon sunset.', address: 'Pai River, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+River+Rafting', phone: '+66 53 699 456', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/pai-river-rafting.jpg', tags: ['rafting', 'bamboo-raft', 'river', 'jungle', 'swimming'] },
  { name: 'Pai Memorial Bridge', slug: 'pai-memorial-bridge', category: 'CULTURE', description: 'A wooden bridge built by Japanese forces during World War II to cross the Pai River, later becoming one of the most photographed sites in northern Thailand. The bridge\'s weathered wood, the Pai River below, and the backdrop of misty mountains create an image that has become synonymous with the Pai experience.', address: 'Ban Santichon, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Memorial+Bridge', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/pai-memorial-bridge.jpg', tags: ['bridge', 'ww2', 'historic', 'river', 'iconic'] },
  { name: 'Chinese Village (Ban Santichon) Pai', slug: 'chinese-village-ban-santichon-pai', category: 'CULTURE', description: 'A Yunnan Chinese village founded by Kuomintang soldiers who fled China in 1949, maintaining distinct Yunnan Chinese cultural traditions including tea ceremonies, Yunnan coffee cultivation, and traditional clothing. The village sits on a hill 4km from Pai with panoramic views and excellent Yunnan-style cooking.', address: 'Ban Santichon, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Ban+Santichon+Chinese+Village+Pai', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/chinese-village-ban-santichon-pai.jpg', tags: ['yunnan', 'chinese-village', 'tea-ceremony', 'kuomintang', 'cultural'] },
  { name: 'Land Split (Wua Laen) Pai', slug: 'land-split-pai', category: 'NATURE', description: 'A dramatic geological fissure that opened in 2008 after heavy rains caused the earth to split, creating a 100-meter long, 3-meter deep crack through a farm\'s corn fields that has become a quirky tourist attraction. An unusual natural formation that somehow became one of the most visited sites near Pai.', address: 'Wua Laen, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Land+Split+Pai+Thailand', phone: null, website: null, priceRange: 'FREE', rating: 4.2, imageUrl: '/spots/land-split-pai.jpg', tags: ['geological', 'unusual', 'fissure', 'nature', 'quirky'] },
  // COWORKING
  { name: 'Pai Nomads Coworking', slug: 'pai-nomads-coworking', category: 'COWORKING', description: 'The dedicated digital nomad hub in Pai town with fast fiber internet, ergonomic chairs, private desks, AC, and a rooftop terrace with mountain valley views. Day, week, and monthly passes available - the most professionally equipped workspace in a town where most people work from guesthouses and cafes.', address: 'Rungsiynanon Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Nomads+Coworking', phone: '+66 92 789 0123', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/pai-nomads-coworking.jpg', tags: ['coworking', 'fiber', 'mountain-views', 'day-pass', 'ergonomic'] },
  { name: 'Pai Slow Life Workspace', slug: 'pai-slow-life-workspace', category: 'COWORKING', description: 'A coworking space attached to a yoga retreat center with 4-hour and full-day rates, bamboo workspace, garden desks, and a philosophy that encourages nomads to work mindfully. The daily yoga session at noon, included with any workspace pass, makes this the most holistic coworking experience in northern Thailand.', address: 'Mae Yen Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Slow+Life+Workspace', phone: '+66 93 890 1234', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/pai-slow-life-workspace.jpg', tags: ['yoga-included', 'mindful', 'bamboo', 'garden', 'holistic'] },
  { name: 'Mountain Work Hub Pai', slug: 'mountain-work-hub-pai', category: 'COWORKING', description: 'A converted farmhouse coworking space 2km from Pai town with rice paddy views from every desk, solar power, a communal kitchen, and a permanent resident community of remote workers on monthly contracts. The combined slow-farm and work experience - feeding chickens before your morning stand-up - is uniquely Pai.', address: 'Mae Hi, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mountain+Work+Hub+Pai', phone: '+66 86 901 2345', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/mountain-work-hub-pai.jpg', tags: ['farmhouse', 'rice-paddy', 'solar', 'monthly', 'community'] },
  { name: 'Chill Work Cafe Pai', slug: 'chill-work-cafe-pai', category: 'COWORKING', description: 'A laid-back cafe-coworking hybrid that occupies an entire floor of a Pai riverside building with long desks, hammock stations, cold brew on tap, and the sound of the Pai River as background music. The open-sided structure means natural breeze instead of AC - bring a light jacket in the cool season.', address: 'Riverside Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Chill+Work+Cafe+Pai', phone: '+66 86 012 3456', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/chill-work-cafe-pai.jpg', tags: ['riverside', 'hammock', 'cold-brew', 'open-air', 'casual'] },
  { name: 'Digital Nomad Pai Community Space', slug: 'digital-nomad-pai-community-space', category: 'COWORKING', description: 'A community-run coworking space on a pay-what-you-can model, created and maintained by the long-stay nomad community in Pai. Membership is a whatsapp group and everyone contributes to the space maintenance, the supply of coffee, and the monthly potluck dinner that has become a Pai nomad institution.', address: 'Chaisongkram Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Digital+Nomad+Pai+Community', phone: '+66 92 123 4567', website: null, priceRange: 'FREE', rating: 4.3, imageUrl: '/spots/digital-nomad-pai-community-space.jpg', tags: ['community', 'pay-what-you-can', 'potluck', 'nomad', 'free'] },
  { name: 'Green Hub Coworking Pai', slug: 'green-hub-coworking-pai', category: 'COWORKING', description: 'An eco-friendly coworking space built from bamboo and recycled materials with solar panels, a compost system, and a permaculture garden where nomads can pick their lunch greens. Green Hub attracts environmentally conscious remote workers with its commitment to zero-waste operations and exceptional mountain views.', address: 'Mae Yen Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Green+Hub+Coworking+Pai', phone: '+66 93 234 5678', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/green-hub-coworking-pai.jpg', tags: ['eco', 'solar', 'bamboo', 'permaculture', 'sustainable'] },
  { name: 'Pai Valley Viewpoint', slug: 'pai-valley-viewpoint', category: 'NATURE', description: 'A scenic viewpoint on the ridge above Pai town offering the most comprehensive panorama of the Pai River valley - a patchwork of rice paddies, farms, and forested hills stretching to the Myanmar mountains. The 10-minute motorbike ride from town and the near-total absence of tourists make it the best sunrise spot near Pai.', address: 'Yun Lai Viewpoint Road, Pai, Mae Hong Son 58130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pai+Valley+Viewpoint', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/pai-valley-viewpoint.jpg', tags: ['viewpoint', 'sunrise', 'valley', 'rice-paddies', 'motorbike'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Pai: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
