const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328gh6000tvi8wfdnhld6a';

const spots = [
  // LUXURY HOTELS
  { name: 'Six Senses Samui', slug: 'six-senses-samui-koh-tao', category: 'ACCOMMODATION', description: 'A short ferry from Koh Tao, Six Senses Samui offers the finest luxury wellness experience in the Gulf of Thailand with 66 private pool villas on a steep hillside, a world-class Alchemy Bar for wellness drinks, and extraordinary marine conservation programs. The perfect pre or post-diving luxury retreat.', address: '9/10 Moo 5, Baan Plai Laem, Ko Samui, Surat Thani 84320, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Six+Senses+Samui', phone: '+66 77 245 678', website: 'https://www.sixsenses.com/samui', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/six-senses-samui-koh-tao.jpg', tags: ['wellness', 'pool-villas', 'conservation', 'luxury', 'nearby-island'] },
  { name: 'Jamahkiri Resort and Spa Koh Tao', slug: 'jamahkiri-resort-spa-koh-tao', category: 'ACCOMMODATION', description: 'Koh Tao\'s finest resort, dramatically built into the granite boulders of the Chalok Ban Kao hillside with villas cantilevered over the sea, a hilltop infinity pool, and a celebrated spa. Jamahkiri offers Koh Tao\'s most sophisticated stay with a private beach cove and an exceptional dive center.', address: '67/7 Moo 3, Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Jamahkiri+Resort+Koh+Tao', phone: '+66 77 457 100', website: 'https://www.jamahkiri.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/jamahkiri-resort-spa-koh-tao.jpg', tags: ['granite-boulders', 'infinity-pool', 'dive-center', 'private-cove', 'hillside'] },
  { name: 'Dusit Buncha Resort Koh Tao', slug: 'dusit-buncha-resort-koh-tao', category: 'ACCOMMODATION', description: 'An elegant boutique resort overlooking Chalok Ban Kao bay with hillside villas, a stunning cliff-edge infinity pool, and a restaurant with the best bay view on the island. The Dusit Buncha combines genuine luxury with Koh Tao\'s relaxed diving culture - most guests spend mornings underwater and afternoons at the pool.', address: '89/1 Moo 3, Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Dusit+Buncha+Koh+Tao', phone: '+66 77 457 155', website: 'https://dusitbuncha.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/dusit-buncha-resort-koh-tao.jpg', tags: ['hillside-villa', 'cliff-pool', 'bay-views', 'diving', 'boutique'] },
  { name: 'Haad Tien Beach Club Koh Tao', slug: 'haad-tien-beach-club-koh-tao', category: 'ACCOMMODATION', description: 'A secluded luxury resort on the wild eastern coast of Koh Tao, accessible only by boat or hiking trail, with just 20 cliff-side villas on a pristine bay with no roads. Haad Tien is Koh Tao\'s ultimate escape - complete isolation, spectacular underwater life, and total peace.', address: 'Haad Tien, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Haad+Tien+Beach+Club+Koh+Tao', phone: '+66 77 456 789', website: null, priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/haad-tien-beach-club-koh-tao.jpg', tags: ['secluded', 'boat-access', 'cliff-villa', 'pristine', 'isolation'] },
  // BUDGET HOTELS
  { name: 'In Touch Resort Koh Tao', slug: 'in-touch-resort-koh-tao', category: 'ACCOMMODATION', description: 'A clean, well-managed mid-range resort on Sairee Beach with an excellent dive shop, beachfront restaurant, and comfortable rooms at fair prices. In Touch is the go-to choice for divers who want proximity to the beach and dive operators without paying luxury hotel rates.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=In+Touch+Resort+Koh+Tao', phone: '+66 77 456 234', website: 'https://intouchresortkohta.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/in-touch-resort-koh-tao.jpg', tags: ['dive-shop', 'sairee-beach', 'beachfront', 'divers', 'value'] },
  { name: 'The Place Leisure & Resort Koh Tao', slug: 'the-place-leisure-resort-koh-tao', category: 'ACCOMMODATION', description: 'A charming boutique resort on the Chalok Ban Kao hillside with fantastic bay views, a beautiful pool, and well-designed bungalows at mid-range prices. The Place is particularly popular with solo travelers and couples who want a quiet, attractive base away from the Sairee beach party scene.', address: 'Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=The+Place+Leisure+Resort+Koh+Tao', phone: '+66 77 456 890', website: 'https://theplacekohtao.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/the-place-leisure-resort-koh-tao.jpg', tags: ['boutique', 'bay-views', 'pool', 'quiet', 'hillside'] },
  { name: 'Seashell Resort Koh Tao', slug: 'seashell-resort-koh-tao', category: 'ACCOMMODATION', description: 'An affordable beachside resort on the Sairee strip with bungalows, a pool, and a beachfront location that puts you 30 seconds from the water and 5 minutes from the best dive schools. The Seashell is reliable, clean, and offers unbeatable price-to-location value on the most popular beach on Koh Tao.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Seashell+Resort+Koh+Tao', phone: '+66 77 457 350', website: 'https://seashellkohtao.com', priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/seashell-resort-koh-tao.jpg', tags: ['beachside', 'sairee', 'pool', 'dive-access', 'budget'] },
  { name: 'Blue Heaven Bungalows Koh Tao', slug: 'blue-heaven-bungalows-koh-tao', category: 'ACCOMMODATION', description: 'Simple, affordable bungalows on the hillside above Mae Haad pier with sweeping sea views and easy access to ferries, dive shops, and the town. Blue Heaven is the best budget option for travelers using Koh Tao as a dive-and-depart base who want clean accommodation without unnecessary expenses.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Blue+Heaven+Bungalows+Koh+Tao', phone: '+66 77 456 567', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/blue-heaven-bungalows-koh-tao.jpg', tags: ['bungalow', 'sea-views', 'mae-haad', 'budget', 'ferry-access'] },
  // HOSTELS
  { name: 'Koh Tao Resort Hostel', slug: 'koh-tao-resort-hostel', category: 'ACCOMMODATION', description: 'A social hostel on Sairee Beach combining dorm accommodation with a pool, beach bar, and the most active social events calendar on Koh Tao. The nightly pub crawls, dive introduction sessions, and bonfire beach parties make it the hub of the island\'s solo traveler community.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Koh+Tao+Resort+Hostel', phone: '+66 77 456 123', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/koh-tao-resort-hostel.jpg', tags: ['social', 'sairee', 'pool', 'pub-crawl', 'beach-party'] },
  { name: 'Papa Koh Tao Hostel', slug: 'papa-koh-tao-hostel', category: 'ACCOMMODATION', description: 'A well-designed hostel near Mae Haad pier with pod bunks, a rooftop, a cafe, and an in-house dive school that offers learn-to-dive packages starting from the day of arrival. Papa Koh Tao is the best-organized budget dive-and-stay package on the island for first-time divers.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Papa+Koh+Tao+Hostel', phone: '+66 77 456 456', website: 'https://papakohtao.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/papa-koh-tao-hostel.jpg', tags: ['pods', 'dive-school', 'mae-haad', 'rooftop', 'beginner-diving'] },
  { name: 'Sairee Cottage Diving Resort', slug: 'sairee-cottage-diving-resort-koh-tao', category: 'ACCOMMODATION', description: 'One of Koh Tao\'s oldest dive resorts on Sairee Beach offering dormitory accommodation, private bungalows, and a complete PADI dive center all under one roof. The social atmosphere in the common areas and dive school is excellent for solo travelers trying to complete their Open Water certification.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Sairee+Cottage+Diving+Koh+Tao', phone: '+66 77 456 126', website: 'https://saireecottage.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/sairee-cottage-diving-resort-koh-tao.jpg', tags: ['dive-resort', 'sairee', 'padi', 'dorms', 'open-water'] },
  { name: 'Monsoon Hostel Koh Tao', slug: 'monsoon-hostel-koh-tao', category: 'ACCOMMODATION', description: 'A clean, quiet hostel in Mae Haad with a small pool, a relaxed garden common area, and a staff team that is particularly good at pairing solo travelers with compatible dive buddies. Monsoon attracts a slightly older, quieter crowd than the Sairee party hostels - more productivity, fewer hangovers.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Monsoon+Hostel+Koh+Tao', phone: '+66 77 456 789', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/monsoon-hostel-koh-tao.jpg', tags: ['quiet', 'pool', 'dive-buddies', 'mae-haad', 'relaxed'] },
  // CAFES
  { name: 'Barracuda Restaurant and Bar Koh Tao', slug: 'barracuda-restaurant-bar-koh-tao', category: 'CAFE', description: 'The most popular beach bar and cafe on Sairee Beach with excellent cocktails, strong iced coffee, and a relaxed beach-side atmosphere that makes it the default meeting place for divers between morning and afternoon dives. The seating on the sand, cold beers, and view of dive boats departing is quintessentially Koh Tao.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Barracuda+Restaurant+Bar+Koh+Tao', phone: '+66 77 457 200', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/barracuda-restaurant-bar-koh-tao.jpg', tags: ['beach-bar', 'sairee', 'cocktails', 'divers', 'meeting-place'] },
  { name: 'Whitening Bar Koh Tao', slug: 'whitening-bar-koh-tao', category: 'CAFE', description: 'A hip beach bar and cafe on the quieter northern end of Sairee with excellent smoothies, healthy food, hammocks over the water, and a relaxed creative vibe that attracts photographers and artists. The aloe vera lemonade and the grilled tuna wraps are the most ordered items.', address: 'Sairee Beach (North), Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Whitening+Bar+Koh+Tao', phone: '+66 77 456 890', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/whitening-bar-koh-tao.jpg', tags: ['hammock', 'smoothies', 'healthy', 'photography', 'relaxed'] },
  { name: 'Caffeine Addiction Koh Tao', slug: 'caffeine-addiction-koh-tao', category: 'CAFE', description: 'The most serious specialty coffee shop on Koh Tao with proper espresso equipment, Thai single-origin beans, and a selection of cold brews and pour-overs. The AC interior is genuinely cold - a rare luxury on a tropical island - making it the most popular working cafe for nomads spending multiple weeks on Koh Tao.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Caffeine+Addiction+Koh+Tao', phone: '+66 92 345 6789', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/caffeine-addiction-koh-tao.jpg', tags: ['specialty', 'ac', 'cold-brew', 'nomad', 'single-origin'] },
  { name: 'Gallery Koh Tao Art Cafe', slug: 'gallery-art-cafe-koh-tao', category: 'CAFE', description: 'An art gallery and cafe in Mae Haad showcasing work by local and visiting artists alongside good coffee and light food. The Gallery hosts monthly art openings, photography exhibitions, and the most intellectual conversation on an island better known for dive tables and buckets of Thai whisky.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Gallery+Art+Cafe+Koh+Tao', phone: '+66 77 457 456', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/gallery-art-cafe-koh-tao.jpg', tags: ['art-gallery', 'coffee', 'exhibitions', 'cultural', 'intellectual'] },
  { name: 'Safety Stop Pub Koh Tao', slug: 'safety-stop-pub-koh-tao', category: 'CAFE', description: 'Named after the diving safety stop at 5 meters, this dive-community bar and cafe is where instructors, dive masters, and divers gather after the last dive of the day. The fish and chips, cold Singha, and the wall-to-wall dive photography make it the most atmospheric post-dive hangout on the island.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Safety+Stop+Pub+Koh+Tao', phone: '+66 77 457 567', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/safety-stop-pub-koh-tao.jpg', tags: ['dive-bar', 'fish-and-chips', 'post-dive', 'community', 'photography'] },
  { name: 'Breakfast Koh Tao', slug: 'breakfast-koh-tao', category: 'CAFE', description: 'A simple but excellent breakfast spot in Mae Haad serving proper all-day English breakfasts, Thai-style omelettes, fresh fruit smoothies, and the strongest coffee on the island. Divers who need a solid pre-dive meal and travelers who need to sit quietly for an hour before the ferry home both love this place equally.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Breakfast+Koh+Tao', phone: '+66 77 456 234', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/breakfast-koh-tao.jpg', tags: ['breakfast', 'all-day', 'smoothies', 'pre-dive', 'simple'] },
  // RESTAURANTS
  { name: 'Koh Tao Cabana Restaurant', slug: 'koh-tao-cabana-restaurant', category: 'FOOD', description: 'The finest restaurant on Koh Tao, set on a private beach at the Koh Tao Cabana Resort, with an elevated Thai and international menu and arguably the best sunset seafood dining on the island. The grilled lobster with garlic butter, whole snapper, and fresh oysters are all outstanding - reservations recommended.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Koh+Tao+Cabana+Restaurant', phone: '+66 77 456 250', website: 'https://kohtaocabana.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/koh-tao-cabana-restaurant.jpg', tags: ['seafood', 'sunset', 'lobster', 'private-beach', 'reservations'] },
  { name: 'Castle Restaurant Koh Tao', slug: 'castle-restaurant-koh-tao', category: 'FOOD', description: 'A quirky restaurant built into the granite boulders on the Chalok Ban Kao hillside with some of the most interesting views and architecture of any restaurant in Thailand. The Thai-international menu is solid and the rotating Thai cooking classes using fresh market ingredients are offered every Tuesday evening.', address: 'Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Castle+Restaurant+Koh+Tao', phone: '+66 77 456 789', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/castle-restaurant-koh-tao.jpg', tags: ['granite-boulders', 'cooking-class', 'views', 'architecture', 'tuesday'] },
  { name: 'Farango Koh Tao', slug: 'farango-koh-tao', category: 'FOOD', description: 'An Italian restaurant on Sairee Beach with genuine wood-fired pizza, fresh pasta, and an impressive wine list - the best Italian food within a 300km radius. The thin-crust Margherita with buffalo mozzarella and basil is extraordinary and the cannoli are made fresh daily.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Farango+Koh+Tao', phone: '+66 77 457 890', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/farango-koh-tao.jpg', tags: ['italian', 'wood-fired-pizza', 'pasta', 'cannoli', 'wine'] },
  { name: 'Chopper\'s Bar and Grill Koh Tao', slug: 'choppers-bar-grill-koh-tao', category: 'FOOD', description: 'A long-running favorite on the Sairee strip serving excellent BBQ, burgers, and steaks alongside cold beers and regular live music nights. Chopper\'s Koh Tao has fed thousands of divers after their last dives and the Tuesday and Friday night BBQ buffet is the most social eating event of the week.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Choppers+Bar+Grill+Koh+Tao', phone: '+66 77 456 012', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/choppers-bar-grill-koh-tao.jpg', tags: ['bbq', 'live-music', 'buffet', 'tuesday-friday', 'social'] },
  { name: 'Zest Cafe Koh Tao', slug: 'zest-cafe-koh-tao', category: 'FOOD', description: 'A health-conscious cafe and restaurant in Mae Haad with excellent organic Thai food, green smoothies, and a strong commitment to environmentally friendly ingredients. Zest Koh Tao is aligned with the island\'s growing reef conservation culture - the packaging is plastic-free and the menu features locally caught sustainable fish.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Zest+Cafe+Koh+Tao', phone: '+66 77 457 123', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/zest-cafe-koh-tao.jpg', tags: ['organic', 'sustainable', 'plastic-free', 'healthy', 'reef-conscious'] },
  { name: 'Pranee\'s Kitchen Koh Tao', slug: 'pranees-kitchen-koh-tao', category: 'FOOD', description: 'A tiny, authentic Thai restaurant in Mae Haad where Pranee has been cooking the same excellent pad kra pao, tom kha, and green curry since 2001. The plastic chairs, neon lights, and market-fresh ingredients define the honest Thai cooking that travelers come to Thailand specifically to find.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Pranees+Kitchen+Koh+Tao', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/pranees-kitchen-koh-tao.jpg', tags: ['thai', 'authentic', 'local', 'pad-kra-pao', '2001'] },
  // MARKETS
  { name: 'Mae Haad Pier Market Koh Tao', slug: 'mae-haad-pier-market-koh-tao', category: 'FOOD', description: 'The daily market area surrounding Koh Tao\'s main pier with food stalls, fresh fruit vendors, dive equipment shops, and souvenir sellers. The morning market sees returning fishing boats land the night catch - fresh yellowfin tuna, barracuda, and mahi-mahi sold directly from boat to vendor.', address: 'Mae Haad Pier, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mae+Haad+Pier+Koh+Tao', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/mae-haad-pier-market-koh-tao.jpg', tags: ['pier-market', 'fresh-fish', 'tuna', 'morning', 'boats'] },
  { name: 'Sairee Night Food Market Koh Tao', slug: 'sairee-night-food-market-koh-tao', category: 'FOOD', description: 'An evening food market at the top of the Sairee Beach road with Thai street food stalls, grilled seafood, som tam salad, pad thai, and fresh fruit shakes at local prices. The market provides an affordable alternative to the beach restaurants and is where the island\'s dive instructors and long-stay workers eat dinner.', address: 'Sairee Road, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Sairee+Night+Market+Koh+Tao', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/sairee-night-food-market-koh-tao.jpg', tags: ['night-market', 'pad-thai', 'som-tam', 'affordable', 'local'] },
  { name: 'Chalok Ban Kao Village Market', slug: 'chalok-ban-kao-village-market-koh-tao', category: 'FOOD', description: 'A small neighborhood market in the quieter Chalok Ban Kao bay area with a few Thai food stalls, fresh coconuts, and a morning coffee cart. The village market captures the authentic community life of the southern bay away from the tourist development of Sairee - a more local Koh Tao experience.', address: 'Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Chalok+Ban+Kao+Village+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/chalok-ban-kao-village-market-koh-tao.jpg', tags: ['village-market', 'local', 'coconut', 'chalok', 'morning'] },
  { name: 'Zero Waste Market Koh Tao', slug: 'zero-waste-market-koh-tao', category: 'FOOD', description: 'A monthly Saturday market organized by Koh Tao\'s conservation community with refill stations for sunscreen, shampoo, and cleaning products, organic produce from island gardens, and handmade eco-products. Koh Tao has one of the most active zero-waste communities in Thailand and this market is the hub.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Zero+Waste+Market+Koh+Tao', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/zero-waste-market-koh-tao.jpg', tags: ['zero-waste', 'refill', 'conservation', 'organic', 'monthly'] },
  { name: 'Dive Equipment Market Koh Tao', slug: 'dive-equipment-market-koh-tao', category: 'FOOD', description: 'A permanent cluster of dive equipment and wetsuit shops along Mae Haad\'s main pier road where second-hand dive gear, wetsuits, fins, and masks are bought, sold, and traded between the rotating population of dive professionals and divers on the island. Essential for long-stay divers looking to upgrade their kit.', address: 'Mae Haad Road, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Dive+Equipment+Shops+Koh+Tao', phone: null, website: null, priceRange: 'MID', rating: 4.3, imageUrl: '/spots/dive-equipment-market-koh-tao.jpg', tags: ['dive-equipment', 'second-hand', 'wetsuit', 'gear', 'equipment'] },
  // TOURIST SITES
  { name: 'Chumphon Pinnacle Koh Tao', slug: 'chumphon-pinnacle-koh-tao', category: 'NATURE', description: 'The finest dive site in the Gulf of Thailand - an underwater granite pinnacle rising from 36 meters with a schooling presence of whale sharks from February to May, plus massive schools of chevron barracuda, giant grouper, and pelagics. Achievable with an Advanced Open Water certification.', address: 'Northwest of Koh Tao, Surat Thani, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Chumphon+Pinnacle+Koh+Tao', phone: null, website: null, priceRange: 'MID', rating: 4.9, imageUrl: '/spots/chumphon-pinnacle-koh-tao.jpg', tags: ['diving', 'whale-sharks', 'pinnacle', 'barracuda', 'advanced'] },
  { name: 'HTMS Sattakut Wreck Dive', slug: 'htms-sattakut-wreck-koh-tao', category: 'NATURE', description: 'A US Navy minesweeper sunk in 2011 specifically to create a dive site, now lying at 30 meters with coral growth, lionfish, scorpionfish, and resident moray eels throughout the 57-meter hull. The most accessible wreck dive in the Gulf of Thailand for Advanced divers.', address: 'South of Koh Tao, Surat Thani, Thailand', googleMapsUrl: 'https://maps.google.com/?q=HTMS+Sattakut+Wreck+Koh+Tao', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/htms-sattakut-wreck-koh-tao.jpg', tags: ['wreck-dive', 'lionfish', 'advanced', 'artificial-reef', 'coral'] },
  { name: 'Tanote Bay Koh Tao', slug: 'tanote-bay-koh-tao', category: 'NATURE', description: 'The most beautiful bay on Koh Tao\'s eastern coast - a protected cove with crystal-clear water, excellent shore diving among giant boulders, and a remote location that requires a 30-minute walk or longtail taxi. The underwater landscape of the bay, with massive granite formations, is unlike any other dive on the island.', address: 'Tanote Bay, East Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Tanote+Bay+Koh+Tao', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/tanote-bay-koh-tao.jpg', tags: ['beach', 'shore-diving', 'granite', 'remote', 'beautiful'] },
  { name: 'Shark Bay (Thian Og Bay) Koh Tao', slug: 'shark-bay-koh-tao', category: 'NATURE', description: 'A sheltered bay where juvenile blacktip reef sharks can be reliably spotted in the shallow waters - one of the few places in the world where you can snorkel with sharks without diving certification. The sharks are small, completely harmless, and the snorkeling from the beach is exceptional.', address: 'Thian Og Bay (Shark Bay), South Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Shark+Bay+Koh+Tao', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/shark-bay-koh-tao.jpg', tags: ['blacktip-sharks', 'snorkeling', 'family-friendly', 'shallow', 'guaranteed'] },
  { name: 'Koh Nang Yuan Island Koh Tao', slug: 'koh-nang-yuan-koh-tao', category: 'NATURE', description: 'Three tiny islands connected by sand bars just 500m from Koh Tao\'s northwest coast, with the most spectacular viewpoint in the Gulf of Thailand from the rocky summit (30-minute climb). The dive sites around Nang Yuan including Japanese Gardens coral reef are among the best beginner dives in Southeast Asia.', address: 'Koh Nang Yuan, near Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Koh+Nang+Yuan', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/koh-nang-yuan-koh-tao.jpg', tags: ['island', 'viewpoint', 'diving', 'sand-bar', 'iconic'] },
  { name: 'Sairee Beach Koh Tao', slug: 'sairee-beach-koh-tao', category: 'NATURE', description: 'The main beach of Koh Tao - a 2km stretch of white sand on the west coast that is the center of diving, nightlife, food, and social activity on the island. The sunset views from Sairee looking towards Koh Nang Yuan are among the best in the Gulf of Thailand and the diving off the beach is accessible for beginners.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Sairee+Beach+Koh+Tao', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/sairee-beach-koh-tao.jpg', tags: ['beach', 'sunset', 'diving', 'nightlife', 'main-beach'] },
  { name: 'Koh Tao Viewpoint (John-Suwan Viewpoint)', slug: 'john-suwan-viewpoint-koh-tao', category: 'NATURE', description: 'The most accessible hilltop viewpoint on Koh Tao, a 20-minute walk from Chalok Ban Kao bay through tropical forest, offering sweeping 270-degree views of the island\'s bays, the Gulf of Thailand, and the surrounding islands on clear days. Best visited at sunrise when the mist over the sea turns golden.', address: 'Between Chalok and Tanote, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=John+Suwan+Viewpoint+Koh+Tao', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/john-suwan-viewpoint-koh-tao.jpg', tags: ['viewpoint', 'sunrise', 'hiking', 'panoramic', 'free'] },
  { name: 'Reef Conservation Koh Tao', slug: 'reef-conservation-koh-tao', category: 'CULTURE', description: 'New Heaven Reef Conservation Program - the most active reef conservation initiative in Thailand, training divers to monitor, restore, and protect Koh Tao\'s coral reefs. Volunteer programs from 1 day to 3 months allow divers to collect data, install coral nurseries, and remove invasive species from reef sites around the island.', address: 'Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=New+Heaven+Reef+Conservation+Koh+Tao', phone: '+66 77 457 045', website: 'https://newheavendiveschool.com', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/reef-conservation-koh-tao.jpg', tags: ['conservation', 'coral-nursery', 'volunteering', 'diving', 'reef-monitoring'] },
  { name: 'Koh Tao Leisure Park', slug: 'koh-tao-leisure-park', category: 'CULTURE', description: 'A recreational park at the top of the island with a zipline over jungle canopy, a cliff jump platform, rock climbing wall, and panoramic sea views. The leisure park is the best non-diving activity on Koh Tao and the zipline provides a bird\'s eye perspective of the island that even longtime divers haven\'t seen.', address: 'North Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Koh+Tao+Leisure+Park', phone: '+66 77 456 098', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/koh-tao-leisure-park.jpg', tags: ['zipline', 'cliff-jump', 'climbing', 'panoramic', 'adventure'] },
  // COWORKING
  { name: 'Koh Tao Coworking Space', slug: 'koh-tao-coworking-space', category: 'COWORKING', description: 'The primary dedicated coworking space on Koh Tao with fast fiber internet, ergonomic chairs, AC, private meeting booths, and a small cafe. Serving the growing community of dive instructor-turned-nomads and visitors working remotely while completing dive certifications, day passes and monthly plans are available.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Koh+Tao+Coworking+Space', phone: '+66 92 456 7890', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/koh-tao-coworking-space.jpg', tags: ['coworking', 'fiber', 'ac', 'day-pass', 'dive-nomad'] },
  { name: 'Deep Blue Dive and Work Koh Tao', slug: 'deep-blue-dive-work-koh-tao', category: 'COWORKING', description: 'A unique hybrid dive school and coworking hub where remote workers can do morning dives and afternoon desk work without changing locations. The desk package includes fiber internet, coffee, dive storage, and equipment rinse station - a concept unique to Koh Tao that serves the island\'s working diver community.', address: 'Mae Haad, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Deep+Blue+Dive+Koh+Tao', phone: '+66 77 456 198', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/deep-blue-dive-work-koh-tao.jpg', tags: ['dive-coworking', 'hybrid', 'morning-dives', 'unique', 'equipment-storage'] },
  { name: 'Ocean View Workspace Koh Tao', slug: 'ocean-view-workspace-koh-tao', category: 'COWORKING', description: 'A breezy open-plan workspace on a hillside above Mae Haad with panoramic ocean views, reliable wifi, standing desks, and a policy of unlimited coffee included with any pass. The best views from a workspace on any island in the Gulf of Thailand - afternoon work here comes with a built-in sunset show.', address: 'Mae Haad Hill, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Ocean+View+Workspace+Koh+Tao', phone: '+66 93 567 8901', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/ocean-view-workspace-koh-tao.jpg', tags: ['ocean-views', 'sunset', 'standing-desks', 'unlimited-coffee', 'hillside'] },
  { name: 'The Island Lab Koh Tao', slug: 'island-lab-koh-tao', category: 'COWORKING', description: 'A tech-forward coworking and entrepreneurship hub run by a Singapore-educated entrepreneur, offering dedicated desks, private offices, a podcast studio, and a monthly "Island Business" community program connecting Koh Tao entrepreneurs with international visitors who can offer expertise and partnerships.', address: 'Sairee, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Island+Lab+Coworking+Koh+Tao', phone: '+66 93 678 9012', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/island-lab-koh-tao.jpg', tags: ['tech', 'podcast-studio', 'community', 'entrepreneur', 'partnerships'] },
  { name: 'Nomad Island Koh Tao Cowork', slug: 'nomad-island-koh-tao-cowork', category: 'COWORKING', description: 'A casual coworking cafe in Chalok Ban Kao with good wifi, simple desks, cold brew on tap, and a terrace overlooking the southern bay. Nomad Island serves the quieter southern side of Koh Tao where diving instructors, conservation researchers, and long-stay nomads prefer to live and work away from the Sairee crowds.', address: 'Chalok Ban Kao, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Nomad+Island+Koh+Tao', phone: '+66 93 789 0123', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/nomad-island-koh-tao-cowork.jpg', tags: ['cafe-cowork', 'chalok', 'cold-brew', 'terrace', 'southern-bay'] },
  { name: 'Sairee Digital Hub Koh Tao', slug: 'sairee-digital-hub-koh-tao', category: 'COWORKING', description: 'A fully equipped coworking space on the main Sairee strip with 50Mbps fiber, ergonomic seating, a printer, meeting room, and a ground-floor cafe with the island\'s best cold brew. Open from 7am to midnight with 24-hour keycard access for monthly members - the most professional workspace on Koh Tao\'s main beach strip.', address: 'Sairee Beach, Koh Tao, Surat Thani 84360, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Sairee+Digital+Hub+Koh+Tao', phone: '+66 93 890 1234', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/sairee-digital-hub-koh-tao.jpg', tags: ['coworking', 'fiber', 'monthly', '24-hour', 'sairee'] },
  { name: 'Japanese Garden Dive Site Koh Tao', slug: 'japanese-garden-dive-site-koh-tao', category: 'NATURE', description: 'The most beautiful and accessible shallow reef in the Gulf of Thailand - an enormous coral garden between Koh Tao and Koh Nang Yuan with staghorn corals, brain corals, and remarkable marine life at depths of 4-14 meters. Japanese Garden is consistently ranked among the top snorkeling and beginner dive sites in all of Southeast Asia.', address: 'Between Koh Tao and Koh Nang Yuan, Surat Thani, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Japanese+Garden+Koh+Tao', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/japanese-garden-dive-site-koh-tao.jpg', tags: ['coral-garden', 'snorkeling', 'shallow-reef', 'beginners', 'top-site'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Koh Tao: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
