const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const CITY_ID = 'cmq328iyu0013vi8wlvyx7snk';

const spots = [
  // 4 Luxury Hotels
  { slug: 'guilin-bravo-hotel', name: 'Guilin Bravo Hotel', category: 'ACCOMMODATION', priceRange: 'HIGH', address: '14 Ronghu North Road, Guilin', description: 'Upscale hotel on the shores of Ronghu Lake with stunning karst views, rooftop pool, and refined Chinese decor. A top choice for solo travelers wanting comfort and a central location.', website: 'https://www.guilinbravo.com', tags: ['luxury', 'lake-view', 'central', 'pool'] },
  { slug: 'sheraton-guilin-hotel', name: 'Sheraton Guilin Hotel', category: 'ACCOMMODATION', priceRange: 'HIGH', address: '15 Binjiang Road, Guilin', description: 'Riverside luxury hotel with floor-to-ceiling views of the Li River and karst peaks. Excellent facilities including a spa, multiple restaurants, and a fitness center.', website: 'https://www.marriott.com', tags: ['luxury', 'river-view', 'spa', 'marriott'] },
  { slug: 'lijiang-waterfall-hotel', name: 'Lijiang Waterfall Hotel', category: 'ACCOMMODATION', priceRange: 'HIGH', address: '1 Shanhu North Road, Guilin', description: 'Famous for its man-made waterfall cascading down the facade, this landmark hotel offers plush rooms, multiple dining options, and a prime location in the city center.', website: 'https://www.waterfallhotel.com.cn', tags: ['landmark', 'waterfall', 'luxury', 'central'] },
  { slug: 'guilin-royal-garden-hotel', name: 'Guilin Royal Garden Hotel', category: 'ACCOMMODATION', priceRange: 'HIGH', address: '1 Yanshan Lane, Guilin', description: 'Elegant hotel set in traditional Chinese garden surroundings near Two Rivers and Four Lakes. Offers tranquil rooms, a tea house, and attentive service for discerning solo travelers.', website: 'https://www.royalgardenhotel.com.cn', tags: ['garden', 'luxury', 'traditional', 'peaceful'] },

  // 4 Budget Hotels
  { slug: 'guilin-park-hotel', name: 'Guilin Park Hotel', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: '2 Zhongshan Middle Road, Guilin', description: 'Affordable and clean hotel in the heart of Guilin, walking distance to major attractions. Simple but comfortable rooms with friendly staff who speak basic English.', website: null, tags: ['budget', 'central', 'solo-friendly'] },
  { slug: 'ninyou-boutique-hotel', name: 'Ninyou Boutique Hotel', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Zhengyang Pedestrian Street, Guilin', description: 'Cozy budget boutique on the famous Zhengyang walking street. Great base for exploring cafes, street food, and the night market right at your doorstep.', website: null, tags: ['budget', 'boutique', 'pedestrian-street', 'convenient'] },
  { slug: 'guilin-city-inn', name: 'Guilin City Inn', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Jiefang East Road, Guilin', description: 'No-frills guesthouse popular with backpackers and budget solo travelers. Clean rooms, fast WiFi, and a helpful front desk that can arrange Li River tours and Yangshuo day trips.', website: null, tags: ['budget', 'backpacker', 'tour-arrangements'] },
  { slug: 'zen-garden-guesthouse', name: 'Zen Garden Guesthouse', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Jingjiang Road, Guilin', description: 'Small family-run guesthouse with a calm courtyard garden. Good value for solo travelers who prefer a quieter stay away from the busiest tourist areas but still central.', website: null, tags: ['budget', 'guesthouse', 'quiet', 'garden'] },

  // 4 Hostels
  { slug: 'beds-and-bars-guilin', name: 'Guilin Mix Hostel', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Zhengyang Pedestrian Street, Guilin', description: 'Lively social hostel on Zhengyang Street with mixed and female-only dorms, a rooftop lounge, and nightly events. Great for solo travelers wanting to connect with others.', website: null, tags: ['hostel', 'social', 'dorms', 'rooftop'] },
  { slug: 'phoenix-hostel-guilin', name: 'Phoenix Hostel Guilin', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Ronghu North Road, Guilin', description: 'Award-winning hostel near Ronghu Lake with stylish dorms, a cozy common room, and a popular bar. Voted one of the best hostels in Guilin for solo travelers.', website: null, tags: ['hostel', 'award-winning', 'bar', 'lake-view'] },
  { slug: 'blue-sky-hostel-guilin', name: 'Blue Sky Hostel', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Jiefang Road, Guilin', description: 'Budget hostel with a relaxed vibe and helpful staff who organize group tours to Yangshuo, the Reed Flute Cave, and Li River cruises. A solid base for solo exploration.', website: null, tags: ['hostel', 'budget', 'tours', 'solo-friendly'] },
  { slug: 'downtown-inn-guilin', name: 'Downtown Inn Guilin', category: 'ACCOMMODATION', priceRange: 'BUDGET', address: 'Zhongshan Road, Guilin', description: 'Central hostel with private rooms and dorms, common kitchen, and a board games lounge. Popular with solo travelers on a tight budget who want a social atmosphere.', website: null, tags: ['hostel', 'dorms', 'kitchen', 'central'] },

  // 6 Cafes
  { slug: 'karst-coffee-guilin', name: 'Karst Coffee', category: 'CAFE', priceRange: 'BUDGET', address: 'Zhengyang Street, Guilin', description: 'Charming independent cafe on the pedestrian street serving specialty coffee and local teas. The upper floor has karst mountain views and is a favorite working spot for solo travelers.', website: null, tags: ['coffee', 'wifi', 'cozy', 'views'] },
  { slug: 'riverside-brew-guilin', name: 'Riverside Brew Cafe', category: 'CAFE', priceRange: 'MID', address: 'Binjiang Road, Guilin', description: 'Stylish cafe on the Li River bank with outdoor seating and excellent cold brews. A relaxing spot to read, work, or watch boats drift past the karst backdrop.', website: null, tags: ['coffee', 'river-view', 'outdoor', 'wifi'] },
  { slug: 'tea-house-guilin-old-town', name: 'Old Town Tea House', category: 'CAFE', priceRange: 'BUDGET', address: 'Jingjiang Prince City area, Guilin', description: 'Traditional Chinese tea house near the Prince City offering an immersive tea ceremony experience. Try Guilin\'s famous osmanthus tea paired with local snacks.', website: null, tags: ['tea', 'traditional', 'cultural', 'osmanthus'] },
  { slug: 'bookworm-cafe-guilin', name: 'The Bookworm Cafe', category: 'CAFE', priceRange: 'BUDGET', address: 'Jiejie Road, Guilin', description: 'Expat-friendly cafe with a good selection of English books, reliable WiFi, and a menu of Western and local dishes. A popular remote work spot for solo digital nomads.', website: null, tags: ['books', 'expat', 'wifi', 'remote-work'] },
  { slug: 'sugar-and-spice-guilin', name: 'Sugar and Spice Bakery Cafe', category: 'CAFE', priceRange: 'BUDGET', address: 'Zhongshan Middle Road, Guilin', description: 'Cozy bakery cafe serving fresh pastries, decent coffee, and light breakfast fare. A convenient and affordable morning spot before heading out to the Li River or caves.', website: null, tags: ['bakery', 'breakfast', 'coffee', 'affordable'] },
  { slug: 'yulong-river-coffee', name: 'Yulong River Coffee', category: 'CAFE', priceRange: 'MID', address: 'Yangshuo area, Guilin district', description: 'Idyllic bamboo-deck cafe beside the Yulong River in Yangshuo, serving hand-drip coffee and freshly squeezed juices. One of the most scenic cafe settings in the region.', website: null, tags: ['coffee', 'scenic', 'bamboo', 'yangshuo'] },

  // 6 Restaurants
  { slug: 'guilin-rice-noodle-house', name: 'Guilin Rice Noodle House', category: 'FOOD', priceRange: 'BUDGET', address: 'Zhengyang Street, Guilin', description: 'The quintessential Guilin experience: a bowl of Guilin mifen (rice noodles) with a tray of toppings to customize. Locals eat this for breakfast; solo travelers eat it all day.', website: null, tags: ['noodles', 'local', 'breakfast', 'budget'] },
  { slug: 'impression-liu-sanjie-restaurant', name: 'Lijiang Restaurant', category: 'FOOD', priceRange: 'MID', address: 'Binjiang Road, Guilin', description: 'Popular restaurant serving authentic Guilin cuisine including beer fish, stuffed li river snails, and osmanthus cake. Riverside tables fill up fast — arrive early for solo seating.', website: null, tags: ['local-cuisine', 'beer-fish', 'river-view', 'authentic'] },
  { slug: 'yangshuo-beer-fish-spot', name: 'West Street Beer Fish Restaurant', category: 'FOOD', priceRange: 'MID', address: 'West Street, Yangshuo', description: 'The famous dish of Yangshuo: Li River fish cooked in local Guilin beer with peppers and tomatoes. This West Street classic is a must-try for any solo traveler visiting Yangshuo.', website: null, tags: ['beer-fish', 'yangshuo', 'must-try', 'local'] },
  { slug: 'osmanthus-pavilion-guilin', name: 'Osmanthus Pavilion', category: 'FOOD', priceRange: 'MID', address: 'Ronghu North Road, Guilin', description: 'Elegant restaurant set in a traditional pavilion overlooking Ronghu Lake. Specializes in Guilin banquet cuisine — perfect for solo travelers wanting a memorable lakeside meal.', website: null, tags: ['lake-view', 'traditional', 'osmanthus', 'elegant'] },
  { slug: 'street-snacks-zhengyang', name: 'Zhengyang Street Night Food Strip', category: 'FOOD', priceRange: 'BUDGET', address: 'Zhengyang Pedestrian Street, Guilin', description: 'A parade of vendors offering grilled skewers, stinky tofu, osmanthus wine, candied hawthorn, and fresh fruit. An unmissable solo-friendly street food experience every evening.', website: null, tags: ['street-food', 'night-market', 'budget', 'snacks'] },
  { slug: 'minority-food-court-guilin', name: 'Zhuang Minority Food Court', category: 'FOOD', priceRange: 'BUDGET', address: 'Nationality Square, Guilin', description: 'Lively food court showcasing dishes from Guangxi\'s ethnic minorities including Zhuang sticky rice parcels, sour fish soup, and rice wine. An authentic cultural dining experience.', website: null, tags: ['minority-cuisine', 'zhuang', 'cultural', 'budget'] },

  // 5 Markets
  { slug: 'guilin-nightmarket', name: 'Guilin Night Market', category: 'FOOD', priceRange: 'BUDGET', address: 'Zhengyang Pedestrian Street, Guilin', description: 'The main evening market of Guilin where locals and travelers mix over skewers, local snacks, and cheap knick-knacks. Lively from 6pm and a great solo people-watching spot.', website: null, tags: ['market', 'night', 'street-food', 'shopping'] },
  { slug: 'zhengyang-pedestrian-market', name: 'Zhengyang Pedestrian Market', category: 'FOOD', priceRange: 'BUDGET', address: 'Zhengyang Road, Guilin', description: 'Guilin\'s main shopping and market street stretching for 800 meters. Find local crafts, jade, Guilin honey, osmanthus wine, and souvenir stalls alongside cafes and restaurants.', website: null, tags: ['market', 'shopping', 'crafts', 'souvenirs'] },
  { slug: 'guilin-arts-crafts-market', name: 'Guilin Arts & Crafts Market', category: 'FOOD', priceRange: 'BUDGET', address: 'Jiefang Road, Guilin', description: 'Covered market selling hand-painted karst scenery prints, minority embroidery, bamboo items, and jade carvings. A good place to find genuine Guangxi souvenirs and gifts.', website: null, tags: ['arts', 'crafts', 'market', 'souvenirs'] },
  { slug: 'yangshuo-street-market', name: 'Yangshuo Country Market', category: 'FOOD', priceRange: 'BUDGET', address: 'West Street, Yangshuo', description: 'The lively West Street market in Yangshuo is a mix of tourist shops and local vendors selling produce, handicrafts, and street food. Best visited in the morning for the freshest finds.', website: null, tags: ['market', 'yangshuo', 'local', 'morning'] },
  { slug: 'guilin-tea-market', name: 'Guilin Tea Market', category: 'FOOD', priceRange: 'BUDGET', address: 'Qixing Road, Guilin', description: 'Wholesale and retail tea market carrying dozens of Guangxi teas including osmanthus, liubao dark tea, and jasmine varieties. Vendors offer free tastings — a solo traveler\'s afternoon delight.', website: null, tags: ['tea', 'market', 'tasting', 'osmanthus'] },

  // 10 Tourist / Cultural / Nature Sites
  { slug: 'li-river-cruise', name: 'Li River Cruise', category: 'NATURE', priceRange: 'MID', address: 'Zhujiang Wharf, Guilin', description: 'The iconic 83km cruise from Guilin to Yangshuo through a landscape of emerald water, bamboo groves, and limestone peaks. One of China\'s most celebrated natural experiences for solo travelers.', website: 'https://www.lirivercruise.com', tags: ['river', 'cruise', 'iconic', 'karst', 'must-do'] },
  { slug: 'reed-flute-cave', name: 'Reed Flute Cave', category: 'CULTURE', priceRange: 'MID', address: 'Ludi Road, Guilin', description: 'A stunning 240-meter-long limestone cave illuminated by colored lights that transform stalactites and stalagmites into a surreal underground world. The highlight of Guilin\'s cave attractions.', website: 'https://www.reedflutecave.com', tags: ['cave', 'limestone', 'lights', 'iconic'] },
  { slug: 'elephant-trunk-hill', name: 'Elephant Trunk Hill', category: 'NATURE', priceRange: 'MID', address: 'Elephant Trunk Hill Park, Guilin', description: 'Guilin\'s most recognizable landmark — a hill shaped like an elephant drinking from the Li River. A must-photograph spot with scenic walking paths and views over the river.', website: null, tags: ['landmark', 'iconic', 'river', 'photogenic'] },
  { slug: 'jingjiang-prince-city', name: 'Jingjiang Prince City', category: 'CULTURE', priceRange: 'MID', address: '1 Jingjiang Road, Guilin', description: 'Ancient Ming-dynasty imperial city in the heart of Guilin, home to one of the oldest well-preserved prince palaces in China. The moat, walls, and palace grounds are a living history lesson.', website: null, tags: ['history', 'ming-dynasty', 'palace', 'culture'] },
  { slug: 'seven-star-park', name: 'Seven Star Park', category: 'NATURE', priceRange: 'BUDGET', address: 'Seven Star Road, Guilin', description: 'Guilin\'s largest park features karst peaks, caves, rivers, a zoo, and the famous Camel Peak. A peaceful place to hike, cycle, and enjoy nature without the tourist crowds.', website: null, tags: ['park', 'hiking', 'karst', 'peaceful'] },
  { slug: 'yangshuo-countryside', name: 'Yangshuo Countryside Cycling', category: 'NATURE', priceRange: 'BUDGET', address: 'Yangshuo County', description: 'Rent a bicycle in Yangshuo and pedal through rice paddies, karst valleys, and rural villages along the Yulong River. One of the best slow travel experiences in Asia.', website: null, tags: ['cycling', 'countryside', 'yangshuo', 'solo-friendly'] },
  { slug: 'longji-rice-terraces', name: 'Longji Rice Terraces', category: 'NATURE', priceRange: 'MID', address: 'Longsheng County, Guilin', description: 'Breathtaking dragon\'s backbone rice terraces carved into steep mountain slopes by Zhuang and Yao minorities over 700 years. Best visited in May (green) or October (golden harvest).', website: null, tags: ['terraces', 'rice', 'minority', 'photography', 'nature'] },
  { slug: 'moon-hill-yangshuo', name: 'Moon Hill', category: 'NATURE', priceRange: 'FREE', address: 'Gaotian Town, Yangshuo', description: 'A natural limestone arch in the shape of a crescent moon, reached by a 30-minute hike up steep stairs. The views from the top over the Yangshuo valley are unforgettable.', website: null, tags: ['hiking', 'arch', 'views', 'yangshuo', 'free'] },
  { slug: 'guilin-two-rivers-four-lakes', name: 'Two Rivers and Four Lakes', category: 'NATURE', priceRange: 'MID', address: 'City center, Guilin', description: 'An evening boat cruise connecting Guilin\'s two rivers (Li and Peach Blossom) and four lakes, passing illuminated pagodas, stone bridges, and karst silhouettes. Magical for solo night wanderers.', website: null, tags: ['cruise', 'evening', 'lakes', 'illuminated', 'romantic'] },
  { slug: 'guilin-sun-moon-twin-pagodas', name: 'Sun and Moon Twin Pagodas', category: 'CULTURE', priceRange: 'BUDGET', address: 'Shan Lake, Guilin', description: 'Iconic twin pagodas rising from Shan Lake connected by an underwater tunnel. The golden Sun Pagoda and bronze Moon Pagoda are especially spectacular after dark when lit up.', website: null, tags: ['pagodas', 'lake', 'iconic', 'night', 'photogenic'] },

  // 6 Coworking
  { slug: 'karst-hub-guilin', name: 'Karst Hub', category: 'COWORKING', priceRange: 'MID', address: 'Zhongshan Middle Road, Guilin', description: 'Modern coworking space with fast fiber WiFi, standing desks, meeting rooms, and a well-stocked coffee bar. Popular with remote workers and freelancers based in Guilin.', website: null, tags: ['coworking', 'wifi', 'standing-desks', 'coffee'] },
  { slug: 'west-street-co-yangshuo', name: 'West Street Co', category: 'COWORKING', priceRange: 'BUDGET', address: 'West Street, Yangshuo', description: 'Informal coworking cafe in Yangshuo catering to digital nomads doing the Li River circuit. Drop-in passes available; good WiFi and a social atmosphere in a prime tourist-hub location.', website: null, tags: ['coworking', 'yangshuo', 'drop-in', 'nomad'] },
  { slug: 'guilin-maker-space', name: 'Guilin Maker Space', category: 'COWORKING', priceRange: 'MID', address: 'Qixing Road, Guilin', description: 'Tech-focused coworking and maker space with 3D printers, laser cutters, and hot desks. Popular with startups and creative freelancers; monthly memberships and daily passes available.', website: null, tags: ['coworking', 'maker', 'tech', 'startup'] },
  { slug: 'ronghu-work-lounge', name: 'Ronghu Work Lounge', category: 'COWORKING', priceRange: 'MID', address: 'Ronghu North Road, Guilin', description: 'Relaxed coworking lounge with lake-view windows, ergonomic chairs, and a curated coffee menu. Ideal for solo remote workers who want a scenic and productive environment.', website: null, tags: ['coworking', 'lake-view', 'ergonomic', 'coffee'] },
  { slug: 'guilin-creative-lab', name: 'Guilin Creative Lab', category: 'COWORKING', priceRange: 'BUDGET', address: 'Jiefang Road, Guilin', description: 'Affordable coworking in a converted art studio with natural light, whiteboard walls, and a collaborative community of designers and writers. Day passes and weekly rates available.', website: null, tags: ['coworking', 'creative', 'affordable', 'artists'] },
  { slug: 'karst-valley-remote-office', name: 'Karst Valley Remote Office', category: 'COWORKING', priceRange: 'MID', address: 'Yangshuo County', description: 'Unique open-air coworking venue set among karst peaks outside Yangshuo. Solar-powered WiFi, bamboo desks, and mountain views make this one of the most scenic remote workspaces in Asia.', website: null, tags: ['coworking', 'outdoor', 'karst-views', 'unique', 'solar'] },
];

async function main() {
  let seeded = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({
      data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } }
    });
    seeded++;
  }
  console.log(`Guilin: ${seeded} seeded, ${skipped} skipped`);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
