const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328d2u000fvi8wcbx5vbhw';

const spots = [
  // LUXURY HOTELS
  { name: 'Eastern & Oriental Hotel Penang', slug: 'eastern-oriental-hotel-penang', category: 'ACCOMMODATION', description: 'The grande dame of Penang, open since 1885 and associated with Somerset Maugham and Noel Coward, set in a magnificent white colonial building on the seafront. The Victory Annexe suites have views over the Strait of Malacca and the famous 1885 dining room remains one of Malaysia\'s great culinary experiences.', address: '10 Lebuh Farquhar, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Eastern+Oriental+Hotel+Penang', phone: '+60 4-222 2000', website: 'https://www.eohotels.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/eastern-oriental-hotel-penang.jpg', tags: ['colonial', 'heritage', '1885', 'historic', 'iconic'] },
  { name: 'Prestige Hotel Penang', slug: 'prestige-hotel-penang', category: 'ACCOMMODATION', description: 'A contemporary luxury hotel in the heritage core of George Town with stunning rooftop infinity pool, a Michelin-recommended restaurant, and suites with balcony views over the UNESCO World Heritage streetscapes. The location on Lebuh Farquhar puts every George Town sight within walking distance.', address: '8 Lebuh Farquhar, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Prestige+Hotel+Penang', phone: '+60 4-259 9000', website: 'https://www.prestigepenang.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/prestige-hotel-penang.jpg', tags: ['luxury', 'rooftop-pool', 'heritage-core', 'michelin', 'views'] },
  { name: 'Shangri-La Rasa Sayang Penang', slug: 'shangri-la-rasa-sayang-penang', category: 'ACCOMMODATION', description: 'The most iconic beach resort in Penang, set on 30 acres of tropical gardens on Batu Ferringhi beach. The Rasa Sayang exudes classic tropical luxury with two massive pools, a world-class spa, and the best sunset views on the island. A legend since 1973.', address: 'Batu Ferringhi, Penang 11100, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Shangri-La+Rasa+Sayang+Penang', phone: '+60 4-888 8888', website: 'https://www.shangri-la.com/penang/rasasayangresort', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/shangri-la-rasa-sayang-penang.jpg', tags: ['beach', 'resort', 'pool', 'spa', 'batu-ferringhi'] },
  { name: 'Seven Terraces Penang', slug: 'seven-terraces-penang', category: 'ACCOMMODATION', description: 'A boutique luxury hotel created from seven 19th-century Peranakan shophouses, with just 18 suites each individually decorated with antique furniture, silk brocades, and period Baba-Nyonya artifacts. The most authentic luxury stay in George Town\'s UNESCO heritage zone.', address: 'Stewart Lane, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Seven+Terraces+Penang', phone: '+60 4-264 2333', website: 'https://www.seventerraces.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/seven-terraces-penang.jpg', tags: ['boutique', 'peranakan', 'shophouse', 'antique', 'heritage'] },
  // BUDGET HOTELS
  { name: 'Ryokan Muntri Penang', slug: 'ryokan-muntri-penang', category: 'ACCOMMODATION', description: 'A Japanese-influenced boutique hotel in a restored 1930s George Town shophouse with minimalist rooms, a Japanese garden courtyard, and excellent coffee downstairs. The fusion of Japanese aesthetics and Penang heritage architecture makes it one of the most distinctive mid-range hotels in Malaysia.', address: '12 Muntri Street, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Ryokan+Muntri+Penang', phone: '+60 4-264 3113', website: 'https://www.ryokanmuntri.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/ryokan-muntri-penang.jpg', tags: ['japanese', 'shophouse', 'boutique', 'garden', 'minimalist'] },
  { name: 'The Edison George Town Penang', slug: 'edison-george-town-penang', category: 'ACCOMMODATION', description: 'A beautifully restored heritage hotel in a 1920s building near the Chinese temple quarter with rooms designed around Penang\'s multicultural history. The Edison George Town\'s rooftop cocktail bar and heritage walking tours make it excellent value for culturally-minded travelers.', address: '15A Lebuh Leith, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Edison+George+Town+Penang', phone: '+60 4-261 2929', website: 'https://theedisonhotels.com/george-town', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/edison-george-town-penang.jpg', tags: ['heritage', '1920s', 'rooftop-bar', 'history', 'walking-tours'] },
  { name: 'Hotel Penaga Penang', slug: 'hotel-penaga-penang', category: 'ACCOMMODATION', description: 'A design-forward boutique hotel in two adjacent George Town shophouses with a stunning art deco aesthetic, a lap pool, and an excellent restaurant. The Penaga\'s location in the heart of the Cannery arts precinct puts galleries, murals, and the best cafes within immediate reach.', address: 'Corner of Hutton Lane and Transfer Road, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Penaga+Penang', phone: '+60 4-229 9229', website: 'https://hotelpenaga.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/hotel-penaga-penang.jpg', tags: ['design', 'art-deco', 'pool', 'arts-precinct', 'boutique'] },
  { name: 'Roomies George Town Penang', slug: 'roomies-george-town-penang', category: 'ACCOMMODATION', description: 'A comfortable budget hotel in the heritage core with well-designed rooms, fast wifi, and a friendly reception team. Roomies punches above its price point with free bicycle rental, a cafe serving local kopitiam breakfast, and a prime location near all the major street art.', address: '226 Lebuh Chulia, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Roomies+George+Town+Penang', phone: '+60 4-261 8888', website: 'https://roomieshotel.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/roomies-george-town-penang.jpg', tags: ['budget', 'bicycle', 'kopitiam', 'street-art', 'central'] },
  // HOSTELS
  { name: 'Yeng Keng Hotel Penang', slug: 'yeng-keng-hotel-penang', category: 'ACCOMMODATION', description: 'One of the oldest continuously operating hotels in George Town, with a history dating to the 1920s and occupying a magnificent colonial building near the waterfront. Affordable heritage stays with high ceilings, original tilework, and the atmosphere of old Malaya that no new hotel can replicate.', address: '362 Lebuh Chulia, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Yeng+Keng+Hotel+Penang', phone: '+60 4-262 2177', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/yeng-keng-hotel-penang.jpg', tags: ['historic', '1920s', 'colonial', 'heritage', 'cheap'] },
  { name: 'Reggae Mansion George Town Penang', slug: 'reggae-mansion-penang', category: 'ACCOMMODATION', description: 'A legendary backpacker institution in the heart of the heritage zone with rooftop bar, social events, and a party atmosphere that has connected generations of travelers. The dorms are clean, the Mango Tree bar is always lively, and the 24-hour reception desk can help with anything Penang-related.', address: '183 Lebuh Chulia, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Reggae+Mansion+Penang', phone: '+60 4-263 2183', website: 'https://reggaemansion.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/reggae-mansion-penang.jpg', tags: ['party', 'rooftop-bar', 'social', 'backpacker', 'institution'] },
  { name: 'Jalan Jalan Guesthouse Penang', slug: 'jalan-jalan-guesthouse-penang', category: 'ACCOMMODATION', description: 'A quiet, well-run guesthouse in a traditional Penang shophouse with a lovely inner courtyard and individually decorated rooms. The Malaysian owner serves a generous local breakfast each morning and is an encyclopedic source of information on every Penang hawker stall worth knowing.', address: '62 Penang Road, George Town, Penang 10000, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Jalan+Jalan+Guesthouse+Penang', phone: '+60 4-261 5500', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/jalan-jalan-guesthouse-penang.jpg', tags: ['quiet', 'shophouse', 'courtyard', 'breakfast', 'local-tips'] },
  { name: 'Penang Backpacker Hostel', slug: 'penang-backpacker-hostel', category: 'ACCOMMODATION', description: 'A no-frills clean hostel on the main backpacker street with pod bunks, AC dorms, secure storage, and an excellent notice board for finding day-trip partners. The hostel runs a free daily walking tour of George Town street art and murals that many guests consider the highlight of their Penang visit.', address: '158 Lebuh Chulia, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Penang+Backpacker+Hostel', phone: '+60 4-261 5500', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/penang-backpacker-hostel.jpg', tags: ['budget', 'pods', 'walking-tour', 'street-art', 'backpacker'] },
  // CAFES
  { name: 'VCR Penang', slug: 'vcr-cafe-penang', category: 'CAFE', description: 'A beloved Penang specialty coffee institution that helped launch the island\'s third-wave coffee scene, with excellent espresso, cold brew, and an all-day brunch menu in a beautifully renovated shophouse. The banana-butterscotch waffle is legendary among Penang food bloggers.', address: '2 Jalan Macalister, George Town, Penang 10400, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=VCR+Cafe+Penang', phone: '+60 4-228 8508', website: 'https://vcr.com.my', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/vcr-cafe-penang.jpg', tags: ['specialty-coffee', 'brunch', 'shophouse', 'waffles', 'instagram'] },
  { name: 'China House Penang', slug: 'china-house-penang', category: 'CAFE', description: 'Three heritage buildings connected by a 100-meter central corridor housing a bakery, cafe, restaurant, art gallery, and live music venue. China House is George Town\'s cultural hub - the homemade cakes are the best in Penang and the evening live jazz on weekends packs the courtyard.', address: '183 Beach Street, George Town, Penang 10300, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=China+House+Penang', phone: '+60 4-263 7299', website: 'https://chinahouse.com.my', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/china-house-penang.jpg', tags: ['heritage', 'bakery', 'gallery', 'live-jazz', 'cultural-hub'] },
  { name: 'Ome by Spacebar Penang', slug: 'ome-by-spacebar-penang', category: 'CAFE', description: 'A minimalist specialty coffee cafe in a Japanese-influenced wooden shophouse interior, known for its single-origin filter coffees, limited-edition Japanese-style cheesecakes, and a serene atmosphere perfect for slow morning reading. One of George Town\'s most photogenic cafes.', address: '58 Lorong Stewart, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Ome+by+Spacebar+Penang', phone: '+60 16-400 5866', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/ome-by-spacebar-penang.jpg', tags: ['specialty', 'japanese', 'filter', 'cheesecake', 'minimalist'] },
  { name: 'Mugshot Cafe Penang', slug: 'mugshot-cafe-penang', category: 'CAFE', description: 'A George Town institution for over a decade, Mugshot serves Penang\'s original specialty espresso in a quirky space decorated with old film posters and vintage cameras. The cold brew coffee float and the smoked-salmon bagel have been on the menu since the beginning and remain the bestsellers.', address: '302 Chulia Street, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Mugshot+Cafe+Penang', phone: '+60 4-251 5377', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/mugshot-cafe-penang.jpg', tags: ['institution', 'cold-brew', 'vintage', 'quirky', 'specialty'] },
  { name: 'Narrow Marrow Penang', slug: 'narrow-marrow-penang', category: 'CAFE', description: 'A compact specialty coffee bar in a converted 1930s row house with just 8 seats and outstanding single-origin pourovers. The barista owner sources directly from Malaysian highland farms and roasts twice weekly - the kind of coffee experience you travel to George Town specifically to have.', address: '22 Muntri Street, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Narrow+Marrow+Penang', phone: '+60 11-2273 6650', website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/narrow-marrow-penang.jpg', tags: ['specialty', 'pourover', 'direct-trade', 'tiny', 'roaster'] },
  { name: 'Lof10 Coffeebar Penang', slug: 'lof10-coffeebar-penang', category: 'CAFE', description: 'A large, airy multi-level specialty coffee bar with fast wifi, plenty of power outlets, and a focused working atmosphere that makes it Penang\'s best digital nomad cafe. The in-house roasted espresso and house-baked kouign-amann pastry are constants on the menu.', address: '10 Jalan Perak, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Lof10+Coffeebar+Penang', phone: '+60 4-261 0550', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/lof10-coffeebar-penang.jpg', tags: ['nomad', 'wifi', 'roaster', 'large', 'espresso'] },
  // RESTAURANTS
  { name: 'Kebaya Restaurant Penang', slug: 'kebaya-restaurant-penang', category: 'FOOD', description: 'The finest Peranakan restaurant in Malaysia, located in the Seven Terraces heritage hotel with a dining room of extraordinary beauty. The Nyonya tasting menu by Chef Edward Voon uses 18th-century Baba-Nyonya recipes with ingredients sourced from heritage seed farms - a Michelin-recognized dining experience.', address: 'Seven Terraces, Stewart Lane, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Kebaya+Restaurant+Penang', phone: '+60 4-264 2333', website: 'https://www.seventerraces.com/kebaya', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/kebaya-restaurant-penang.jpg', tags: ['peranakan', 'nyonya', 'fine-dining', 'tasting-menu', 'michelin'] },
  { name: 'Hameediyah Restaurant Penang', slug: 'hameediyah-restaurant-penang', category: 'FOOD', description: 'The oldest Mamak restaurant in Penang, serving murtabak, nasi kandar, and biryani since 1907 in an atmospheric old George Town building. The mutton murtabak is the most famous version in Malaysia and the dhal with roti canai has been a local breakfast institution for over a century.', address: '164A Campbell Street, George Town, Penang 10100, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Hameediyah+Restaurant+Penang', phone: '+60 4-261 1095', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/hameediyah-restaurant-penang.jpg', tags: ['mamak', 'murtabak', 'nasi-kandar', '1907', 'institution'] },
  { name: 'Teksen Restaurant Penang', slug: 'teksen-restaurant-penang', category: 'FOOD', description: 'A Michelin Bib Gourmand restaurant serving innovative Cantonese-Penang fusion in a no-frills setting that always has a queue. The signature crispy pork with chilli and vinegar, steamed clams with Shaoxing wine, and wok-fried noodles are all extraordinary - some of the best Chinese cooking in Malaysia.', address: '18 Carnarvon Street, George Town, Penang 10100, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Teksen+Restaurant+Penang', phone: '+60 4-261 3469', website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/teksen-restaurant-penang.jpg', tags: ['michelin', 'cantonese', 'fusion', 'queue', 'bib-gourmand'] },
  { name: 'Lorong Baru Hawker Centre Penang', slug: 'lorong-baru-hawker-centre-penang', category: 'FOOD', description: 'One of Penang\'s best-loved open-air hawker centres with legendary char kway teow, Hokkien mee, oyster omelette, and cendol stalls that have operated for generations. Go in the evening when all stalls are open and the woks are blazing - the most authentic hawker experience in George Town.', address: 'Lorong Baru (New Lane), George Town, Penang 10400, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Lorong+Baru+Hawker+Centre+Penang', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/lorong-baru-hawker-centre-penang.jpg', tags: ['hawker', 'char-kway-teow', 'evening', 'authentic', 'local'] },
  { name: 'Sri Ananda Bahwan Restaurant Penang', slug: 'sri-ananda-bahwan-restaurant-penang', category: 'FOOD', description: 'The finest South Indian vegetarian restaurant in Malaysia, serving banana-leaf meals of extraordinary complexity - 12 different preparations surrounding a mound of rice served on fresh banana leaf. The weekend thali is a pilgrimage for Indian food lovers from across the country.', address: '55 Lebuh Penang, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Sri+Ananda+Bahwan+Penang', phone: '+60 4-261 4884', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/sri-ananda-bahwan-restaurant-penang.jpg', tags: ['indian', 'vegetarian', 'banana-leaf', 'thali', 'south-indian'] },
  { name: 'Auntie Gaik Lean\'s Old School Eatery', slug: 'auntie-gaik-leans-penang', category: 'FOOD', description: 'A Michelin Bib Gourmand Peranakan home-cooking restaurant where 80-year-old Auntie Gaik Lean serves recipes that have never left her family kitchen. Limited menu, fixed hours, and a tiny dining room mean booking weeks ahead is essential - the ayam pongteh and inchi kabin chicken are irreplaceable.', address: '25 Kelawei Road, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Auntie+Gaik+Lean+Penang', phone: '+60 4-229 3438', website: null, priceRange: 'MID', rating: 4.9, imageUrl: '/spots/auntie-gaik-leans-penang.jpg', tags: ['peranakan', 'home-cooking', 'michelin', 'must-book', 'legendary'] },
  // MARKETS
  { name: 'Chowrasta Market Penang', slug: 'chowrasta-market-penang', category: 'FOOD', description: 'The most authentic wet market in George Town, operating since 1890 with ground-floor stalls of fresh produce, spices, and dried goods surrounding a food court of classic Penang breakfast stalls upstairs. The morning dim sum, apom balik pancakes, and iced Horlicks teh tarik are the best in the city.', address: 'Penang Road, George Town, Penang 10000, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Chowrasta+Market+Penang', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/chowrasta-market-penang.jpg', tags: ['wet-market', '1890', 'dim-sum', 'breakfast', 'local'] },
  { name: 'Gurney Drive Hawker Centre Penang', slug: 'gurney-drive-hawker-centre-penang', category: 'FOOD', description: 'Penang\'s most famous hawker strip on the waterfront esplanade with over 100 stalls serving every classic Penang dish under open-air pavilions at the edge of the sea. Arrive after 6pm for peak atmosphere - the crab, Hokkien noodles, and rojak are the must-orders.', address: 'Gurney Drive, George Town, Penang 10250, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Gurney+Drive+Hawker+Centre+Penang', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/gurney-drive-hawker-centre-penang.jpg', tags: ['hawker', 'waterfront', 'evening', 'crab', 'famous'] },
  { name: 'Penang Night Market (Pasar Malam)', slug: 'penang-night-market-pasar-malam', category: 'FOOD', description: 'A rotating weekly night market that sets up in different George Town neighborhoods on different nights, selling local snacks, clothes, toys, and street food. The stalls selling fried quail eggs, curry puffs, and ais kacang shaved ice are the authentic Malaysian street market experience.', address: 'Various locations, George Town, Penang', googleMapsUrl: 'https://maps.google.com/?q=Penang+Pasar+Malam', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/penang-night-market-pasar-malam.jpg', tags: ['night-market', 'rotating', 'street-food', 'local', 'cheap'] },
  { name: 'Batu Ferringhi Night Market', slug: 'batu-ferringhi-night-market-penang', category: 'FOOD', description: 'A nightly tourist-oriented market along the Batu Ferringhi beach road selling batik sarongs, t-shirts, knockoff bags, and beach paraphernalia alongside excellent seafood restaurants. Visit for the grilled seafood restaurants on the beach road rather than the market stalls themselves.', address: 'Batu Ferringhi Road, Penang 11100, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Batu+Ferringhi+Night+Market+Penang', phone: null, website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/batu-ferringhi-night-market-penang.jpg', tags: ['night-market', 'beach', 'touristy', 'seafood', 'batu-ferringhi'] },
  { name: 'Little India Penang', slug: 'little-india-penang', category: 'FOOD', description: 'The most vibrant Little India enclave in Malaysia - a concentrated block of Indian textile shops, spice merchants, banana-leaf restaurants, and jasmine garland sellers around Lebuh Pasar and Campbell Street. The sights, sounds, and smells of a South Indian town transposed to a Penang shophouse block.', address: 'Lebuh Pasar, George Town, Penang 10000, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Little+India+Penang', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/little-india-penang.jpg', tags: ['little-india', 'spices', 'textiles', 'banana-leaf', 'colorful'] },
  // TOURIST SITES
  { name: 'George Town UNESCO Street Art', slug: 'george-town-street-art-penang', category: 'CULTURE', description: 'George Town\'s world-famous street art trail - over 50 iron rod sculptures and painted murals spread across the heritage city, commissioned for the 2012 George Town Festival. Ernest Zacharevic\'s "Children on a Bicycle" is the most photographed artwork in Malaysia and a selfie pilgrimage site for millions.', address: 'George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=George+Town+Street+Art+Penang', phone: null, website: null, priceRange: 'FREE', rating: 4.8, imageUrl: '/spots/george-town-street-art-penang.jpg', tags: ['street-art', 'murals', 'instagram', 'walking', 'free'] },
  { name: 'Khoo Kongsi Clan House Penang', slug: 'khoo-kongsi-penang', category: 'CULTURE', description: 'The most elaborate clan house in Malaysia - a 19th-century Hokkien Chinese community temple with a rooftop adorned with 2-ton dragon sculptures, intricately painted eaves, and gold-leaf ceremonial halls. The Khoo Kongsi represents the wealth and ambition of Penang\'s early Chinese merchant community.', address: 'Cannon Square, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Khoo+Kongsi+Penang', phone: '+60 4-261 4609', website: 'https://khookongsi.com.my', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/khoo-kongsi-penang.jpg', tags: ['clan-house', 'chinese', 'heritage', 'dragon', 'gold-leaf'] },
  { name: 'Pinang Peranakan Mansion Penang', slug: 'pinang-peranakan-mansion-penang', category: 'CULTURE', description: 'A jaw-dropping museum inside a restored Peranakan magnate\'s mansion decorated with over 1,000 antiques - Scottish cast-iron columns, French Baroque furniture, Chinese porcelain, and English tiles from the 1890s. The best window into the extraordinary Baba-Nyonya hybrid culture of the Straits Settlements.', address: '29 Church Street, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Pinang+Peranakan+Mansion+Penang', phone: '+60 4-264 2929', website: 'https://pinangperanakanmansion.com.my', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/pinang-peranakan-mansion-penang.jpg', tags: ['peranakan', 'mansion', 'antiques', 'museum', 'heritage'] },
  { name: 'Penang Hill (Bukit Bendera)', slug: 'penang-hill-penang', category: 'NATURE', description: 'A funicular railway climbs 830m above sea level to a colonial hill station with panoramic views over George Town, the Strait of Malacca, and the mainland mountains. The summit has nature trails, a colonial hotel, and temperatures 5 degrees cooler than the city below - a refreshing escape from the heat.', address: 'Bukit Bendera, Air Itam, Penang 11500, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Penang+Hill+Malaysia', phone: '+60 4-828 8880', website: 'https://www.penanghill.gov.my', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/penang-hill-penang.jpg', tags: ['hill', 'funicular', 'views', 'nature', 'colonial'] },
  { name: 'Sri Mahamariamman Temple Penang', slug: 'sri-mahamariamman-temple-penang', category: 'CULTURE', description: 'George Town\'s most spectacular Hindu temple with a towering gopuram (gateway tower) covered in hundreds of colorful deity statues. Built in 1833 and rebuilt in spectacular South Indian Dravidian style in 1993, the temple is the departure point for the annual Thaipusam festival procession.', address: 'Lebuh Queen, George Town, Penang 10200, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Sri+Mahamariamman+Temple+Penang', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/sri-mahamariamman-temple-penang.jpg', tags: ['hindu', 'temple', 'gopuram', 'thaipusam', 'colorful'] },
  { name: 'Clan Jetties of Penang', slug: 'clan-jetties-penang', category: 'CULTURE', description: 'Six wooden jetty settlements extending over the water of the Penang seafront, where Chinese clan communities have lived in stilted wooden houses since the 1800s. The Chew Jetty is the largest and most visited, with a living village of a few hundred residents who maintain the oldest waterfront community in Southeast Asia.', address: 'Weld Quay, George Town, Penang 10300, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Clan+Jetties+Penang', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/clan-jetties-penang.jpg', tags: ['jetty', 'chinese', 'heritage', 'stilted-houses', 'living-village'] },
  { name: 'Tropical Spice Garden Penang', slug: 'tropical-spice-garden-penang', category: 'NATURE', description: 'A beautifully designed 8-acre spice garden on a hillside in Teluk Bahang with over 500 tropical plant species arranged in themed gardens. The guided spice walk identifies nutmeg, black pepper, vanilla, and cardamom growing in a forest setting - educational and genuinely beautiful.', address: 'Lot 595, Mukim 2, Teluk Bahang, Penang 11050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Tropical+Spice+Garden+Penang', phone: '+60 4-881 1797', website: 'https://tropicalspicegarden.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/tropical-spice-garden-penang.jpg', tags: ['spice-garden', 'nature', 'educational', 'plants', 'teluk-bahang'] },
  { name: 'Kek Lok Si Temple Penang', slug: 'kek-lok-si-temple-penang', category: 'CULTURE', description: 'The largest Buddhist temple in Southeast Asia, cascading up the hillside above Air Itam with a 30-meter bronze Kuan Yin statue, seven-story pagoda, and temple courtyards illuminated by 10,000 lanterns during Chinese New Year. Over 100 years old and still expanding with new halls and statues.', address: 'Air Itam, Penang 11500, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Kek+Lok+Si+Temple+Penang', phone: '+60 4-828 3317', website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/kek-lok-si-temple-penang.jpg', tags: ['buddhist', 'largest', 'kuan-yin', 'pagoda', 'chinese-new-year'] },
  { name: 'Penang National Park', slug: 'penang-national-park', category: 'NATURE', description: 'Malaysia\'s smallest national park packs extraordinary biodiversity into 2,568 acres at the northwest tip of the island, accessible by hiking trail or speedboat. The secluded Monkey Beach and Kerachut Beach are among the only truly wild beaches in Malaysia, with nesting turtles from May to October.', address: 'Teluk Bahang, Penang 11050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Penang+National+Park', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/penang-national-park.jpg', tags: ['national-park', 'hiking', 'beach', 'turtles', 'jungle'] },
  { name: 'Batik Boutique Gallery Penang', slug: 'batik-boutique-gallery-penang', category: 'CULTURE', description: 'A gallery and workshop in a restored George Town shophouse where master batik artists demonstrate traditional wax-resist dyeing and visitors can try hand-painting. The gallery shop sells exceptional hand-drawn batik art that represents genuine Penang craft at prices that properly support the artisan.', address: '158 Lebuh Carnarvon, George Town, Penang 10100, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Batik+Boutique+Gallery+Penang', phone: '+60 4-262 2123', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/batik-boutique-gallery-penang.jpg', tags: ['batik', 'workshop', 'art', 'craft', 'shophouse'] },
  // COWORKING
  { name: 'Common Ground Penang', slug: 'common-ground-penang', category: 'COWORKING', description: 'Malaysia\'s premier coworking brand with a beautifully designed George Town location in a heritage shophouse, offering hot desks, private offices, meeting rooms, and a ground-floor cafe. The Penang community includes tech startups, creative agencies, and remote workers from across Southeast Asia.', address: '10 Jalan Argyll, George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Common+Ground+Penang', phone: '+60 3-2110 1618', website: 'https://www.commonground.work/penang', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/common-ground-penang.jpg', tags: ['coworking', 'heritage', 'community', 'startup', 'cafe'] },
  { name: 'Ourspace Coworking Penang', slug: 'ourspace-coworking-penang', category: 'COWORKING', description: 'A popular coworking hub near Gurney Plaza with 24-hour access, ergonomic furniture, a podcasting studio, and a monthly community of tech professionals and designers. The day pass is well-priced and includes unlimited espresso from the cafe counter - a practical choice for nomads in Georgetown.', address: '170-G Jalan Kelawei, George Town, Penang 10250, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Ourspace+Coworking+Penang', phone: '+60 4-228 7558', website: 'https://ourspace.my', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/ourspace-coworking-penang.jpg', tags: ['coworking', '24-hour', 'podcast-studio', 'day-pass', 'espresso'] },
  { name: 'Penang Digital Library Coworking', slug: 'penang-digital-library-coworking', category: 'COWORKING', description: 'A government-supported digital hub offering free or heavily subsidized coworking alongside digital skills training. The modern facility has fast internet, 3D printers, a maker lab, and regular tech meetups that connect Penang\'s growing tech community with international visitors.', address: 'Komtar, Penang 10000, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Penang+Digital+Library', phone: '+60 4-261 1111', website: null, priceRange: 'FREE', rating: 4.3, imageUrl: '/spots/penang-digital-library-coworking.jpg', tags: ['free', 'government', 'maker-lab', '3d-printer', 'tech'] },
  { name: 'Gravity Coworking Penang', slug: 'gravity-coworking-penang', category: 'COWORKING', description: 'A bright, modern coworking space in the E-Gate tech corridor with a diverse membership of tech companies, remote workers, and entrepreneurs. Gravity offers flexible plans from hourly passes to dedicated desks with 24-hour card access - a solid professional workspace away from the tourist areas.', address: '118 Jalan Anson, George Town, Penang 10400, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Gravity+Coworking+Penang', phone: '+60 4-228 4888', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/gravity-coworking-penang.jpg', tags: ['coworking', 'tech', 'modern', 'flexible', 'professional'] },
  { name: 'The Hub Penang', slug: 'the-hub-penang', category: 'COWORKING', description: 'A coworking space and startup ecosystem in the heart of George Town with mentorship programs, investor access, and a community of Penang-based tech founders. International remote workers are welcomed alongside local startups with affordable day and week passes and a relaxed open-plan layout.', address: 'George Town, Penang 10050, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=The+Hub+Penang', phone: '+60 16-461 2345', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/the-hub-penang.jpg', tags: ['startup', 'ecosystem', 'mentorship', 'coworking', 'community'] },
  { name: 'Workhaus Penang', slug: 'workhaus-penang', category: 'COWORKING', description: 'A boutique coworking space in a renovated Penang heritage building near the CBD, offering private offices, hot desks, and a curated community of professionals. The restored internal architecture of timber beams and colorful Penang tiles makes it one of the most characterful work environments in Malaysia.', address: 'Lebuh Pantai, George Town, Penang 10300, Malaysia', googleMapsUrl: 'https://maps.google.com/?q=Workhaus+Penang', phone: '+60 4-261 9900', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/workhaus-penang.jpg', tags: ['heritage', 'boutique', 'timber', 'tiles', 'characterful'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Penang: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
