const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfl82000fvimo02q79epj';

const spots = [
  // ACCOMMODATION — luxury
  { name: 'Hotel de Russie', slug: 'hotel-de-russie-rome', category: 'ACCOMMODATION', description: "Rome's most beautiful luxury hotel — a Rocco Forte property steps from the Piazza del Popolo with a legendary secret garden, a wellness spa, and a terracotta terrace that has been the city's most glamorous lunch address for a century. Picasso, Cocteau, and Stravinsky all called it home.", address: 'Via del Babuino 9, 00187 Rome', googleMapsUrl: 'https://maps.google.com/?q=Hotel+de+Russie+Rome', phone: '+39 06 328881', website: 'https://www.roccofortehotels.com/hotels-and-resorts/hotel-de-russie/', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/hotel-de-russie-rome.jpg', tags: ['luxury', 'garden', 'rocco-forte', 'piazza-del-popolo', 'historic'] },
  { name: 'J.K. Place Roma', slug: 'jk-place-roma', category: 'ACCOMMODATION', description: "An intimate 30-room boutique hotel in a historic palazzo on Via di Monte d'Oro, decorated like a Roman intellectual's private home — antiques, contemporary art, library alcoves, and a rooftop terrace with views over the old city. The definition of Roman elegance.", address: 'Via di Monte d\'Oro 30, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=JK+Place+Roma', phone: '+39 06 9826 3300', website: 'https://www.jkplace.com/roma', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/jk-place-roma.jpg', tags: ['boutique', 'palazzo', 'rooftop', 'intimate', 'library'] },
  // ACCOMMODATION — mid-range
  { name: 'The Hoxton Rome', slug: 'the-hoxton-rome', category: 'ACCOMMODATION', description: "The Hoxton's Rome outpost in a beautifully restored 16th-century palazzo near the Colosseum, with the brand's signature warm design aesthetic, a lively ground-floor restaurant, and private courtyard. The Rome entry point that balances style and accessibility perfectly.", address: 'Via dei Lucchesi 41, 00187 Rome', googleMapsUrl: 'https://maps.google.com/?q=The+Hoxton+Rome', phone: '+39 06 9286 3440', website: 'https://thehoxton.com/rome', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/the-hoxton-rome.jpg', tags: ['design', 'palazzo', 'courtyard', 'restaurant', 'colosseum'] },
  { name: 'Residenza in Farnese', slug: 'residenza-in-farnese-rome', category: 'ACCOMMODATION', description: "A charming guesthouse in a 15th-century building steps from the Campo de' Fiori and Piazza Farnese. Exposed stone walls, painted ceilings, and a rooftop terrace with views over the Renaissance roofscape. The most atmospheric mid-range option in central Rome.", address: 'Via del Mascherone 59, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Residenza+in+Farnese+Rome', phone: '+39 06 6821 0980', website: 'https://www.residenzainfarnese.it', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/residenza-in-farnese-rome.jpg', tags: ['guesthouse', 'campo-de-fiori', 'rooftop', 'historic', 'charming'] },
  { name: 'Hotel Santa Maria Trastevere', slug: 'hotel-santa-maria-trastevere', category: 'ACCOMMODATION', description: "A 16th-century cloister converted into a tranquil boutique hotel in the heart of Trastevere, with orange tree-filled courtyards, terracotta-tiled rooms, and the most charming neighborhood in Rome on your doorstep. The perfect base for a Rome that feels like a local's city.", address: 'Vicolo del Piede 2, 00153 Rome', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Santa+Maria+Trastevere', phone: '+39 06 589 4626', website: 'https://www.hotelsantamaria.info', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/hotel-santa-maria-trastevere.jpg', tags: ['cloister', 'trastevere', 'courtyard', 'tranquil', 'local-feel'] },
  // ACCOMMODATION — hostels
  { name: 'The Yellow Hostel Rome', slug: 'the-yellow-hostel-rome', category: 'ACCOMMODATION', description: "Rome's best-known social hostel near Termini station with a legendary rooftop bar, live music nights, pizza kitchen, and a social program that makes it impossible to eat alone. The Yellow has been connecting solo travelers in Rome for 25 years.", address: 'Via Palestra 40, 00185 Rome', googleMapsUrl: 'https://maps.google.com/?q=The+Yellow+Hostel+Rome', phone: '+39 06 4938 2682', website: 'https://www.the-yellow.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/the-yellow-hostel-rome.jpg', tags: ['hostel', 'rooftop', 'social', 'live-music', 'termini'] },
  { name: 'Fawlty Towers Rome', slug: 'fawlty-towers-rome', category: 'ACCOMMODATION', description: "A well-run budget hotel-hostel hybrid near Termini with private rooms, clean dorms, and a famously helpful staff that specializes in Vatican reservations and city logistics. The name is ironic — the service here is excellent and the solo traveler community is genuine.", address: 'Via Magenta 39, 00185 Rome', googleMapsUrl: 'https://maps.google.com/?q=Fawlty+Towers+Rome', phone: '+39 06 445 4802', website: 'https://www.fawltytowersrome.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/fawlty-towers-rome.jpg', tags: ['hostel', 'helpful-staff', 'termini', 'budget', 'clean'] },
  // CAFES
  { name: 'Caffè Sant\'Eustachio', slug: 'caffe-sant-eustachio-rome', category: 'CAFE', description: "Roasting coffee since 1938, Sant'Eustachio is a Roman institution and the city's most revered espresso bar. The granita di caffè (frozen espresso with cream) is the definitive Roman summer drink. The baristas are theatrical; the coffee is extraordinary.", address: 'Piazza di Sant\'Eustachio 82, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Caffe+Sant+Eustachio+Rome', phone: '+39 06 6880 2048', website: 'https://www.santeustachioilcaffe.it', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/caffe-sant-eustachio-rome.jpg', tags: ['espresso', 'historic', 'granita', 'institution', '1938'] },
  { name: 'Sciascia Caffè', slug: 'sciascia-caffe-rome', category: 'CAFE', description: "A hidden gem in Prati with Rome's most intense espresso and a 1919 interior of mahogany, mirrors, and marble that has barely changed. The specialty is caffè e menta — espresso topped with concentrated peppermint syrup. A mandatory detour for anyone staying near the Vatican.", address: 'Via Fabio Massimo 80a, 00192 Rome', googleMapsUrl: 'https://maps.google.com/?q=Sciascia+Caffe+Rome', phone: '+39 06 321 1580', website: null, priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/sciascia-caffe-rome.jpg', tags: ['espresso', '1919', 'prati', 'historic', 'hidden-gem'] },
  { name: 'Roscioli Caffè Pasticceria', slug: 'roscioli-caffe-rome', category: 'CAFE', description: "The café arm of Rome's most celebrated food family — a sleek corner bar in the Campo de' Fiori area serving the city's best cornetti (croissants), extraordinary pastries, and technically flawless espresso. The almond croissant alone is worth getting up early for.", address: 'Piazza Benedetto Cairoli 16, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Roscioli+Caffe+Rome', phone: '+39 06 916 5330', website: 'https://www.rosciolicaffe.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/roscioli-caffe-rome.jpg', tags: ['pastry', 'espresso', 'cornetti', 'campo-de-fiori', 'roscioli'] },
  // FOOD
  { name: 'Supplì Roma', slug: 'suppli-roma', category: 'FOOD', description: "The city's finest supplì (Roman fried rice balls) — a queue-worthy street food institution near the Campo de' Fiori that has been serving crispy, molten-centered supplì al telefono since 1978. The chickpea fritters and fried salt cod are equally legendary.", address: 'Via di San Francesco a Ripa 137, 00153 Rome', googleMapsUrl: 'https://maps.google.com/?q=Suppli+Roma', phone: '+39 06 589 7110', website: 'https://www.suppli.it', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/suppli-roma.jpg', tags: ['street-food', 'suppli', 'fried-food', 'trastevere', 'queue-worthy'] },
  { name: 'Trattoria Da Enzo al 29', slug: 'trattoria-da-enzo-rome', category: 'FOOD', description: "The definitive Roman trattoria in Trastevere — no reservations, red-checked tablecloths, carbonara and cacio e pepe made exactly as they should be, and house wine served in carafes. Arrive at 12:30 or 19:30 and queue outside; it's always worth the wait.", address: 'Via dei Vascellari 29, 00153 Rome', googleMapsUrl: 'https://maps.google.com/?q=Trattoria+Da+Enzo+al+29+Rome', phone: '+39 06 581 2260', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/trattoria-da-enzo-rome.jpg', tags: ['trattoria', 'carbonara', 'trastevere', 'classic', 'no-reservations'] },
  { name: 'Roscioli Salumeria', slug: 'roscioli-salumeria-rome', category: 'FOOD', description: "Part deli, part restaurant, part wine cellar — Roscioli is the most important address in Roman food culture. A counter groaning with 300 cheeses and cured meats leads to a dining room where the carbonara, amatriciana, and anchovy dishes are arguably the best in the city.", address: 'Via dei Giubbonari 21, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Roscioli+Rome', phone: '+39 06 687 5287', website: 'https://www.salumeriaroscioli.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/roscioli-salumeria-rome.jpg', tags: ['deli', 'carbonara', 'wine', 'cheese', 'essential'] },
  { name: 'Campo de\' Fiori Market', slug: 'campo-de-fiori-market-rome', category: 'FOOD', description: "Rome's most theatrical morning market — an open-air produce market in a piazza dominated by the hooded statue of Giordano Bruno (who was burned here as a heretic in 1600). Fresh fruit, herbs, flowers, and local vendors until noon; the piazza becomes a bar scene at night.", address: 'Campo de\' Fiori, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Campo+de+Fiori+Rome', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/campo-de-fiori-market-rome.jpg', tags: ['market', 'morning', 'historic', 'produce', 'piazza'] },
  // CULTURE
  { name: 'Colosseum', slug: 'colosseum-rome', category: 'CULTURE', description: "The greatest monument of the ancient world — a 2,000-year-old amphitheatre that held 50,000 spectators for gladiatorial combat. Book timed entry tickets online weeks in advance to avoid the enormous queues; the arena floor access and underground tunnels are worth the premium ticket.", address: 'Piazza del Colosseo 1, 00184 Rome', googleMapsUrl: 'https://maps.google.com/?q=Colosseum+Rome', phone: '+39 06 3996 7700', website: 'https://www.coopculture.it/colosseum', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/colosseum-rome.jpg', tags: ['ancient', 'gladiators', 'must-see', 'book-ahead', 'iconic'] },
  { name: 'Vatican Museums & Sistine Chapel', slug: 'vatican-museums-rome', category: 'CULTURE', description: "The world's greatest single art collection — 54 galleries of ancient sculptures, Renaissance paintings, and Raphael's Rooms leading to Michelangelo's Sistine Chapel ceiling. Allow 4 hours minimum; book timed entry weeks ahead. The early morning tours (before public opening) offer an unforgettable silent viewing.", address: 'Viale Vaticano, 00120 Vatican City', googleMapsUrl: 'https://maps.google.com/?q=Vatican+Museums+Rome', phone: '+39 06 6988 4676', website: 'https://www.museivaticani.va', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/vatican-museums-rome.jpg', tags: ['sistine-chapel', 'michelangelo', 'raphael', 'must-see', 'book-weeks-ahead'] },
  { name: 'Pantheon', slug: 'pantheon-rome', category: 'CULTURE', description: "The best-preserved building of ancient Rome — a 125 AD domed temple converted to a church, with a 43-meter concrete dome that remained the world's largest for 1,300 years. The oculus (open hole at the dome's apex) lets in rain, which drains through the ancient floor. Extraordinary.", address: 'Piazza della Rotonda, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Pantheon+Rome', phone: '+39 06 8305 9080', website: 'https://pantheon.roma.it', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/pantheon-rome.jpg', tags: ['ancient', 'dome', 'oculus', 'must-see', 'free-with-church-pass'] },
  { name: 'Trevi Fountain', slug: 'trevi-fountain-rome', category: 'CULTURE', description: "The world's most famous fountain — Nicola Salvi's 1762 Baroque masterpiece at the terminus of one of Rome's ancient aqueducts. Visit at 5am to see it empty; by 10am the crowds make coin-throwing impossible. The fountain collects €3,000 daily, donated to charity.", address: 'Piazza di Trevi, 00187 Rome', googleMapsUrl: 'https://maps.google.com/?q=Trevi+Fountain+Rome', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/trevi-fountain-rome.jpg', tags: ['fountain', 'baroque', 'iconic', 'visit-early', 'wish-coin'] },
  { name: 'Roman Forum', slug: 'roman-forum-rome', category: 'CULTURE', description: "The beating heart of ancient Rome — the temples, basilicas, and triumphal arches of the world's greatest empire, now open ruins between the Colosseum and the Capitoline Hill. Walking here at golden hour, with the Forum stretching in every direction, is the closest thing to time travel.", address: 'Via Sacra, 00186 Rome', googleMapsUrl: 'https://maps.google.com/?q=Roman+Forum', phone: '+39 06 3996 7700', website: 'https://www.coopculture.it', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/roman-forum-rome.jpg', tags: ['ancient', 'ruins', 'history', 'colosseum-combo', 'golden-hour'] },
  { name: 'Borghese Gallery', slug: 'borghese-gallery-rome', category: 'CULTURE', description: "Rome's most intimate major museum — 20 rooms of Bernini sculptures and Caravaggio paintings in a 17th-century villa inside Villa Borghese park. Entry is strictly limited to 360 visitors at a time in 2-hour slots (book weeks ahead). The Bernini 'Apollo and Daphne' alone justifies the trip to Rome.", address: 'Piazzale Scipione Borghese 5, 00197 Rome', googleMapsUrl: 'https://maps.google.com/?q=Borghese+Gallery+Rome', phone: '+39 06 841 3979', website: 'https://www.galleriaborghese.it', priceRange: 'MID', rating: 4.9, imageUrl: '/spots/borghese-gallery-rome.jpg', tags: ['bernini', 'caravaggio', 'intimate', 'must-book', 'villa-borghese'] },
  { name: 'Castel Sant\'Angelo', slug: 'castel-sant-angelo-rome', category: 'CULTURE', description: "A 2nd-century mausoleum converted to a medieval fortress, papal refuge, and now one of Rome's most fascinating museums. The rooftop terrace offers the finest view of St. Peter's Basilica and the Tiber. The passetto — a secret elevated corridor connecting the castle to the Vatican — is extraordinary.", address: 'Lungotevere Castello 50, 00193 Rome', googleMapsUrl: 'https://maps.google.com/?q=Castel+Sant+Angelo+Rome', phone: '+39 06 6819 111', website: 'https://castelsantangelo.beniculturali.it', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/castel-sant-angelo-rome.jpg', tags: ['castle', 'rooftop', 'tiber', 'papal', 'history'] },
  { name: 'Villa Borghese Park', slug: 'villa-borghese-rome', category: 'NATURE', description: "Rome's most elegant park — 80 hectares of manicured gardens, fountains, and tree-lined avenues on the hill above the Piazza del Popolo. Rent a boat on the lake, cycle the avenues, or simply picnic on the grass above the city. The terrace overlooks are among Rome's finest viewpoints.", address: 'Piazzale Napoleone I, 00197 Rome', googleMapsUrl: 'https://maps.google.com/?q=Villa+Borghese+Rome', phone: null, website: 'https://www.villaeborghese.it', priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/villa-borghese-rome.jpg', tags: ['park', 'gardens', 'cycling', 'picnic', 'viewpoint'] },
  { name: 'Trastevere Neighborhood', slug: 'trastevere-rome', category: 'CULTURE', description: "Rome's most atmospheric quarter — a dense tangle of cobblestone lanes, ivy-covered facades, and piazzas full of trattorias that come alive at night. Trastevere has the neighborhood feel that the tourist center lost decades ago. The basilica, the market, and the nightlife are all unmissable.", address: 'Trastevere, 00153 Rome', googleMapsUrl: 'https://maps.google.com/?q=Trastevere+Rome', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/trastevere-rome.jpg', tags: ['neighborhood', 'cobblestones', 'evening', 'local', 'atmosphere'] },
  // COWORKING
  { name: 'Talent Garden Rome Ostiense', slug: 'talent-garden-rome', category: 'COWORKING', description: "Italy's biggest tech coworking campus has its Rome outpost in the trendy Ostiense neighborhood — a 4,000m² space hosting 300+ startups, innovation labs, and a packed events program. Day passes available; the network here is the best route into Rome's startup ecosystem.", address: 'Via Pier Carlo Boggio 55, 00154 Rome', googleMapsUrl: 'https://maps.google.com/?q=Talent+Garden+Rome', phone: '+39 06 5456 6000', website: 'https://talentgarden.com/innovation-school/campus/rome/', priceRange: 'MID', rating: 4.4, imageUrl: '/spots/talent-garden-rome.jpg', tags: ['startup', 'campus', 'ostiense', 'community', 'day-pass'] },
  { name: 'Copernico Roma Tiburtina', slug: 'copernico-roma-tiburtina', category: 'COWORKING', description: "A beautifully designed coworking space near Tiburtina station in a converted industrial building, with terraces, event spaces, and a membership base of local professionals, entrepreneurs, and remote workers. Good natural light, reliable wifi, and a strong community feel.", address: 'Via degli Olivetani 10/12, 00185 Rome', googleMapsUrl: 'https://maps.google.com/?q=Copernico+Roma+Tiburtina', phone: '+39 06 2078 8601', website: 'https://copernicostazioni.it/en/rome/', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/copernico-roma-tiburtina.jpg', tags: ['coworking', 'industrial', 'tiburtina', 'terrace', 'community'] },
  // WELLNESS
  { name: 'Terme di Caracalla', slug: 'terme-di-caracalla-rome', category: 'CULTURE', description: "The best-preserved ancient bath complex in the Roman world — 11 hectares of towering brick ruins that once held 1,600 bathers simultaneously. The mosaics, marble fragments, and monumental scale are astonishing. The summer opera season (July–August) stages performances inside the ruins.", address: 'Viale delle Terme di Caracalla 52, 00153 Rome', googleMapsUrl: 'https://maps.google.com/?q=Terme+di+Caracalla+Rome', phone: '+39 06 3996 7700', website: 'https://www.coopculture.it', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/terme-di-caracalla-rome.jpg', tags: ['ancient', 'ruins', 'opera', 'baths', 'vast'] },
  { name: 'Garbatella Neighborhood Walk', slug: 'garbatella-rome', category: 'NATURE', description: "Rome's most underrated neighborhood — a 1920s planned community of garden blocks, communal courtyards, and Fascist-era architecture in the Ostiense area. Far from the tourist trail, Garbatella offers the authentic working-class Rome that existed before gentrification. The theater and the lofts are fascinating.", address: 'Garbatella, 00154 Rome', googleMapsUrl: 'https://maps.google.com/?q=Garbatella+Rome', phone: null, website: null, priceRange: 'FREE', rating: 4.4, imageUrl: '/spots/garbatella-rome.jpg', tags: ['neighborhood', 'architecture', 'authentic', 'ostiense', 'underrated'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Rome: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
