const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328ejj000lvi8wavcm6ylk';

const spots = [
  // LUXURY HOTELS
  { name: 'COMO Uma Ubud', slug: 'como-uma-ubud', category: 'ACCOMMODATION', description: 'An intimate luxury resort on a ridge above the Tjampuhan Valley with rice terrace views from every villa, a celebrated Shambhala spa, and a COMO Cuisine restaurant serving the best modern Indonesian food in Bali. The combination of spiritual setting, wellness focus, and elegant design makes Uma Ubud exceptional.', address: 'Jalan Raya Sanggingan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=COMO+Uma+Ubud', phone: '+62 361 972 448', website: 'https://www.comohotels.com/uma-ubud', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/como-uma-ubud.jpg', tags: ['luxury', 'valley-views', 'spa', 'wellness', 'rice-terraces'] },
  { name: 'Four Seasons Resort Bali at Sayan', slug: 'four-seasons-sayan-ubud', category: 'ACCOMMODATION', description: 'A suspended elliptical lotus pond floating over the Ayung River gorge announces one of Asia\'s most theatrical hotel arrivals. The Four Seasons Sayan combines extraordinary jungle architecture with river suite villas and suites accessible only by suspension bridge, surrounded by the sounds of the Ayung rapids below.', address: 'Sayan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Four+Seasons+Sayan+Ubud', phone: '+62 361 977 577', website: 'https://www.fourseasons.com/sayan', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/four-seasons-sayan-ubud.jpg', tags: ['jungle', 'river-gorge', 'lotus-pond', 'villas', 'dramatic'] },
  { name: 'Alaya Resort Ubud', slug: 'alaya-resort-ubud', category: 'ACCOMMODATION', description: 'A beautiful boutique resort in the heart of Ubud town with rice terrace views, private plunge pools, a rooftop infinity pool, and a spa drawing on traditional Balinese healing practices. Alaya\'s central location means all of Ubud\'s markets, temples, and restaurants are within easy walking distance.', address: 'Jalan Hanoman 75, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Alaya+Resort+Ubud', phone: '+62 361 972 200', website: 'https://alayaresorts.com/ubud', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/alaya-resort-ubud.jpg', tags: ['central', 'plunge-pool', 'rice-terraces', 'spa', 'rooftop'] },
  { name: 'Komaneka at Bisma Ubud', slug: 'komaneka-at-bisma-ubud', category: 'ACCOMMODATION', description: 'An award-winning boutique resort perched on a ridge above the sacred Campuhan River with infinity pools appearing to merge with the rice paddies and jungle below. Komaneka\'s 22 suites and villas feature handmade Balinese furnishings, private terraces, and deeply personal service that keeps guests returning annually.', address: 'Jalan Bisma, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Komaneka+Bisma+Ubud', phone: '+62 361 971 933', website: 'https://komaneka.com/bisma', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/komaneka-at-bisma-ubud.jpg', tags: ['ridge', 'infinity-pool', 'rice-paddy', 'boutique', 'balinese-art'] },
  // BUDGET HOTELS
  { name: 'Nick\'s Hidden Cottages Ubud', slug: 'nicks-hidden-cottages-ubud', category: 'ACCOMMODATION', description: 'A charming family-run guesthouse hidden in a rice paddy compound on the quieter north side of Ubud with simple but beautiful bungalows, a small pool, and home-cooked Balinese breakfasts. Exceptional value - the kind of authentic Ubud experience that has almost disappeared as the town has grown.', address: 'Jalan Bisma, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Nicks+Hidden+Cottages+Ubud', phone: '+62 361 975 526', website: 'https://nickhiddencottages.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/nicks-hidden-cottages-ubud.jpg', tags: ['family-run', 'rice-paddy', 'bungalow', 'breakfast', 'authentic'] },
  { name: 'Swasti Eco Cottages Ubud', slug: 'swasti-eco-cottages-ubud', category: 'ACCOMMODATION', description: 'An organic farm-stay resort on the edge of Ubud where guests stay in bamboo cottages surrounded by the vegetables and herbs that appear on the breakfast table. Yoga classes, cooking lessons, and guided rice terrace walks are included in the room rate - excellent value for wellness-focused travelers.', address: 'Jalan Nyuh Kuning, Mas, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Swasti+Eco+Cottages+Ubud', phone: '+62 361 975 719', website: 'https://swasticottages.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/swasti-eco-cottages-ubud.jpg', tags: ['eco', 'farm-stay', 'organic', 'yoga', 'cooking-classes'] },
  { name: 'Munduk Moding Plantation Bali', slug: 'munduk-moding-plantation-bali', category: 'ACCOMMODATION', description: 'A working coffee and spice plantation resort in the cool highlands above Ubud with panoramic views over Lake Tamblingan. The 24 infinity villas surrounded by coffee trees, cacao bushes, and cloves offer a Bali experience far removed from the tourist crowds, at mid-range prices that include a plantation tour.', address: 'Desa Munduk, Buleleng, Bali 81161, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Munduk+Moding+Plantation+Bali', phone: '+62 361 877 6222', website: 'https://mundukmodingplantation.com', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/munduk-moding-plantation-bali.jpg', tags: ['plantation', 'highlands', 'coffee', 'lake-views', 'infinity-pool'] },
  { name: 'Bisma Eight Ubud', slug: 'bisma-eight-ubud', category: 'ACCOMMODATION', description: 'A stylish boutique hotel on the famous Bisma road with stunning rice terrace views from a two-tiered infinity pool, minimalist rooms with private balconies, and an excellent restaurant. Bisma Eight hits a sweet spot between design-hotel quality and accessible pricing that few Ubud properties match.', address: 'Jalan Bisma, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Bisma+Eight+Ubud', phone: '+62 361 971 174', website: 'https://bismaeight.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/bisma-eight-ubud.jpg', tags: ['boutique', 'infinity-pool', 'rice-terraces', 'minimalist', 'design'] },
  // HOSTELS
  { name: 'Kosta Ubud Hostel', slug: 'kosta-ubud-hostel', category: 'ACCOMMODATION', description: 'Ubud\'s most social hostel with a rice field-facing pool, hammock garden, free yoga classes, and nightly community dinners that make solo travel easy. The clean dorms with reading lights and lockers attract a mix of yoga retreaters and backpackers who all find their people here within a day.', address: 'Jalan Hanoman, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Kosta+Ubud+Hostel', phone: '+62 361 970 090', website: 'https://kostahostelbali.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/kosta-ubud-hostel.jpg', tags: ['social', 'pool', 'yoga', 'community-dinner', 'rice-fields'] },
  { name: 'Griya Sari Hostel Ubud', slug: 'griya-sari-hostel-ubud', category: 'ACCOMMODATION', description: 'A quiet, clean hostel in a traditional Balinese compound with open-air common areas, a small pool, and a kitchen. Griya Sari attracts long-stay budget travelers who appreciate the authentic compound setting, the helpful owners, and the Ubud location that puts everything within cycling distance.', address: 'Jalan Raya Ubud, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Griya+Sari+Hostel+Ubud', phone: '+62 361 975 620', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/griya-sari-hostel-ubud.jpg', tags: ['balinese-compound', 'quiet', 'pool', 'kitchen', 'long-stay'] },
  { name: 'Ubud Backpacker Hostel', slug: 'ubud-backpacker-hostel', category: 'ACCOMMODATION', description: 'The most centrally located hostel in Ubud, a 5-minute walk from Monkey Forest and the night market, with clean dorms, a cafe downstairs, and a staff team that arranges temple tours, waterfall trips, and cooking classes at fair prices. Reliable wifi and daily housekeeping complete the package.', address: 'Monkey Forest Road, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Ubud+Backpacker+Hostel', phone: '+62 361 978 321', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/ubud-backpacker-hostel.jpg', tags: ['central', 'monkey-forest', 'cafe', 'tours', 'reliable'] },
  { name: 'Alune Retreat Hostel Ubud', slug: 'alune-retreat-hostel-ubud', category: 'ACCOMMODATION', description: 'A wellness-oriented hostel with daily yoga classes included in the dorm rate, healthy breakfast, and a serene atmosphere that makes Ubud\'s spiritual side accessible on a budget. The mixed dorm bunks have privacy curtains, each has a personal light and phone charger, and the garden yoga deck faces rice paddies.', address: 'Jalan Sri Wedari, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Alune+Retreat+Hostel+Ubud', phone: '+62 361 971 789', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/alune-retreat-hostel-ubud.jpg', tags: ['wellness', 'yoga', 'healthy-breakfast', 'rice-paddies', 'spiritual'] },
  // CAFES
  { name: 'Seniman Coffee Studio Ubud', slug: 'seniman-coffee-studio-ubud', category: 'CAFE', description: 'Bali\'s most respected specialty coffee roastery, sourcing exclusively from Indonesian farms and roasting in the cafe. Seniman\'s menu includes single-origin pourovers from Sumatra, Flores, and Bali highlands, and the monthly coffee pairing events are considered essential by coffee professionals visiting the island.', address: 'Jalan Sri Wedari 5, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Seniman+Coffee+Studio+Ubud', phone: '+62 361 972 085', website: 'https://senimancoffe.com', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/seniman-coffee-studio-ubud.jpg', tags: ['specialty', 'indonesian-coffee', 'roaster', 'pourover', 'best-in-bali'] },
  { name: 'Anomali Coffee Ubud', slug: 'anomali-coffee-ubud', category: 'CAFE', description: 'A beautiful, spacious multi-level cafe with rice terrace views from the upper balcony, excellent Indonesian single-origin espresso, and a full food menu. The long working tables with power outlets, fast wifi, and tranquil setting make Anomali the most popular nomad cafe in Ubud.', address: 'Jalan Raya Ubud, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Anomali+Coffee+Ubud', phone: '+62 361 978 430', website: 'https://anomalicoffee.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/anomali-coffee-ubud.jpg', tags: ['nomad', 'wifi', 'rice-terrace-views', 'espresso', 'spacious'] },
  { name: 'Zest Ubud Cafe', slug: 'zest-ubud-cafe', category: 'CAFE', description: 'A plant-based cafe and restaurant with Campuhan ridge views, serving the best health food in Ubud - colorful acai bowls, raw cacao desserts, turmeric lattes, and innovative vegan Indonesian cooking. Zest\'s rooftop terrace is the most coveted table in Ubud for healthy-food-loving travelers.', address: 'Jalan Goutama Sel, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Zest+Ubud+Cafe', phone: '+62 361 971 781', website: 'https://zestubud.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/zest-ubud-cafe.jpg', tags: ['vegan', 'plant-based', 'health-food', 'rooftop', 'ridge-views'] },
  { name: 'Clear Cafe Ubud', slug: 'clear-cafe-ubud', category: 'CAFE', description: 'A popular multi-level organic cafe on Hanoman Road with an extensive healthy menu, live music most evenings, a roof terrace, and an overall welcoming atmosphere that has made it a fixture of the Ubud community for over a decade. The raw chocolate brownies and turmeric ginger tea are constants.', address: 'Jalan Hanoman 8, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Clear+Cafe+Ubud', phone: '+62 361 978 517', website: 'https://clearcafebali.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/clear-cafe-ubud.jpg', tags: ['organic', 'live-music', 'rooftop', 'community', 'raw-chocolate'] },
  { name: 'Motif Coffee & Eatery Ubud', slug: 'motif-coffee-ubud', category: 'CAFE', description: 'A design-forward specialty cafe with a batik-inspired interior, excellent Indonesian single-origin filter coffees, and a creative small plates menu featuring Balinese ingredients. The iced coconut cold brew and the sambal eggs benedict are the most-ordered items in a menu of consistently great food.', address: 'Jalan Raya Ubud, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Motif+Coffee+Ubud', phone: '+62 812 3456 7890', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/motif-coffee-ubud.jpg', tags: ['specialty', 'design', 'batik', 'indonesian-coffee', 'brunch'] },
  { name: 'Kafe Batan Waru Ubud', slug: 'kafe-batan-waru-ubud', category: 'CAFE', description: 'An Ubud institution for over 20 years - a casual open-air cafe facing the main street with excellent Balinese coffee, freshly blended juices, and a menu of Indonesian and international dishes that keeps both tourists and locals coming back. The casual friendly atmosphere is the antidote to Ubud\'s premium wellness scene.', address: 'Jalan Dewi Sita, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Kafe+Batan+Waru+Ubud', phone: '+62 361 977 528', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/kafe-batan-waru-ubud.jpg', tags: ['institution', 'casual', 'balinese-coffee', 'juice', 'local'] },
  // RESTAURANTS
  { name: 'Room4Dessert Ubud', slug: 'room4dessert-ubud', category: 'FOOD', description: 'A remarkable dessert tasting bar by world pastry chef Will Goldfarb - a 14-course dessert-only menu featuring tropical Balinese ingredients in extraordinary combinations. Room4Dessert appeared in Netflix\'s Chef\'s Table and continues to be the most creative eating experience in Bali.', address: 'Jalan Raya Sanggingan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Room4Dessert+Ubud', phone: '+62 361 908 3529', website: 'https://room4dessert.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/room4dessert-ubud.jpg', tags: ['dessert-tasting', 'chefs-table', 'creative', 'netflix', 'must-book'] },
  { name: 'Locavore Ubud Restaurant', slug: 'locavore-ubud', category: 'FOOD', description: 'Consistently ranked among Asia\'s 50 Best Restaurants, Locavore presents a tasting menu using exclusively Balinese and Indonesian ingredients to produce refined, playful modern cooking. The menu changes with the seasons and every dish tells a story of the island\'s extraordinary biodiversity.', address: 'Jalan Dewi Sita 10, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Locavore+Ubud', phone: '+62 361 977 733', website: 'https://locavore.co.id', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/locavore-ubud.jpg', tags: ['asia-50-best', 'tasting-menu', 'seasonal', 'local-ingredients', 'must-book'] },
  { name: 'Bebek Bengil (Dirty Duck) Ubud', slug: 'bebek-bengil-dirty-duck-ubud', category: 'FOOD', description: 'The most famous restaurant in Ubud - an open-air jungle restaurant famous for its crispy duck (bebek betutu), served in a dramatic setting of rice paddies and lily ponds. The slow-roasted duck marinated in 30 Balinese spices has been the signature dish since the restaurant opened in 1990.', address: 'Jalan Hanoman, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Bebek+Bengil+Dirty+Duck+Ubud', phone: '+62 361 975 489', website: 'https://bebekbengil.co.id', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/bebek-bengil-dirty-duck-ubud.jpg', tags: ['crispy-duck', 'rice-paddies', 'iconic', '1990', 'balinese'] },
  { name: 'Naughty Nuri\'s Warung Ubud', slug: 'naughty-nuris-ubud', category: 'FOOD', description: 'A legendary warung that launched on the strength of its outrageous pork ribs - slathered in house sauce and grilled over charcoal until they fall from the bone - plus bucket-sized martinis. Naughty Nuri\'s has fed every generation of Ubud travelers since 1995 and remains an essential Bali rite of passage.', address: 'Jalan Raya Sanggingan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Naughty+Nuris+Ubud', phone: '+62 361 977 547', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/naughty-nuris-ubud.jpg', tags: ['pork-ribs', 'martinis', 'institution', '1995', 'must-visit'] },
  { name: 'Warung Babi Guling Ibu Oka Ubud', slug: 'warung-babi-guling-ibu-oka-ubud', category: 'FOOD', description: 'Anthony Bourdain\'s No Reservations episode made Ibu Oka\'s Balinese suckling pig (babi guling) world famous. The crispy skin, aromatic spice-stuffed pork, and accompanying lawar salad and black rice still draw queues from 11am until sold out (usually around 2pm).', address: 'Jalan Suweta 2, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Babi+Guling+Ibu+Oka+Ubud', phone: '+62 361 976 345', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/warung-babi-guling-ibu-oka-ubud.jpg', tags: ['babi-guling', 'suckling-pig', 'bourdain', 'famous', 'lunch-only'] },
  { name: 'Mozaic Restaurant Ubud', slug: 'mozaic-restaurant-ubud', category: 'FOOD', description: 'A romantic fine dining restaurant in a tropical garden with an ever-changing tasting menu by French-trained Chef Chris Salans, presenting progressive European cuisine using Balinese and Indonesian ingredients. Mozaic has held its position among Bali\'s best restaurants for over 20 years.', address: 'Jalan Raya Sanggingan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Mozaic+Restaurant+Ubud', phone: '+62 361 975 768', website: 'https://mozaic-bali.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/mozaic-restaurant-ubud.jpg', tags: ['fine-dining', 'garden', 'french', 'tasting-menu', 'romantic'] },
  // MARKETS
  { name: 'Ubud Traditional Market (Pasar Ubud)', slug: 'ubud-traditional-market', category: 'FOOD', description: 'The central market of Ubud with a morning fresh produce section (before 9am) and an afternoon handicraft market selling Balinese carvings, textiles, and incense. The morning fruit and vegetable market is the authentic local experience; the afternoon is tourist-oriented but the bargaining culture is genuine.', address: 'Jalan Raya Ubud, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Ubud+Traditional+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/ubud-traditional-market.jpg', tags: ['market', 'morning', 'crafts', 'produce', 'bargaining'] },
  { name: 'Ubud Night Market', slug: 'ubud-night-market', category: 'FOOD', description: 'An atmospheric evening food market that sets up in the car park behind the traditional market, with Balinese local food stalls serving nasi campur mixed rice, satay, sate lilit fish skewers, and es campur shaved ice. Prices are local, portions generous, and the atmosphere authentic community eating.', address: 'Jalan Wanara Wana, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Ubud+Night+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/ubud-night-market.jpg', tags: ['night-market', 'nasi-campur', 'satay', 'local', 'balinese'] },
  { name: 'Pasar Gianyar Night Market', slug: 'pasar-gianyar-night-market-ubud', category: 'FOOD', description: 'A 15-minute drive from Ubud in the regency capital of Gianyar, this sprawling nightly market has the most authentic Balinese street food outside temple festivals. The babi guling (suckling pig), ayam betutu (slow-roasted chicken), and lawar (mixed meat and vegetable) are all outstanding at genuinely local prices.', address: 'Jalan Ngurah Rai, Gianyar, Bali 80511, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Pasar+Gianyar+Night+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/pasar-gianyar-night-market-ubud.jpg', tags: ['night-market', 'gianyar', 'authentic', 'babi-guling', 'local'] },
  { name: 'Tegallalang Handicraft Centre', slug: 'tegallalang-handicraft-centre-ubud', category: 'FOOD', description: 'The main cluster of wood-carving workshops and showrooms along the road from Ubud to the famous rice terraces, where master craftsmen produce the ceremonial Garuda sculptures, decorative masks, and furniture that fill Bali\'s arts shops. Watch the carvers work and buy direct for authentic pieces.', address: 'Jalan Raya Tegallalang, Bali 80561, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Tegallalang+Handicraft+Centre', phone: null, website: null, priceRange: 'MID', rating: 4.3, imageUrl: '/spots/tegallalang-handicraft-centre-ubud.jpg', tags: ['wood-carving', 'handicrafts', 'garuda', 'masks', 'workshops'] },
  { name: 'Kumbasari Market Denpasar', slug: 'kumbasari-market-denpasar-ubud', category: 'FOOD', description: 'Bali\'s largest traditional market in Denpasar (45 minutes from Ubud) with four floors of textiles, offerings supplies, Balinese ceremonial items, spices, and food stalls. The ground-floor food court serves excellent Balinese and Indonesian meals from 5am, and the upper floors have the best textile prices on the island.', address: 'Jalan Gajah Mada, Denpasar, Bali 80112, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Kumbasari+Market+Denpasar', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/kumbasari-market-denpasar-ubud.jpg', tags: ['textiles', 'ceremonial', 'spices', 'largest', 'local'] },
  // TOURIST SITES
  { name: 'Tegallalang Rice Terraces Ubud', slug: 'tegallalang-rice-terraces-ubud', category: 'NATURE', description: 'The most famous rice terraces in Bali - dramatic green staircase paddies carved into the hillside using the traditional subak irrigation system, a UNESCO-recognized cultural landscape. Arrive before 8am to photograph the terraces in mist with almost no other visitors; the light at dawn is extraordinary.', address: 'Tegallalang, Gianyar, Bali 80561, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Tegallalang+Rice+Terraces', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/tegallalang-rice-terraces-ubud.jpg', tags: ['rice-terraces', 'unesco', 'sunrise', 'iconic', 'subak'] },
  { name: 'Sacred Monkey Forest Sanctuary Ubud', slug: 'sacred-monkey-forest-ubud', category: 'NATURE', description: 'A Hindu temple complex in a forest inhabited by over 700 long-tailed Balinese macaques who interact fearlessly with visitors. Three ancient temples, a cool forest trail, and the occasional monkey-on-head encounter make the Monkey Forest Ubud\'s most visited attraction and genuinely memorable.', address: 'Jalan Monkey Forest, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Sacred+Monkey+Forest+Ubud', phone: '+62 361 971 304', website: 'https://www.monkeyforestubud.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/sacred-monkey-forest-ubud.jpg', tags: ['monkeys', 'temple', 'forest', 'wildlife', 'interactive'] },
  { name: 'Campuhan Ridge Walk Ubud', slug: 'campuhan-ridge-walk-ubud', category: 'NATURE', description: 'Ubud\'s most beautiful free walk - a 2km ridge trail beginning at the Gunung Lebah Temple and winding through rice paddies, coconut groves, and jungle above the confluence of two rivers. Best walked at sunrise before the heat builds; the views of the surrounding volcanic mountains on clear mornings are spectacular.', address: 'Campuhan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Campuhan+Ridge+Walk+Ubud', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/campuhan-ridge-walk-ubud.jpg', tags: ['walk', 'sunrise', 'rice-paddies', 'free', 'nature'] },
  { name: 'Pura Tirta Empul Temple Ubud', slug: 'pura-tirta-empul-ubud', category: 'CULTURE', description: 'A 10th-century water temple surrounding a sacred spring where Balinese Hindus perform ritual purification by bathing in the holy spring water flowing through a series of carved spouts. The active daily ceremonies, processions of white-clad devotees, and profound spiritual atmosphere make it the most meaningful temple visit in Bali.', address: 'Tampaksiring, Gianyar, Bali 80552, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Pura+Tirta+Empul+Bali', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/pura-tirta-empul-ubud.jpg', tags: ['temple', 'holy-spring', 'purification', '10th-century', 'ceremonies'] },
  { name: 'Ubud Palace (Puri Saren Agung)', slug: 'ubud-palace-puri-saren-agung', category: 'CULTURE', description: 'The former royal palace of the Ubud royal family in the town center, still inhabited by the family and functioning as the stage for nightly Kecak dance performances. The carved stone gates, flowering frangipani courtyards, and the electricity of a live traditional dance performance are collectively unmissable.', address: 'Jalan Raya Ubud, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Ubud+Palace+Bali', phone: '+62 361 975 057', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/ubud-palace-puri-saren-agung.jpg', tags: ['palace', 'royal-family', 'kecak-dance', 'evening-performance', 'cultural'] },
  { name: 'Goa Gajah (Elephant Cave) Ubud', slug: 'goa-gajah-ubud', category: 'CULTURE', description: 'An 11th-century Hindu cave sanctuary with a carved stone demon face entrance and two bathing pools with female figure fountains. The cave interior contains Shiva lingams and a Buddha statue suggesting the site served both Hindu and Buddhist communities. One of Bali\'s most intriguing archaeological sites.', address: 'Bedulu, Blahbatuh, Gianyar, Bali 80582, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Goa+Gajah+Ubud', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/goa-gajah-ubud.jpg', tags: ['cave', '11th-century', 'hindu', 'archaeological', 'carvings'] },
  { name: 'Mount Batur Sunrise Trek', slug: 'mount-batur-sunrise-trek-ubud', category: 'NATURE', description: 'An active volcano with a 2-hour pre-dawn hike to the 1,717m summit for one of the most spectacular sunrises in Southeast Asia - the sun emerging from behind Lombok\'s Rinjani volcano while Bali\'s highlands glow below. Guides are mandatory; tours leave from Ubud around midnight.', address: 'Kintamani, Bangli, Bali 80652, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Mount+Batur+Bali', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/mount-batur-sunrise-trek-ubud.jpg', tags: ['volcano', 'sunrise-trek', 'hiking', 'crater-lake', 'guide-required'] },
  { name: 'Neka Art Museum Ubud', slug: 'neka-art-museum-ubud', category: 'CULTURE', description: 'The finest collection of traditional and modern Balinese art - six pavilions of paintings, drawings, and photographs spanning 600 years of Balinese artistic tradition from the Kamasan wayang style through the Ubud school to contemporary masters. An essential counterpart to temple visits for understanding Balinese culture.', address: 'Jalan Raya Sanggingan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Neka+Art+Museum+Ubud', phone: '+62 361 975 074', website: 'https://www.nekaartmuseum.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/neka-art-museum-ubud.jpg', tags: ['art-museum', 'balinese-art', 'traditional', 'paintings', '600-years'] },
  { name: 'Agung Rai Museum of Art (ARMA) Ubud', slug: 'arma-museum-ubud', category: 'CULTURE', description: 'The most comprehensive private museum of Balinese and Indonesian art in Ubud, set in a stunning complex of traditional Balinese pavilions and gardens. ARMA runs daily Balinese painting, dancing, and woodcarving classes that are the best way for visitors to engage actively with Balinese artistic tradition.', address: 'Jalan Raya Pengosekan, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=ARMA+Museum+Ubud', phone: '+62 361 976 659', website: 'https://armamuseum.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/arma-museum-ubud.jpg', tags: ['museum', 'balinese-art', 'classes', 'garden', 'painting'] },
  // COWORKING
  { name: 'Hubud Coworking Ubud', slug: 'hubud-coworking-ubud', category: 'COWORKING', description: 'The world\'s most famous jungle coworking space - Hubud pioneered the concept of combining digital nomad community with Bali\'s spiritual setting. A bamboo and wood open-air structure surrounded by rice paddies, with fast fiber internet, a cafe, yoga classes, and a community of remote workers from 50+ countries.', address: 'Jalan Monkey Forest 88x, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Hubud+Coworking+Ubud', phone: '+62 361 978 073', website: 'https://www.hubud.org', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/hubud-coworking-ubud.jpg', tags: ['jungle', 'bamboo', 'pioneer', 'community', 'yoga'] },
  { name: 'Dojo Bali Coworking Canggu', slug: 'dojo-bali-coworking-canggu', category: 'COWORKING', description: 'Bali\'s largest coworking space in Canggu (45 minutes from Ubud) with 24/7 access, a surf break 5 minutes away, an outdoor pool, sleeping pods, and a community of over 3,000 registered nomads. The Dojo is the social hub of Bali\'s nomad community with events every night of the week.', address: 'Jalan Padang Linjong 99, Canggu, Bali 80361, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Dojo+Bali+Coworking+Canggu', phone: '+62 361 934 9217', website: 'https://www.dojobali.org', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/dojo-bali-coworking-canggu.jpg', tags: ['largest', 'canggu', 'pool', 'surf', 'community'] },
  { name: 'Outpost Ubud Coworking', slug: 'outpost-ubud-coworking', category: 'COWORKING', description: 'A premium coworking and coliving space in central Ubud with ergonomic desks, private meeting rooms, a rooftop terrace with jungle views, and a coliving program that places nomads in local family compounds. The weekly nomad community dinners and temple excursions distinguish Outpost from standard coworking.', address: 'Jalan Raya Penestanan Kelod, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Outpost+Ubud+Coworking', phone: '+62 361 908 0038', website: 'https://www.outpost-asia.com/ubud', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/outpost-ubud-coworking.jpg', tags: ['coliving', 'jungle-views', 'community-dinners', 'temples', 'premium'] },
  { name: 'Kumpul Coworking Ubud', slug: 'kumpul-coworking-ubud', category: 'COWORKING', description: 'An affordable Ubud coworking space with a simple, focused working environment - fast internet, standing desks, AC, and a coffee bar. Kumpul is popular with long-stay nomads who want a reliable daily workspace without the social programming of the larger spaces.', address: 'Jalan Raya Ubud, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Kumpul+Coworking+Ubud', phone: '+62 812 9876 5432', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/kumpul-coworking-ubud.jpg', tags: ['affordable', 'focused', 'standing-desks', 'long-stay', 'simple'] },
  { name: 'Ubud Hub Coworking', slug: 'ubud-hub-coworking', category: 'COWORKING', description: 'A compact, well-maintained coworking space in central Ubud with a garden terrace, fast fiber internet, and day passes available without prior booking. The resident community is small and friendly, making it easier to get work done without the distractions of larger, more social coworking spaces.', address: 'Jalan Dewi Sita, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Ubud+Hub+Coworking', phone: '+62 819 1234 5678', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/ubud-hub-coworking.jpg', tags: ['compact', 'garden-terrace', 'day-pass', 'fiber', 'quiet'] },
  { name: 'Milk & Madu Seminyak Coworking', slug: 'milk-madu-coworking-bali', category: 'COWORKING', description: 'A cafe-coworking hybrid in Seminyak (1.5 hours from Ubud) that is Bali\'s best cafe workspace - long tables, power outlets at every seat, excellent food, and the right balance of cafe buzz and working focus. The best option for nomads spending a night or two in Seminyak before or after Ubud.', address: 'Jalan Batu Belig No.99, Seminyak, Bali 80351, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Milk+Madu+Seminyak', phone: '+62 361 934 9555', website: 'https://milkandmadu.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/milk-madu-coworking-bali.jpg', tags: ['cafe-coworking', 'seminyak', 'food', 'tables', 'power-outlets'] },
  { name: 'Bali Spirit Festival Grounds Ubud', slug: 'bali-spirit-festival-ubud', category: 'CULTURE', description: 'The venue and spiritual community surrounding the annual BaliSpirit Festival - the world\'s largest yoga, dance, and music festival held each March at the Purnati arts center in Ubud. Year-round, the site hosts smaller retreats, sound healing sessions, and community ceremonies open to visiting travelers.', address: 'Purnati Center for the Arts, Ubud, Bali 80571, Indonesia', googleMapsUrl: 'https://maps.google.com/?q=Purnati+Center+Arts+Ubud', phone: '+62 361 978 954', website: 'https://balispiritfestival.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/bali-spirit-festival-ubud.jpg', tags: ['festival', 'yoga', 'healing', 'community', 'spiritual'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Ubud: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
