const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328fki000pvi8wkr0xexjj';

const spots = [
  // LUXURY HOTELS
  { name: 'El Nido Resorts Miniloc Island', slug: 'el-nido-resorts-miniloc-island', category: 'ACCOMMODATION', description: 'The original El Nido Resorts property on Miniloc Island, accessible only by boat, with overwater cottages on a turquoise lagoon surrounded by limestone karst cliffs. Ten Knots\' flagship property balances eco-luxury with genuine conservation practice - reef restoration and sea turtle protection programs are at the heart of the operation.', address: 'Miniloc Island, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Nido+Resorts+Miniloc+Island', phone: '+63 2 8902 5950', website: 'https://www.elnidoresorts.com/miniloc', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/el-nido-resorts-miniloc-island.jpg', tags: ['overwater', 'island-resort', 'eco-luxury', 'lagoon', 'conservation'] },
  { name: 'El Nido Resorts Lagen Island', slug: 'el-nido-resorts-lagen-island', category: 'ACCOMMODATION', description: 'A more secluded Ten Knots resort on forested Lagen Island with water cottages extending over the lagoon and forest cottages on the hillside. The private island setting, excellent diving access, and the extraordinary view of karst towers rising from the sea make Lagen the most atmospheric luxury stay in Palawan.', address: 'Lagen Island, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Nido+Resorts+Lagen+Island', phone: '+63 2 8902 5950', website: 'https://www.elnidoresorts.com/lagen', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/el-nido-resorts-lagen-island.jpg', tags: ['island-resort', 'water-cottages', 'diving', 'karst', 'secluded'] },
  { name: 'Pangulasian Island Resort El Nido', slug: 'pangulasian-island-resort-el-nido', category: 'ACCOMMODATION', description: 'A private 580-hectare island resort accessible only by speedboat, with 42 luxurious villas on a pristine white sand beach at the southern end of El Nido. Pangulasian\'s all-inclusive concept, impeccable service, and extraordinary beach make it the best ultra-luxury experience in Palawan.', address: 'Pangulasian Island, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Pangulasian+Island+Resort+El+Nido', phone: '+63 2 8902 5950', website: 'https://www.elnidoresorts.com/pangulasian', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/pangulasian-island-resort-el-nido.jpg', tags: ['private-island', 'all-inclusive', 'beach', 'ultra-luxury', 'speedboat'] },
  { name: 'Cauayan Island Resort El Nido', slug: 'cauayan-island-resort-el-nido', category: 'ACCOMMODATION', description: 'An 8-villa boutique luxury resort on private Cauayan Island in the middle of Bacuit Bay with a panoramic pool, excellent spa, and a dining pavilion built around a 600-year-old Balete tree. Cauayan is quieter and more intimate than the Ten Knots properties with truly personalized service.', address: 'Cauayan Island, Bacuit Bay, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Cauayan+Island+Resort+El+Nido', phone: '+63 917 531 3127', website: 'https://cauayanisland.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/cauayan-island-resort-el-nido.jpg', tags: ['boutique', 'private-island', 'intimate', 'balete-tree', 'spa'] },
  // BUDGET HOTELS
  { name: 'Spin Designer Hostel El Nido', slug: 'spin-designer-hostel-el-nido', category: 'ACCOMMODATION', description: 'The most design-forward accommodation in El Nido town with beautiful private rooms, excellent wifi, a rooftop with karst views, and a tour desk that organizes island-hopping at competitive prices. Spin proves you don\'t need to spend a fortune to have a stylish, comfortable base in El Nido.', address: 'Hama Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Spin+Designer+Hostel+El+Nido', phone: '+63 917 810 6155', website: 'https://spindesignerhostel.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/spin-designer-hostel-el-nido.jpg', tags: ['design', 'rooftop', 'island-hopping', 'wifi', 'stylish'] },
  { name: 'Frendz Resort El Nido', slug: 'frendz-resort-el-nido', category: 'ACCOMMODATION', description: 'A well-run guesthouse resort a short walk from the town beach with clean rooms, a breezy terrace restaurant, a dive center, and an excellent travel desk. Frendz has the friendliest staff in El Nido and the private room rates are the best value in the mid-range category for the location.', address: 'Calle Hama, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Frendz+Resort+El+Nido', phone: '+63 917 558 4437', website: 'https://frendzresort.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/frendz-resort-el-nido.jpg', tags: ['guesthouse', 'dive-center', 'friendly', 'terrace', 'value'] },
  { name: 'Buena Vida Resort El Nido', slug: 'buena-vida-resort-el-nido', category: 'ACCOMMODATION', description: 'A comfortable beach resort on Corong-Corong beach, 3km from El Nido town, with a pool, beachfront rooms, and a relaxed atmosphere away from the town bustle. The beachside hammocks, paddleboards, and kayaks are all free for guests - the best budget beach-stay option in the El Nido area.', address: 'Corong-Corong Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Buena+Vida+Resort+El+Nido', phone: '+63 917 803 3024', website: 'https://buenavidaresort.com.ph', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/buena-vida-resort-el-nido.jpg', tags: ['beach', 'corong-corong', 'pool', 'kayak', 'hammock'] },
  { name: 'Arte Hostel El Nido', slug: 'arte-hostel-el-nido', category: 'ACCOMMODATION', description: 'A colorful art-themed guesthouse in El Nido town run by a local artist family with hand-painted rooms, a cafe downstairs, and a rooftop with Bacuit Bay views. Arte is a uniquely personal accommodation that reflects the owner\'s creative spirit - the kind of place that makes El Nido feel less like a tourist machine.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Arte+Hostel+El+Nido', phone: '+63 917 456 3210', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/arte-hostel-el-nido.jpg', tags: ['art', 'colorful', 'cafe', 'local', 'personal'] },
  // HOSTELS
  { name: 'Imagine Beach Resort El Nido', slug: 'imagine-beach-resort-el-nido', category: 'ACCOMMODATION', description: 'A laid-back beach hostel on a quiet stretch of sand at Corong-Corong with bamboo bungalows, a garden hammock area, and an atmosphere that feels like you\'ve stepped back to when El Nido was still a secret. The island-hopping tours organized by the owner use smaller private boats for a more intimate experience.', address: 'Corong-Corong Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Imagine+Beach+Resort+El+Nido', phone: '+63 917 333 4567', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/imagine-beach-resort-el-nido.jpg', tags: ['beach', 'bamboo', 'hammock', 'private-tours', 'laid-back'] },
  { name: 'El Nido Cove Resort Hostel', slug: 'el-nido-cove-resort-hostel', category: 'ACCOMMODATION', description: 'A social hostel on the El Nido town beach with dorms, private rooms, a swim-up bar, and a party atmosphere on weekends. The nightly bonfire and communal barbecue on the beach create the easiest solo travel social scene in El Nido - you\'ll have island-hopping companions by the first evening.', address: 'Rizal Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Nido+Cove+Resort+Hostel', phone: '+63 917 567 8901', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/el-nido-cove-resort-hostel.jpg', tags: ['social', 'beach', 'bonfire', 'bbq', 'communal'] },
  { name: 'Backpacker El Nido Hostel', slug: 'backpacker-el-nido-hostel', category: 'ACCOMMODATION', description: 'A clean, reliable hostel in central El Nido town with pod bunks, a kitchen, secure lockers, and a dedicated tour desk. The hostel staff are among the most knowledgeable in El Nido for trip planning - their custom island-hopping combinations avoid the most crowded routes and include secret beaches.', address: 'Calle Real, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Backpacker+El+Nido+Hostel', phone: '+63 917 678 9012', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/backpacker-el-nido-hostel.jpg', tags: ['pods', 'kitchen', 'lockers', 'tour-desk', 'secret-beaches'] },
  { name: 'El Rio y Mar Resort El Nido', slug: 'el-rio-y-mar-resort-el-nido', category: 'ACCOMMODATION', description: 'A small riverside resort where a river meets the sea at the edge of El Nido town - accessible by private boat and offering a secluded setting with dorms and private rooms at budget prices. The morning canoe paddling through mangroves to the nearest beach is an experience unique to this property.', address: 'Maremegmeg (Las Cabanas) Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Rio+y+Mar+Resort+El+Nido', phone: '+63 917 789 0123', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/el-rio-y-mar-resort-el-nido.jpg', tags: ['riverside', 'mangroves', 'canoe', 'secluded', 'budget'] },
  // CAFES
  { name: 'Altrove Caffe El Nido', slug: 'altrove-caffe-el-nido', category: 'CAFE', description: 'The best espresso in El Nido - an Italian-owned cafe in the town center with proper espresso machines, Italian pastries, and a selection of aperitivo drinks served on a breezy terrace. The spritz and the ricotta-filled cornetto have made Altrove a daily ritual for long-stay El Nido visitors.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Altrove+Caffe+El+Nido', phone: '+63 917 890 1234', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/altrove-caffe-el-nido.jpg', tags: ['italian', 'espresso', 'spritz', 'aperitivo', 'terrace'] },
  { name: 'Republica Sunset Bar El Nido', slug: 'republica-sunset-bar-el-nido', category: 'CAFE', description: 'The most beloved sunset-watching spot in El Nido - a clifftop bar at Las Cabanas Beach with sweeping views of Bacuit Bay and the limestone karst formations. Arrive 30 minutes before sunset, order a Palawan Brew, and watch the sky turn orange and pink above one of the world\'s most beautiful bays.', address: 'Las Cabanas Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Republica+Sunset+Bar+El+Nido', phone: '+63 917 901 2345', website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/republica-sunset-bar-el-nido.jpg', tags: ['sunset', 'clifftop', 'palawan-brew', 'views', 'las-cabanas'] },
  { name: 'Bay Bean Coffee El Nido', slug: 'bay-bean-coffee-el-nido', category: 'CAFE', description: 'A specialty coffee shop using single-origin Philippine beans sourced from Sagada and Benguet, with a simple menu of espresso drinks, cold brew, and homemade muffins. The outdoor seating area faces a small garden and the morning light through the coconut palms makes it El Nido\'s most peaceful breakfast spot.', address: 'Hama Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Bay+Bean+Coffee+El+Nido', phone: '+63 917 012 3456', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/bay-bean-coffee-el-nido.jpg', tags: ['specialty', 'philippine-coffee', 'cold-brew', 'garden', 'peaceful'] },
  { name: 'El Nido Boutique and Art Cafe', slug: 'el-nido-boutique-art-cafe', category: 'CAFE', description: 'A charming combination art gallery, boutique, and cafe in a heritage building in El Nido town, serving strong Arabica coffee alongside Filipino snacks and showcasing handmade jewelry, paintings, and crafts by local Palawan artists. The courtyard seating under bougainvillea is the most atmospheric spot in town.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Nido+Boutique+Art+Cafe', phone: '+63 917 123 4567', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/el-nido-boutique-art-cafe.jpg', tags: ['art-gallery', 'boutique', 'philippine-coffee', 'local-art', 'courtyard'] },
  { name: 'Happiness Organics El Nido', slug: 'happiness-organics-el-nido', category: 'CAFE', description: 'A health-focused cafe serving organic smoothie bowls, fresh coconut water, raw desserts, and cold-pressed juices using locally sourced tropical fruits. The menu changes with what\'s available from local farms and the daily cacao ceremony has become a morning ritual for wellness-oriented travelers.', address: 'Calle Hama, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Happiness+Organics+El+Nido', phone: '+63 917 234 5678', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/happiness-organics-el-nido.jpg', tags: ['organic', 'smoothie', 'raw', 'cacao-ceremony', 'wellness'] },
  { name: 'La Plage Bar El Nido', slug: 'la-plage-bar-el-nido', category: 'CAFE', description: 'A French-influenced beachside bar at Maremegmeg (Las Cabanas) Beach with great cocktails, decent coffee, and direct beach access. La Plage is the morning coffee and evening cocktail destination for the Las Cabanas beach strip - the beach bar ambiance, with toes in the sand and a gin tonic, is perfectly El Nido.', address: 'Maremegmeg Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=La+Plage+Bar+El+Nido', phone: '+63 917 345 6789', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/la-plage-bar-el-nido.jpg', tags: ['beach-bar', 'cocktails', 'french', 'las-cabanas', 'toes-in-sand'] },
  // RESTAURANTS
  { name: 'Tuna & Tides El Nido', slug: 'tuna-and-tides-el-nido', category: 'FOOD', description: 'The finest dining restaurant in El Nido town, with an Italian-Filipino menu showcasing the extraordinary fresh seafood of Palawan - line-caught yellowfin tuna tartare, grilled barracuda with garlic and olive oil, and Palawan prawns cooked in butter and local herbs. The freshest fish you will eat in the Philippines.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Tuna+Tides+El+Nido', phone: '+63 917 456 7890', website: null, priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/tuna-and-tides-el-nido.jpg', tags: ['seafood', 'tuna', 'italian-filipino', 'fresh', 'fine-dining'] },
  { name: 'Altrove Restaurant El Nido', slug: 'altrove-restaurant-el-nido', category: 'FOOD', description: 'The sister restaurant to Altrove Caffe, serving proper Italian cuisine - fresh pasta, wood-fired pizza, and excellent tiramisu - in an open-air setting facing the main street. For travelers exhausted by a week of island-hopping, a plate of cacio e pepe and a bottle of Primitivo is the perfect reset.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Altrove+Restaurant+El+Nido', phone: '+63 917 567 8901', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/altrove-restaurant-el-nido.jpg', tags: ['italian', 'pasta', 'pizza', 'tiramisu', 'open-air'] },
  { name: 'Tatay Dodge BBQ El Nido', slug: 'tatay-dodge-bbq-el-nido', category: 'FOOD', description: 'The most authentic local BBQ experience in El Nido - a family-run grill where fresh fish, pork skewers, and prawns are cooked over charcoal at tables in the street. Prices are genuinely local, the portions are huge, and the experience of eating lechon manok with a cold Pale Pilsen under the stars is El Nido at its most real.', address: 'Real Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Tatay+Dodge+BBQ+El+Nido', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/tatay-dodge-bbq-el-nido.jpg', tags: ['bbq', 'local', 'charcoal', 'cheap', 'street-dining'] },
  { name: 'Square Bar and Restaurant El Nido', slug: 'square-bar-restaurant-el-nido', category: 'FOOD', description: 'A lively open-air bar and restaurant in central El Nido serving Filipino favorites alongside international dishes, with a large beer selection and a happy hour that draws most of the town\'s travelers. The garlic rice, adobo, and kare-kare are all well-executed at prices that make El Nido\'s food scene excellent value.', address: 'Calle Hama, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Square+Bar+Restaurant+El+Nido', phone: '+63 917 678 9012', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/square-bar-restaurant-el-nido.jpg', tags: ['filipino', 'bar', 'happy-hour', 'adobo', 'social'] },
  { name: 'Sea Slug Restaurant El Nido', slug: 'sea-slug-restaurant-el-nido', category: 'FOOD', description: 'A colorful Filipino-international restaurant known for its gigantic fresh seafood platters, competitive prices, and a menu that features local specialties like sinigang na hipon (tamarind shrimp soup) and kinilaw de tanigue (tuna ceviche) alongside pasta and burgers. The catch-of-the-day is always the best order.', address: 'Real Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Sea+Slug+Restaurant+El+Nido', phone: '+63 917 789 0123', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/sea-slug-restaurant-el-nido.jpg', tags: ['seafood', 'sinigang', 'kinilaw', 'catch-of-day', 'filipino'] },
  { name: 'Trattoria Altrove El Nido Rooftop', slug: 'trattoria-rooftop-el-nido', category: 'FOOD', description: 'The rooftop dining experience above the Altrove complex with panoramic views of El Nido bay and the karst formations, serving a curated menu of aperitivo small plates and antipasti. The pre-sunset aperitivo hour between 5-7pm with a Negroni and fresh oysters is the most sophisticated experience in town.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Trattoria+Altrove+El+Nido', phone: '+63 917 890 1234', website: null, priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/trattoria-rooftop-el-nido.jpg', tags: ['rooftop', 'aperitivo', 'negroni', 'oysters', 'panoramic'] },
  // MARKETS
  { name: 'El Nido Public Market', slug: 'el-nido-public-market', category: 'FOOD', description: 'The main daily market of El Nido town with fresh fish sections, vegetable vendors, rice stalls, and a small food court serving local breakfast. The morning tuna auction at the back of the market is an extraordinary sight - huge yellowfin tuna selling by hand signal to local restaurants and vendors.', address: 'El Nido Town Proper, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Nido+Public+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/el-nido-public-market.jpg', tags: ['market', 'tuna-auction', 'local', 'morning', 'fresh-fish'] },
  { name: 'El Nido Night Market', slug: 'el-nido-night-market', category: 'FOOD', description: 'A nightly street food market along the El Nido town beach road with vendors grilling fresh seafood, serving Filipino street snacks, and selling tropical fruit shakes. The market is informal and authentic - prices are local, the atmosphere is festive, and the grilled bangus milkfish with garlic rice is excellent.', address: 'Rizal Beach Road, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=El+Nido+Night+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/el-nido-night-market.jpg', tags: ['night-market', 'seafood-grill', 'street-food', 'bangus', 'local'] },
  { name: 'Corong-Corong Local Market', slug: 'corong-corong-local-market-el-nido', category: 'FOOD', description: 'A small neighborhood market in the Corong-Corong beach area catering to the local fishing community and the growing tourist accommodation along this stretch. The morning pan de sal bread and native chicken adobo cooked by local grandmothers at 6am is the authentic breakfast that every El Nido food guide misses.', address: 'Corong-Corong, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Corong-Corong+Market+El+Nido', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/corong-corong-local-market-el-nido.jpg', tags: ['local', 'pan-de-sal', 'adobo', 'morning', 'neighborhood'] },
  { name: 'Palawan Souvenir Alley El Nido', slug: 'palawan-souvenir-alley-el-nido', category: 'FOOD', description: 'A concentrated row of souvenir shops along the main street of El Nido selling Palawan pearls, shell jewelry, woven bags, and locally made handicrafts. The pearl vendors here sell genuine south sea pearls directly from Palawan pearl farms at prices far below Manila retail - worth inspecting carefully with the right eye.', address: 'Calle Real, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Palawan+Souvenir+Alley+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.2, imageUrl: '/spots/palawan-souvenir-alley-el-nido.jpg', tags: ['souvenirs', 'palawan-pearls', 'jewelry', 'handicrafts', 'shopping'] },
  { name: 'Las Cabanas Sunset Strip El Nido', slug: 'las-cabanas-sunset-strip-el-nido', category: 'FOOD', description: 'A stretch of casual beachside food and drink stalls along Las Cabanas Beach that comes to life from late afternoon, serving grilled seafood, fresh coconuts, Palawan beers, and cocktails as the sun sets over the karst islands. Every evening becomes an impromptu gathering of travelers watching one of the world\'s best sunsets.', address: 'Maremegmeg Beach (Las Cabanas), El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Las+Cabanas+Beach+El+Nido', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/las-cabanas-sunset-strip-el-nido.jpg', tags: ['sunset', 'beach-food', 'cocktails', 'social', 'evening'] },
  // TOURIST SITES
  { name: 'Big Lagoon El Nido', slug: 'big-lagoon-el-nido', category: 'NATURE', description: 'The most famous of El Nido\'s lagoons - a vast turquoise lake enclosed within towering limestone cliffs, accessible only by kayak through a narrow rocky passage at low tide. The water changes color from aquamarine to deep blue through the day and the silence inside the lagoon walls is absolute.', address: 'Miniloc Island, Bacuit Bay, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Big+Lagoon+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.9, imageUrl: '/spots/big-lagoon-el-nido.jpg', tags: ['lagoon', 'kayak', 'turquoise', 'limestone', 'iconic'] },
  { name: 'Small Lagoon El Nido', slug: 'small-lagoon-el-nido', category: 'NATURE', description: 'A perfectly circular enclosed lagoon accessible by swimming through a small hole in the limestone karst at low tide, with stunning vertical cliff walls rising 100m straight up from the translucent water. The experience of emerging through the rock wall into the hidden lagoon is one of the most memorable moments in Philippine travel.', address: 'Miniloc Island, Bacuit Bay, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Small+Lagoon+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.9, imageUrl: '/spots/small-lagoon-el-nido.jpg', tags: ['lagoon', 'swimming', 'karst', 'hidden', 'extraordinary'] },
  { name: 'Nacpan Beach El Nido', slug: 'nacpan-beach-el-nido', category: 'NATURE', description: 'A 4km twin beach on the north coast of El Nido accessible by habal-habal motorcycle taxi, with powdery white sand, coconut trees, turquoise water, and almost no tourist infrastructure. Consistently voted one of the world\'s most beautiful beaches - visit on a weekday morning for the experience of a genuinely empty paradise beach.', address: 'Nacpan, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Nacpan+Beach+El+Nido', phone: null, website: null, priceRange: 'FREE', rating: 4.9, imageUrl: '/spots/nacpan-beach-el-nido.jpg', tags: ['beach', 'white-sand', 'empty', 'paradise', 'world-best'] },
  { name: 'Secret Lagoon El Nido', slug: 'secret-lagoon-el-nido', category: 'NATURE', description: 'A shallow, crystal-clear lagoon hidden behind a small beach cove, entered through a narrow crack in the limestone rock. The secret lagoon\'s shallow interior hosts a coral flat with juvenile fish, nudibranch, and sea horses while the entrance is barely wide enough for one swimmer at a time.', address: 'Miniloc Island, Bacuit Bay, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Secret+Lagoon+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/secret-lagoon-el-nido.jpg', tags: ['lagoon', 'snorkeling', 'coral', 'seahorse', 'hidden'] },
  { name: 'Cadlao Lagoon El Nido', slug: 'cadlao-lagoon-el-nido', category: 'NATURE', description: 'A stunning enclosed lagoon on Cadlao Island - the largest island in the El Nido archipelago - with dramatic overhanging limestone walls, clear water, and excellent snorkeling on the edges of the lagoon. Less visited than the Tour A lagoons, Cadlao offers a more peaceful El Nido experience.', address: 'Cadlao Island, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Cadlao+Lagoon+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/cadlao-lagoon-el-nido.jpg', tags: ['lagoon', 'limestone', 'snorkeling', 'less-crowded', 'peaceful'] },
  { name: 'Matinloc Shrine El Nido', slug: 'matinloc-shrine-el-nido', category: 'CULTURE', description: 'An abandoned concrete shrine on a clifftop on Matinloc Island, dramatically positioned over the Hidden Beach below with panoramic views of the Bacuit archipelago. The climb to the shrine is short but steep and the platform views of dozens of karst islands stretching to the horizon are the finest in all of El Nido.', address: 'Matinloc Island, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Matinloc+Shrine+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/matinloc-shrine-el-nido.jpg', tags: ['shrine', 'clifftop', 'views', 'abandoned', 'panoramic'] },
  { name: 'Helicopter Island El Nido', slug: 'helicopter-island-el-nido', category: 'NATURE', description: 'An island shaped like a helicopter from above, with a beautiful white sand beach on its windward side and excellent snorkeling along its rocky southern coast. Helicopter Island is the most accessible uncrowded beach day-trip from El Nido, reachable in 15 minutes by bangka boat.', address: 'Dilumacad Island, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Helicopter+Island+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/helicopter-island-el-nido.jpg', tags: ['island', 'beach', 'snorkeling', 'accessible', 'uncrowded'] },
  { name: 'Palawan Wildlife Rescue Center El Nido', slug: 'palawan-wildlife-rescue-center-el-nido', category: 'CULTURE', description: 'A wildlife rehabilitation center in El Nido rescuing and treating injured and confiscated endemic Palawan wildlife including bearcat, pangolin, Philippine cockatoo, and sea turtles. Guided tours give visitors close encounters with recovering wildlife and explain the threats facing Palawan\'s extraordinary endemic biodiversity.', address: 'Lio Tourism Estate, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Palawan+Wildlife+Rescue+Center', phone: '+63 48 719 5025', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/palawan-wildlife-rescue-center-el-nido.jpg', tags: ['wildlife', 'conservation', 'pangolin', 'turtle', 'endemic'] },
  { name: 'Lio Beach El Nido', slug: 'lio-beach-el-nido', category: 'NATURE', description: 'A protected government-managed beach in the Lio Tourism Estate north of El Nido town with white sand, clear water, and resort facilities managed by the Ten Knots group. The low-key resort development, paddleboard rentals, beach bars, and excellent snorkeling reefs make it the most accessible luxury beach day in El Nido.', address: 'Lio Tourism Estate, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Lio+Beach+El+Nido', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/lio-beach-el-nido.jpg', tags: ['beach', 'paddleboard', 'snorkeling', 'managed', 'resort-day'] },
  // COWORKING
  { name: 'Coworking El Nido', slug: 'coworking-el-nido', category: 'COWORKING', description: 'The dedicated digital nomad coworking space in El Nido town with fiber internet, standing desks, AC, and a rooftop terrace with karst views - the only purpose-built coworking space in El Nido. Day and weekly passes available; most island-hopping is done in the morning leaving afternoons free for work.', address: 'Rizal Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Coworking+El+Nido', phone: '+63 917 012 3456', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/coworking-el-nido.jpg', tags: ['coworking', 'fiber', 'karst-views', 'day-pass', 'nomad'] },
  { name: 'Spin Designer Hostel Cowork El Nido', slug: 'spin-designer-hostel-cowork-el-nido', category: 'COWORKING', description: 'The coworking area within Spin Designer Hostel - a well-equipped work space with desks, fast internet, power outlets, and a pleasant common area open to non-guests by day pass. The rooftop access and the social hostel environment make it good for nomads who want to combine working with meeting other travelers.', address: 'Hama Street, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Spin+Hostel+Cowork+El+Nido', phone: '+63 917 810 6155', website: 'https://spindesignerhostel.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/spin-designer-hostel-cowork-el-nido.jpg', tags: ['hostel-cowork', 'rooftop', 'social', 'day-pass', 'budget'] },
  { name: 'Lio Tourism Estate Business Hub', slug: 'lio-business-hub-el-nido', category: 'COWORKING', description: 'A small business center within the Lio Tourism Estate providing meeting rooms, video conferencing facilities, and a quiet workspace for resort guests and day visitors. The Estate setting amid beachfront development, with reliable power and internet, makes it the most professional work environment accessible in El Nido.', address: 'Lio Tourism Estate, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Lio+Tourism+Estate+El+Nido', phone: '+63 48 719 5025', website: 'https://www.elnidoresorts.com', priceRange: 'MID', rating: 4.3, imageUrl: '/spots/lio-business-hub-el-nido.jpg', tags: ['meeting-rooms', 'video-conferencing', 'estate', 'professional', 'reliable'] },
  { name: 'The Beach Hub El Nido', slug: 'beach-hub-el-nido', category: 'COWORKING', description: 'A casual open-air coworking setup on the Corong-Corong beachfront with shaded tables, solar-powered outlets, and fast 4G internet, specifically designed for nomads who want to work with sand between their toes. Open sunrise to sunset with cold brew coffee and fresh coconuts available at your desk.', address: 'Corong-Corong Beach, El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Beach+Hub+Coworking+El+Nido', phone: '+63 917 234 5678', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/beach-hub-el-nido.jpg', tags: ['beach-coworking', 'solar', 'cold-brew', 'casual', 'open-air'] },
  { name: 'Nomads Paradise El Nido', slug: 'nomads-paradise-el-nido', category: 'COWORKING', description: 'A coliving and coworking compound in El Nido town combining private rooms, shared apartments, a well-equipped workspace, and organized social activities. Monthly memberships include accommodation, workspace access, a shared kitchen, and weekly island-hopping excursions that make El Nido genuinely livable for remote workers.', address: 'El Nido Town, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Nomads+Paradise+El+Nido', phone: '+63 917 345 6789', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/nomads-paradise-el-nido.jpg', tags: ['coliving', 'coworking', 'monthly', 'island-hopping', 'community'] },
  { name: 'Remote Year El Nido Hub', slug: 'remote-year-hub-el-nido', category: 'COWORKING', description: 'A workspace created by the Remote Year community during their Palawan programming, with ergonomic desks, reliable fiber, and a curated calendar of professional workshops and island excursions. Available to non-Remote Year members during off-program months at day and week rates.', address: 'El Nido, Palawan 5313, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Remote+Year+Hub+El+Nido', phone: '+63 917 456 7890', website: null, priceRange: 'MID', rating: 4.3, imageUrl: '/spots/remote-year-hub-el-nido.jpg', tags: ['remote-year', 'workshops', 'fiber', 'professional', 'excursions'] },
  { name: 'Twin Lagoon Coron Day Trip El Nido', slug: 'twin-lagoon-coron-el-nido', category: 'NATURE', description: 'A day trip from El Nido to Coron\'s iconic Twin Lagoon - two connected lagoons with a natural rock wall between them, accessible by swimming through an underwater passage. The thermocline effect creating warm and cold water layers in the same lagoon is unlike anything else in the Philippines.', address: 'Coron, Palawan 5316, Philippines', googleMapsUrl: 'https://maps.google.com/?q=Twin+Lagoon+Coron+Palawan', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/twin-lagoon-coron-el-nido.jpg', tags: ['lagoon', 'coron', 'thermocline', 'swimming', 'day-trip'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('El Nido: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
