const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfmxl000lvimo7f1f5ri3';

const spots = [
  // ACCOMMODATION
  { name: 'Hotel Grande Bretagne', slug: 'hotel-grande-bretagne-athens', category: 'ACCOMMODATION', description: "Athens' grandest hotel since 1874 — a Neoclassical palace on Syntagma Square with a rooftop restaurant offering the most iconic Acropolis view in the city, a legendary spa, and a history of hosting every head of state, writer, and notable traveler who has passed through Greece. Churchill wrote part of his WWII memoirs here.", address: 'Vas. Georgiou A 1, Athens 105 64', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Grande+Bretagne+Athens', phone: '+30 21 0333 0000', website: 'https://www.grandebretagne.gr', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/hotel-grande-bretagne-athens.jpg', tags: ['luxury', 'syntagma', 'acropolis-view', 'rooftop', '1874'] },
  { name: 'New Hotel Athens', slug: 'new-hotel-athens', category: 'ACCOMMODATION', description: "The most design-forward hotel in Athens — a 1957 Olympic Palace Hotel reimagined by the Campana Brothers with sculptural furniture made from repurposed building materials, a lively rooftop bar, and a perfect central location on Filellinon Street.", address: 'Filellinon 16, Athens 105 57', googleMapsUrl: 'https://maps.google.com/?q=New+Hotel+Athens', phone: '+30 21 0327 3000', website: 'https://yeshotels.gr/new-hotel', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/new-hotel-athens.jpg', tags: ['design', 'campana-brothers', 'rooftop', 'sculptural', 'central'] },
  { name: 'Herodion Hotel', slug: 'herodion-hotel-athens', category: 'ACCOMMODATION', description: "A stylish 4-star hotel at the foot of the Acropolis in Makrygianni, with a rooftop terrace where breakfast is served against an unobstructed view of the Parthenon. The best location for exploring the Acropolis and Plaka at a sensible price.", address: 'Rovertou Galli 4, Athens 117 42', googleMapsUrl: 'https://maps.google.com/?q=Herodion+Hotel+Athens', phone: '+30 21 0923 6832', website: 'https://www.herodion.gr', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/herodion-hotel-athens.jpg', tags: ['acropolis-view', 'rooftop-breakfast', 'makrygianni', 'mid-range', 'location'] },
  { name: 'Athens Backpackers', slug: 'athens-backpackers', category: 'ACCOMMODATION', description: "The best hostel in Greece — a rooftop bar with a direct view of the Acropolis lit up at night, an excellent social program, and a central location in Monastiraki. Athens Backpackers has been the meeting point for solo travelers in Greece since 2000.", address: 'Makri 12, Athens 117 42', googleMapsUrl: 'https://maps.google.com/?q=Athens+Backpackers', phone: '+30 21 0922 4044', website: 'https://www.athensbackpackers.gr', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/athens-backpackers.jpg', tags: ['hostel', 'acropolis-view', 'rooftop', 'social', 'monastiraki'] },
  { name: 'CityZen Hotel Athens', slug: 'cityzen-hotel-athens', category: 'ACCOMMODATION', description: "A budget-friendly design hotel in the Metaxourgeio arts district with individually decorated rooms, a strong local food program, and excellent community connections. The neighborhood itself is the attraction — Athens' most creatively interesting district is happening right outside the door.", address: 'Achilleos 22, Athens 104 36', googleMapsUrl: 'https://maps.google.com/?q=CityZen+Hotel+Athens', phone: '+30 21 0523 2045', website: 'https://cityzenhotel.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/cityzen-hotel-athens.jpg', tags: ['metaxourgeio', 'arts', 'budget', 'local', 'design'] },
  // CAFES
  { name: 'Taf Coffee Athens', slug: 'taf-coffee-athens', category: 'CAFE', description: "Greece's most celebrated specialty coffee roastery — a sleek Monastiraki bar that set the standard for third-wave coffee in Athens. Rotating single-origin filter and espresso, cold brew, and the best coffee education in the city. The Athens coffee renaissance started here.", address: 'Emporikón 7, Athens 105 55', googleMapsUrl: 'https://maps.google.com/?q=Taf+Coffee+Athens', phone: '+30 21 0323 0994', website: 'https://www.tafcoffee.gr', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/taf-coffee-athens.jpg', tags: ['specialty', 'roaster', 'single-origin', 'monastiraki', 'pioneering'] },
  { name: 'Mokka Coffee Athens', slug: 'mokka-coffee-athens', category: 'CAFE', description: "A neighborhood café-bar in Exarcheia beloved by students, anarchists, and everyone in between, with strong Greek coffee, cheap beer, and a terrace that overlooks the most politically charged square in Athens. The quintessential Exarcheia experience.", address: 'Themistokleous 48, Athens 106 78', googleMapsUrl: 'https://maps.google.com/?q=Mokka+Coffee+Athens', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/mokka-coffee-athens.jpg', tags: ['cafe', 'exarcheia', 'students', 'terrace', 'neighborhood'] },
  { name: 'Little Tree Books & Coffee', slug: 'little-tree-books-coffee-athens', category: 'CAFE', description: "A beautiful bookshop-café in Kolonaki with floor-to-ceiling bookshelves, exceptional specialty coffee, and an avocado toast that consistently wins best-breakfast rankings. The perfect place to plan a day of Athens exploration.", address: 'Skoufa 2, Athens 106 73', googleMapsUrl: 'https://maps.google.com/?q=Little+Tree+Books+Coffee+Athens', phone: '+30 21 0364 1918', website: 'https://www.littletree.gr', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/little-tree-books-coffee-athens.jpg', tags: ['bookshop-cafe', 'specialty', 'kolonaki', 'avocado-toast', 'charming'] },
  // FOOD
  { name: 'Diporto Agoras', slug: 'diporto-agoras-athens', category: 'FOOD', description: "A legendary underground taverna near the Central Market with no menu, no sign, and no written prices — the owner simply brings whatever was cooked that day. Revithia (chickpea soup), grilled fish, and house wine from the barrel. The most authentic lunch in Athens.", address: 'Sokratous 9, Athens 105 52', googleMapsUrl: 'https://maps.google.com/?q=Diporto+Agoras+Athens', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/diporto-agoras-athens.jpg', tags: ['taverna', 'legendary', 'no-menu', 'authentic', 'lunch'] },
  { name: 'Monastiraki Flea Market', slug: 'monastiraki-flea-market-athens', category: 'FOOD', description: "Athens' most vibrant market district — Avyssinias Square fills with antique dealers, vintage vinyl, icons, and curiosities every Sunday morning. The surrounding streets host gyros stalls, souvlaki joints, and spice shops. Arrive hungry and leave having found something you didn't know you needed.", address: 'Plateía Avyssinías, Athens 105 55', googleMapsUrl: 'https://maps.google.com/?q=Monastiraki+Flea+Market+Athens', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/monastiraki-flea-market-athens.jpg', tags: ['flea-market', 'antiques', 'sunday', 'souvlaki', 'monastiraki'] },
  { name: 'Vezene Restaurant', slug: 'vezene-athens', category: 'FOOD', description: "The finest modern Greek restaurant in Athens — a sleek Kolonaki space where chef Elias Mamalakis reinterprets traditional Greek recipes with seasonal produce and exceptional presentation. The mezze progression is the best way to eat here; the natural Greek wine list is extraordinary.", address: 'Valaoritou 15, Athens 106 71', googleMapsUrl: 'https://maps.google.com/?q=Vezene+Athens', phone: '+30 21 0361 7312', website: 'https://www.vezene.gr', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/vezene-athens.jpg', tags: ['modern-greek', 'mezze', 'natural-wine', 'kolonaki', 'fine-dining'] },
  { name: 'Varvakios Central Market', slug: 'varvakios-central-market-athens', category: 'FOOD', description: "Athens' central covered market — a 19th-century iron-and-glass hall full of fishmongers, butchers, and produce vendors who have served the city since 1880. The atmosphere is theatrical, the freshness is extraordinary, and the souvlaki stall outside produces the best skewer in the city at 7am.", address: 'Athinas 42, Athens 105 51', googleMapsUrl: 'https://maps.google.com/?q=Varvakios+Central+Market+Athens', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/varvakios-central-market-athens.jpg', tags: ['market', 'fish', 'meat', '1880', 'early-morning'] },
  // CULTURE
  { name: 'Acropolis of Athens', slug: 'acropolis-athens', category: 'CULTURE', description: "The most important ancient monument in the Western world — a rocky plateau 156 meters above Athens bearing the Parthenon, the Erechtheion, and the Temple of Athena Nike. The view from the top over modern Athens is extraordinary. Buy tickets online; visit at opening time (8am) to beat the crowds.", address: 'Acropolis, Athens 105 58', googleMapsUrl: 'https://maps.google.com/?q=Acropolis+Athens', phone: '+30 21 0321 0219', website: 'https://www.theacropolismuseum.gr', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/acropolis-athens.jpg', tags: ['ancient', 'parthenon', 'must-see', 'visit-early', 'iconic'] },
  { name: 'Acropolis Museum', slug: 'acropolis-museum-athens', category: 'CULTURE', description: "One of the world's great modern museums — a glass-and-concrete Acropolis-aligned building housing the finest sculpture from the ancient monument, with the Parthenon Gallery on the top floor aligned exactly with the temple visible through the glass above. The Caryatid hall is one of the most moving rooms in European museum architecture.", address: 'Dionysiou Areopagitou 15, Athens 117 42', googleMapsUrl: 'https://maps.google.com/?q=Acropolis+Museum+Athens', phone: '+30 21 0900 0900', website: 'https://www.theacropolismuseum.gr', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/acropolis-museum-athens.jpg', tags: ['museum', 'parthenon-marbles', 'caryatids', 'modern-architecture', 'essential'] },
  { name: 'Ancient Agora of Athens', slug: 'ancient-agora-athens', category: 'CULTURE', description: "The civic heart of ancient Athens — the marketplace, meeting place, and democratic assembly ground where Socrates, Plato, and St. Paul all walked. The remarkably well-preserved Stoa of Attalos houses the Agora museum. Far less crowded than the Acropolis; often more evocative.", address: 'Adrianou 24, Athens 105 55', googleMapsUrl: 'https://maps.google.com/?q=Ancient+Agora+Athens', phone: '+30 21 0321 0185', website: 'https://www.ascsa.edu.gr/agora', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/ancient-agora-athens.jpg', tags: ['ancient', 'socrates', 'stoa', 'museum', 'less-crowded'] },
  { name: 'National Archaeological Museum', slug: 'national-archaeological-museum-athens', category: 'CULTURE', description: "The greatest collection of ancient Greek art in the world — the gold Mask of Agamemnon, the bronze Artemision Jockey, Akrotiri frescoes, and over 11,000 objects spanning human history from prehistoric to Roman. The Antikythera Mechanism is displayed here. Allow 3 hours minimum.", address: 'Patission 44, Athens 106 82', googleMapsUrl: 'https://maps.google.com/?q=National+Archaeological+Museum+Athens', phone: '+30 21 3214 4800', website: 'https://www.namuseum.gr', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/national-archaeological-museum-athens.jpg', tags: ['museum', 'mask-of-agamemnon', 'antikythera', 'world-class', 'essential'] },
  { name: 'Monastiraki Neighborhood', slug: 'monastiraki-athens', category: 'CULTURE', description: "Athens' most vibrant historic neighborhood — a maze of Byzantine churches, Ottoman mosque, Roman Agora ruins, and narrow streets full of street food vendors, vinyl shops, and rooftop bars. The view of the Acropolis from Monastiraki Square is the most reproduced image of modern Athens.", address: 'Monastiraki, Athens 105 55', googleMapsUrl: 'https://maps.google.com/?q=Monastiraki+Athens', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/monastiraki-athens.jpg', tags: ['neighborhood', 'byzantine', 'ottoman', 'roman', 'acropolis-view'] },
  { name: 'Syntagma Square & Parliament', slug: 'syntagma-square-athens', category: 'CULTURE', description: "The central square of modern Athens — the Hellenic Parliament in the former Royal Palace faces a square where the Evzone guards perform the ceremonial changing of the guard every Sunday at 11am in their elaborate traditional uniforms. The Tomb of the Unknown Soldier is directly below.", address: 'Plateia Syntagmatos, Athens 105 57', googleMapsUrl: 'https://maps.google.com/?q=Syntagma+Square+Athens', phone: null, website: null, priceRange: 'FREE', rating: 4.4, imageUrl: '/spots/syntagma-square-athens.jpg', tags: ['parliament', 'evzones', 'changing-of-guard', 'central', 'sunday'] },
  // COWORKING
  { name: 'The Cube Athens', slug: 'the-cube-athens', category: 'COWORKING', description: "Athens' leading coworking space and startup hub in Chalandri — a 3,000m² campus for Greece's most active tech community, with coworking floors, a dedicated accelerator, and regular demo days and investor meetups.", address: 'Athinodoros 8, Chalandri 152 33', googleMapsUrl: 'https://maps.google.com/?q=The+Cube+Athens', phone: '+30 21 0685 4474', website: 'https://www.thecube.gr', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/the-cube-athens.jpg', tags: ['coworking', 'startup', 'accelerator', 'chalandri', 'tech'] },
  { name: 'Synergy Coworking Athens', slug: 'synergy-coworking-athens', category: 'COWORKING', description: "A central, well-equipped coworking space in the heart of Athens near Omonia Square with day passes, dedicated desks, private offices, and a strong base of freelancers, digital nomads, and small startups. Good natural light and reliable gigabit internet.", address: 'Patission 39, Athens 104 34', googleMapsUrl: 'https://maps.google.com/?q=Synergy+Coworking+Athens', phone: '+30 21 0825 8770', website: 'https://www.synergy.gr', priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/synergy-coworking-athens.jpg', tags: ['coworking', 'central', 'day-pass', 'affordable', 'omonia'] },
  // NATURE
  { name: 'Athens Riviera Walk', slug: 'athens-riviera', category: 'NATURE', description: "The tram line from Syntagma to Glyfada opens up 20km of Athenian Riviera — a succession of open-air seawater pools, beach clubs, and seafront promenades. Vouliagmeni lake (fed by thermal springs) is a highlight. The entire coast is accessible by public tram for under €2.", address: 'Poseidonos, Glyfada 166 74', googleMapsUrl: 'https://maps.google.com/?q=Athens+Riviera', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/athens-riviera.jpg', tags: ['beach', 'riviera', 'tram', 'swimming', 'thermal-lake'] },
  { name: 'Lycabettus Hill', slug: 'lycabettus-hill-athens', category: 'NATURE', description: "The highest point in Athens — a 277-meter limestone peak topped with a 19th-century chapel offering a 360° panoramic view of the entire city, the Acropolis, Piraeus port, and the Saronic Gulf. Take the funicular or hike up through the pine forest. The sunset view is the finest in Athens.", address: 'Lycabettus, Athens 114 72', googleMapsUrl: 'https://maps.google.com/?q=Lycabettus+Hill+Athens', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/lycabettus-hill-athens.jpg', tags: ['hilltop', 'panoramic', 'sunset', 'funicular', 'chapel'] },
  // WELLNESS + NIGHTLIFE
  { name: 'Hammam Baths Athens', slug: 'hammam-baths-athens', category: 'WELLNESS', description: "A traditional Ottoman hammam experience in a restored 17th-century bathhouse in Monastiraki — steam rooms, hot marble slabs, and a genuine scrub and soap massage in one of the most beautiful historic interiors in Athens. Book in advance; sessions fill quickly.", address: 'Agion Asomaton 8, Athens 105 53', googleMapsUrl: 'https://maps.google.com/?q=Hammam+Baths+Athens', phone: '+30 21 0325 1073', website: 'https://www.hammamahtina.gr', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/hammam-baths-athens.jpg', tags: ['hammam', 'ottoman', '17th-century', 'steam', 'wellness'] },
  { name: 'Six D.O.G.S Athens', slug: 'six-dogs-athens', category: 'NIGHTLIFE', description: "Athens' most beloved multi-purpose cultural space in Monastiraki — a garden bar, art gallery, music venue, and concept store all in one. Six D.O.G.S is the heartbeat of alternative Athens: packed summer garden, eclectic events, and the most mixed, interesting crowd in the city.", address: 'Avramiótou 6-8, Athens 105 51', googleMapsUrl: 'https://maps.google.com/?q=Six+Dogs+Athens', phone: '+30 21 0321 0510', website: 'https://sixdogs.gr', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/six-dogs-athens.jpg', tags: ['garden-bar', 'gallery', 'music', 'alternative', 'eclectic'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Athens: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
