const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfoxe000rvimo7m4336of';

const spots = [
  // ACCOMMODATION
  { name: 'The Yeatman Hotel Porto', slug: 'the-yeatman-hotel-porto', category: 'ACCOMMODATION', description: "Porto's finest hotel — a wine hotel perched on the hillside of Vila Nova de Gaia opposite the city, with infinity pool views over the Douro River and Ribeira, two Michelin stars in the restaurant, and the most comprehensive cellar of Portuguese wine anywhere on Earth. The view at sunset is worth the splurge.", address: 'Rua do Choupelo 88, 4400-088 Vila Nova de Gaia', googleMapsUrl: 'https://maps.google.com/?q=The+Yeatman+Hotel+Porto', phone: '+351 22 013 3100', website: 'https://www.the-yeatman-hotel.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/the-yeatman-hotel-porto.jpg', tags: ['luxury', 'wine-hotel', 'douro-view', 'michelin', 'infinity-pool'] },
  { name: 'Torel Palace Porto', slug: 'torel-palace-porto', category: 'ACCOMMODATION', description: "A 19th-century palace converted to a boutique hotel in the historic Cedofeita neighborhood, with a rooftop pool, individually decorated rooms, and views over the city's terracotta roofscape. The most atmospheric mid-luxury option in the city center.", address: 'Rua do Heroísmo 133, 4300-259 Porto', googleMapsUrl: 'https://maps.google.com/?q=Torel+Palace+Porto', phone: '+351 22 040 2000', website: 'https://www.torelpalace.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/torel-palace-porto.jpg', tags: ['palace', 'rooftop-pool', 'historic', 'cedofeita', 'views'] },
  { name: 'Gallery Hostel Porto', slug: 'gallery-hostel-porto', category: 'ACCOMMODATION', description: "Europe's most award-winning hostel — a 19th-century townhouse in the Bonfim neighborhood with rotating art exhibitions in every room, an excellent restaurant, weekly gallery openings, and a community of travelers who keep coming back. Gallery Hostel has consistently been named the world's best hostel.", address: 'Rua de Miguel Bombarda 222, 4050-379 Porto', googleMapsUrl: 'https://maps.google.com/?q=Gallery+Hostel+Porto', phone: '+351 22 096 4313', website: 'https://www.gallery-hostel.com', priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/gallery-hostel-porto.jpg', tags: ['hostel', 'art', 'award-winning', 'world-best', 'gallery'] },
  { name: 'Casa do Conto Porto', slug: 'casa-do-conto-porto', category: 'ACCOMMODATION', description: "An architectural boutique hotel in a restored 19th-century house near the Clérigos Tower, where each room is a different design statement and the common areas function as an ongoing contemporary art exhibition. One of the most intellectually stimulating places to stay in Portugal.", address: 'Rua da Boavista 703, 4050-112 Porto', googleMapsUrl: 'https://maps.google.com/?q=Casa+do+Conto+Porto', phone: '+351 22 209 6160', website: 'https://www.casadoconto.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/casa-do-conto-porto.jpg', tags: ['boutique', 'art', 'design', 'clerigos', 'intellectual'] },
  { name: 'Porto River Hotel', slug: 'porto-river-hotel', category: 'ACCOMMODATION', description: "A stylish mid-range hotel on the Ribeira waterfront with direct Douro views, clean modern rooms, a rooftop terrace, and the city's best neighbourhood on its doorstep. The Ribeira waterfront is Porto's most atmospheric address.", address: 'Rua do Infante D. Henrique 1, 4050-297 Porto', googleMapsUrl: 'https://maps.google.com/?q=Porto+River+Hotel', phone: '+351 22 096 0040', website: 'https://www.portorivernhotel.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/porto-river-hotel.jpg', tags: ['douro-view', 'ribeira', 'rooftop', 'waterfront', 'mid-range'] },
  // CAFES
  { name: 'Combi Coffee Porto', slug: 'combi-coffee-porto', category: 'CAFE', description: "Porto's best specialty coffee bar — a sun-filled corner space in Bonfim with a serious filter program, exceptional espresso, and house-baked pastries that sell out by noon. The neighborhood and the coffee are both worth the walk from the historic center.", address: 'Rua de Cesário Verde 9, 4300-064 Porto', googleMapsUrl: 'https://maps.google.com/?q=Combi+Coffee+Porto', phone: null, website: 'https://www.combi.coffee', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/combi-coffee-porto.jpg', tags: ['specialty', 'filter', 'bonfim', 'pastries', 'sunny'] },
  { name: 'Flor dos Congregados', slug: 'flor-dos-congregados-porto', category: 'CAFE', description: "Porto's most beloved traditional café — a narrow tiled interior near the Cathedral with marble counters, strong bicas (espresso), and the best pastéis de nata in the city. The waiters are older than the furniture; the prices haven't changed since 1982.", address: 'Travessa dos Congregados 11, 4000-086 Porto', googleMapsUrl: 'https://maps.google.com/?q=Flor+dos+Congregados+Porto', phone: '+351 22 200 0863', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/flor-dos-congregados-porto.jpg', tags: ['traditional', 'pastel-de-nata', 'tiled', 'espresso', 'unchanged'] },
  { name: 'Moustache Porto', slug: 'moustache-porto', category: 'CAFE', description: "A hugely popular café-restaurant in Cedofeita with a beautiful tiled interior, excellent brunch, creative cocktails, and one of the best terraces on the street. The weekend brunch queue is long — arrive at opening or book ahead.", address: 'Rua do Rosário 264, 4050-518 Porto', googleMapsUrl: 'https://maps.google.com/?q=Moustache+Porto', phone: '+351 22 206 0222', website: 'https://www.moustache.com.pt', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/moustache-porto.jpg', tags: ['brunch', 'tiled', 'terrace', 'cedofeita', 'cocktails'] },
  // FOOD
  { name: 'Mercado do Bolhão', slug: 'mercado-do-bolhao-porto', category: 'FOOD', description: "Porto's 1914 Neo-Renaissance iron-and-stone covered market, beautifully restored and returned to its original glory — fishmongers, butchers, cheesemakers, and flower sellers in a soaring two-level arcade. The most beautiful market building in Portugal.", address: 'Rua Formosa 322, 4000-252 Porto', googleMapsUrl: 'https://maps.google.com/?q=Mercado+do+Bolhao+Porto', phone: '+351 22 332 6024', website: 'https://www.mercadobolhao.pt', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/mercado-do-bolhao-porto.jpg', tags: ['market', '1914', 'iron-architecture', 'fish', 'restored'] },
  { name: 'Cantinho do Avillez Porto', slug: 'cantinho-do-avillez-porto', category: 'FOOD', description: "José Avillez's Porto outpost — a bistro version of Portugal's most famous chef's cooking, with petiscos (Portuguese tapas), excellent seafood rice, and the city's finest bifanas (pork sandwiches) in a relaxed, beautiful space in the Cedofeita Cultural Corridor.", address: 'Rua de Mouzinho da Silveira 166, 4050-418 Porto', googleMapsUrl: 'https://maps.google.com/?q=Cantinho+do+Avillez+Porto', phone: '+351 22 322 7879', website: 'https://www.cantinhodoavillez.pt', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/cantinho-do-avillez-porto.jpg', tags: ['jose-avillez', 'petiscos', 'seafood', 'cedofeita', 'bistro'] },
  { name: 'Taberna dos Mercadores', slug: 'taberna-dos-mercadores-porto', category: 'FOOD', description: "The best traditional Portuguese restaurant in the Ribeira — a narrow stone-walled tavern with small tables, a chalkboard menu, and cooking that celebrates cod, pork, and Portuguese wine with genuine skill and no pretension. The bacalhau à brás and the baked goat rice are both extraordinary.", address: 'Rua dos Mercadores 36, 4050-374 Porto', googleMapsUrl: 'https://maps.google.com/?q=Taberna+dos+Mercadores+Porto', phone: '+351 22 010 0340', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/taberna-dos-mercadores-porto.jpg', tags: ['traditional', 'cod', 'ribeira', 'stone-walls', 'chalkboard-menu'] },
  // CULTURE
  { name: 'Dom Luís I Bridge', slug: 'dom-luis-i-bridge-porto', category: 'CULTURE', description: "Porto's most iconic structure — a double-deck iron arch bridge designed by a disciple of Gustave Eiffel and completed in 1886. The upper deck (pedestrian) connects Porto directly to the port wine lodges of Gaia; the view from the deck at sunset is one of Europe's finest urban panoramas.", address: 'Ponte Luís I, 4000-117 Porto', googleMapsUrl: 'https://maps.google.com/?q=Dom+Luis+I+Bridge+Porto', phone: null, website: null, priceRange: 'FREE', rating: 4.8, imageUrl: '/spots/dom-luis-i-bridge-porto.jpg', tags: ['bridge', 'iron', 'eiffel', 'sunset-views', 'iconic'] },
  { name: 'Livraria Lello', slug: 'livraria-lello-porto', category: 'CULTURE', description: "The most beautiful bookshop in the world — a 1906 Neo-Gothic library that inspired J.K. Rowling's Hogwarts library with its crimson staircase, stained glass ceiling, and carved wooden shelves. Book a timed ticket online; the €8 entry fee is redeemable against a purchase.", address: 'Rua das Carmelitas 144, 4050-161 Porto', googleMapsUrl: 'https://maps.google.com/?q=Livraria+Lello+Porto', phone: '+351 22 200 2037', website: 'https://www.livrarialello.pt', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/livraria-lello-porto.jpg', tags: ['bookshop', '1906', 'gothic', 'rowling', 'stained-glass'] },
  { name: 'Clérigos Church & Tower', slug: 'clerigos-church-porto', category: 'CULTURE', description: "Porto's most distinctive skyline landmark — an 18th-century Baroque church by Nicolau Nasoni with a 75-meter tower that served as the tallest building in Portugal for over 200 years. The 225-step climb to the top provides the finest bird's-eye view over the city's roofscape.", address: 'Rua de São Filipe de Nery, 4050-546 Porto', googleMapsUrl: 'https://maps.google.com/?q=Clerigos+Church+Porto', phone: '+351 22 014 5489', website: 'https://www.torredosclerigos.pt', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/clerigos-church-porto.jpg', tags: ['baroque', 'tower', 'nasoni', 'views', 'landmark'] },
  { name: 'Porto Cathedral (Sé)', slug: 'porto-cathedral', category: 'CULTURE', description: "Porto's oldest monument — a Romanesque fortress-cathedral begun in the 12th century with a Gothic rose window, a beautiful 14th-century cloister lined with azulejo tiles, and sweeping views over the city from its elevated position. The cloister alone justifies the entry fee.", address: 'Terreiro da Sé, 4050-573 Porto', googleMapsUrl: 'https://maps.google.com/?q=Porto+Cathedral', phone: '+351 22 205 9028', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/porto-cathedral.jpg', tags: ['romanesque', 'cathedral', 'cloister', 'azulejos', '12th-century'] },
  { name: 'Ribeira Quarter Porto', slug: 'ribeira-porto', category: 'CULTURE', description: "UNESCO-listed waterfront district and Porto's most atmospheric neighborhood — layers of medieval, Baroque, and 19th-century architecture stacked up the steep hillside from the river's edge. Colorful laundry between the buildings, tile-covered facades, and the smell of grilled sardines define the Ribeira experience.", address: 'Ribeira, 4050-518 Porto', googleMapsUrl: 'https://maps.google.com/?q=Ribeira+Porto', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/ribeira-porto.jpg', tags: ['unesco', 'waterfront', 'medieval', 'atmosphere', 'sardines'] },
  { name: 'Palácio da Bolsa', slug: 'palacio-da-bolsa-porto', category: 'CULTURE', description: "Porto's 19th-century stock exchange palace — the centerpiece is the Arab Room, a Moorish Revival reception hall gilded with 18kg of gold leaf, considered the finest interior in Portugal. Guided tours run every 30 minutes; the Arab Room is genuinely one of the most extraordinary rooms in Europe.", address: 'Rua de Ferreira Borges, 4050-253 Porto', googleMapsUrl: 'https://maps.google.com/?q=Palacio+da+Bolsa+Porto', phone: '+351 22 339 9000', website: 'https://www.palaciodabolsa.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/palacio-da-bolsa-porto.jpg', tags: ['stock-exchange', 'arab-room', 'gold-leaf', 'moorish', 'must-see'] },
  // PORT WINE
  { name: 'Graham\'s Port Wine Lodge', slug: 'grahams-port-lodge-porto', category: 'CULTURE', description: "The most atmospheric of the port wine lodges on the Gaia hillside — a 200-year-old lodge with ancient wooden casks, tasting rooms, a terrace with the best view of Porto's Ribeira, and an excellent wine museum. The tasting of Tawny and Vintage ports is the definitive Porto experience.", address: 'Rua do Agro 141, 4400-281 Vila Nova de Gaia', googleMapsUrl: 'https://maps.google.com/?q=Grahams+Port+Lodge+Porto', phone: '+351 22 377 6484', website: 'https://www.grahams-port.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/grahams-port-lodge-porto.jpg', tags: ['port-wine', 'lodge', 'tasting', 'gaia', 'douro-views'] },
  // COWORKING
  { name: 'Cowork Porto', slug: 'cowork-porto', category: 'COWORKING', description: "Porto's best-established coworking space in the Bonfim neighborhood — a 1,200m² former warehouse with excellent natural light, a large terrace, reliable gigabit internet, and a member community of Porto's most interesting startups and freelancers.", address: 'Rua de Brito Capelo 480, 4450-069 Matosinhos', googleMapsUrl: 'https://maps.google.com/?q=Cowork+Porto', phone: '+351 22 937 2614', website: 'https://www.coworkporto.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/cowork-porto.jpg', tags: ['coworking', 'warehouse', 'terrace', 'gigabit', 'community'] },
  { name: 'Heden Porto', slug: 'heden-porto', category: 'COWORKING', description: "A premium coworking space in the Cedofeita Cultural Corridor with a curated member base, excellent amenities, private offices, and a ground-floor café open to the public. The most aesthetically impressive work space in the city.", address: 'Rua de Miguel Bombarda 285, 4050-379 Porto', googleMapsUrl: 'https://maps.google.com/?q=Heden+Porto', phone: '+351 22 010 1320', website: 'https://www.heden.pt', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/heden-porto.jpg', tags: ['premium', 'cedofeita', 'private-offices', 'café', 'design'] },
  // NATURE / WELLNESS
  { name: 'Foz do Douro Beach', slug: 'foz-do-douro-porto', category: 'NATURE', description: "Where the Douro River meets the Atlantic — a 30-minute tram ride from the center brings you to the seafront promenade, tidal pools, and Atlantic beaches of Foz. The most pleasant afternoon escape from Porto's narrow streets, with excellent seafood restaurants along the waterfront.", address: 'Foz do Douro, 4150 Porto', googleMapsUrl: 'https://maps.google.com/?q=Foz+do+Douro+Porto', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/foz-do-douro-porto.jpg', tags: ['beach', 'atlantic', 'tram', 'seafront', 'tidal-pools'] },
  { name: 'Crystal Palace Gardens', slug: 'crystal-palace-gardens-porto', category: 'NATURE', description: "Porto's finest viewpoint park — formal gardens surrounding a domed events pavilion with sweeping views over the Douro River and the Serra do Pilar monastery on the opposite bank. Peacocks wander freely; the rose garden is magnificent in spring.", address: 'Rua Dom Manuel II, 4050-346 Porto', googleMapsUrl: 'https://maps.google.com/?q=Crystal+Palace+Gardens+Porto', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/crystal-palace-gardens-porto.jpg', tags: ['gardens', 'douro-views', 'peacocks', 'roses', 'panoramic'] },
  { name: 'Serralves Museum of Contemporary Art', slug: 'serralves-museum-porto', category: 'CULTURE', description: "Portugal's most important contemporary art museum — a spectacular pink Art Deco villa surrounded by 18 hectares of gardens, with a striking new building by Álvaro Siza Vieira that holds the permanent collection of international and Portuguese contemporary art. The gardens alone justify the visit.", address: 'Rua Dom João de Castro 210, 4150-417 Porto', googleMapsUrl: 'https://maps.google.com/?q=Serralves+Museum+Porto', phone: '+351 22 615 6500', website: 'https://www.serralves.pt', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/serralves-museum-porto.jpg', tags: ['contemporary-art', 'siza-vieira', 'gardens', 'art-deco', 'museum'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Porto: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
