const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328bdo0007vi8w1595uibr';

const spots = [
  // LUXURY HOTELS
  { name: 'Mandarin Oriental Bangkok', slug: 'mandarin-oriental-bangkok', category: 'ACCOMMODATION', description: "The grande dame of Southeast Asian hotels, operating since 1876 on the banks of the Chao Phraya River. Two wings of colonial elegance, an award-winning spa, and impeccable service that has hosted every notable traveler from Joseph Conrad to David Bowie.", address: '48 Oriental Avenue, Bang Rak, Bangkok 10500, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mandarin+Oriental+Bangkok', phone: '+66 2 659 9000', website: 'https://www.mandarinoriental.com/bangkok', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/mandarin-oriental-bangkok.jpg', tags: ['luxury', 'riverside', 'historic', 'spa', 'iconic'] },
  { name: 'The Peninsula Bangkok', slug: 'the-peninsula-bangkok', category: 'ACCOMMODATION', description: "Perched on the Chao Phraya's west bank with a three-tiered pool cascading toward the river, the Peninsula delivers Bangkok's most spectacular river views. Helicopter transfers, a fleet of longtail boats, and the city's best afternoon tea complete the picture.", address: '333 Charoennakorn Road, Khlong San, Bangkok 10600, Thailand', googleMapsUrl: 'https://maps.google.com/?q=The+Peninsula+Bangkok', phone: '+66 2 020 2888', website: 'https://www.peninsula.com/bangkok', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/the-peninsula-bangkok.jpg', tags: ['luxury', 'riverside', 'pool', 'spa', 'views'] },
  { name: 'Capella Bangkok', slug: 'capella-bangkok', category: 'ACCOMMODATION', description: "A discreet riverside sanctuary with just 101 suites and villas, all with private balconies facing the river. Capella Bangkok blends Thai craftsmanship with contemporary design - teak screens, silk cushions, and hand-laid mosaic pools. Consistently voted best hotel in Thailand.", address: '300-304 Charoenkrung Road, Bang Rak, Bangkok 10500, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Capella+Bangkok', phone: '+66 2 098 3888', website: 'https://www.capellahotels.com/bangkok', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/capella-bangkok.jpg', tags: ['luxury', 'riverside', 'boutique', 'design', 'suites'] },
  { name: 'Rosewood Bangkok', slug: 'rosewood-bangkok', category: 'ACCOMMODATION', description: "A 30-storey tower in the heart of the central business district combining residential luxury with cutting-edge Thai design. The rooftop bar at 30 floors has panoramic skyline views, and the 5-star spa is Bangkok's most talked-about wellness retreat.", address: '1041/38 Ploenchit Road, Lumphini, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Rosewood+Bangkok', phone: '+66 2 080 0088', website: 'https://www.rosewoodhotels.com/bangkok', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/rosewood-bangkok.jpg', tags: ['luxury', 'skyline', 'rooftop', 'spa', 'business'] },
  // BUDGET HOTELS
  { name: 'Lub d Bangkok Siam', slug: 'lub-d-bangkok-siam', category: 'ACCOMMODATION', description: "Bangkok's sleekest design hostel-hotel hybrid, right next to Siam BTS. Lub d delivers hotel-quality private rooms at budget prices with a rooftop bar, co-working space, and the city's most stylish common areas. The social events calendar is packed every week.", address: '925/9 Rama 1 Road, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Lub+d+Bangkok+Siam', phone: '+66 2 612 4999', website: 'https://www.lubd.com/bangkok-siam', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/lub-d-bangkok-siam.jpg', tags: ['design', 'siam', 'rooftop', 'bts', 'social'] },
  { name: 'The Yard Hostel Bangkok', slug: 'the-yard-hostel-bangkok', category: 'ACCOMMODATION', description: "A converted heritage shophouse in the creative Ari neighborhood with beautifully designed rooms and a garden courtyard. The Yard is everything a budget hotel should be - thoughtful design, fast wifi, great breakfast, and a vibe that makes you want to linger.", address: '51 Phahonyothin Road Soi 7, Phaya Thai, Bangkok 10400, Thailand', googleMapsUrl: 'https://maps.google.com/?q=The+Yard+Hostel+Bangkok', phone: '+66 2 617 9966', website: 'https://theyardhostel.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/the-yard-hostel-bangkok.jpg', tags: ['boutique', 'heritage', 'ari', 'garden', 'design'] },
  { name: 'Rambuttri Village Inn', slug: 'rambuttri-village-inn-bangkok', category: 'ACCOMMODATION', description: "Clean, well-managed budget hotel on Rambuttri Alley - the quieter, more charming extension of Khao San Road. Compact rooms with good AC, a rooftop pool that feels like a luxury bonus, and the classic backpacker atmosphere at your doorstep.", address: '95 Rambuttri Road, Banglamphu, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Rambuttri+Village+Inn+Bangkok', phone: '+66 2 282 9162', website: 'https://rambuttrivillage.com', priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/rambuttri-village-inn-bangkok.jpg', tags: ['budget', 'khao-san', 'pool', 'backpacker', 'central'] },
  { name: 'Sleep Whale Bangkok', slug: 'sleep-whale-bangkok', category: 'ACCOMMODATION', description: "An affordable boutique hotel in the trendy On Nut area, loved by digital nomads for its proximity to the BTS, fast wifi, and a cafe downstairs that doubles as a co-working space. Spotlessly clean with thoughtful design touches at a price that makes Bangkok very easy.", address: '29/1 Sukhumvit Soi 50, Phra Khanong, Bangkok 10260, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Sleep+Whale+Bangkok', phone: '+66 2 742 5566', website: 'https://sleepwhale.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/sleep-whale-bangkok.jpg', tags: ['boutique', 'on-nut', 'bts', 'nomad', 'clean'] },
  // HOSTELS
  { name: 'NapPark Hostel Bangkok', slug: 'nappark-hostel-bangkok', category: 'ACCOMMODATION', description: "Bangkok's most-loved hostel - an 11-storey heritage building off Khao San Road with pod-style bunks, an incredible rooftop terrace, and a community board full of travel-match opportunities. The social atmosphere here is why people extend their Bangkok stays by a week.", address: '5 Tanao Road, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=NapPark+Hostel+Bangkok', phone: '+66 2 282 2324', website: 'https://nappark.com', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/nappark-hostel-bangkok.jpg', tags: ['social', 'rooftop', 'khao-san', 'community', 'pods'] },
  { name: 'Slumber Party Bangkok', slug: 'slumber-party-bangkok', category: 'ACCOMMODATION', description: "A party-friendly hostel on Sukhumvit Soi 11 where the pool bar, nightly pub crawls, and resident DJ sets make it impossible to be lonely. For solo travelers who want Bangkok's nightlife handed to them on a plate, Slumber Party is the right call.", address: '4/1 Sukhumvit Soi 11, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Slumber+Party+Bangkok', phone: '+66 2 651 7380', website: 'https://slumberpartyhostel.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/slumber-party-bangkok.jpg', tags: ['party', 'nightlife', 'sukhumvit', 'pool', 'pub-crawl'] },
  { name: 'HQ Hostel Bangkok', slug: 'hq-hostel-bangkok', category: 'ACCOMMODATION', description: "A well-designed, quiet hostel near Khao San Road that attracts travelers who want the Banglamphu neighborhood without the Khao San chaos. Clean dorms with individual reading lights and curtains, solid lockers, and a calm rooftop to decompress on.", address: '68/2 Soi Rambutri, Chana Songkhram, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=HQ+Hostel+Bangkok', phone: '+66 2 629 4180', website: 'https://hqhostelbangkok.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/hq-hostel-bangkok.jpg', tags: ['quiet', 'khao-san', 'clean', 'boutique', 'pods'] },
  { name: 'Glur Bangkok Hostel', slug: 'glur-bangkok-hostel', category: 'ACCOMMODATION', description: "A design-forward hostel near the Democracy Monument with Insta-worthy interiors, private pod bunks, and a ground-floor cafe. Located in the cultural heart of the old city - Khao San Road, the Grand Palace, and Wat Pho are all walkable.", address: '90 Tanao Road, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Glur+Bangkok+Hostel', phone: '+66 2 622 3889', website: 'https://glurhostel.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/glur-bangkok-hostel.jpg', tags: ['design', 'pods', 'cafe', 'old-city', 'instagrammable'] },
  // CAFES
  { name: 'Broccoli Revolution', slug: 'broccoli-revolution-bangkok', category: 'CAFE', description: "Bangkok's most beloved healthy cafe - a bright, plant-filled space in the Sukhumvit area with the city's best smoothie bowls, vegan burgers, cold brew, and a community board connecting plant-based travelers. Full wifi, long tables, and a crowd of digital nomads most mornings.", address: '899 Sukhumvit Soi 49, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Broccoli+Revolution+Bangkok', phone: '+66 2 662 3500', website: 'https://broccolirevolution.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/broccoli-revolution-bangkok.jpg', tags: ['vegan', 'healthy', 'nomad', 'smoothie', 'sukhumvit'] },
  { name: 'Roots Coffee Roaster', slug: 'roots-coffee-roaster-bangkok', category: 'CAFE', description: "Bangkok's third-wave coffee pioneer and the cafe most frequented by the city's specialty-coffee community. Roots roasts in-house with Thai single-origin beans from Chiang Rai and Doi Chang, and their all-day menu has become a Bangkok institution.", address: '150 Sukhumvit Soi 51, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Roots+Coffee+Roaster+Bangkok', phone: '+66 92 472 0202', website: 'https://rootsbkk.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/roots-coffee-roaster-bangkok.jpg', tags: ['specialty', 'single-origin', 'roaster', 'thai-coffee'] },
  { name: 'Factory Coffee', slug: 'factory-coffee-bangkok', category: 'CAFE', description: "A pioneering specialty cafe in a converted warehouse in Silom that sparked Bangkok's third-wave coffee movement. Serious baristas, rotating guest roasters, and a minimalist industrial space that becomes a co-working hub for the city's creative class.", address: '4/1 Silom Soi 2, Bang Rak, Bangkok 10500, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Factory+Coffee+Bangkok', phone: '+66 81 834 1282', website: 'https://www.facebook.com/FactoryCoffeeBKK', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/factory-coffee-bangkok.jpg', tags: ['specialty', 'warehouse', 'silom', 'industrial', 'wifi'] },
  { name: 'Gaysorn Village Cafe', slug: 'gaysorn-village-cafe-bangkok', category: 'CAFE', description: "A serene cafe inside the leafy Gaysorn Village complex offering great espresso, light bites, and a respite from Ploenchit's shopping crowds. The jasmine tea service and Thai-inspired pastries make it a memorable mid-morning stop.", address: '999 Ploenchit Road, Lumphini, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Gaysorn+Village+Bangkok', phone: '+66 2 656 1149', website: 'https://gaysorn.com', priceRange: 'MID', rating: 4.4, imageUrl: '/spots/gaysorn-village-cafe-bangkok.jpg', tags: ['calm', 'ploenchit', 'bts', 'tea', 'pastries'] },
  { name: 'Ceresia Coffee Roasters', slug: 'ceresia-coffee-roasters-bangkok', category: 'CAFE', description: "A community-focused specialty roastery in the Phrom Phong area with a warm, welcoming atmosphere and some of the most consistent espresso in the city. Ceresia runs regular cupping events and coffee education sessions - great for coffee-curious solo travelers.", address: '98/4 Sukhumvit Soi 38, Phra Khanong, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Ceresia+Coffee+Roasters+Bangkok', phone: '+66 81 861 3688', website: 'https://www.ceresiacoffee.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/ceresia-coffee-roasters-bangkok.jpg', tags: ['specialty', 'community', 'cupping', 'education', 'roaster'] },
  { name: 'The Local Bangkok', slug: 'the-local-cafe-bangkok', category: 'CAFE', description: "A cozy, neighborhood cafe in the quieter Ekkamai area with excellent Northern Thai-style coffee drinks, homemade cakes, and the relaxed pace of old Bangkok. The covered terrace out back is the perfect spot to work for an afternoon.", address: '32/1 Ekkamai Soi 6, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=The+Local+Cafe+Ekkamai+Bangkok', phone: '+66 85 323 0506', website: 'https://www.facebook.com/thelocalcafebkk', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/the-local-cafe-bangkok.jpg', tags: ['neighborhood', 'ekkamai', 'terrace', 'relaxed', 'wifi'] },
  // RESTAURANTS
  { name: 'Nahm Restaurant', slug: 'nahm-restaurant-bangkok', category: 'FOOD', description: "David Thompson's legendary fine dining interpretation of ancient Thai recipes at the COMO Metropolitan. Nahm holds a consistent place on Asia's 50 Best list and challenges every assumption about Thai food with dishes pulled from 19th-century manuscripts.", address: 'COMO Metropolitan Bangkok, 27 South Sathorn Road, Bangkok 10120, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Nahm+Restaurant+Bangkok', phone: '+66 2 625 3388', website: 'https://comohotels.com/metropolitan-bangkok/dining/nahm', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/nahm-restaurant-bangkok.jpg', tags: ['fine-dining', 'thai', 'historic-recipes', 'asia-50-best'] },
  { name: 'Jeh O Chula', slug: 'jeh-o-chula-bangkok', category: 'FOOD', description: "A legendary late-night pork noodle joint near Chulalongkorn University that operates from midnight until it sells out - usually around 5am. The signature kuay tiew moo tom yen (cold pork noodles) has inspired queues of hours and pilgrimages from across Bangkok.", address: '113 Soi Charoenkrung 34, Bang Rak, Bangkok 10500, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Jeh+O+Chula+Bangkok', phone: '+66 2 221 4926', website: null, priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/jeh-o-chula-bangkok.jpg', tags: ['midnight', 'noodles', 'legendary', 'late-night', 'pork'] },
  { name: 'Or Tor Kor Market Restaurant Row', slug: 'or-tor-kor-market-bangkok', category: 'FOOD', description: "Bangkok's premium fresh market attached to Chatuchak Market has a restaurant row serving the finest versions of Thai classics - green papaya salad with blue crab, whole grilled river fish, northern-style sai ua sausage. The freshest ingredients in the city at market prices.", address: 'Kamphaeng Phet Road, Chatuchak, Bangkok 10900, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Or+Tor+Kor+Market+Bangkok', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/or-tor-kor-market-bangkok.jpg', tags: ['market', 'street-food', 'fresh', 'chatuchak', 'local'] },
  { name: 'Raan Jay Fai', slug: 'raan-jay-fai-bangkok', category: 'FOOD', description: "The world's most famous street food stall - Jay Fai earned a Michelin star while cooking in welding goggles over roaring charcoal flames. Her crab omelette and dry tom yum are extraordinary. Expect waits of 3-4 hours; book online far in advance.", address: '327 Mahachai Road, Samran Rat, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Raan+Jay+Fai+Bangkok', phone: '+66 2 223 9384', website: null, priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/raan-jay-fai-bangkok.jpg', tags: ['michelin', 'street-food', 'crab-omelette', 'legendary', 'booking-required'] },
  { name: 'Thipsamai Pad Thai', slug: 'thipsamai-pad-thai-bangkok', category: 'FOOD', description: "Since 1966, this Old City institution has been serving what many consider the definitive pad thai - wrapped in a thin egg omelette with fat river prawns, fresh bean sprouts, and chilli. The queues extend down the street every evening. No reservations; arrive early.", address: '313 Mahachai Road, Samran Rat, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Thipsamai+Pad+Thai+Bangkok', phone: '+66 2 221 6280', website: 'https://thipsamai.com', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/thipsamai-pad-thai-bangkok.jpg', tags: ['pad-thai', 'iconic', '1966', 'old-city', 'queue-worthy'] },
  { name: 'Gaggan Anand', slug: 'gaggan-anand-bangkok', category: 'FOOD', description: "Bangkok's most internationally acclaimed restaurant - Chef Gaggan Anand's progressive Indian tasting menu has held the No.1 spot in Asia's 50 Best for four consecutive years. An emoji menu, edible pictures, and theatrical courses make it the most talked-about dining experience in Asia.", address: '68/1 Soi Langsuan, Lumphini, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Gaggan+Anand+Bangkok', phone: '+66 2 652 1700', website: 'https://eatatgaggan.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/gaggan-anand-bangkok.jpg', tags: ['fine-dining', 'progressive', 'asia-50-best', 'tasting-menu', 'must-book'] },
  // MARKETS
  { name: 'Chatuchak Weekend Market', slug: 'chatuchak-weekend-market-bangkok', category: 'FOOD', description: "One of the world's largest markets with over 15,000 stalls covering 35 acres. Every Saturday and Sunday from 6am, Chatuchak sells everything from vintage clothing and antiques to live parrots and handmade ceramics. Wear comfortable shoes and arrive early.", address: 'Kamphaeng Phet 2 Road, Chatuchak, Bangkok 10900, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Chatuchak+Weekend+Market+Bangkok', phone: null, website: 'https://www.chatuchakmarket.org', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/chatuchak-weekend-market-bangkok.jpg', tags: ['weekend', 'massive', 'vintage', 'antiques', '15000-stalls'] },
  { name: 'Asiatique The Riverfront', slug: 'asiatique-riverfront-bangkok', category: 'FOOD', description: "An atmospheric open-air night market in converted 1900s dockside warehouses along the Chao Phraya River. Hundreds of boutiques, restaurants, and entertainment including the 60-meter Asiatique Sky Ferris wheel. Accessible by free ferry from Saphan Taksin BTS.", address: '2194 Charoenkrung Road, Wat Phraya Krai, Bang Kho Laem, Bangkok 10120, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Asiatique+Riverfront+Bangkok', phone: '+66 2 108 4488', website: 'https://www.theasiatique.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/asiatique-riverfront-bangkok.jpg', tags: ['night-market', 'riverside', 'warehouse', 'ferris-wheel', 'free-ferry'] },
  { name: 'Talad Rot Fai (Train Market)', slug: 'talad-rot-fai-bangkok', category: 'FOOD', description: "Bangkok's coolest vintage night market, held in a former rail yard near Ekkamai. Antique furniture, retro fashion, classic cars, and street food stalls under Edison lights. The Train Market at Ekkamai is more local and less tourist-heavy than the Srinakharin location.", address: 'Ekkamai Soi 2, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Talad+Rot+Fai+Ekkamai+Bangkok', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/talad-rot-fai-bangkok.jpg', tags: ['vintage', 'night-market', 'antiques', 'retro', 'cool'] },
  { name: 'Bang Nam Phueng Floating Market', slug: 'bang-nam-phueng-floating-market-bangkok', category: 'FOOD', description: "Bangkok's most authentic floating market - a weekend-only wooden boat market in a lush community garden on Bang Krachao island, the 'green lung of Bangkok'. Vendors sell homemade Thai sweets, grilled meats, and tropical fruit by longboat. Rent a bicycle to explore the island.", address: 'Bang Nam Phueng, Phra Pradaeng, Samut Prakan 10130, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Bang+Nam+Phueng+Floating+Market', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/bang-nam-phueng-floating-market-bangkok.jpg', tags: ['floating-market', 'local', 'bicycle', 'authentic', 'green-lung'] },
  { name: 'Chinatown (Yaowarat) Street Food', slug: 'yaowarat-chinatown-bangkok', category: 'FOOD', description: "Bangkok's Chinatown is the greatest street food strip in a city full of great street food. Yaowarat Road comes alive at night with vendors grilling whole fish, ladling bird's nest soup, frying crispy pork, and serving shark fin, crab, and oyster omelette from carts under neon Chinese signs.", address: 'Yaowarat Road, Samphanthawong, Bangkok 10100, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Yaowarat+Chinatown+Bangkok', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/yaowarat-chinatown-bangkok.jpg', tags: ['chinatown', 'street-food', 'night', 'neon', 'legendary'] },
  // TOURIST SITES
  { name: 'Wat Phra Kaew (Grand Palace)', slug: 'wat-phra-kaew-grand-palace-bangkok', category: 'CULTURE', description: "Thailand's most sacred site - the Grand Palace complex contains Wat Phra Kaew (Temple of the Emerald Buddha), whose tiny jade Buddha has presided over the Thai kingdom since 1784. Cover shoulders and knees; the complex is massive and easily fills a half-day.", address: 'Na Phra Lan Road, Phra Borom Maha Ratchawang, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Wat+Phra+Kaew+Grand+Palace+Bangkok', phone: '+66 2 623 5500', website: 'https://www.royalgrandpalace.th', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/wat-phra-kaew-grand-palace-bangkok.jpg', tags: ['temple', 'grand-palace', 'iconic', 'emerald-buddha', 'must-see'] },
  { name: 'Wat Pho - Temple of the Reclining Buddha', slug: 'wat-pho-bangkok', category: 'CULTURE', description: "Home to Thailand's largest reclining Buddha - 46 meters long and covered in gold leaf. Wat Pho is also the birthplace of traditional Thai massage and has the most reputable massage school in the country on site. One of Bangkok's most atmospheric temples.", address: '2 Sanam Chai Road, Phra Borom Maha Ratchawang, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Wat+Pho+Bangkok', phone: '+66 2 226 0335', website: 'https://watpho.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/wat-pho-bangkok.jpg', tags: ['temple', 'reclining-buddha', 'massage', 'historic', 'must-see'] },
  { name: 'Wat Arun (Temple of Dawn)', slug: 'wat-arun-bangkok', category: 'CULTURE', description: "The most visually striking temple in Bangkok - a 70-meter prangs (spire) encrusted entirely in colorful Chinese porcelain and ceramic fragments that shimmer in sunlight. Best viewed from the opposite bank at sunset, or crossed by ferry for close-up exploration.", address: '158 Wang Doem Road, Wat Arun, Bangkok Yai, Bangkok 10600, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Wat+Arun+Bangkok', phone: '+66 2 891 2185', website: 'https://watarun.net', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/wat-arun-bangkok.jpg', tags: ['temple', 'sunrise', 'sunset', 'porcelain', 'iconic'] },
  { name: 'Jim Thompson House', slug: 'jim-thompson-house-bangkok', category: 'CULTURE', description: "The former home of American silk entrepreneur Jim Thompson - six traditional Thai houses relocated and combined into an extraordinary museum of Southeast Asian art. Thompson mysteriously disappeared in Malaysia in 1967; his house and his story remain Bangkok's most compelling mystery.", address: '6 Kasem San 2 Road, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Jim+Thompson+House+Bangkok', phone: '+66 2 216 7368', website: 'https://www.jimthompsonhouse.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/jim-thompson-house-bangkok.jpg', tags: ['museum', 'thai-art', 'silk', 'mystery', 'heritage'] },
  { name: 'Khao San Road', slug: 'khao-san-road-bangkok', category: 'CULTURE', description: "The most famous backpacker street on earth - 400 meters of guesthouses, bars, street food, fake IDs, Chang beer, and travelers from every country. Bangkok locals call it 'the road for budget travelers who want to find themselves' - chaotic, cheap, and unmissable.", address: 'Khao San Road, Banglamphu, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Khao+San+Road+Bangkok', phone: null, website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/khao-san-road-bangkok.jpg', tags: ['backpacker', 'nightlife', 'iconic', 'street-food', 'budget'] },
  { name: 'Lumphini Park', slug: 'lumphini-park-bangkok', category: 'NATURE', description: "Bangkok's Central Park - 58 hectares of lakes, lawns, and tree-shaded pathways in the middle of the CBD. At dawn, dozens of tai chi groups practice on the grass alongside runners and outdoor aerobics classes. The giant monitor lizards are a surprise attraction.", address: 'Lumphini, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Lumphini+Park+Bangkok', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/lumphini-park-bangkok.jpg', tags: ['park', 'morning', 'jogging', 'monitor-lizards', 'free'] },
  { name: 'Chao Phraya River Boat Tour', slug: 'chao-phraya-river-boat-bangkok', category: 'CULTURE', description: "The Chao Phraya Express Boat is Bangkok's original public transit - and the cheapest city tour. Hop-on-hop-off orange flag boats stop at all major temples, the Grand Palace pier, Chinatown, and Asiatique for under 50 baht. Best ridden at golden hour.", address: 'Sathorn/Central Pier, Bang Rak, Bangkok 10120, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Chao+Phraya+Express+Boat+Bangkok', phone: null, website: 'https://www.chaophrayaexpressboat.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/chao-phraya-river-boat-bangkok.jpg', tags: ['boat', 'river', 'temples', 'hop-on-hop-off', 'budget'] },
  { name: 'Chatuchak Park & Or Tor Kor', slug: 'chatuchak-park-area-bangkok', category: 'NATURE', description: "The green lung of north Bangkok - Chatuchak Park, Or Tor Kor premium market, and Jatujak Weekend Market all cluster around Mo Chit BTS. A perfect full-day loop: morning fresh market, afternoon shopping, evening park beers.", address: 'Kamphaeng Phet Road, Chatuchak, Bangkok 10900, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Chatuchak+Park+Bangkok', phone: null, website: null, priceRange: 'FREE', rating: 4.4, imageUrl: '/spots/chatuchak-park-area-bangkok.jpg', tags: ['park', 'green', 'mo-chit', 'relax', 'free'] },
  { name: 'MOCA Bangkok (Museum of Contemporary Art)', slug: 'moca-bangkok', category: 'CULTURE', description: "Thailand's finest collection of modern and contemporary Thai art - five floors of paintings, sculptures, and installations from the past century in a striking building near Chatuchak. Frequently overlooked in favor of temples; one of the best museums in Southeast Asia.", address: '499 Kamphaeng Phet 6 Road, Lat Yao, Chatuchak, Bangkok 10900, Thailand', googleMapsUrl: 'https://maps.google.com/?q=MOCA+Bangkok', phone: '+66 2 953 1005', website: 'https://mocabangkok.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/moca-bangkok.jpg', tags: ['museum', 'contemporary-art', 'thai-art', 'underrated', 'culture'] },
  { name: 'Banglamphu Old Quarter', slug: 'banglamphu-old-quarter-bangkok', category: 'CULTURE', description: "The historic heart of Bangkok - leafy streets lined with wooden shophouses, canal-side temples, and the Democracy Monument. Less visited than the Grand Palace area, Banglamphu rewards slow exploration: vintage bookshops, old-school noodle stalls, and the Bangkok that existed before the skyscrapers.", address: 'Banglamphu, Phra Nakhon, Bangkok 10200, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Banglamphu+Bangkok', phone: null, website: null, priceRange: 'FREE', rating: 4.4, imageUrl: '/spots/banglamphu-old-quarter-bangkok.jpg', tags: ['historic', 'shophouses', 'walking', 'old-city', 'canals'] },
  // COWORKING
  { name: 'The Hive Bangkok', slug: 'the-hive-bangkok', category: 'COWORKING', description: "Bangkok's best-known coworking brand with multiple locations across the city. The Hive delivers premium amenities - standing desks, private phone booths, podcast studios, and a curated events calendar - at mid-market prices. The Ekkamai flagship has a stunning garden terrace.", address: '1 Ekkamai Road, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=The+Hive+Bangkok', phone: '+66 2 392 4804', website: 'https://thehive.co.th', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/the-hive-bangkok.jpg', tags: ['coworking', 'premium', 'ekkamai', 'events', 'standing-desks'] },
  { name: 'HUBBA-TO Coworking', slug: 'hubba-to-coworking-bangkok', category: 'COWORKING', description: "Bangkok's original startup hub - a converted warehouse on Ekamai that pioneered the city's tech community. HUBBA-TO hosts a packed calendar of startup pitches, tech talks, and entrepreneur meetups alongside its coworking floors. The best place to meet Bangkok's startup scene.", address: '1991 Sukhumvit Soi 63, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=HUBBA-TO+Bangkok', phone: '+66 2 714 3140', website: 'https://hubba.co', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/hubba-to-coworking-bangkok.jpg', tags: ['startup', 'community', 'events', 'tech', 'ekkamai'] },
  { name: 'Paperwork Silom', slug: 'paperwork-silom-bangkok', category: 'COWORKING', description: "A boutique coworking space in the business district with excellent air conditioning, gigabit wifi, private phone booths, and a great espresso bar. Hourly passes available - ideal for visitors who just need a professional address for a few hours between meetings.", address: '191/18 Silom Road, Silom, Bang Rak, Bangkok 10500, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Paperwork+Silom+Bangkok', phone: '+66 2 635 7444', website: 'https://paperworkspace.com', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/paperwork-silom-bangkok.jpg', tags: ['coworking', 'silom', 'hourly', 'professional', 'espresso'] },
  { name: 'Mango Coworking Bangkok', slug: 'mango-coworking-bangkok', category: 'COWORKING', description: "A friendly, affordable coworking space near Asok BTS with fast internet, good natural light, and a helpful team that can assist with SIM cards, printing, and logistics. Day passes start at just 200 baht. Popular with budget-conscious nomads on extended Bangkok stays.", address: '8/4 Sukhumvit Soi 33, Watthana, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Mango+Coworking+Bangkok', phone: '+66 85 489 1234', website: 'https://mangocoworking.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/mango-coworking-bangkok.jpg', tags: ['coworking', 'budget', 'asok', 'day-pass', 'affordable'] },
  { name: 'Garage Society Bangkok', slug: 'garage-society-bangkok', category: 'COWORKING', description: "A premium coworking brand originating from Hong Kong with a stunning Bangkok outpost in the One Bangkok mixed-use development. Designer furniture, biophilic interiors, rooftop terrace, and a community of high-caliber international professionals make it Bangkok's most aspirational work address.", address: '57 Wireless Road, Lumphini, Pathumwan, Bangkok 10330, Thailand', googleMapsUrl: 'https://maps.google.com/?q=Garage+Society+Bangkok', phone: '+66 2 012 7100', website: 'https://www.garagesociety.com/bangkok', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/garage-society-bangkok.jpg', tags: ['premium', 'rooftop', 'biophilic', 'design', 'international'] },
  { name: 'FIND Coworking Bangkok', slug: 'find-coworking-bangkok', category: 'COWORKING', description: "A no-fuss reliable coworking space near Phrom Phong BTS with 24-hour access, 1Gbps fiber internet, meeting rooms, and a quiet, focused atmosphere. Very popular with remote workers on longer stays who want a steady work base without the boutique pricing.", address: '2/4 Sukhumvit Soi 26, Khlong Toei, Bangkok 10110, Thailand', googleMapsUrl: 'https://maps.google.com/?q=FIND+Coworking+Bangkok', phone: '+66 95 363 4555', website: 'https://findcoworking.com', priceRange: 'MID', rating: 4.4, imageUrl: '/spots/find-coworking-bangkok.jpg', tags: ['coworking', '24-hour', 'fiber', 'quiet', 'phrom-phong'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Bangkok: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
