const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfsv20015vimodo2d0fu0';

const spots = [
  { name: 'Hotel Copernicus Kraków', slug: 'hotel-copernicus-krakow', category: 'ACCOMMODATION', description: "Kraków's finest boutique hotel in a meticulously restored 15th-century Renaissance townhouse on Kanonicza Street — the most beautiful street in Kraków, leading to Wawel Castle. Frescoed ceilings, a Gothic cellar restaurant, rooftop pool, and the closest hotel to the castle.", address: 'Kanonicza 16, 31-002 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Copernicus+Krakow', phone: '+48 12 424 3400', website: 'https://www.hotelcopernicus.pl', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/hotel-copernicus-krakow.jpg', tags: ['luxury', '15th-century', 'kanonicza', 'rooftop-pool', 'wawel'] },
  { name: 'Hotel Stary Kraków', slug: 'hotel-stary-krakow', category: 'ACCOMMODATION', description: "A restored medieval tenement in the heart of the Old Town with a rooftop pool overlooking the city, a spa in the 14th-century cellars, and beautifully designed rooms that blend Gothic arches with contemporary comfort.", address: 'ul. Szczepańska 5, 31-011 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Stary+Krakow', phone: '+48 12 384 0808', website: 'https://www.stary.hotel.com.pl', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/hotel-stary-krakow.jpg', tags: ['medieval', 'rooftop-pool', 'gothic-cellars', 'spa', 'old-town'] },
  { name: 'Greg & Tom Hostel Kraków', slug: 'greg-and-tom-hostel-krakow', category: 'ACCOMMODATION', description: "The most-loved hostel in Poland — a warm, sociable hostel in the center of the Old Town with free home-cooked breakfast, free beer at check-in, and a community-building philosophy that has created genuine friendships between travelers for 20 years.", address: 'ul. Pawia 12/7, 31-154 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Greg+and+Tom+Hostel+Krakow', phone: '+48 12 422 4100', website: 'https://www.gregtom.com', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/greg-and-tom-hostel-krakow.jpg', tags: ['hostel', 'free-breakfast', 'free-beer', 'social', 'best-in-poland'] },
  { name: 'Hotel Pod Różą Kraków', slug: 'hotel-pod-roza-krakow', category: 'ACCOMMODATION', description: "Kraków's oldest continuously operating hotel (since 1792) on Floriańska Street — a beautiful Renaissance building with individually decorated rooms, an excellent breakfast buffet, and a location in the absolute heart of the Old Town.", address: 'ul. Floriańska 14, 31-021 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Pod+Roza+Krakow', phone: '+48 12 424 3300', website: 'https://www.hotel.com.pl', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/hotel-pod-roza-krakow.jpg', tags: ['1792', 'renaissance', 'florjanska', 'historic', 'breakfast'] },
  // CAFES
  { name: 'Szara Gęś Coffee Kraków', slug: 'szara-ges-coffee-krakow', category: 'CAFE', description: "Kraków's most celebrated specialty coffee bar in Kazimierz — a warm, book-lined space with excellent single-origin filter coffees, homemade pastries, and a devoted regular crowd of students, writers, and digital nomads. The best place to work in Kraków.", address: 'ul. Szeroka 5/6, 31-053 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Szara+Ges+Coffee+Krakow', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/szara-ges-coffee-krakow.jpg', tags: ['specialty', 'kazimierz', 'books', 'nomad', 'work-friendly'] },
  { name: 'Camelot Café Kraków', slug: 'camelot-cafe-krakow', category: 'CAFE', description: "A legendary Kraków institution in a Gothic cellar on Św. Tomasza Street — low vaulted ceilings, candlelight, classical music, and the city's most atmospheric afternoon coffee experience. The cheesecake and the apple pie have been served unchanged since 1989.", address: 'ul. Świętego Tomasza 17, 31-021 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Camelot+Cafe+Krakow', phone: '+48 12 421 0123', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/camelot-cafe-krakow.jpg', tags: ['gothic-cellar', 'candlelight', 'atmospheric', '1989', 'cheesecake'] },
  // FOOD
  { name: 'Noworolski Café Kraków', slug: 'noworolski-cafe-krakow', category: 'FOOD', description: "The grandest café in Kraków, inside the Cloth Hall on the Main Market Square since 1910 — a Vienna Secession interior of marble, mirrors, and gilt, serving Polish cakes, coffee, and light lunches. The most beautiful room in Kraków for an afternoon break.", address: 'Rynek Główny 1/3, 31-042 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Noworolski+Cafe+Krakow', phone: '+48 12 422 4771', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/noworolski-cafe-krakow.jpg', tags: ['grand-cafe', '1910', 'cloth-hall', 'vienna-secession', 'polish-cakes'] },
  { name: 'Starka Restaurant Kraków', slug: 'starka-restaurant-krakow', category: 'FOOD', description: "The best modern Polish restaurant in Kraków — a sophisticated take on traditional Polish cuisine with a 300-bottle Polish vodka and nalewka (infused liqueur) list, and dishes that reinvent żurek, bigos, and pierogi with modern technique and seasonal ingredients.", address: 'ul. Józefa 14, 31-056 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Starka+Restaurant+Krakow', phone: '+48 12 430 6531', website: 'https://www.starka-restauracja.pl', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/starka-restaurant-krakow.jpg', tags: ['modern-polish', 'vodka', 'pierogi', 'bigos', 'kazimierz'] },
  { name: 'Kazimierz Jewish Quarter Eating', slug: 'kazimierz-food-scene-krakow', category: 'FOOD', description: "Kraków's revived Jewish Quarter is the city's most exciting food neighborhood — Szeroka Street and the surrounding lanes are full of authentic Jewish restaurants (gefilte fish, challah, cholent), Georgian wine bars, craft beer bars, and food trucks. The Sunday flea market is a highlight.", address: 'Kazimierz, Kraków', googleMapsUrl: 'https://maps.google.com/?q=Kazimierz+Krakow', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/kazimierz-food-scene-krakow.jpg', tags: ['jewish-quarter', 'georgian-wine', 'craft-beer', 'flea-market', 'food-scene'] },
  // CULTURE
  { name: 'Wawel Castle Kraków', slug: 'wawel-castle-krakow', category: 'CULTURE', description: "Poland's most important monument — a Renaissance castle and Gothic cathedral on a limestone hill above the Vistula, home of the Polish Crown Jewels, Leonardo's Lady with an Ermine, and the tombs of Poland's kings. The dragon's cave below the castle breathes fire every 5 minutes.", address: 'Wawel 5, 31-001 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Wawel+Castle+Krakow', phone: '+48 12 422 5155', website: 'https://wawel.krakow.pl', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/wawel-castle-krakow.jpg', tags: ['castle', 'renaissance', 'crown-jewels', 'leonardo', 'dragon'] },
  { name: 'Main Market Square (Rynek Główny)', slug: 'rynek-glowny-krakow', category: 'CULTURE', description: "The largest medieval market square in Europe — 200×200 meters of cobblestone surrounded by Gothic churches, Renaissance tenements, and the Cloth Hall arcade. The Rynek is the social center of Kraków: outdoor cafés, horse-drawn carriages, street musicians, and the most atmospheric evening promenade in Central Europe.", address: 'Rynek Główny, 31-042 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Rynek+Glowny+Krakow', phone: null, website: null, priceRange: 'FREE', rating: 4.8, imageUrl: '/spots/rynek-glowny-krakow.jpg', tags: ['market-square', 'largest', 'gothic', 'cloth-hall', 'evening'] },
  { name: 'Wieliczka Salt Mine', slug: 'wieliczka-salt-mine-krakow', category: 'CULTURE', description: "A UNESCO World Heritage underground world — salt miners carved 287km of tunnels, chapels, and chambers between the 13th and 20th centuries, including the 54-meter Cathedral of St. Kinga (entirely carved from salt) and salt-crystal chandeliers. The most extraordinary underground site in Europe, 15km from Kraków.", address: 'Park Kingi 1, 32-020 Wieliczka', googleMapsUrl: 'https://maps.google.com/?q=Wieliczka+Salt+Mine', phone: '+48 12 278 7302', website: 'https://www.wieliczka-saltmine.com', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/wieliczka-salt-mine-krakow.jpg', tags: ['unesco', 'salt-mine', 'chapel', 'underground', 'must-do'] },
  { name: 'St. Mary\'s Basilica Kraków', slug: 'st-marys-basilica-krakow', category: 'CULTURE', description: "The most important Gothic church in Poland — a 14th-century Basilica on the Market Square with the finest altarpiece in Central Europe (the 1489 carved wooden polyptych by Veit Stoss) and the famous bugler who plays the Hejnał Mariacki every hour from the taller tower.", address: 'plac Mariacki 5, 31-042 Kraków', googleMapsUrl: 'https://maps.google.com/?q=St+Marys+Basilica+Krakow', phone: '+48 12 422 0521', website: 'https://www.mariacki.com', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/st-marys-basilica-krakow.jpg', tags: ['gothic', 'altarpiece', 'bugler', 'veit-stoss', 'market-square'] },
  { name: 'Kazimierz Jewish Quarter', slug: 'kazimierz-krakow', category: 'CULTURE', description: "Kraków's historic Jewish Quarter — a medieval district that was the heart of Polish-Jewish life for 500 years, devastated in WWII, and now experiencing a remarkable cultural renaissance. The Remuh Synagogue, Old Synagogue, and the surrounding streets are moving, atmospheric, and increasingly vibrant.", address: 'Kazimierz, 31-053 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Kazimierz+Krakow', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/kazimierz-krakow.jpg', tags: ['jewish-heritage', 'synagogue', 'renaissance', 'history', 'cultural'] },
  { name: 'Auschwitz-Birkenau Memorial', slug: 'auschwitz-birkenau-krakow', category: 'CULTURE', description: "The most important Holocaust memorial and museum in the world — the Nazi German concentration and extermination camp where 1.1 million people were murdered. Essential to understanding 20th-century history. Book a guided tour in advance; it fills weeks ahead. Located 70km west of Kraków.", address: 'Więźniów Oświęcimia 20, 32-603 Oświęcim', googleMapsUrl: 'https://maps.google.com/?q=Auschwitz+Birkenau', phone: '+48 33 844 8100', website: 'https://www.auschwitz.org', priceRange: 'FREE', rating: 4.9, imageUrl: '/spots/auschwitz-birkenau-krakow.jpg', tags: ['holocaust', 'memorial', 'essential', 'guided-tour', 'history'] },
  { name: 'Wawel Cathedral', slug: 'wawel-cathedral-krakow', category: 'CULTURE', description: "The coronation church and burial place of Polish kings — a Gothic cathedral atop Wawel Hill containing royal tombs, Sigismund's Bell (one of Europe's largest, rung only on national holidays), and the oldest clock tower in Kraków. John Paul II was ordained here.", address: 'Wawel 3, 31-001 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Wawel+Cathedral+Krakow', phone: '+48 12 429 9516', website: 'https://katedra-wawelska.pl', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/wawel-cathedral-krakow.jpg', tags: ['gothic', 'royal-tombs', 'sigismund-bell', 'john-paul-ii', 'coronation'] },
  // COWORKING
  { name: 'React Coworking Kraków', slug: 'react-coworking-krakow', category: 'COWORKING', description: "Kraków's best coworking space near the old town in a beautifully renovated space with private offices, dedicated desks, meeting rooms, and the city's most active startup community. Day passes available; the mentorship and investor network here is the best in southern Poland.", address: 'ul. Jana 1, 31-013 Kraków', googleMapsUrl: 'https://maps.google.com/?q=React+Coworking+Krakow', phone: '+48 12 431 0003', website: 'https://react.org.pl', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/react-coworking-krakow.jpg', tags: ['coworking', 'startup', 'day-pass', 'old-town', 'mentorship'] },
  // NIGHTLIFE
  { name: 'Piwnica pod Baranami', slug: 'piwnica-pod-baranami-krakow', category: 'NIGHTLIFE', description: "Kraków's most legendary cabaret venue in the cellar of the Cloth Hall — the literary cabaret that hosted the dissident intelligentsia throughout the Communist era and still produces extraordinary music and spoken-word performances. The Friday evening show is a Kraków institution.", address: 'Rynek Główny 27, 31-010 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Piwnica+pod+Baranami+Krakow', phone: '+48 12 421 2500', website: 'https://www.piwnica.pl', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/piwnica-pod-baranami-krakow.jpg', tags: ['cabaret', 'cellar', 'dissident', 'literary', 'institution'] },
  // WELLNESS / NATURE
  { name: 'Planty Park Kraków', slug: 'planty-park-krakow', category: 'NATURE', description: "A circular park belt that replaced the medieval city walls — 4km of tree-lined paths encircling the entire Old Town, Kraków's equivalent of Vienna's Ringstraße but as a park. The most pleasant morning walk in the city.", address: 'Planty, 31-000 Kraków', googleMapsUrl: 'https://maps.google.com/?q=Planty+Park+Krakow', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/planty-park-krakow.jpg', tags: ['park', 'circular', 'walking', 'free', 'morning'] },
  { name: 'Zakopane Day Trip Kraków', slug: 'zakopane-day-trip-krakow', category: 'NATURE', description: "Poland's mountain capital 2 hours south of Kraków — a Tatra Mountain resort town with cable car to Kasprowy Wierch (1987m), Morskie Oko glacial lake, and the most authentic Polish highland folk culture. Buses run every hour; the mountains are extraordinary in both summer and winter.", address: 'Zakopane, 34-500', googleMapsUrl: 'https://maps.google.com/?q=Zakopane+Poland', phone: null, website: 'https://www.zakopane.eu', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/zakopane-day-trip-krakow.jpg', tags: ['tatra', 'mountains', 'day-trip', 'cable-car', 'folk-culture'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Kraków: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
