const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328hxe000zvi8w5mon00qg';

const spots = [
  // LUXURY HOTELS
  { name: 'The Temple House Chengdu', slug: 'temple-house-chengdu', category: 'ACCOMMODATION', description: 'One of the most celebrated boutique luxury hotels in China, built within a restored Qing Dynasty temple complex in the heart of Taikoo Li, with 100 rooms blending contemporary design with preserved ancient courtyard architecture. The Temple House Chengdu is routinely named among Asia\'s top hotels and is the most architecturally significant hotel in Sichuan.', address: '81 Bitieshi Street, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=The+Temple+House+Chengdu', phone: '+86 28 6500 8866', website: 'https://www.thetemplehousechengdu.com', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/temple-house-chengdu.jpg', tags: ['temple', 'qing-dynasty', 'taikoo-li', 'heritage', 'best-hotel'] },
  { name: 'St. Regis Chengdu', slug: 'st-regis-chengdu', category: 'ACCOMMODATION', description: 'A 42-floor glass tower in the Jinjiang business district with spacious rooms and the most comprehensive butler service in Chengdu, a rooftop bar with panoramic views of the Chengdu basin and snow-capped Qinghai Tibet Plateau on clear days, and the finest Western dining in the city. The St. Regis Chengdu is the top choice for global business travelers.', address: 'No. 88 Renmin South Road, Jinjiang District, Chengdu, Sichuan 610021, China', googleMapsUrl: 'https://maps.google.com/?q=St+Regis+Chengdu', phone: '+86 28 8537 8888', website: 'https://www.marriott.com/st-regis-chengdu', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/st-regis-chengdu.jpg', tags: ['butler-service', 'rooftop-bar', 'panoramic', 'business', 'western-dining'] },
  { name: 'Four Seasons Hotel Chengdu', slug: 'four-seasons-chengdu', category: 'ACCOMMODATION', description: 'A 45-floor luxury hotel in Chengdu\'s financial district with a dramatic lobby waterfall, a Michelin-quality Cantonese restaurant, an exceptional spa with traditional Sichuan massage treatments, and floor-to-ceiling windows in every room. Four Seasons Chengdu consistently outranks other luxury properties for service quality.', address: '8 Binjiang Zhong Road, Qingyang District, Chengdu, Sichuan 610023, China', googleMapsUrl: 'https://maps.google.com/?q=Four+Seasons+Chengdu', phone: '+86 28 8878 6999', website: 'https://www.fourseasons.com/chengdu', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/four-seasons-chengdu.jpg', tags: ['four-seasons', 'cantonese', 'spa', 'sichuan-massage', 'waterfall'] },
  { name: 'Niccolo Chengdu', slug: 'niccolo-chengdu', category: 'ACCOMMODATION', description: 'A bold luxury hotel in the IFS shopping complex right at the heart of Chengdu\'s modern commercial core, with dramatic art-installation decor, a sky pool, and an outstanding restaurant serving contemporary Sichuanese haute cuisine. The Niccolo is the hotel that best captures Chengdu\'s identity as a modern Chinese lifestyle capital.', address: '1 Section 3, Hongxing Road, Jinjiang District, Chengdu, Sichuan 610021, China', googleMapsUrl: 'https://maps.google.com/?q=Niccolo+Chengdu', phone: '+86 28 8719 8999', website: 'https://www.niccolohotels.com/chengdu', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/niccolo-chengdu.jpg', tags: ['ifs', 'art', 'sky-pool', 'sichuanese-haute', 'lifestyle'] },
  // BUDGET HOTELS
  { name: 'Sim\'s Cozy Guesthouse Chengdu', slug: 'sims-cozy-guesthouse-chengdu', category: 'ACCOMMODATION', description: 'The legendary backpacker institution of Chengdu with private rooms and dormitories in a converted traditional courtyard house near Wuhou Temple, offering excellent local tour packages, Tibet permit assistance, and a restaurant serving both Western and Sichuan food. Sim\'s is where Chengdu backpackers have started their Southwest China adventures for over 20 years.', address: 'Tongzilin South Road 4, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Sims+Cozy+Guesthouse+Chengdu', phone: '+86 28 8552 9688', website: 'https://www.simscozy.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/sims-cozy-guesthouse-chengdu.jpg', tags: ['institution', 'courtyard', 'tibet-permit', 'backpacker', '20-years'] },
  { name: 'Lazy Bones Hostel Chengdu', slug: 'lazy-bones-hostel-chengdu', category: 'ACCOMMODATION', description: 'A creative, well-designed hostel in the hip Yulin area with a cafe, a cinema room, and a rooftop with Chengdu city views, consistently rated the best-designed budget accommodation in Chengdu. The Yulin location is walking distance from the city\'s best hot pot restaurants and the Sichuan Opera theater.', address: 'Yulin, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Lazy+Bones+Hostel+Chengdu', phone: '+86 28 8555 9876', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/lazy-bones-hostel-chengdu.jpg', tags: ['creative', 'cinema', 'yulin', 'rooftop', 'hotpot-access'] },
  { name: 'Chengdu Mix Hostel', slug: 'chengdu-mix-hostel', category: 'ACCOMMODATION', description: 'A social hostel in the Jinli area near the Wuhou Shrine with clean dormitories, private rooms, an excellent common room, and a location that puts the city\'s main tourist attractions within walking distance. The regular organized Sichuan cooking classes and local food tours make it the best experience-oriented budget option.', address: 'Jinli, Wuhou District, Chengdu, Sichuan 610042, China', googleMapsUrl: 'https://maps.google.com/?q=Chengdu+Mix+Hostel', phone: '+86 28 8558 6789', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/chengdu-mix-hostel.jpg', tags: ['jinli', 'cooking-class', 'food-tour', 'social', 'wuhou'] },
  { name: 'Blooming Garden Boutique Hotel Chengdu', slug: 'blooming-garden-boutique-hotel-chengdu', category: 'ACCOMMODATION', description: 'A beautiful mid-range boutique hotel set in a restored 1930s garden villa in the Qingyang district with elegant Chinese antique furnishings, a tranquil garden, and exceptionally attentive service. The Blooming Garden offers boutique hotel quality at less than half the price of Chengdu\'s luxury tier - excellent value.', address: 'Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Blooming+Garden+Hotel+Chengdu', phone: '+86 28 8773 2888', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/blooming-garden-boutique-hotel-chengdu.jpg', tags: ['garden-villa', '1930s', 'antique', 'boutique', 'value'] },
  // HOSTELS (combined with above for 4+4+4=12)
  { name: 'Dragon Town Youth Hostel Chengdu', slug: 'dragon-town-youth-hostel-chengdu', category: 'ACCOMMODATION', description: 'A popular hostel in Chengdu\'s Jinli ancient street area with pod dormitories, regular social events, a courtyard bar, and an extremely knowledgeable staff team for organizing panda base visits, Leshan Buddha day trips, Jiuzhaigou tours, and Tibet train bookings. The social center of the budget Chengdu traveler scene.', address: 'Jinli, Wuhou District, Chengdu, Sichuan 610042, China', googleMapsUrl: 'https://maps.google.com/?q=Dragon+Town+Youth+Hostel+Chengdu', phone: '+86 28 8555 7788', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/dragon-town-youth-hostel-chengdu.jpg', tags: ['pods', 'panda-tours', 'leshan', 'tibet', 'social'] },
  { name: 'Mix Hostel Chengdu Kuanzhai', slug: 'mix-hostel-chengdu-kuanzhai', category: 'ACCOMMODATION', description: 'The best-located hostel in Chengdu right next to the Kuanzhai Alley heritage zone, with comfortable dorms, a bar, and extraordinary access to Chengdu\'s most atmospheric old neighborhood. The rooftop terrace overlooks the Qing Dynasty courtyard buildings of Kuanzhai Alley - a view that no other hostel in the city can offer.', address: 'Kuanzhai Alley, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Mix+Hostel+Chengdu+Kuanzhai', phone: '+86 28 8773 1234', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/mix-hostel-chengdu-kuanzhai.jpg', tags: ['kuanzhai', 'heritage', 'rooftop', 'qing-dynasty', 'location'] },
  { name: 'Chengdu Traffic Youth Hostel', slug: 'chengdu-traffic-youth-hostel', category: 'ACCOMMODATION', description: 'The original and longest-established youth hostel in Chengdu with a vibrant social scene, organized group activities, an in-house bar serving Chengdu craft beer and local baijiu, and the most comprehensive free city information of any hostel. Traffic Hostel has been the Chengdu starting point for generations of Southwest China travelers.', address: 'Xinnanmen Bus Station area, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Chengdu+Traffic+Youth+Hostel', phone: '+86 28 8545 4212', website: 'https://www.cdtraffichostel.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/chengdu-traffic-youth-hostel.jpg', tags: ['original', 'social', 'baijiu', 'southwest-china', 'generations'] },
  { name: 'Holly\'s Hostel Chengdu', slug: 'hollys-hostel-chengdu', category: 'ACCOMMODATION', description: 'A clean, relaxed hostel near Renmin Park with a small garden, a communal kitchen, and some of the most comfortable private rooms in the budget category. Holly\'s is popular with mature backpackers, long-stay digital nomads, and travelers who want a quieter environment than the party hostels near Jinli.', address: 'Renmin Park area, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Hollys+Hostel+Chengdu', phone: '+86 28 8779 2344', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/hollys-hostel-chengdu.jpg', tags: ['garden', 'quiet', 'mature', 'renmin-park', 'nomads'] },
  // CAFES
  { name: 'Hefa Gastronomique Chengdu', slug: 'hefa-gastronomique-chengdu', category: 'CAFE', description: 'A striking contemporary cafe and patisserie in Taikoo Li with French-trained pastry techniques applied to Chinese ingredients - chrysanthemum madeleines, osmanthus financiers, red bean croissants. The best cafes in Chengdu are set to a remarkably high standard and Hefa sets the benchmark for the Taikoo Li area.', address: 'Taikoo Li, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=Hefa+Gastronomique+Chengdu', phone: '+86 28 8610 1234', website: null, priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/hefa-gastronomique-chengdu.jpg', tags: ['patisserie', 'french', 'chrysanthemum', 'taikoo-li', 'croissant'] },
  { name: 'Jellyfish Art and Cafe Chengdu', slug: 'jellyfish-art-cafe-chengdu', category: 'CAFE', description: 'A beautiful gallery-cafe hybrid in the Yulin area showing work by Sichuan\'s best emerging artists alongside specialty coffee, handmade mooncakes, and a carefully curated selection of Sichuan oolongs and pu\'er teas. Jellyfish Art Cafe exemplifies the creative ecosystem that has made Chengdu one of China\'s most exciting cultural cities.', address: 'Yulin, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Jellyfish+Art+Cafe+Chengdu', phone: '+86 28 8555 2345', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/jellyfish-art-cafe-chengdu.jpg', tags: ['gallery-cafe', 'sichuan-art', 'pu-er', 'mooncakes', 'yulin'] },
  { name: 'Bookworm Chengdu', slug: 'bookworm-chengdu', category: 'CAFE', description: 'Chengdu\'s most beloved literary cafe with a library of 10,000 English books available to borrow, regular author talks, excellent Western and Sichuan food, and an atmosphere that has made it the intellectual hub of Chengdu\'s expat community. The Bookworm is the most important cultural venue for the English-speaking community in all of western China.', address: '2-7 Yujie East Road, Jinjiang District, Chengdu, Sichuan 610021, China', googleMapsUrl: 'https://maps.google.com/?q=Bookworm+Chengdu', phone: '+86 28 8552 0177', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/bookworm-chengdu.jpg', tags: ['library', 'expat', 'author-talks', 'literary', 'english-books'] },
  { name: 'Wuhou Tea House Chengdu', slug: 'wuhou-tea-house-chengdu', category: 'CAFE', description: 'A traditional bamboo teahouse in the gardens adjacent to Wuhou Shrine serving gaiwan tea service, local Sichuan opera face-changing performances, and an afternoon of ear-cleaning, mahjong-watching, and the quintessential Chengdu art of doing nothing slowly. This is the most authentic teahouse experience in modern Chengdu.', address: 'Wuhou Shrine, Wuhou District, Chengdu, Sichuan 610042, China', googleMapsUrl: 'https://maps.google.com/?q=Wuhou+Tea+House+Chengdu', phone: '+86 28 8555 1823', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/wuhou-tea-house-chengdu.jpg', tags: ['gaiwan', 'face-changing', 'ear-cleaning', 'mahjong', 'traditional'] },
  { name: 'Renmin Park Tea Garden Chengdu', slug: 'renmin-park-tea-garden-chengdu', category: 'CAFE', description: 'The most famous open-air teahouse in China - hundreds of bamboo chairs arranged under ancient plane trees in Renmin Park where Chengdu residents sit for hours drinking gaiwan tea, playing mahjong, and watching the famous Chengdu street life pass. The purest expression of the Chengdu lifestyle philosophy of leisure.', address: 'Renmin Park, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Renmin+Park+Tea+Garden+Chengdu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/renmin-park-tea-garden-chengdu.jpg', tags: ['open-air', 'most-famous', 'mahjong', 'plane-trees', 'chengdu-life'] },
  { name: 'Kunkun Coffee Chengdu', slug: 'kunkun-coffee-chengdu', category: 'CAFE', description: 'A Chengdu-born specialty roaster and cafe chain with the city\'s best espresso, a wide range of single-origin pour-overs, and multiple locations serving the city\'s growing specialty coffee community. Kunkun has proved that Chinese third-wave coffee culture reaches the same level as any specialty market in the world.', address: 'Taikoo Li, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=Kunkun+Coffee+Chengdu', phone: '+86 28 8610 2345', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/kunkun-coffee-chengdu.jpg', tags: ['specialty-roaster', 'pour-over', 'third-wave', 'chinese-coffee', 'espresso'] },
  // RESTAURANTS
  { name: 'Chengdu Long Chaoshou Restaurant', slug: 'chengdu-long-chaoshou-restaurant', category: 'FOOD', description: 'The most famous restaurant in Chengdu, a state-owned institution since 1941 serving the definitive version of Sichuan\'s signature dishes: Long Chaoshou red oil wontons, fuqi feipian cold beef slices, dan dan mian noodles, and mapo tofu. Long Chaoshou is the standard against which all Sichuan food in the world is measured.', address: 'Chunxi Road, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=Long+Chaoshou+Chengdu', phone: '+86 28 8666 1883', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/chengdu-long-chaoshou-restaurant.jpg', tags: ['wontons', 'mapo-tofu', 'dan-dan-mian', '1941', 'institution'] },
  { name: 'Huang Cheng Lao Ma Hot Pot Chengdu', slug: 'huang-cheng-lao-ma-hot-pot-chengdu', category: 'FOOD', description: 'The most celebrated Chengdu hot pot institution - a palace-style restaurant with hundreds of tables and the most complex spice-blend broth in the city. The Sichuan mala (numb-spicy) hot pot here with premium ingredients - wagyu beef slices, fresh tofu, lotus root, offal - is the definitive Chengdu hot pot experience.', address: 'Renmin South Road, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Huang+Cheng+Lao+Ma+Hot+Pot+Chengdu', phone: '+86 28 8554 3999', website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/huang-cheng-lao-ma-hot-pot-chengdu.jpg', tags: ['hot-pot', 'mala', 'institution', 'wagyu', 'spicy'] },
  { name: 'Mapo Tofu Restaurant Wangpo Chengdu', slug: 'mapo-tofu-restaurant-wangpo-chengdu', category: 'FOOD', description: 'The restaurant credited with preserving the original 1862 recipe of mapo tofu - silken tofu in a fermented black bean and chili oil sauce with ground pork and Sichuan pepper. Wangpo is in the same neighborhood where Chen Mapo, the dish\'s inventor, ran her original restaurant on the Qing Dynasty Grand Trunk Road.', address: 'Wan Fu Bridge Street, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Wangpo+Mapo+Tofu+Chengdu', phone: '+86 28 8669 6600', website: null, priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/mapo-tofu-restaurant-wangpo-chengdu.jpg', tags: ['mapo-tofu', '1862', 'original-recipe', 'chen-mapo', 'historical'] },
  { name: 'Baguobuyi Chengdu', slug: 'baguobuyi-chengdu', category: 'FOOD', description: 'An elegant restaurant specializing in Sichuan cuisine served in refined traditional setting - spicy twice-cooked pork, fish-fragrant eggplant, kung pao chicken, and a full selection of classic Sichuan cold dishes in the most beautifully presented version of each dish. Baguobuyi is the benchmark for upscale traditional Sichuan cooking.', address: '20 Renmin South Road, Section 4, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Baguobuyi+Chengdu', phone: '+86 28 8552 9988', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/baguobuyi-chengdu.jpg', tags: ['twice-cooked-pork', 'kung-pao', 'traditional', 'refined', 'cold-dishes'] },
  { name: 'Mao Jia Restaurant Chengdu', slug: 'mao-jia-restaurant-chengdu', category: 'FOOD', description: 'A Hunanese restaurant in Chengdu that serves the personal favorite dishes of Chairman Mao Zedong - red-braised pork belly, steamed fish head with chili, and spicy dried tofu - in a restaurant filled with Cultural Revolution memorabilia and posters. The most politically and gastronomically interesting meal in Chengdu.', address: 'Renmin South Road, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Mao+Jia+Restaurant+Chengdu', phone: '+86 28 8555 1234', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/mao-jia-restaurant-chengdu.jpg', tags: ['hunanese', 'mao-zedong', 'red-braised-pork', 'cultural-revolution', 'unique'] },
  { name: 'Zhi Wei Guan Chengdu', slug: 'zhi-wei-guan-chengdu', category: 'FOOD', description: 'One of the best dim sum and Cantonese restaurants in Chengdu with over 100 varieties of dim sum, char siu bao, har gow, and innovative Sichuan-Cantonese fusion dishes that blend the best of both regional cuisines. The Sunday brunch service with live dim sum cart service is the best Cantonese brunch in western China.', address: 'Chunxi Road area, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=Zhi+Wei+Guan+Chengdu', phone: '+86 28 8669 3333', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/zhi-wei-guan-chengdu.jpg', tags: ['dim-sum', 'cantonese', 'char-siu', 'brunch', 'fusion'] },
  // MARKETS
  { name: 'Jinli Ancient Street Market Chengdu', slug: 'jinli-ancient-street-market-chengdu', category: 'FOOD', description: 'A beautifully restored Han Dynasty-style street of souvenir shops, street food stalls, craft stores, and traditional Sichuan snack vendors adjacent to the Wuhou Shrine. The tanghulu sugar-coated fruit skewers, sesame rice balls, and Sichuan peppercorn treats make Jinli the best street food circuit in the city.', address: 'Jinli, Wuhou District, Chengdu, Sichuan 610042, China', googleMapsUrl: 'https://maps.google.com/?q=Jinli+Ancient+Street+Chengdu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/jinli-ancient-street-market-chengdu.jpg', tags: ['han-dynasty', 'tanghulu', 'sesame-balls', 'wuhou', 'street-food'] },
  { name: 'Kuanzhai Alley Chengdu', slug: 'kuanzhai-alley-chengdu', category: 'FOOD', description: 'Three carefully restored Qing Dynasty alleyways - Wide Alley, Narrow Alley, and Well Alley - lined with tea houses, restaurants, craft shops, and bars in courtyard buildings dating from the 1700s. The most picturesque heritage district in Chengdu and the best place to eat and drink in a historic setting.', address: 'Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Kuanzhai+Alley+Chengdu', phone: null, website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/kuanzhai-alley-chengdu.jpg', tags: ['qing-dynasty', 'three-alleys', 'courtyard', '1700s', 'heritage'] },
  { name: 'Sichuan Chili and Spice Market Chengdu', slug: 'sichuan-spice-market-chengdu', category: 'FOOD', description: 'The wholesale spice quarter in the Binjiang area where Sichuan\'s most important culinary ingredients - dried red chilies, Sichuan peppercorns, doubanjiang fermented bean paste, and local mushrooms - are sold at commercial scale to Chengdu\'s restaurants. An extraordinary sensory immersion in the foundation of the world\'s spiciest cuisine.', address: 'Binjiang, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Sichuan+Spice+Market+Chengdu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/sichuan-spice-market-chengdu.jpg', tags: ['sichuan-pepper', 'chili', 'doubanjiang', 'wholesale', 'spice'] },
  { name: 'Chunxi Road Shopping Street Chengdu', slug: 'chunxi-road-shopping-chengdu', category: 'FOOD', description: 'The main commercial pedestrian street of Chengdu - a 500-meter shopping corridor with flagship international brands, Chinese fashion designers, street food carts, and the original Taikoo Li complex. Chunxi Road is the busiest retail street in western China and a fascinating window into China\'s consumer culture.', address: 'Chunxi Road, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=Chunxi+Road+Chengdu', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/chunxi-road-shopping-chengdu.jpg', tags: ['shopping', 'pedestrian', 'taikoo-li', 'fashion', 'consumer-culture'] },
  { name: 'Yulin Market Night Food Street Chengdu', slug: 'yulin-night-food-street-chengdu', category: 'FOOD', description: 'The most authentic local evening food street in Chengdu, in the Yulin residential district where the city\'s real residents (not tourists) eat. Dozens of mom-and-pop stands serving spicy rabbit head, cold sesame noodles, grilled skewers, and hand-pulled noodles from 6pm until midnight - the most honest Chengdu food experience.', address: 'Yulin South Street, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Yulin+Night+Food+Street+Chengdu', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/yulin-night-food-street-chengdu.jpg', tags: ['rabbit-head', 'sesame-noodles', 'skewers', 'local', 'night-food'] },
  // TOURIST SITES
  { name: 'Chengdu Research Base of Giant Panda Breeding', slug: 'giant-panda-base-chengdu', category: 'NATURE', description: 'The world\'s leading giant panda research and breeding center, home to over 200 giant and red pandas in naturalistic bamboo forest enclosures. Arrive at opening (7:30am) to see the morning feeding when pandas are most active - the world\'s most accessible and well-managed panda encounter and the single most-visited attraction in all of western China.', address: '1375 Xiongmao Avenue, Chenghua District, Chengdu, Sichuan 610081, China', googleMapsUrl: 'https://maps.google.com/?q=Giant+Panda+Base+Chengdu', phone: '+86 28 8351 0033', website: 'https://www.panda.org.cn', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/giant-panda-base-chengdu.jpg', tags: ['giant-panda', 'red-panda', 'breeding', 'morning-feeding', 'essential'] },
  { name: 'Wuhou Shrine Chengdu', slug: 'wuhou-shrine-chengdu', category: 'CULTURE', description: 'China\'s only temple jointly dedicated to a ruler (Liu Bei of Shu Han) and his minister (Zhuge Liang) from the Three Kingdoms period, set in a large park with ancient cypress trees, red walls, and stone carvings. The Wuhou Shrine is the most important historical site in Chengdu and the adjacent Jinli Street the best street food area.', address: 'Wuhou District, Chengdu, Sichuan 610042, China', googleMapsUrl: 'https://maps.google.com/?q=Wuhou+Shrine+Chengdu', phone: '+86 28 8555 2173', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/wuhou-shrine-chengdu.jpg', tags: ['three-kingdoms', 'liu-bei', 'zhuge-liang', 'cypress', 'essential'] },
  { name: 'Dujiangyan Irrigation System', slug: 'dujiangyan-irrigation-system-chengdu', category: 'CULTURE', description: 'A 2,300-year-old hydraulic engineering masterpiece and UNESCO World Heritage Site an hour from Chengdu, built in 256 BC to control the Min River without a dam - still fully operational today. Dujiangyan transformed the Chengdu Plain from flood-prone to the most productive agricultural land in China and the foundation of Sichuan\'s prosperity.', address: 'Dujiangyan, Chengdu, Sichuan 611800, China', googleMapsUrl: 'https://maps.google.com/?q=Dujiangyan+Irrigation+System', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/dujiangyan-irrigation-system-chengdu.jpg', tags: ['UNESCO', '256-BC', 'hydraulic', 'day-trip', '2300-years'] },
  { name: 'Mount Emei Day Trip from Chengdu', slug: 'mount-emei-day-trip-chengdu', category: 'NATURE', description: 'One of China\'s Four Sacred Buddhist Mountains, a UNESCO World Heritage Site two hours from Chengdu with a 3,100-meter summit, ancient temples at every altitude, misty monkey-filled trails, and the famous Golden Summit with a giant Puxian Bodhisattva statue. Emeishan is the most dramatically beautiful day trip from Chengdu.', address: 'Mount Emei, Leshan, Sichuan 614200, China', googleMapsUrl: 'https://maps.google.com/?q=Mount+Emei+Sichuan', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/mount-emei-day-trip-chengdu.jpg', tags: ['sacred-mountain', 'UNESCO', 'golden-summit', 'monkeys', 'day-trip'] },
  { name: 'Leshan Giant Buddha Day Trip', slug: 'leshan-giant-buddha-chengdu', category: 'CULTURE', description: 'The world\'s largest stone Buddha - a 71-meter Tang Dynasty figure carved into a cliff face at the confluence of three rivers, two hours from Chengdu. The Leshan Giant Buddha has sat meditating over the river junction since 803 AD and is both a UNESCO World Heritage Site and the most awe-inspiring sculpture in China.', address: 'Leshan, Sichuan 614000, China', googleMapsUrl: 'https://maps.google.com/?q=Leshan+Giant+Buddha', phone: null, website: null, priceRange: 'MID', rating: 4.8, imageUrl: '/spots/leshan-giant-buddha-chengdu.jpg', tags: ['giant-buddha', 'tang-dynasty', '71-meters', 'UNESCO', '803-AD'] },
  { name: 'Sanxingdui Museum Chengdu', slug: 'sanxingdui-museum-chengdu', category: 'CULTURE', description: 'One of the most important and mysterious archaeological discoveries in the world - the 4,000-year-old Sanxingdui civilization whose alien bronze masks, sacred trees, and gold artifacts have no parallel in any known ancient culture. The new museum opened in 2023 is a world-class facility housing the most extraordinary ancient bronze collection in existence.', address: 'Guanghan City, near Chengdu, Sichuan 618300, China', googleMapsUrl: 'https://maps.google.com/?q=Sanxingdui+Museum+Guanghan+Chengdu', phone: '+86 838 550 9988', website: 'https://www.sanxingdui.com', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/sanxingdui-museum-chengdu.jpg', tags: ['sanxingdui', 'bronze-masks', '4000-years', 'mysterious', 'world-class'] },
  { name: 'Sichuan Opera Face-Changing Show Chengdu', slug: 'sichuan-opera-face-changing-chengdu', category: 'CULTURE', description: 'An evening of traditional Sichuan Opera at Shufeng Yayun Teahouse or Jinsha Theatre with the famous bianlian face-changing illusion, fire-breathing, shadow puppetry, and acrobatics. The Sichuan Opera face-changing performance - where silk masks are swapped in milliseconds - is the most impressive theatrical trick in Chinese performance arts.', address: 'Shufeng Yayun Teahouse, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Sichuan+Opera+Face+Changing+Chengdu', phone: '+86 28 8776 4530', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/sichuan-opera-face-changing-chengdu.jpg', tags: ['face-changing', 'bianlian', 'opera', 'fire-breathing', 'performance'] },
  { name: 'Qingcheng Mountain National Park', slug: 'qingcheng-mountain-national-park-chengdu', category: 'NATURE', description: 'One of Taoism\'s most sacred mountains, an hour from Chengdu, with 36 ancient temples hidden in a lush forested mountain park. The walk from the base to the summit of Qingcheng Front Mountain passes tea plantations, waterfalls, ancient stone steps, and meditating Taoist monks - the most spiritual day trip from Chengdu.', address: 'Qingcheng Mountain, Dujiangyan, Chengdu, Sichuan 611830, China', googleMapsUrl: 'https://maps.google.com/?q=Qingcheng+Mountain+Sichuan', phone: null, website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/qingcheng-mountain-national-park-chengdu.jpg', tags: ['taoism', 'sacred-mountain', 'temples', 'day-trip', 'spiritual'] },
  { name: 'Tianfu Square and Mao Zedong Statue', slug: 'tianfu-square-mao-statue-chengdu', category: 'CULTURE', description: 'The central plaza of Chengdu - a monumental square dominated by the largest Mao Zedong statue in China, flanked by the provincial government building, the Sichuan Science and Technology Museum, and the underground Tianfu Square metro station. The best place to sense the scale of Chinese urban planning and modern Sichuan political identity.', address: 'Tianfu Square, Qingyang District, Chengdu, Sichuan 610015, China', googleMapsUrl: 'https://maps.google.com/?q=Tianfu+Square+Chengdu', phone: null, website: null, priceRange: 'FREE', rating: 4.4, imageUrl: '/spots/tianfu-square-mao-statue-chengdu.jpg', tags: ['mao-statue', 'central-square', 'urban-planning', 'government', 'symbolic'] },
  // COWORKING
  { name: 'MFG Lab Chengdu', slug: 'mfg-lab-chengdu', category: 'COWORKING', description: 'One of China\'s leading innovation coworking spaces in the Taikoo Li area, with a tech startup community, a hardware prototyping lab, 3D printers, laser cutters, and a regular investor demo day program. MFG Lab connects Chengdu\'s entrepreneurial scene with the resources of China\'s national innovation ecosystem.', address: 'Taikoo Li, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=MFG+Lab+Chengdu', phone: '+86 28 8610 3456', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/mfg-lab-chengdu.jpg', tags: ['innovation', 'hardware', '3d-printing', 'startup', 'investor'] },
  { name: 'Garage Cafe Chengdu', slug: 'garage-cafe-chengdu', category: 'COWORKING', description: 'A well-established coworking cafe in the tech district with fast WiFi, private meeting pods, standing desks, and a focus on the design and creative tech community. Garage Cafe Chengdu is popular with game developers, UI designers, and digital nomads who want a productive day environment close to the Chunxi Road shopping district.', address: 'Chenghua District, Chengdu, Sichuan 610081, China', googleMapsUrl: 'https://maps.google.com/?q=Garage+Cafe+Chengdu', phone: '+86 28 8666 4567', website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/garage-cafe-chengdu.jpg', tags: ['tech', 'design', 'game-dev', 'pods', 'creative'] },
  { name: 'WeWork Chengdu IFS', slug: 'wework-chengdu-ifs', category: 'COWORKING', description: 'WeWork\'s flagship Chengdu location in the IFS (International Finance Square) tower with premium private offices, hot desks, a rooftop bar, excellent meeting rooms, and the international coworking community that WeWork brings globally. The best professional infrastructure for foreign companies entering the western China market.', address: 'IFS, 1 Section 3, Hongxing Road, Jinjiang District, Chengdu, Sichuan 610021, China', googleMapsUrl: 'https://maps.google.com/?q=WeWork+Chengdu+IFS', phone: '+86 400 100 0001', website: 'https://www.wework.com/buildings/china--chengdu--ifs', priceRange: 'HIGH', rating: 4.5, imageUrl: '/spots/wework-chengdu-ifs.jpg', tags: ['wework', 'ifs', 'premium', 'international', 'western-china'] },
  { name: 'Regus Chengdu Chunxi Road', slug: 'regus-chengdu-chunxi', category: 'COWORKING', description: 'A professional serviced office and coworking center on Chunxi Road with private offices, virtual office services for company registration in China, meeting rooms, and business lounge access - particularly useful for foreign businesses establishing a Sichuan presence. The Chunxi Road location is the most central commercial location in Chengdu.', address: 'Chunxi Road, Jinjiang District, Chengdu, Sichuan 610016, China', googleMapsUrl: 'https://maps.google.com/?q=Regus+Chengdu+Chunxi', phone: '+86 28 8669 5555', website: 'https://www.regus.cn/chengdu', priceRange: 'HIGH', rating: 4.4, imageUrl: '/spots/regus-chengdu-chunxi.jpg', tags: ['regus', 'serviced-office', 'company-registration', 'chunxi', 'foreign-business'] },
  { name: 'Yibai Creative Cowork Chengdu', slug: 'yibai-creative-cowork-chengdu', category: 'COWORKING', description: 'A Chengdu-local coworking space in the creative Yulin district, designed for artists, musicians, writers, and digital creatives, with a recording studio booth, a photography studio, and a gallery space for monthly member exhibitions. The most culturally rich coworking environment in western China.', address: 'Yulin, Wuhou District, Chengdu, Sichuan 610041, China', googleMapsUrl: 'https://maps.google.com/?q=Yibai+Creative+Cowork+Chengdu', phone: '+86 28 8555 5678', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/yibai-creative-cowork-chengdu.jpg', tags: ['creative', 'recording-studio', 'photography-studio', 'gallery', 'yulin'] },
  { name: 'Chengdu Innovation Center Cowork', slug: 'chengdu-innovation-center-cowork', category: 'COWORKING', description: 'A government-backed innovation hub in the Tianfu New Area - Chengdu\'s planned tech city south of the center - with dedicated support for tech startups, access to government procurement contracts, and connections to Chengdu\'s large video game development industry (the city produces more games than anywhere outside Shanghai).', address: 'Tianfu New Area, Chengdu, Sichuan 610213, China', googleMapsUrl: 'https://maps.google.com/?q=Chengdu+Innovation+Center', phone: '+86 28 8700 3456', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/chengdu-innovation-center-cowork.jpg', tags: ['government-backed', 'tianfu', 'games', 'tech-startup', 'procurement'] },
  { name: 'Jinsha Site Museum', slug: 'jinsha-site-museum-chengdu', category: 'CULTURE', description: 'An extraordinary Bronze Age archaeological site uncovered in 2001 during construction, revealing a 3,000-year-old Shu Kingdom civilization pre-dating written history. The gold sun disc, elephant tusks, and jade artifacts on display are among the most important Bronze Age discoveries in China — a world-class museum that most Chengdu visitors miss entirely.', address: '227 Jinsha Site Road, Qingyang District, Chengdu, Sichuan 610075, China', website: 'https://www.jinshasitemuseum.com', priceRange: 'MID', tags: ['bronze-age', 'shu-kingdom', 'gold', 'jade', 'archaeology'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Chengdu: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
