const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq328ihx0011vi8w7zyznr13';

const spots = [
  // LUXURY HOTELS
  { name: 'Sofitel Legend Peoples Grand Hotel Xian', slug: 'sofitel-legend-peoples-grand-xian', category: 'ACCOMMODATION', description: 'A monumental 1953 Soviet-influenced landmark hotel at the center of Xi\'an, built as the most ambitious hotel project in post-liberation China and recently restored as a Sofitel Legend with exceptional luxury. The hotel\'s dramatic architecture, the largest hotel lobby in China, and a prime location on Chang\'an Road make it Xi\'an\'s most prestigious address.', address: '319 Dongxin Street, Xincheng District, Xi\'an, Shaanxi 710004, China', googleMapsUrl: 'https://maps.google.com/?q=Sofitel+Legend+Peoples+Grand+Hotel+Xian', phone: '+86 29 8792 8888', website: 'https://www.sofitel-legend.com/xian', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/sofitel-legend-peoples-grand-xian.jpg', tags: ['1953', 'soviet', 'monumental', 'legend', 'landmark'] },
  { name: 'Grand Mercure on Renmin Square Xian', slug: 'grand-mercure-renmin-square-xian', category: 'ACCOMMODATION', description: 'An elegant luxury hotel in a restored Republican-era building directly on Renmin Square in central Xi\'an, with beautifully preserved 1930s Chinese architecture, rooftop city views, and walking distance of the Muslim Quarter, Drum Tower, and City Wall. One of the most characterful heritage hotel conversions in China.', address: '8 Xijuyuan Lane, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Grand+Mercure+Renmin+Square+Xian', phone: '+86 29 8788 8888', website: 'https://www.grandmercure-xian.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/grand-mercure-renmin-square-xian.jpg', tags: ['republican-era', 'heritage', 'rooftop', 'renmin-square', '1930s'] },
  { name: 'Hyatt Regency Xian', slug: 'hyatt-regency-xian', category: 'ACCOMMODATION', description: 'A sleek modern tower adjacent to the Xi\'an City Wall with 509 spacious rooms, a spectacular indoor pool, multiple award-winning restaurants, and a location inside the ancient city that gives easy walking access to the Bell Tower, Drum Tower, and Muslim Quarter. The Hyatt Regency is Xi\'an\'s premier business luxury hotel.', address: '158 Dongdajie, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Hyatt+Regency+Xian', phone: '+86 29 8769 1234', website: 'https://www.hyatt.com/xian', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/hyatt-regency-xian.jpg', tags: ['indoor-pool', 'city-wall', 'bell-tower', 'business', 'modern'] },
  { name: 'Wyndham Grand Xian South', slug: 'wyndham-grand-xian-south', category: 'ACCOMMODATION', description: 'A stunning luxury hotel in the rapidly developing Qujiang New Area near the Tang Paradise theme park with dramatic architecture referencing Tang Dynasty palace design, a rooftop infinity pool with ancient pagoda views, and excellent transport to the Terracotta Warriors. The best luxury base for the south Xi\'an sights.', address: 'No. 68 Yannan Road, Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Wyndham+Grand+Xian+South', phone: '+86 29 8560 6888', website: 'https://www.wyndhamhotels.com/xian', priceRange: 'HIGH', rating: 4.6, imageUrl: '/spots/wyndham-grand-xian-south.jpg', tags: ['qujiang', 'tang-dynasty', 'infinity-pool', 'pagoda-views', 'terracotta'] },
  // BUDGET HOTELS
  { name: 'Bell Tower Youth Hostel Xian', slug: 'bell-tower-youth-hostel-xian', category: 'ACCOMMODATION', description: 'The most famous budget property in Xi\'an - a traditional courtyard guesthouse 200 meters from the Bell Tower in the heart of the ancient city, with dormitories and private rooms at budget prices, an excellent common room, and staff who have been helping travelers reach the Terracotta Warriors for 25 years.', address: 'Xian Hutong 2, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Bell+Tower+Youth+Hostel+Xian', phone: '+86 29 8728 5333', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/bell-tower-youth-hostel-xian.jpg', tags: ['bell-tower', 'courtyard', 'backpacker', '25-years', 'terracotta-help'] },
  { name: 'Shuyuan Youth Hostel Xian', slug: 'shuyuan-youth-hostel-xian', category: 'ACCOMMODATION', description: 'A charming hostel in a restored Tang Dynasty courtyard right at the south gate of the City Wall in a location that offers the most beautiful surrounding architecture of any budget property in China. Shuyuan has been consistently rated one of the top hostels in mainland China for its atmosphere, staff, and location.', address: 'South Gate, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Shuyuan+Youth+Hostel+Xian', phone: '+86 29 8727 6882', website: 'https://www.shuyuanhostel.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/shuyuan-youth-hostel-xian.jpg', tags: ['tang-dynasty', 'city-wall', 'south-gate', 'top-rated', 'atmosphere'] },
  { name: 'Xi\'an Backpacker International Youth Hostel', slug: 'xian-backpacker-international-hostel', category: 'ACCOMMODATION', description: 'A well-run hostel in the Muslim Quarter neighborhood with private rooms and dorms, a rooftop terrace with views of the Drum Tower, an excellent Silk Road tour desk, and the most convenient location in the city for exploring the old Muslim Quarter market every morning with the first mosque-goers.', address: 'Muslim Quarter area, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Xian+Backpacker+International+Hostel', phone: '+86 29 8727 5888', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/xian-backpacker-international-hostel.jpg', tags: ['muslim-quarter', 'drum-tower', 'silk-road', 'rooftop', 'morning'] },
  { name: 'Melody Hotel Xian', slug: 'melody-hotel-xian', category: 'ACCOMMODATION', description: 'A charming mid-range boutique hotel in a renovated 1950s building near the South Gate with individually decorated rooms, a garden courtyard, and a location within walking distance of Shaanxi History Museum, Small Wild Goose Pagoda, and the south City Wall. Melody Hotel offers excellent value for the quality and ambiance.', address: 'Youyi Road, Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Melody+Hotel+Xian', phone: '+86 29 8525 3888', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/melody-hotel-xian.jpg', tags: ['boutique', 'garden', 'shaanxi-museum', 'pagoda', 'south-gate'] },
  // HOSTELS
  { name: 'Flying Tiger Hostel Xian', slug: 'flying-tiger-hostel-xian', category: 'ACCOMMODATION', description: 'A social hostel inside the ancient city walls with a bar, regular events, a nightly hot pot communal dinner, and an excellent free walking tour of the Muslim Quarter every morning. Flying Tiger has one of the best free city guide programs of any hostel in China and is the top recommendation for solo travelers to Xi\'an.', address: 'Inside City Walls, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Flying+Tiger+Hostel+Xian', phone: '+86 29 8727 9999', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/flying-tiger-hostel-xian.jpg', tags: ['inside-walls', 'hot-pot', 'walking-tour', 'bar', 'solo-travel'] },
  { name: 'Han Tang Inn Hostel Xian', slug: 'han-tang-inn-hostel-xian', category: 'ACCOMMODATION', description: 'A well-designed hostel in the Nanmen area with a beautiful traditional Chinese courtyard, a rooftop terrace, and accommodation ranging from dorms to private rooms. The Han Tang Inn is particularly popular with Chinese domestic travelers and offers a good immersion in the country\'s backpacker culture.', address: 'Nanmen area, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Han+Tang+Inn+Hostel+Xian', phone: '+86 29 8726 1555', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/han-tang-inn-hostel-xian.jpg', tags: ['courtyard', 'rooftop', 'nanmen', 'domestic', 'traditional'] },
  { name: 'Tang West Market Hostel Xian', slug: 'tang-west-market-hostel-xian', category: 'ACCOMMODATION', description: 'A characterful hostel in the Tang West Market area on the western side of the ancient city with Tang Dynasty-style decor, a communal kitchen, a cinema room, and the best organized tours of the Muslim Quarter and Terracotta Warriors at fair prices. An underrated option away from the Drum Tower crowds.', address: 'Tang West Market, Lianhu District, Xi\'an, Shaanxi 710016, China', googleMapsUrl: 'https://maps.google.com/?q=Tang+West+Market+Hostel+Xian', phone: '+86 29 8727 4444', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/tang-west-market-hostel-xian.jpg', tags: ['tang-dynasty', 'cinema', 'western-city', 'tours', 'underrated'] },
  { name: 'Xiangzi Inn Hostel Xian', slug: 'xiangzi-inn-hostel-xian', category: 'ACCOMMODATION', description: 'A clean, friendly hostel in the East Street area with reliably comfortable beds, a helpful English-speaking front desk, and a location equidistant between the Muslim Quarter and the City Wall east gate. Xiangzi Inn offers the simplest, most reliable budget base for travelers who want to cover all of Xi\'an\'s main sights.', address: 'East Street, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Xiangzi+Inn+Xian', phone: '+86 29 8726 2888', website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/xiangzi-inn-hostel-xian.jpg', tags: ['east-street', 'english-staff', 'reliable', 'clean', 'central'] },
  // CAFES
  { name: 'Defachang Dumpling Restaurant Xian', slug: 'defachang-dumpling-restaurant-xian', category: 'CAFE', description: 'The most famous restaurant in Xi\'an for the legendary dumpling banquet - a multi-course meal of 18 different dumpling shapes each representing a different Tang Dynasty figure or legend. Defachang has served the definitive Xi\'an dumpling experience since 1936 and is the most visited restaurant in Shaanxi Province.', address: '3 Dong Street, Bell Tower, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Defachang+Dumpling+Restaurant+Xian', phone: '+86 29 8721 4066', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/defachang-dumpling-restaurant-xian.jpg', tags: ['dumpling-banquet', '1936', 'tang-dynasty', 'institution', 'famous'] },
  { name: 'Lao Liu Jia Paomo Xian', slug: 'lao-liu-jia-paomo-xian', category: 'CAFE', description: 'The most acclaimed traditional restaurant for yangrou paomo - Xi\'an\'s iconic dish of hand-torn unleavened bread soaked in rich mutton broth with glass noodles and vermicelli, served with pickled garlic and chili paste. Lao Liu Jia\'s paomo has been the standard for this Silk Road dish for three generations.', address: 'Muslim Quarter, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Lao+Liu+Jia+Paomo+Xian', phone: '+86 29 8727 2345', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/lao-liu-jia-paomo-xian.jpg', tags: ['paomo', 'mutton-broth', 'muslim-quarter', 'silk-road', 'three-generations'] },
  { name: 'Yongxingfang Intangible Heritage Food Street', slug: 'yongxingfang-food-street-xian', category: 'CAFE', description: 'A large indoor heritage food complex near the South City Wall where vendors preserve 100+ traditional Shaanxi food crafts - hand-pulled biangbiang noodles, persimmon cakes, rose bing pastries, liangpi cold skin noodles - in a beautifully restored Qing Dynasty building. The most comprehensive Shaanxi food experience under one roof.', address: 'Longshou Zhongluguan Jiayuan, Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Yongxingfang+Food+Street+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/yongxingfang-food-street-xian.jpg', tags: ['biangbiang', 'persimmon-cake', 'liangpi', 'heritage', 'traditional'] },
  { name: 'Kaiyuan Coffee Xian', slug: 'kaiyuan-coffee-xian', category: 'CAFE', description: 'Xi\'an\'s best specialty coffee shop in the South Gate area near the university district, with excellent single-origin pour-over coffee, beautiful campus-adjacent atmosphere, and a loyal community of university students and young professionals. The most comfortable work cafe in the ancient city.', address: 'South Gate area, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Kaiyuan+Coffee+Xian', phone: '+86 29 8525 4567', website: null, priceRange: 'MID', rating: 4.6, imageUrl: '/spots/kaiyuan-coffee-xian.jpg', tags: ['specialty', 'pour-over', 'university', 'south-gate', 'workspace'] },
  { name: 'Huxian Teahouse Xian', slug: 'huxian-teahouse-xian', category: 'CAFE', description: 'An atmospheric traditional teahouse inside the ancient city walls with private tearooms, a large selection of Shaanxi, Sichuan, and Yunnan teas, traditional Chinese instruments played in the evenings, and a beautiful wooden interior that is the best place in Xi\'an to slow down from the Terracotta Warrior rush.', address: 'Inside City Walls, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Huxian+Teahouse+Xian', phone: '+86 29 8726 3456', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/huxian-teahouse-xian.jpg', tags: ['teahouse', 'shaanxi-tea', 'instruments', 'slow-down', 'private-rooms'] },
  { name: 'Beilin Museum Coffee Bar Xian', slug: 'beilin-museum-coffee-xian', category: 'CAFE', description: 'A unique museum cafe inside the Forest of Stone Steles museum grounds, serving excellent coffee and Chinese tea among the world\'s largest collection of ancient inscribed stone tablets. Sipping coffee surrounded by 2,000-year-old Han Dynasty carved stones is among the most extraordinary cafe settings in the world.', address: 'Beilin Museum, Sanxue Street, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Beilin+Museum+Coffee+Xian', phone: '+86 29 8721 2057', website: null, priceRange: 'MID', rating: 4.7, imageUrl: '/spots/beilin-museum-coffee-xian.jpg', tags: ['museum-cafe', 'stone-steles', 'han-dynasty', 'unique', 'historic'] },
  // RESTAURANTS
  { name: 'Muslim Quarter Night Market Xian', slug: 'muslim-quarter-night-market-xian', category: 'FOOD', description: 'The most famous food street in western China - 500 meters of Muslim-Chinese street food stalls serving roujiamo meat buns, lamb skewers, stinky tofu, pomegranate juice, and dozens of other traditional Hui Muslim and Shaanxi dishes. The Muslim Quarter night market is Xi\'an\'s essential culinary experience and has been running every evening for centuries.', address: 'Huimin Street, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Muslim+Quarter+Night+Market+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/muslim-quarter-night-market-xian.jpg', tags: ['roujiamo', 'lamb-skewers', 'hui-muslim', 'centuries', 'essential'] },
  { name: 'Tongshengxiang Restaurant Xian', slug: 'tongshengxiang-restaurant-xian', category: 'FOOD', description: 'The most celebrated restaurant for paomo - the Xi\'an specialty of lamb broth with hand-torn flatbread - with a 100-year history and the most perfected version of this Silk Road dish. Tongshengxiang is a Xi\'an institution where you break the bread yourself and hand it to the kitchen, a tradition maintained since the Tang Dynasty.', address: '5 Xiyangshi Street, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Tongshengxiang+Restaurant+Xian', phone: '+86 29 8721 4706', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/tongshengxiang-restaurant-xian.jpg', tags: ['paomo', '100-year', 'lamb-broth', 'flatbread', 'institution'] },
  { name: 'Jiasan Guantang Baozi Xian', slug: 'jiasan-guantang-baozi-xian', category: 'FOOD', description: 'The most famous restaurant in Xi\'an for guantang baozi - soup-filled steamed buns with a hot savory broth inside each dumpling. Jiasan\'s mutton soup dumplings have been made the same way for four generations and the morning queue outside their tiny shop is the most authentic local experience in the Muslim Quarter.', address: 'Muslim Quarter, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Jiasan+Guantang+Baozi+Xian', phone: '+86 29 8727 1566', website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/jiasan-guantang-baozi-xian.jpg', tags: ['soup-dumplings', 'mutton', 'four-generations', 'morning-queue', 'authentic'] },
  { name: 'Lao Sun Jia Muslim Restaurant Xian', slug: 'lao-sun-jia-muslim-restaurant-xian', category: 'FOOD', description: 'The oldest and most beloved large-format Muslim restaurant in Xi\'an serving yangrou paomo, lamb hotpot, and a full menu of Hui Muslim cuisine in a massive restaurant that can seat 1,000 diners. Lao Sun Jia has operated continuously since 1898 and is where Xi\'an families bring visiting relatives for a traditional meal.', address: '364 Dong Street, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Lao+Sun+Jia+Xian', phone: '+86 29 8721 3297', website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/lao-sun-jia-muslim-restaurant-xian.jpg', tags: ['1898', 'hui-muslim', 'lamb-hotpot', '1000-seats', 'families'] },
  { name: 'Xian Biangbiang Noodles Xiaomei', slug: 'xian-biangbiang-noodles-xiaomei', category: 'FOOD', description: 'An acclaimed hand-pulled noodle restaurant serving the definitive biangbiang noodles - Xi\'an\'s iconic belt-width flat noodles with chili oil, black vinegar, and a mix of toppings. The name \'biangbiang\' uses the most complex Chinese character ever created, with 57 strokes, and this tiny restaurant serves the finest version in the city.', address: 'Near Drum Tower, Lianhu District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Xian+Biangbiang+Noodles', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/xian-biangbiang-noodles-xiaomei.jpg', tags: ['biangbiang', 'hand-pulled', 'chili-oil', 'complex-character', 'definitive'] },
  { name: 'Tang Palace Dumpling Banquet Xian', slug: 'tang-palace-dumpling-banquet-xian', category: 'FOOD', description: 'An upscale restaurant serving a refined version of the traditional dumpling banquet in an elegant Tang Dynasty-themed dining room. Each of the 18 dumpling styles is presented with a story about its Tang Dynasty origin - a food-theater experience that makes this the best upscale dining for visitors in Xi\'an.', address: 'Bell Tower area, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Tang+Palace+Dumpling+Banquet+Xian', phone: '+86 29 8721 5888', website: null, priceRange: 'HIGH', rating: 4.5, imageUrl: '/spots/tang-palace-dumpling-banquet-xian.jpg', tags: ['dumpling-banquet', 'tang-dynasty', 'food-theater', 'refined', 'upscale'] },
  // MARKETS
  { name: 'Yanta Muslim Market Xian', slug: 'yanta-muslim-market-xian', category: 'FOOD', description: 'The city\'s largest wholesale Muslim food market serving Xi\'an\'s Hui community, selling fresh lamb, spiced dried meats, Shaanxi flatbreads, Persian-origin dried fruits, and hand-made noodles. The Yanta Muslim Market is the most authentic food market in the city - zero tourist presence, entirely local commerce.', address: 'Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Yanta+Muslim+Market+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/yanta-muslim-market-xian.jpg', tags: ['wholesale', 'hui-community', 'dried-meats', 'flatbread', 'authentic'] },
  { name: 'Tang West Market Xian', slug: 'tang-west-market-xian', category: 'FOOD', description: 'A large cultural market complex built on the site of the original Tang Dynasty international market - the largest commercial hub in the ancient Silk Road world - with an underground museum showing the original market artifacts and a ground floor of Shaanxi crafts, silks, tea, and street food. History and shopping combined.', address: 'Tang West Market, Lianhu District, Xi\'an, Shaanxi 710016, China', googleMapsUrl: 'https://maps.google.com/?q=Tang+West+Market+Xian', phone: null, website: null, priceRange: 'MID', rating: 4.4, imageUrl: '/spots/tang-west-market-xian.jpg', tags: ['silk-road-market', 'tang-dynasty', 'underground-museum', 'silk', 'heritage'] },
  { name: 'Zhongxin Jiexin Night Market Xian', slug: 'zhongxin-jiexin-night-market-xian', category: 'FOOD', description: 'A lively modern night market in the university district with an excellent selection of Xi\'an street food, stinky tofu, grilled corn, roasted sweet potato, bubble tea stalls, and a young local crowd. The most energetic and affordable late-night food option in Xi\'an outside the Muslim Quarter.', address: 'University District, Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Zhongxin+Jiexin+Night+Market+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.3, imageUrl: '/spots/zhongxin-jiexin-night-market-xian.jpg', tags: ['night-market', 'university', 'stinky-tofu', 'young', 'affordable'] },
  { name: 'Shuyuanmen Culture Street Xian', slug: 'shuyuanmen-culture-street-xian', category: 'FOOD', description: 'A traditional art and craft street near the South Gate with dozens of calligraphy studios, painting galleries, antique bookshops, and souvenir stalls specializing in stone rubbings of the Forest of Steles and reproductions of Tang Dynasty art. The best street for cultural shopping and art in Xi\'an.', address: 'Shuyuanmen Street, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Shuyuanmen+Culture+Street+Xian', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/shuyuanmen-culture-street-xian.jpg', tags: ['calligraphy', 'stone-rubbings', 'tang-art', 'antique', 'culture'] },
  { name: 'Daxi Market Xian', slug: 'daxi-market-xian', category: 'FOOD', description: 'A large daily market in the Weiyang District serving northwestern Xi\'an\'s residential neighborhoods, with an extraordinary selection of Shaanxi and northwestern Chinese ingredients - hand-made vinegars, 100 varieties of dried chili, local grain alcohols, and fresh produce from the Wei River Plain. The most complete local provisions market in the city.', address: 'Weiyang District, Xi\'an, Shaanxi 710018, China', googleMapsUrl: 'https://maps.google.com/?q=Daxi+Market+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.2, imageUrl: '/spots/daxi-market-xian.jpg', tags: ['local', 'vinegar', 'dried-chili', 'grain-alcohol', 'wei-river'] },
  // TOURIST SITES
  { name: 'Terracotta Army Museum Xian', slug: 'terracotta-army-museum-xian', category: 'CULTURE', description: 'The most important archaeological discovery of the 20th century - 8,000 life-size clay soldiers, horses, and chariots buried with China\'s first emperor Qin Shi Huang in 210 BC, each with a unique face. The three excavation pits, with thousands of warriors still being restored under protective domes, are the most awe-inspiring sight in China.', address: 'Lintong District, Xi\'an, Shaanxi 710600, China', googleMapsUrl: 'https://maps.google.com/?q=Terracotta+Army+Museum+Xian', phone: '+86 29 8139 9001', website: 'https://www.bmy.com.cn', priceRange: 'MID', rating: 4.9, imageUrl: '/spots/terracotta-army-museum-xian.jpg', tags: ['terracotta', 'qin-shi-huang', '210-BC', 'UNESCO', 'most-important'] },
  { name: 'Ancient City Wall Xian', slug: 'ancient-city-wall-xian', category: 'CULTURE', description: 'The most complete ancient city wall in China - a 14km Ming Dynasty rampart from 1370, 12 meters high and 15 meters wide, encircling the entire ancient city with 98 watchtowers and 4 monumental gates. The best way to see it is to rent a bicycle and cycle the full circuit - one of the most unique urban cycling routes in the world.', address: 'City Wall, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Xian+Ancient+City+Wall', phone: null, website: null, priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/ancient-city-wall-xian.jpg', tags: ['ming-dynasty', '1370', 'cycling', '14km', 'complete'] },
  { name: 'Shaanxi History Museum Xian', slug: 'shaanxi-history-museum-xian', category: 'CULTURE', description: 'One of the finest museums in China with over 370,000 artifacts spanning 1.15 million years of human history in the Yellow River region. The Tang Dynasty gold and silver treasures, the Qin bronze weapons, and the Han Dynasty painted pottery are among the most important collections in the world - absolutely essential context for any Xi\'an visit.', address: '91 Xiaozhai East Road, Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Shaanxi+History+Museum+Xian', phone: '+86 29 8525 4727', website: 'https://www.sxhm.com', priceRange: 'BUDGET', rating: 4.8, imageUrl: '/spots/shaanxi-history-museum-xian.jpg', tags: ['history-museum', 'tang-gold', 'qin-bronze', '370000-artifacts', 'essential'] },
  { name: 'Big Wild Goose Pagoda Xian', slug: 'big-wild-goose-pagoda-xian', category: 'CULTURE', description: 'A 64-meter Tang Dynasty Buddhist pagoda built in 652 AD to house the sacred Buddhist scriptures brought back from India by the monk Xuanzang. The pagoda is the most iconic structure in Xi\'an and the surrounding Tang Paradise cultural complex with its nightly water-light fountain show is Xi\'an\'s most spectacular evening attraction.', address: 'Yanta South Road, Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Big+Wild+Goose+Pagoda+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/big-wild-goose-pagoda-xian.jpg', tags: ['652-AD', 'xuanzang', 'tang-dynasty', 'fountain-show', 'iconic'] },
  { name: 'Xi\'an Bell Tower and Drum Tower', slug: 'bell-tower-drum-tower-xian', category: 'CULTURE', description: 'The twin Ming Dynasty towers at the exact center of the ancient city - the 1384 Bell Tower and the 1380 Drum Tower - which once regulated Xi\'an\'s daily life by sounding bells at dawn and drums at dusk. The rooftop views from both towers encompass the entire ancient city grid in a panorama unchanged since the Ming Dynasty.', address: 'Bell Tower Square, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Bell+Tower+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/bell-tower-drum-tower-xian.jpg', tags: ['ming-dynasty', '1384', 'dawn-dusk', 'city-center', 'panorama'] },
  { name: 'Huaqing Palace Xian', slug: 'huaqing-palace-xian', category: 'CULTURE', description: 'An imperial hot spring palace complex at the foot of Lishan Mountain, 30km from Xi\'an, where China\'s most famous love story unfolded - Tang Emperor Xuanzong and his concubine Yang Guifei. The gardens, thermal pools, and the site of the 1936 Xi\'an Incident (where Chiang Kai-shek was arrested) make this the most layered historical site near the city.', address: 'Lishan National Forest Park, Lintong District, Xi\'an, Shaanxi 710600, China', googleMapsUrl: 'https://maps.google.com/?q=Huaqing+Palace+Xian', phone: null, website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/huaqing-palace-xian.jpg', tags: ['imperial', 'hot-spring', 'yang-guifei', 'tang-dynasty', '1936-incident'] },
  { name: 'Small Wild Goose Pagoda and Tang Cultural Heritage Park', slug: 'small-wild-goose-pagoda-xian', category: 'CULTURE', description: 'A slender Tang Dynasty pagoda from 707 AD in a beautiful park setting with less crowds than the Big Goose Pagoda, surrounded by the Xi\'an Museum of history inside the Jianfu Temple grounds. The morning tai chi practitioners, the resident peacocks in the grounds, and the tree-lined paths make it a serene contrast to Xi\'an\'s busier sites.', address: 'Youyi West Road, Beilin District, Xi\'an, Shaanxi 710065, China', googleMapsUrl: 'https://maps.google.com/?q=Small+Wild+Goose+Pagoda+Xian', phone: null, website: null, priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/small-wild-goose-pagoda-xian.jpg', tags: ['707-AD', 'serene', 'peacocks', 'tai-chi', 'museum'] },
  { name: 'Great Mosque of Xi\'an (Huajue Lane)', slug: 'great-mosque-xian', category: 'CULTURE', description: 'One of the largest and oldest mosques in China, built in 742 AD and expanded during the Ming Dynasty into a stunning blend of Islamic and Chinese architecture. The Great Mosque sits in the heart of the Muslim Quarter and its peaceful garden courtyards offer a tranquil escape from the food street bustle outside its walls.', address: 'Huajue Lane, Muslim Quarter, Lianhu District, Xi\'an, Shaanxi 710001, China', website: null, priceRange: 'BUDGET', tags: ['742-AD', 'mosque', 'chinese-islamic', 'muslim-quarter', 'garden'] },
  { name: 'Qianling Mausoleum', slug: 'qianling-mausoleum-xian', category: 'CULTURE', description: 'The joint tomb of Tang Emperor Gaozong and China\'s only female emperor Wu Zetian, buried under a natural mountain 80km from Xi\'an. The Spirit Way lined with stone statues of foreign envoys, horses, and ostriches is one of the most haunting and overlooked imperial sites in China — far fewer visitors than the Terracotta Warriors.', address: 'Qian County, Xianyang, Shaanxi 713200, China', website: null, priceRange: 'MID', tags: ['wu-zetian', 'tang-dynasty', 'spirit-way', 'mausoleum', 'overlooked'] },
  { name: 'Hanyangling Museum (Han Emperor\'s Mausoleum)', slug: 'hanyangling-museum-xian', category: 'CULTURE', description: 'The underground glass-floor museum above the burial pits of Han Emperor Jing Di, featuring thousands of miniature terracotta figures including the only known terracotta female soldiers in China. Visitors walk over glass floors with excavated pits below — a technically stunning museum experience that rivals the Terracotta Warriors in intimacy.', address: 'Weicheng District, Xianyang, Shaanxi 712000, China', website: 'https://www.hyl.cn', priceRange: 'MID', tags: ['han-dynasty', 'glass-floor', 'female-soldiers', 'underground', 'emperor-jingdi'] },
  // COWORKING
  { name: 'Sugarcode Innovation Cowork Xian', slug: 'sugarcode-innovation-cowork-xian', category: 'COWORKING', description: 'Xi\'an\'s leading tech innovation coworking space in the high-tech industrial zone, with a strong community of software engineers, game developers (Xi\'an has a significant gaming industry), and tech entrepreneurs, plus excellent event programming and startup support. The best coworking for tech professionals in Shaanxi Province.', address: 'High-Tech Zone, Xi\'an, Shaanxi 710065, China', googleMapsUrl: 'https://maps.google.com/?q=Sugarcode+Cowork+Xian', phone: '+86 29 8898 1234', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/sugarcode-innovation-cowork-xian.jpg', tags: ['tech', 'gaming', 'high-tech-zone', 'startup', 'software'] },
  { name: 'Nanmen Cowork Xian', slug: 'nanmen-cowork-xian', category: 'COWORKING', description: 'A stylish coworking space 200 meters inside the South Gate of the ancient city wall with spectacular views of the gate tower from every window, high-speed fiber, ergonomic chairs, and a community of creative professionals and digital nomads who want to work inside a 650-year-old Ming Dynasty city. The most atmospheric workspace in China.', address: 'South Gate area, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Nanmen+Cowork+Xian', phone: '+86 29 8527 2345', website: null, priceRange: 'MID', rating: 4.5, imageUrl: '/spots/nanmen-cowork-xian.jpg', tags: ['south-gate', 'city-wall', 'ming-dynasty', 'atmospheric', 'nomad'] },
  { name: 'WeWork Xian Greenland Center', slug: 'wework-xian-greenland', category: 'COWORKING', description: 'WeWork\'s Xi\'an flagship in the Greenland Pylon tower in the High-Tech Zone with the full WeWork service - hot desks, private offices, meeting rooms, a rooftop bar, and international community events. The best connected professional workspace for foreign businesses and international companies entering the Xi\'an and northwestern China market.', address: 'Greenland Pylon, High-Tech Zone, Xi\'an, Shaanxi 710065, China', googleMapsUrl: 'https://maps.google.com/?q=WeWork+Xian+Greenland', phone: '+86 400 100 0001', website: 'https://www.wework.com/buildings/china--xian', priceRange: 'HIGH', rating: 4.4, imageUrl: '/spots/wework-xian-greenland.jpg', tags: ['wework', 'high-tech', 'rooftop', 'international', 'greenland'] },
  { name: 'Xi\'an University District Cowork', slug: 'xian-university-district-cowork', category: 'COWORKING', description: 'A coworking space in the Yanta University District surrounded by over 50 universities and research institutes, with a community heavily weighted toward academics, researchers, and PhD-level entrepreneurs. The monthly lecture series from Jiaotong University and Northwest University professors is unlike any other coworking event in China.', address: 'Yanta District, Xi\'an, Shaanxi 710061, China', googleMapsUrl: 'https://maps.google.com/?q=Xian+University+District+Cowork', phone: '+86 29 8525 3456', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/xian-university-district-cowork.jpg', tags: ['academic', 'university', 'research', 'lectures', 'phd'] },
  { name: 'Silk Road Cowork Xian', slug: 'silk-road-cowork-xian', category: 'COWORKING', description: 'A coworking space near the Tang West Market area with a design theme celebrating Xi\'an\'s Silk Road heritage, dedicated support for import/export businesses and cross-border e-commerce, and connections to the Xi\'an international trade community. Particularly useful for businesses working with Central Asian and Middle Eastern markets.', address: 'Tang West Market area, Lianhu District, Xi\'an, Shaanxi 710016, China', googleMapsUrl: 'https://maps.google.com/?q=Silk+Road+Cowork+Xian', phone: '+86 29 8763 4567', website: null, priceRange: 'MID', rating: 4.3, imageUrl: '/spots/silk-road-cowork-xian.jpg', tags: ['silk-road', 'import-export', 'central-asia', 'trade', 'heritage-design'] },
  { name: 'Bell Tower Creative Hub Xian', slug: 'bell-tower-creative-hub-xian', category: 'COWORKING', description: 'A creative coworking and events space in a restored Republican-era building near the Bell Tower with a photography studio, a ceramic workshop, a printmaking room, and a gallery space for monthly member exhibitions. The cultural crossroads of Xi\'an\'s creative scene and a community of artists, designers, and cultural entrepreneurs.', address: 'Bell Tower area, Beilin District, Xi\'an, Shaanxi 710001, China', googleMapsUrl: 'https://maps.google.com/?q=Bell+Tower+Creative+Hub+Xian', phone: '+86 29 8722 5678', website: null, priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/bell-tower-creative-hub-xian.jpg', tags: ['creative', 'ceramics', 'printmaking', 'gallery', 'republican-era'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log("Xi'an: created=" + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
