const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rflri000hvimopx6kvsmm';

const spots = [
  // ACCOMMODATION — luxury/boutique
  { name: 'Four Seasons Hotel Prague', slug: 'four-seasons-prague', category: 'ACCOMMODATION', description: "Three Renaissance and Baroque buildings joined together on the Vltava riverbank, with views of Charles Bridge and Prague Castle from every riverside room. The Four Seasons Prague is the finest address in the city — impeccable service, an exceptional spa, and the most dramatic location in Central Europe.", address: 'Veleslavínova 2a, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Four+Seasons+Hotel+Prague', phone: '+420 221 427 000', website: 'https://www.fourseasons.com/prague', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/four-seasons-prague.jpg', tags: ['luxury', 'vltava', 'charles-bridge-view', 'baroque', 'spa'] },
  { name: 'Hotel Josef Prague', slug: 'hotel-josef-prague', category: 'ACCOMMODATION', description: "Eva Jiřičná's award-winning glass-and-steel design hotel in the Jewish Quarter — a cool, minimalist contrast to Prague's Baroque streetscape. The glass-spiral staircase and interior courtyard garden are architectural landmarks in their own right.", address: 'Rybná 20, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Josef+Prague', phone: '+420 221 700 111', website: 'https://www.hoteljosef.com', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/hotel-josef-prague.jpg', tags: ['design', 'jewish-quarter', 'minimalist', 'glass', 'boutique'] },
  // ACCOMMODATION — mid-range
  { name: 'Mosaic House Design Hotel', slug: 'mosaic-house-prague', category: 'ACCOMMODATION', description: "A stylish Art Nouveau building near Náměstí Míru with a split personality — design hotel and social hostel under one roof, sharing the city's best rooftop terrace and a lively bar. The private rooms have the feel of a boutique hotel at hostel prices on the right nights.", address: 'Odbojářů 4, 150 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Mosaic+House+Prague', phone: '+420 246 008 750', website: 'https://www.mosaichouse.com', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/mosaic-house-prague.jpg', tags: ['hybrid', 'rooftop', 'art-nouveau', 'bar', 'design'] },
  { name: 'Vintage Design Hotel Sax', slug: 'vintage-design-hotel-sax-prague', category: 'ACCOMMODATION', description: "A charming retro-design hotel in Malá Strana (Lesser Town) where every room is decorated in 1950s–70s Czechoslovak design aesthetic — original furniture, vinyl record players, and vintage Czech posters. Steps from Charles Bridge and perfectly located for Prague Castle.", address: 'Jánský Vršek 3, 118 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Vintage+Design+Hotel+Sax+Prague', phone: '+420 257 531 268', website: 'https://www.hotelsax.cz', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/vintage-design-hotel-sax-prague.jpg', tags: ['retro', 'mala-strana', 'vintage', 'charles-bridge', 'design'] },
  // ACCOMMODATION — hostels
  { name: 'Sir Toby\'s Hostel', slug: 'sir-tobys-hostel-prague', category: 'ACCOMMODATION', description: "Prague's most-loved independent hostel in a beautiful 1920s building in Holešovice — the city's most interesting neighborhood, away from the tourist center. Excellent breakfast, a great bar, neighborhood tours, and a local vibe that the Old Town hostels can't replicate.", address: 'Dělnická 24, 170 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Sir+Toby+Hostel+Prague', phone: '+420 246 032 610', website: 'https://www.sirtobys.com', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/sir-tobys-hostel-prague.jpg', tags: ['hostel', 'holesovice', 'local', 'breakfast', 'bar'] },
  { name: 'Czech Inn', slug: 'czech-inn-prague', category: 'ACCOMMODATION', description: "Award-winning design hostel in Vinohrady with architect-designed communal spaces, private and dorm rooms, and a bar that feels like a concept restaurant. The Vinohrady location means local cafés, parks, and restaurants rather than the souvenir shops of the Old Town.", address: 'Francouzská 76, 101 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Czech+Inn+Prague', phone: '+420 267 267 600', website: 'https://www.czech-inn.com', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/czech-inn-prague.jpg', tags: ['hostel', 'design', 'vinohrady', 'architect', 'bar'] },
  // CAFES
  { name: 'Café Savoy Prague', slug: 'cafe-savoy-prague', category: 'CAFE', description: "A grand 19th-century neo-Renaissance café in Malá Strana with a ceiling fresco, ornate chandeliers, and impeccably trained waitstaff in white jackets. The morning pastry cabinet is the finest in Prague — croissants, sourdough, and the legendary chlebíčky (Czech open-faced sandwiches).", address: 'Vítězná 5, 150 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Cafe+Savoy+Prague', phone: '+420 257 311 562', website: 'https://www.cafesavoy.ambi.cz', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/cafe-savoy-prague.jpg', tags: ['grand-cafe', 'neo-renaissance', 'pastry', 'historic', 'mala-strana'] },
  { name: 'EMA Espresso Bar', slug: 'ema-espresso-bar-prague', category: 'CAFE', description: "Prague's most respected specialty coffee bar in the New Town, with rotating single-origin filter coffees, exceptional espresso, and a cult following among the city's coffee community. Minimal interior, maximum quality — the standard against which all Prague coffee is measured.", address: 'nám. Republiky 5, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=EMA+Espresso+Bar+Prague', phone: '+420 774 697 777', website: 'https://www.emacoffee.cz', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/ema-espresso-bar-prague.jpg', tags: ['specialty', 'single-origin', 'minimalist', 'community', 'quality'] },
  { name: 'Kavárna Nová Cukrárna', slug: 'kavarna-nova-cukrarna-prague', category: 'CAFE', description: "A beautiful patisserie-café in a restored Jugendstil building in Vinohrady, producing the city's finest Czech pastries — medovník (honey cake), větrník (cream-filled choux), and seasonal tarts. The garden terrace fills with Vinohrady's creative class every Sunday morning.", address: 'Mánesova 73, 120 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Nova+Cukrarna+Prague', phone: '+420 602 100 462', website: null, priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/kavarna-nova-cukrarna-prague.jpg', tags: ['patisserie', 'czech-pastry', 'vinohrady', 'jugendstil', 'terrace'] },
  // FOOD
  { name: 'Lokál Dlouhááá', slug: 'lokal-dlouhaaa-prague', category: 'FOOD', description: "The best Czech pub in Prague — a long, beautifully tiled beer hall in the Old Town serving Pilsner Urquell tankové (tank-fresh, unpasteurised) at the ideal 3-degree serving temperature, alongside classic Czech pub food: svíčková, goulash, and smažený sýr. The Lokál chain has perfected the Czech pub experience.", address: 'Dlouhá 33, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Lokal+Dlouhaaa+Prague', phone: '+420 734 283 874', website: 'https://lokal-dlouha.ambi.cz', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/lokal-dlouhaaa-prague.jpg', tags: ['czech-pub', 'pilsner', 'tank-beer', 'svickova', 'old-town'] },
  { name: 'Manifesto Market Prague', slug: 'manifesto-market-prague', category: 'FOOD', description: "A hip street food market made from repurposed shipping containers in Florenc, with 20+ vendors serving everything from Korean tacos to Czech chlebíčky. The design, the vibe, and the quality are well above the standard Central European street food market.", address: 'Na Florenci 21, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Manifesto+Market+Prague', phone: null, website: 'https://www.manifestomarket.com', priceRange: 'BUDGET', rating: 4.4, imageUrl: '/spots/manifesto-market-prague.jpg', tags: ['street-food', 'containers', 'varied', 'hip', 'florenc'] },
  { name: 'Naše Maso', slug: 'nase-maso-prague', category: 'FOOD', description: "A legendary craft butcher and standing-room restaurant in the Old Town producing the best beef tartare in Prague — hand-cut on a marble counter, seasoned to your specification, served with sourdough toast and the most generous portion size in the city.", address: 'Dlouhá 39, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Nase+Maso+Prague', phone: '+420 222 311 378', website: 'https://www.nasemaso.cz', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/nase-maso-prague.jpg', tags: ['beef-tartare', 'butcher', 'standing', 'old-town', 'legendary'] },
  // CULTURE
  { name: 'Prague Castle', slug: 'prague-castle', category: 'CULTURE', description: "The largest ancient castle complex in the world — a 70,000m² ensemble of Gothic cathedrals, Baroque palaces, Romanesque churches, and Renaissance gardens overlooking the city. The castle complex includes St. Vitus Cathedral, the Royal Palace, and Golden Lane. Allow a full day.", address: 'Hradčany, 119 08 Prague', googleMapsUrl: 'https://maps.google.com/?q=Prague+Castle', phone: '+420 224 372 423', website: 'https://www.hrad.cz', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/prague-castle.jpg', tags: ['castle', 'largest', 'cathedral', 'panoramic', 'must-see'] },
  { name: 'Charles Bridge', slug: 'charles-bridge-prague', category: 'CULTURE', description: "The most beautiful bridge in Central Europe — a 14th-century Gothic stone bridge lined with 30 Baroque statues of saints, connecting the Old Town to Malá Strana. Visit at 5am for the extraordinary experience of the statues lit by dawn light with no crowds. UNESCO World Heritage Site.", address: 'Karlův most, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Charles+Bridge+Prague', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/charles-bridge-prague.jpg', tags: ['bridge', 'gothic', 'baroque-statues', 'visit-dawn', 'iconic'] },
  { name: 'Old Town Square', slug: 'old-town-square-prague', category: 'CULTURE', description: "The medieval heart of Prague — a cobblestone square ringed by Gothic and Baroque architecture, centered on the 15th-century Astronomical Clock, the Gothic twin-spired Týn Church, and the Jan Hus Memorial. The clock performs an hourly mechanical show from 8am to 10pm.", address: 'Staroměstské náměstí, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Old+Town+Square+Prague', phone: null, website: null, priceRange: 'FREE', rating: 4.7, imageUrl: '/spots/old-town-square-prague.jpg', tags: ['square', 'astronomical-clock', 'gothic', 'baroque', 'iconic'] },
  { name: 'Prague Astronomical Clock', slug: 'prague-astronomical-clock', category: 'CULTURE', description: "The world's oldest working astronomical clock, installed in 1410 on the Old Town Hall tower. Every hour, the clock performs a mechanical procession of the Twelve Apostles, while the four symbolic figures (Death, Vanity, Greed, Pagan) move below. Climb the tower for panoramic views.", address: 'Staroměstské náměstí 1, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Prague+Astronomical+Clock', phone: '+420 775 400 052', website: 'https://www.staromestskaradnice.cz', priceRange: 'BUDGET', rating: 4.5, imageUrl: '/spots/prague-astronomical-clock.jpg', tags: ['clock', '1410', 'hourly-show', 'tower', 'medieval'] },
  { name: 'Josefov Jewish Quarter', slug: 'josefov-jewish-quarter-prague', category: 'CULTURE', description: "One of the most important Jewish heritage sites in the world — six synagogues, the oldest Jewish cemetery in Central Europe, and the Jewish Town Hall clustered in the Old Town's former ghetto. The Old-New Synagogue (1270) is the oldest functioning synagogue in Europe.", address: 'Josefov, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Josefov+Prague', phone: '+420 222 317 191', website: 'https://www.jewishmuseum.cz', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/josefov-jewish-quarter-prague.jpg', tags: ['jewish-heritage', 'synagogue', 'cemetery', 'must-see', 'history'] },
  { name: 'Vyšehrad Fortress', slug: 'vysehrad-prague', category: 'CULTURE', description: "Prague's other great hilltop monument — a medieval fortress above the Vltava with legendary cemetery (where Dvořák and Smetana are buried), a Romanesque rotunda, and panoramic views of the river valley. Far less crowded than Prague Castle; far more atmospheric.", address: 'V Pevnosti 159/5b, 128 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Vysehrad+Prague', phone: '+420 241 410 348', website: 'https://www.praha-vysehrad.cz', priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/vysehrad-prague.jpg', tags: ['fortress', 'cemetery', 'dvořák', 'panoramic', 'less-crowded'] },
  { name: 'Petřín Tower and Gardens', slug: 'petrin-tower-prague', category: 'NATURE', description: "Prague's answer to the Eiffel Tower — a 60-meter steel lookout tower built in 1891, reached by funicular railway up a forested hill with orchards, gardens, and a mirror maze. The view from the top encompasses the entire city; the walk down through the orchards is magical in spring.", address: 'Petřínské sady, 118 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Petrin+Tower+Prague', phone: '+420 257 320 112', website: 'https://www.muzeumprahy.cz', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/petrin-tower-prague.jpg', tags: ['tower', 'views', 'funicular', 'gardens', 'spring-blossoms'] },
  // COWORKING
  { name: 'Locus Workspace Prague', slug: 'locus-workspace-prague', category: 'COWORKING', description: "A beautifully designed coworking space in Vinohrady with high ceilings, natural light, and a community of Prague's best designers, writers, and developers. Day passes available; the monthly events and skill-sharing sessions are some of the best in the city.", address: 'Blanická 29, 120 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Locus+Workspace+Prague', phone: '+420 773 220 073', website: 'https://www.locusworkspace.cz', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/locus-workspace-prague.jpg', tags: ['coworking', 'vinohrady', 'design', 'community', 'day-pass'] },
  { name: 'Impact Hub Prague', slug: 'impact-hub-prague', category: 'COWORKING', description: "Part of the global Impact Hub network, Prague's version is in a converted factory in Holešovice with a strong focus on social enterprise, sustainability, and the NGO community. Excellent events calendar, rooftop terrace, and a member base that is doing genuinely interesting work.", address: 'Drtinova 557/10, 150 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Impact+Hub+Prague', phone: '+420 774 545 045', website: 'https://www.hubpraha.cz', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/impact-hub-prague.jpg', tags: ['coworking', 'impact', 'social-enterprise', 'holesovice', 'rooftop'] },
  // NIGHTLIFE
  { name: 'Hemingway Bar Prague', slug: 'hemingway-bar-prague', category: 'NIGHTLIFE', description: "One of Europe's great cocktail bars — a tiny, perfectly appointed Art Deco bar in the Old Town where the bartenders in white jackets make the finest pre-Prohibition cocktails outside of New York. The absinthe service and the Hemingway Daiquiri are legendary.", address: 'Karolíny Světlé 26, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Hemingway+Bar+Prague', phone: '+420 773 974 764', website: 'https://www.hemingwaybar.cz', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/hemingway-bar-prague.jpg', tags: ['cocktails', 'art-deco', 'bartenders', 'absinthe', 'intimate'] },
  { name: 'Cross Club Prague', slug: 'cross-club-prague', category: 'NIGHTLIFE', description: "Prague's most extraordinary nightclub — an industrial complex of pipes, gears, and screens in Holešovice that looks like the set of a steampunk film. Multiple floors of techno, drum & bass, and experimental electronic music. The outdoor terrace and the décor alone are worth the trip.", address: 'Plynární 1096/23, 170 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Cross+Club+Prague', phone: '+420 736 535 053', website: 'https://www.crossclub.cz', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/cross-club-prague.jpg', tags: ['nightclub', 'steampunk', 'techno', 'industrial', 'holesovice'] },
  // WELLNESS
  { name: 'Prague City Bike Tours', slug: 'prague-city-bike-tour', category: 'WELLNESS', description: "The best way to see Prague — a 3-hour guided cycling tour through the Old Town, Holešovice, and Letná Park with small groups and excellent local guides who know the city's history and hidden corners. A much more active and social alternative to the walking tours.", address: 'Náměstí Jana Palacha 3, 110 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Prague+Bike+Tours', phone: '+420 776 180 771', website: 'https://www.praguebiketours.cz', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/prague-city-bike-tour.jpg', tags: ['cycling', 'guided-tour', 'social', 'active', 'morning'] },
  { name: 'Letná Park Prague', slug: 'letna-park-prague', category: 'NATURE', description: "A vast hilltop park above the Vltava bend with the city's finest panoramic viewpoint, a beloved beer garden (pivnice), and cycling and running paths through chestnut forests. The giant metronome (site of the world's largest Stalin statue, demolished in 1962) is an interesting footnote.", address: 'Letenské sady, 170 00 Prague', googleMapsUrl: 'https://maps.google.com/?q=Letna+Park+Prague', phone: null, website: null, priceRange: 'FREE', rating: 4.6, imageUrl: '/spots/letna-park-prague.jpg', tags: ['park', 'panoramic', 'beer-garden', 'cycling', 'free'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Prague: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
