const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const CITY_ID = 'cmq4rfnh2000nvimon9rl90fe';

const spots = [
  // ACCOMMODATION
  { name: 'Hotel Sacher Wien', slug: 'hotel-sacher-wien', category: 'ACCOMMODATION', description: "Vienna's most famous hotel and the birthplace of the Sachertorte — a 5-star institution on Philharmonikerstrasse opposite the State Opera since 1876. The red velvet salons, original oil paintings, and impeccable service encapsulate everything that is extraordinary about Viennese hospitality.", address: 'Philharmonikerstraße 4, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Sacher+Wien', phone: '+43 1 51456 0', website: 'https://www.sacher.com', priceRange: 'HIGH', rating: 4.8, imageUrl: '/spots/hotel-sacher-wien.jpg', tags: ['luxury', 'sachertorte', 'state-opera', '1876', 'iconic'] },
  { name: 'Das Triest Hotel Vienna', slug: 'das-triest-hotel-vienna', category: 'ACCOMMODATION', description: "Designed by Terence Conran, this stylish boutique hotel near the Naschmarkt occupies a former staging post for coaches between Vienna and Trieste. The courtyard garden, rooftop lounge, and Collio restaurant make it one of the most atmospheric places to stay in the 4th district.", address: 'Wiedner Hauptstraße 12, 1040 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Das+Triest+Hotel+Vienna', phone: '+43 1 589 180', website: 'https://www.dastriest.at', priceRange: 'HIGH', rating: 4.7, imageUrl: '/spots/das-triest-hotel-vienna.jpg', tags: ['conran', 'boutique', 'naschmarkt', 'courtyard', 'design'] },
  { name: 'Hotel Rathaus Wein & Design', slug: 'hotel-rathaus-wein-design-vienna', category: 'ACCOMMODATION', description: "A wine-lover's boutique hotel where every room is dedicated to a specific Austrian winemaker, with samples from that producer on arrival. Located in the 8th district, the hotel is perfectly placed for the MuseumsQuartier, the Ringstraße, and Vienna's best restaurant strip.", address: 'Lange Gasse 13, 1080 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Hotel+Rathaus+Wein+Design+Vienna', phone: '+43 1 400 1122', website: 'https://www.hotel-rathaus-wien.at', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/hotel-rathaus-wein-design-vienna.jpg', tags: ['wine-theme', 'austrian-wine', 'museumsquartier', 'boutique', 'unique'] },
  { name: 'Wombat\'s Vienna Naschmarkt', slug: 'wombats-vienna-naschmarkt', category: 'ACCOMMODATION', description: "Vienna's best hostel by a wide margin — a thoughtfully designed, professionally run hostel with an excellent bar, clean dorms, private rooms, and a perfect location beside the Naschmarkt. Wombat's has redefined hostel hospitality and consistently wins Europe's best hostel awards.", address: 'Rechte Wienzeile 35, 1040 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Wombats+Vienna+Naschmarkt', phone: '+43 1 897 2336', website: 'https://www.wombats-hostels.com/vienna/naschmarkt/', priceRange: 'BUDGET', rating: 4.7, imageUrl: '/spots/wombats-vienna-naschmarkt.jpg', tags: ['hostel', 'naschmarkt', 'bar', 'clean', 'award-winning'] },
  { name: 'Ruby Lilly Hotel Vienna', slug: 'ruby-lilly-hotel-vienna', category: 'ACCOMMODATION', description: "A lean luxury concept hotel in the 7th district with beautifully designed rooms, a 24-hour bar, and thoughtful amenities at a price point that makes sense. Ruby Hotels invented the lean luxury category; Vienna's edition is among their best.", address: 'Mariahilfer Straße 98-100, 1070 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Ruby+Lilly+Hotel+Vienna', phone: '+43 1 205 1550', website: 'https://www.ruby-hotels.com/en/hotels/vienna/ruby-lilly', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/ruby-lilly-hotel-vienna.jpg', tags: ['lean-luxury', '7th-district', 'design', '24h-bar', 'accessible'] },
  // CAFES
  { name: 'Café Central Vienna', slug: 'cafe-central-vienna', category: 'CAFE', description: "One of the great European coffeehouses — a vaulted marble hall in the Palais Ferstel where Freud, Hitler, Lenin, and Trotsky all took their morning papers. The Melange (Viennese coffee with milk foam) and flaky Apfelstrudel are both outstanding. Touristy but absolutely worth it.", address: 'Herrengasse 14, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Cafe+Central+Vienna', phone: '+43 1 533 3763', website: 'https://www.cafecentral.wien', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/cafe-central-vienna.jpg', tags: ['grand-cafe', 'historic', 'freud', 'melange', 'strudel'] },
  { name: 'Café Hawelka', slug: 'cafe-hawelka-vienna', category: 'CAFE', description: "The most legendary Viennese coffeehouse — an unchanged 1930s interior where Hundertwasser, Kokoschka, and every significant Viennese artist of the 20th century sat. The Buchteln (sweet dumplings served only after 10pm) are the dessert Vienna is most sentimental about.", address: 'Dorotheergasse 6, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Cafe+Hawelka+Vienna', phone: '+43 1 512 8230', website: 'https://hawelka.at', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/cafe-hawelka-vienna.jpg', tags: ['legendary', '1930s', 'artists', 'buchteln', 'unchanged'] },
  { name: 'Supersense Vienna', slug: 'supersense-vienna', category: 'CAFE', description: "The most interesting café in Vienna — a concept store and café celebrating analog culture (film photography, vinyl records, letterpress, instant cameras) with excellent specialty coffee and a community of creatives who find it impossible to leave.", address: 'Praterstraße 70, 1020 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Supersense+Vienna', phone: '+43 1 920 4695', website: 'https://www.supersense.com', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/supersense-vienna.jpg', tags: ['analog', 'vinyl', 'film', 'specialty-coffee', 'creative'] },
  // FOOD
  { name: 'Naschmarkt Vienna', slug: 'naschmarkt-vienna', category: 'FOOD', description: "Vienna's legendary 1.5km open-air market — a Jugendstil strip of 120 stalls selling everything from Syrian spices and Turkish pickles to Austrian cheeses, Styrian pumpkin oil, and the finest smoked fish in Central Europe. The Saturday flea market alongside is one of Europe's best.", address: 'Linke Wienzeile, 1060 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Naschmarkt+Vienna', phone: null, website: 'https://www.naschmarkt-wien.com', priceRange: 'BUDGET', rating: 4.6, imageUrl: '/spots/naschmarkt-vienna.jpg', tags: ['market', 'spices', 'cheese', 'saturday-flea', 'jugendstil'] },
  { name: 'Steirereck im Stadtpark', slug: 'steirereck-vienna', category: 'FOOD', description: "The best restaurant in Austria and one of the top 10 in the world (World's 50 Best) — a glass pavilion in Stadtpark where chef Heinz Reitbauer's tasting menu elevates Austrian and Central European ingredients to extraordinary heights. Book months in advance.", address: 'Am Heumarkt 2A, 1030 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Steirereck+Vienna', phone: '+43 1 713 3168', website: 'https://www.steirereck.at', priceRange: 'HIGH', rating: 4.9, imageUrl: '/spots/steirereck-vienna.jpg', tags: ['world-50-best', 'tasting-menu', 'austrian', 'stadtpark', 'book-months-ahead'] },
  { name: 'Zum Wohl Wine Bar', slug: 'zum-wohl-wine-bar-vienna', category: 'FOOD', description: "Vienna's best natural wine bar — a relaxed, candlelit space in the 1st district with an all-Austrian wine list of 100+ natural producers, charcuterie boards, and the most knowledgeable staff about Austrian wine outside of a winery. Perfect for solo dinner at the bar.", address: 'Riemergasse 12, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Zum+Wohl+Vienna', phone: '+43 1 512 4950', website: 'https://www.zum-wohl.at', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/zum-wohl-wine-bar-vienna.jpg', tags: ['natural-wine', 'austrian', 'charcuterie', 'candlelit', 'solo-bar'] },
  // CULTURE
  { name: 'Schönbrunn Palace', slug: 'schonbrunn-palace-vienna', category: 'CULTURE', description: "The Habsburg empire's summer residence — a 1,441-room Baroque palace with the world's oldest zoo (founded 1752), manicured gardens, a triumphal arch, and a hilltop Gloriette offering Vienna's finest city panorama. The Grand Tour of 40 Imperial rooms is the must-see ticket.", address: 'Schönbrunner Schloßstraße 47, 1130 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Schonbrunn+Palace+Vienna', phone: '+43 1 811 130', website: 'https://www.schoenbrunn.at', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/schonbrunn-palace-vienna.jpg', tags: ['palace', 'baroque', 'zoo', 'gardens', 'imperial'] },
  { name: 'Belvedere Palace & Museum', slug: 'belvedere-palace-vienna', category: 'CULTURE', description: "Two Baroque palaces in formal gardens housing the finest collection of Austrian art — the Upper Belvedere contains Klimt's 'The Kiss' and Schiele's collection; the Lower Belvedere holds a mirror hall and museum of medieval art. The golden Klimt room is unmissable.", address: 'Prinz-Eugen-Straße 27, 1030 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Belvedere+Palace+Vienna', phone: '+43 1 795 570', website: 'https://www.belvedere.at', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/belvedere-palace-vienna.jpg', tags: ['klimt', 'the-kiss', 'schiele', 'baroque', 'austrian-art'] },
  { name: 'Kunsthistorisches Museum', slug: 'kunsthistorisches-museum-vienna', category: 'CULTURE', description: "One of the world's great art museums — the Imperial collection of Raphael, Titian, Vermeer, Bruegel, Caravaggio, and Velázquez in a palatial 1891 building facing the Natural History Museum. The coffered main hall with a Canova-decorated staircase is one of Europe's great museum interiors.", address: 'Maria-Theresien-Platz, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Kunsthistorisches+Museum+Vienna', phone: '+43 1 525 240', website: 'https://www.khm.at', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/kunsthistorisches-museum-vienna.jpg', tags: ['museum', 'raphael', 'bruegel', 'imperial-collection', 'must-see'] },
  { name: 'Vienna State Opera', slug: 'vienna-state-opera', category: 'CULTURE', description: "One of the world's leading opera houses — a Neo-Renaissance building on the Ringstraße that has staged world premieres and hosted the greatest conductors and singers since 1869. Standing tickets (Stehplätze) cost €4 and are sold 80 minutes before curtain; the best-value ticket in Vienna's cultural life.", address: 'Opernring 2, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Vienna+State+Opera', phone: '+43 1 514 442 250', website: 'https://www.wiener-staatsoper.at', priceRange: 'MID', rating: 4.8, imageUrl: '/spots/vienna-state-opera.jpg', tags: ['opera', 'standing-tickets', 'neo-renaissance', 'world-premiere', 'affordable'] },
  { name: 'Prater & Riesenrad', slug: 'prater-riesenrad-vienna', category: 'NATURE', description: "Vienna's vast urban park along the Danube — the historic amusement park (Wurstelprater), chestnut-lined cycling avenues, and the 1897 Riesenrad (Giant Ferris Wheel) that features in The Third Man. Hire a bike and cycle the Hauptallee; ride the ferris wheel at sunset.", address: 'Prater, 1020 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Prater+Vienna', phone: null, website: 'https://www.praterwien.com', priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/prater-riesenrad-vienna.jpg', tags: ['park', 'ferris-wheel', 'third-man', 'cycling', 'chestnut-allee'] },
  { name: 'MuseumsQuartier Vienna', slug: 'museumsquartier-vienna', category: 'CULTURE', description: "One of the largest cultural complexes in the world — a converted Imperial stable housing MUMOK (modern art), the Leopold Museum (Schiele and Klimt), Kunsthalle, the Architecture Center, and the Electric Avenue outdoor space where young Viennese gather in summer on colored Enzis (deckchairs).", address: 'Museumsplatz 1, 1070 Vienna', googleMapsUrl: 'https://maps.google.com/?q=MuseumsQuartier+Vienna', phone: '+43 1 523 5881', website: 'https://www.mqw.at', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/museumsquartier-vienna.jpg', tags: ['museums', 'schiele', 'mumok', 'courtyard', 'summer-meeting-point'] },
  // COWORKING
  { name: 'CoSpace Vienna', slug: 'cospace-vienna', category: 'COWORKING', description: "A beautifully designed coworking space in the 7th district near the MuseumsQuartier with excellent natural light, private phone booths, meeting rooms, and a friendly community of Vienna's creatives and startups. Day passes and weekly passes available.", address: 'Lindengasse 30, 1070 Vienna', googleMapsUrl: 'https://maps.google.com/?q=CoSpace+Vienna', phone: '+43 1 522 3645', website: 'https://www.cospace.at', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/cospace-vienna.jpg', tags: ['coworking', '7th-district', 'natural-light', 'day-pass', 'creatives'] },
  { name: 'Talent Garden Vienna', slug: 'talent-garden-vienna', category: 'COWORKING', description: "The Vienna outpost of Europe's biggest tech coworking network — a dynamic campus in Mariahilf with a strong startup community, regular networking events, and the fastest route into Vienna's growing tech ecosystem.", address: 'Gumpendorfer Str. 15, 1060 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Talent+Garden+Vienna', phone: '+43 1 9420 9110', website: 'https://talentgarden.com/campus/vienna', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/talent-garden-vienna.jpg', tags: ['startup', 'tech', 'campus', 'networking', 'mariahilf'] },
  // NIGHTLIFE / WELLNESS
  { name: 'Volksgarten Clubdiskothek', slug: 'volksgarten-vienna', category: 'NIGHTLIFE', description: "Vienna's most beloved outdoor club — a sprawling garden venue on the Ringstraße that transforms from an afternoon café terrace into an open-air dance floor and club after dark. The Volksgarten is the most uniquely Viennese nightlife experience, blending elegance with genuine hedonism.", address: 'Burgring 1, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Volksgarten+Vienna', phone: '+43 1 532 0907', website: 'https://www.volksgarten.at', priceRange: 'MID', rating: 4.5, imageUrl: '/spots/volksgarten-vienna.jpg', tags: ['outdoor-club', 'ringstrasse', 'garden', 'elegant', 'summer'] },
  { name: 'Stadtpark Vienna', slug: 'stadtpark-vienna', category: 'NATURE', description: "Vienna's main city park along the Wien River — site of the famous golden Johann Strauss statue, the Kursalon concert hall (where Strauss himself conducted), and one of Vienna's most pleasant walking circuits. Free Sunday morning classical music performances run May through September.", address: 'Parkring 1, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Stadtpark+Vienna', phone: null, website: null, priceRange: 'FREE', rating: 4.5, imageUrl: '/spots/stadtpark-vienna.jpg', tags: ['park', 'strauss-statue', 'walking', 'free-concerts', 'romantic'] },
  { name: 'Therme Wien', slug: 'therme-wien', category: 'WELLNESS', description: "Vienna's urban thermal spa — a vast wellness complex in Oberlaa with 25 indoor and outdoor pools, Finnish saunas, steam baths, and a textile-free area. The waters come from a 2,400-meter deep thermal spring at 34°C. The most comprehensive spa day available within the city limits.", address: 'Kurbadstraße 14, 1100 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Therme+Wien', phone: '+43 1 680 090', website: 'https://www.thermewien.at', priceRange: 'MID', rating: 4.6, imageUrl: '/spots/therme-wien.jpg', tags: ['thermal', 'sauna', 'spa', 'pools', 'wellness'] },
  { name: 'Burgtheater Vienna', slug: 'burgtheater-vienna', category: 'CULTURE', description: "One of the most important theatres in the German-speaking world — a Neo-Baroque building on the Ringstraße where the most celebrated actors, directors, and dramatists have worked since 1741. The painted ceiling (by Klimt and his brother) is extraordinary. Standing tickets cost €3.", address: 'Universitätsring 2, 1010 Vienna', googleMapsUrl: 'https://maps.google.com/?q=Burgtheater+Vienna', phone: '+43 1 514 44 4145', website: 'https://www.burgtheater.at', priceRange: 'MID', rating: 4.7, imageUrl: '/spots/burgtheater-vienna.jpg', tags: ['theatre', 'klimt-ceiling', 'standing-tickets', 'neo-baroque', 'german-theatre'] },
];

async function main() {
  let created = 0, skipped = 0;
  for (const spot of spots) {
    const { tags, ...data } = spot;
    const exists = await prisma.spot.findFirst({ where: { cityId: CITY_ID, slug: data.slug } });
    if (exists) { skipped++; continue; }
    await prisma.spot.create({ data: { ...data, cityId: CITY_ID, published: true, tags: { create: tags.map(t => ({ tag: t })) } } });
    created++;
  }
  console.log('Vienna: created=' + created + ' skipped=' + skipped);
  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
